Chatterino/chatterino2

chatterino.pro
chatwidgetheader.cpp
chatwidgetheader.h
chatwidgetview.cpp
message.cpp
notebookpage.cpp
notebookpage.h
scrollbar.h
settingsdialogtab.h
signallabel.h
word.h
wordpart.cpp
wordpart.h

getting rid of tons of warnings

---

messages/messagebuilder.h
platform/borderless/winnativewindow.h
usermanager.h
widgets/mainwindow.cpp
windowmanager.cpp
windowmanager.h

settingsPath that is being written to from ptree tree, no need for explicit initialization of _windowMutex - it is done by default already

windowmanager destructor free _mainwindow, fix save - remove const in

---

forms/accountpopupform.ui
widgets/accountpopup.cpp
widgets/accountpopup.h
widgets/chatwidgetview.h

Renamed the userpopup stuff to accountpopup

Renamed User* to Account*

---

.gitmodules
chatterino.pro

fix MSVC (2015) libcommuni link errors, and use correct warn flag

---

chatterino.pro
src/widgets/chatwidgetinput.cpp
src/widgets/chatwidgetinput.hpp
src/widgets/resizingtextedit.cpp
src/widgets/resizingtextedit.hpp

refactoring ResizingTextEdit, tab to auto complete

---

src/widgets/chatwidgetinput.cpp
src/widgets/chatwidgetinput.hpp

This implements the feature of Issue #71 .

Implemented issues #71 and #72

---

src/messages/messagebuilder.cpp

Also cleaned up a bit and changed to http as default URL scheme as it's more compatible with every site.

Fixed regex triggering on everything.

---

forms/accountpopupform.ui
src/messages/messagebuilder.cpp
src/widgets/accountpopup.cpp
src/widgets/accountpopup.hpp
src/widgets/chatwidgetview.cpp

Removed the purge button temporarily as I'll try to add some more features to the popup like timeout templates and custom time spans.

Implemented the accountpopup. Also fixed regex again.

---

src/settingsmanager.cpp
src/settingsmanager.hpp
src/widgets/chatwidget.cpp
src/widgets/chatwidget.hpp
src/widgets/chatwidgetheader.cpp
src/widgets/settingsdialog.cpp
src/widgets/settingsdialog.hpp

Relies on settings entry & loads best available quality by default.

Simple streamlink support

---

src/widgets/chatwidgetheader.cpp

Didn't work anymore after some changes.

Fixed live status

---

src/messages/lazyloadedimage.cpp
src/messages/lazyloadedimage.hpp

Make fetching of LazyLoadedImage non-blocking.
I recommend that someone checks if this is memory-safe and stuff.

Threaded image downloading

---

README.md

A bit of redesign of README file.
I think it should be clearly stated that Qt Creator is NOT a requirement for building this project. Someone should check whether Ubuntu and Mac Homebrew have Qt 5 packages WITHOUT Qt Creator (which I am certain they do).

Make README nicer

---

README.md

although not entirely sure about the deps at this point it errors out less than with the original deps you had listed and it does work 4Head

update Arch install instructions

---

src/widgets/chatwidgetinput.cpp

https://github.com/fourtf/chatterino2/issues/93 
@fourtf  👉 👌
@pajlada  👉 👌

Use user's font in chat input

---

src/emotemanager.cpp

actually show channel ffz emotes as channel ffz emotes

---

src/widgets/notebook.cpp
src/widgets/notebook.hpp

Added a confirmation Dialog when trying to close a tab

---

src/widgets/settingspages/behaviourpage.cpp
src/widgets/split.cpp

you missed a thing

---

src/widgets/settingspages/appearancepage.cpp

It was bugging that I couldn't have purple theme.

Fixed the Theme Color Slider

---

src/singletons/settingsmanager.hpp
src/widgets/qualitypopup.cpp
src/widgets/qualitypopup.hpp
src/widgets/settingspages/behaviourpage.cpp
src/widgets/split.cpp

More streamlink stuff ![pajaDank](https://cdn.frankerfacez.com/emoticon/139658/1)
Fixes #261

Add additional options for streamlink, remove static from qualitypopup

---

chatterino.pro

Bug and the workaround are described [here](https://bugreports.qt.io/browse/QTBUG-27018)

clang PCH workaround

---

src/providers/twitch/twitchchannel.cpp

Fix Send Duplicate Messages not working

---

src/widgets/basewindow.cpp

Fixed crash upon starting

---

src/widgets/helper/notebooktab.cpp
src/widgets/split.cpp
src/widgets/textinputdialog.cpp
src/widgets/textinputdialog.hpp

Something missing from chatterino 1.

Now highlights the text in the channel change and tab rename dialogue.

---

README.md

githubs .md is different hence the change
(my bad should have double checked)

We need to escape > for it to render

---

README.md

Also made the link to the image an actual image.
Am I a Chatterino contributor now? :thinking:

Added a bunch of code blocks.

---

src/singletons/emotemanager.cpp
src/singletons/emotemanager.hpp
src/widgets/emotepopup.cpp

Show Twitch account emotes in EmotePopup

---

.gitmodules
README.md
chatterino.pro
dependencies/boost.pri
dependencies/openssl.pri
dependencies/websocketpp.pri
src/application.cpp
src/messages/layouts/messagelayoutcontainer.cpp
src/messages/selection.hpp
src/providers/twitch/twitchaccount.cpp
src/providers/twitch/twitchaccount.hpp
src/providers/twitch/twitchaccountmanager.cpp
src/providers/twitch/twitchchannel.cpp
src/providers/twitch/twitchchannel.hpp
src/providers/twitch/twitchmessagebuilder.cpp
src/providers/twitch/twitchserver.hpp
src/singletons/accountmanager.cpp
src/singletons/accountmanager.hpp
src/singletons/emotemanager.cpp
src/singletons/helper/pubsubactions.cpp
src/singletons/helper/pubsubactions.hpp
src/singletons/helper/pubsubhelpers.cpp
src/singletons/helper/pubsubhelpers.hpp
src/singletons/pubsubmanager.cpp
src/singletons/pubsubmanager.hpp
src/singletons/resourcemanager.cpp
src/util/networkrequest.hpp
src/util/rapidjson-helpers.cpp
src/util/rapidjson-helpers.hpp
src/widgets/helper/channelview.cpp

This is the initial work on a PubSub system.
What's left to do:
I need to figure out exactly when to start and stop listening to whispers (when you change account etc)
I need to see if there are any rate limits we need to abide by
Test listening to over 50 topics to ensure that the multi-connections work
These things are easier to figure out in the master branch once this has been pulled in.
This change will add a dependency to OpenSSL 1.1 and the ability to link to OpenSSL libs
The Readme has been updated to reflect these new dependencies for Windows using Visual Studio

PubSub system

---

README.md

added useful information for building on osx

---

src/widgets/selectchanneldialog.cpp

Fixes Issue #431

---

src/widgets/selectchanneldialog.cpp

Default 'add split' to channel

---

src/widgets/userinfopopup.cpp

fix weeks time, add days, clang formatting

Fix minor userinfopopup moderator tool bugs

---

src/providers/twitch/twitchemotes.cpp
src/providers/twitch/twitchemotes.hpp
src/util/networkrequest.hpp
src/widgets/emotepopup.cpp
src/widgets/helper/splitheader.cpp

This allows us to display the emote sets channel name in the emote popup

Emote popup channelname

---

src/widgets/basewindow.cpp
src/widgets/settingspages/appearancepage.cpp

font selection fix is very similar to 8b4f9d0,
crash fix similar to 573abe9 (fixes #521).

Fix font selection window showing behind client and #521

---

src/providers/twitch/IrcMessageHandler.cpp
src/widgets/splits/SplitHeader.cpp

should whispers containing highlight phrases be sent to the mentions channel though?
seems unnecessary.

Fix for minor issue with slowmode checkbox and #525

---

chatterino.pro
src/providers/twitch/TwitchMessageBuilder.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/AppearancePage.cpp
src/widgets/settingspages/LookPage.cpp

Seems like clang autoformatted some stuff

Add option to make links lowercase

---

src/providers/twitch/TwitchMessageBuilder.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/HighlightingPage.cpp

Title
requested by lajamerr (I created the issue)

Adding option for bold @username

---

src/messages/Message.cpp

Better time display for timeouts

---

src/controllers/moderationactions/ModerationAction.cpp

Fixed issue with timeoutbuttons #613

---

src/controllers/commands/CommandController.cpp
src/providers/twitch/TwitchAccount.cpp

Fixed /ignore and /unignore as well as give description for the command

---

src/providers/twitch/TwitchApi.cpp

I messed an #include up in my TwitchApi.cpp file

changed an #include

---

src/controllers/highlights/HighlightController.cpp
src/controllers/highlights/HighlightController.hpp

Fixes #616 
does not fix the users tab though

Fixed issue with Excluded users not saving from the highlights tab

---

src/widgets/dialogs/LogsPopup.cpp
src/widgets/dialogs/LogsPopup.hpp

Very ugly code for room-id stuff

Add channel badges and emotes to LogsPopup

---

src/providers/twitch/TwitchChannel.cpp

uncommented lines, idk why this wasn't enabled

fixed (live) issue #626

---

Jenkinsfile

Also add a webhook trigger to `https://nalthis.pajlada.com/generic-webhook-trigger/invoke` with no secret for now
also please squash this

Linux GCC and Clang Jenkins build

---

BUILDING_ON_MAC.md

give a little more detailed installation guide for the qt installation

mac docs update relating to qt

---

src/widgets/dialogs/UserInfoPopup.cpp

TODO: better way of determening when a button is changed, currently stateChanged gives a pulse when the userinfopopup opens (added stuff so it doesn't fuck up anything, but it could be done better) #617

'ignore highlights' checkbox in user info popup - did request

---

src/singletons/Settings.hpp
src/widgets/settingspages/LookPage.cpp
src/widgets/settingspages/LookPage.hpp
src/widgets/splits/SplitHeader.cpp

Added functionality of customizable split headers #637

---

chatterino.pro
src/providers/twitch/PubsubHelpers.hpp
src/providers/twitch/TwitchChannel.cpp
src/widgets/BaseWindow.cpp

* fix some log calls
* fix some weakOf calls
* comment out images resource for now
* add some include directories

Fix compiling on macOS High Sierra 

---

src/providers/twitch/TwitchMessageBuilder.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/HighlightingPage.cpp

Added functionality of option of highlightsound on whisper

---

src/providers/twitch/IrcMessageHandler.cpp

Fixed /mentions 

---

src/singletons/Settings.hpp
src/singletons/WindowManager.cpp
src/widgets/settingspages/LookPage.cpp
src/widgets/settingspages/LookPage.hpp

Could probably be refined, feedback appreciated

Which badges that are shown are now customizable #282

---

src/singletons/NativeMessaging.cpp

replace malloc with make_unique (minor)

---

src/widgets/splits/Split.cpp

How it was:  
How it should be:

Dont show empty categories in viewer list.

---

src/providers/twitch/TwitchChannel.cpp

Fixed custom subscriber badges tooltip

---

src/widgets/helper/ChannelView.cpp
src/widgets/helper/ChannelView.hpp
src/widgets/splits/Split.cpp
src/widgets/splits/SplitContainer.cpp
src/widgets/splits/SplitContainer.hpp

This PR adds "Join to channel" button in context menu of urls with `twitch.tv` domain.

Added button in menu to join to channel.

---

src/messages/MessageBuilder.cpp

This took all in all 4 hours to find FeelsDankMan

Fixes that timeout/ban messages didn't show

---

src/controllers/ignores/IgnoreModel.cpp
src/controllers/ignores/IgnorePhrase.hpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/providers/twitch/TwitchMessageBuilder.hpp
src/singletons/Settings.hpp
src/widgets/settingspages/IgnoresPage.cpp

Everything should be working now
see #587

Ignored Phrases

---

src/providers/twitch/TwitchChannel.cpp

Fixed messages getting added multiple times after roomstate change.

---

src/singletons/WindowManager.cpp
src/widgets/helper/NotebookTab.cpp
src/widgets/helper/NotebookTab.hpp

Now saves the enable highlight on new message tab setting.

---

src/singletons/Settings.hpp
src/singletons/Theme.cpp
src/singletons/Theme.hpp

change `highlighting/color` to any hex color like requested in #703

Add hidden setting for highlight color

---

src/singletons/WindowManager.cpp

This is more of a "hack" than a real fix but it seems the issue lies in the implementation of Qt.
I've debugged the calls and all values are set/loaded properly yet it still messes up.
Fixes #747

Fixed window moving 1px to the left each restart.

---

src/common/Channel.cpp
src/common/Channel.hpp
src/providers/twitch/IrcMessageHandler.cpp
src/widgets/helper/ChannelView.cpp

Prevent normal channel split headers from changing colours when receiving a whisper

Don't change split header for whisper

---

src/widgets/helper/ChannelView.cpp
src/widgets/helper/ChannelView.hpp
src/widgets/splits/Split.cpp
src/widgets/splits/Split.hpp

This PR fixes this issue: https://github.com/fourtf/chatterino2/issues/759
And a bit refactors code.

Moved creating UserInfoPopup in one place.

---

src/widgets/helper/NotebookTab.cpp
src/widgets/helper/NotebookTab.hpp

Added scrolling over tabs with wheel to switch channels.

---

src/controllers/notifications/NotificationController.cpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/HighlightingPage.cpp

Added functionality of making the flash taskbar last until the app is focused again

---

src/providers/twitch/TwitchMessageBuilder.cpp

Fixed message collapsing

---

src/singletons/Settings.hpp

fix typo in username settings path

---

src/widgets/dialogs/EmotePopup.cpp

How it was, and how it's now.
Also this PR allows easily add labels to tiers in the future.

Combined emotes of different tiers in Emote Popup.

---

src/widgets/settingspages/LookPage.cpp

this saying the opposite has been annoying me ever since it was added ![demo](https://i.imgur.com/og6uZsr.png)

correct options text of hiding buttons

---

BUILDING_ON_LINUX.md
BUILDING_ON_MAC.md
BUILDING_ON_WINDOWS.md

Also adds instructions on how to produce standalone builds

Update windows build instructions

---

src/widgets/helper/NotebookTab.cpp

Got triggered by pixels
from
to

Moved the red dot live indicator

---

src/widgets/helper/NotebookTab.cpp

Also resize tabs if height has changed

---

src/widgets/Window.cpp
src/widgets/settingspages/KeyboardSettingsPage.cpp
src/widgets/splits/Split.cpp
src/widgets/splits/Split.hpp

F5 keybinding added for refreshing emotes

---

src/widgets/splits/SplitInput.cpp

This should fix #818. Didn't build and don't really know c++ #yolo #pleasereview #kappa

fixed broken "show message length"

---

src/controllers/commands/CommandController.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/providers/twitch/TwitchServer.cpp
src/providers/twitch/TwitchServer.hpp

render bttv/ffz global emotes in incoming whispers, bttv/ffz/twitch emotes in outgoing whispers

render global emotes in whispers

---

src/singletons/Settings.hpp
src/singletons/Theme.cpp
src/widgets/settingspages/LookPage.cpp

adds a "Custom" theme with a custom theme multiplier

custom theme multiplier support

---

src/providers/twitch/TwitchChannel.cpp

the custom mod badges are loaded here already as well, might as well also refresh the custom sub and cheer badges here so they show up in the history.
resolves #716

load custom badges for old chat as well

---

src/widgets/dialogs/LoginDialog.cpp

Ability to click error message when not providing correct account info

---

src/controllers/commands/CommandController.cpp

Render emojis in whispers

---

src/widgets/helper/ChannelView.cpp

Hide "below" button after clearing messages.

---

src/messages/layouts/MessageLayoutElement.cpp
src/providers/twitch/TwitchAccount.cpp
src/providers/twitch/TwitchEmotes.cpp
src/providers/twitch/TwitchEmotes.hpp

Fixed copying of emotes with '< >' symbols.

---

src/providers/bttv/BttvEmotes.cpp

I guess I have autismo or something, but this bothered me for some time, sorry.

BTTV changed to uppercase

---

BUILDING_ON_WINDOWS.md

Broken links in BUILDING_ON_WINDOWS.md

---

src/providers/twitch/TwitchServer.cpp

I tested it, works for me :tm:

Use secure IRC connections

---

src/singletons/WindowManager.cpp

this relies on fourtf/appbase/pull/1 being merged

Unremove wordflagslistener

---

src/widgets/splits/Split.cpp

Broadcaster was added to the viewer list api
Closes #967

Added the broadcaster to the viewer list 

---

chatterino.pro
src/common/Channel.cpp
src/common/Channel.hpp
src/providers/twitch/ChatroomChannel.cpp
src/providers/twitch/ChatroomChannel.hpp
src/providers/twitch/TwitchApi.cpp
src/providers/twitch/TwitchApi.hpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchChannel.hpp
src/providers/twitch/TwitchServer.cpp

chatrooms being identified by their twitch format of `chatrooms:<channel` ID>:<room UUID>`

Use ffz/bttv channel emotes for chatrooms

---

src/controllers/ignores/IgnoreController.hpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/IgnoresPage.cpp

Closes #849 
preview: https://i.nuuls.com/_4PM6.gif

Show ignored users messages anyway setting

---

src/controllers/commands/CommandController.cpp
src/messages/MessageBuilder.cpp
src/messages/MessageBuilder.hpp
src/providers/twitch/TwitchMessageBuilder.cpp

Refactored some code into the base MessageBuilder class to prevent duplicate code.
Fixes #970

Made links clickable in sent whispers.

---

src/widgets/settingspages/GeneralPage.cpp

I got triggered by the consistency in wording, so I fixed it

Made wording more consistent in generalpage

---

src/messages/layouts/MessageLayout.cpp
src/providers/twitch/IrcMessageHandler.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp

https://i.nuuls.com/UAlVK.mp4
don't know how big the real delay is, since this is built off qt-creator
closes #999

Option to hide moderated messages (timed out messages)

---

src/singletons/WindowManager.cpp
src/widgets/splits/SplitContainer.cpp

Makes moderationMode persistent after reboot, think I covered all cases.
Would close #661

Save chat moderation state in splits

---

BUILDING_ON_WINDOWS.md

Changed convenience link to (newest) release 1.70.0 instead of 1.67.0

Updated links in building_on_windows.md

---

src/messages/MessageElement.hpp

remove unprofessional (puke) inside comments

remove unprofessional (puke) inside comments

---

BUILDING_ON_WINDOWS.md

These dll's are needed for a standalone chatterino release.
(tested on windows 8.1)

Update BUILDING_ON_WINDOWS.md add step with required dll's

---

src/providers/twitch/TwitchServer.cpp

Pubsub messages now go into the correct channel

---

src/messages/MessageBuilder.cpp

Needed to make sub ticket in sub only chat-message accessible. 
Solution for  #565 
Please review again if there is a smarter way of implementing this. :)

made links in system messages clickable

---

src/providers/twitch/TwitchChannel.cpp

fixes correct displayname for chatrooms
fix #1062

fix correct displayname for is offline in chatroom msg

---

src/controllers/commands/CommandController.cpp
src/controllers/commands/CommandController.hpp
src/providers/twitch/IrcMessageHandler.cpp

fix whispers display and not sending in case of double spaces before name

---

src/common/DownloadManager.cpp
src/common/SignalVectorModel.hpp
src/controllers/accounts/AccountModel.cpp
src/controllers/commands/CommandController.cpp
src/controllers/notifications/NotificationController.cpp
src/messages/MessageBuilder.cpp
src/messages/MessageElement.cpp
src/messages/layouts/MessageLayout.cpp
src/messages/layouts/MessageLayoutContainer.cpp
src/providers/emoji/Emojis.cpp
src/providers/irc/AbstractIrcServer.cpp
src/providers/twitch/TwitchAccountManager.cpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/providers/twitch/TwitchServer.cpp
src/singletons/Paths.cpp
src/singletons/Theme.cpp
src/singletons/Toasts.cpp
src/singletons/WindowManager.cpp
src/singletons/helper/LoggingChannel.cpp
src/util/StreamLink.cpp
src/widgets/Scrollbar.cpp
src/widgets/dialogs/SelectChannelDialog.cpp
src/widgets/helper/NotebookTab.cpp
src/widgets/settingspages/AdvancedPage.cpp
src/widgets/settingspages/ExternalToolsPage.cpp
src/widgets/settingspages/ModerationPage.cpp

This PR slightly refactors code and clears some warnings during compilation.
Removed some unused variables.
Renamed variables with duplicate names within single methods.
Refactored some conditions into a concise form.

Refactored code.

---

src/messages/layouts/MessageLayout.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp

Option to hide system moderation messages

---

src/messages/MessageBuilder.cpp

Added in-line moderation buttons next to automod messages

---

src/providers/twitch/TwitchMessageBuilder.cpp
src/widgets/settingspages/GeneralPage.cpp

Change emote parsing order to FFZ -> BTTV -> GlobalFFZ -> GlobalBTTV

---

src/controllers/commands/CommandController.cpp
src/widgets/dialogs/UserInfoPopup.cpp

Added usercard button to link to twitch's usercard

---

src/widgets/Window.cpp
src/widgets/Window.hpp

This PR partially solves [this issue](https://github.com/Chatterino/chatterino2/issues/1077) and adds one item to go to settings.

Added Preferences item in menu bar for OS X.

---

chatterino.pro
src/messages/layouts/MessageLayoutElement.cpp
src/messages/layouts/MessageLayoutElement.hpp
src/singletons/Settings.hpp
src/singletons/TooltipPreviewImage.cpp
src/singletons/TooltipPreviewImage.hpp
src/widgets/helper/ChannelView.cpp
src/widgets/helper/ChannelView.hpp
src/widgets/settingspages/GeneralPage.cpp

Solution for #976
Requires PR https://github.com/fourtf/appbase/pull/3
I'm not really sure how to properly submit such changes. We need to probably merge https://github.com/fourtf/appbase/pull/3 first and then I'll have to update this PR to make appbase point to the latest commit. Please let me know what would be the best approach.
Also, I'm not familiar with the code base that well, so please let me know if I implemented that feature completely wrong.

(#976) Implement Emote preview on mouse hover

---

src/widgets/dialogs/SettingsDialog.cpp

Make button "Manage Accounts" open the Accounts tab

---

src/widgets/settingspages/LookPage.cpp

Related to #1117 which added VIP to that badge "class"

Add VIP to settings description of badge toggle

---

appveyor.yml
chatterino.pro
conanfile.txt

Appveyor will now also use boost installed by Conan

👷 Manage Boost with conan

---

.travis.yml
chatterino.pro

Travis will now use [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) to build and deploy an [AppImage](https://appimage.org/) for Linux

📦 Create appimage

---

src/widgets/helper/NotebookTab.cpp
src/widgets/helper/NotebookTab.hpp

Unfortunately, my implementation of the switching tabs with the scroll is useless for the Mac users with the trackpad. =(
So this PR fixes it.
[i.imgur.com/GQtSFFZ.mp4](https://i.imgur.com/GQtSFFZ.mp4)

Fixed switching tabs using trackpad scroll.

---

.travis.yml

Travis needs to have set `overwrite: true` otherwise it won't upload the dmg and the AppImage to GitHub releases

🐛 Fixed Travis not uploading dmg and AppImage

---

.CI/CreateAppImage.sh
.CI/InstallQTStylePlugins.sh
.travis.yml

Hopefully this fixes the AppImage complaining about missing shared objects

🐛 Fixed AppImage not including QT style plugins

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-suggestion.md
.github/ISSUE_TEMPLATE/something-completely-different.md

These can be edited with a visual editor under GitHub repository settings -> Features -> Issues
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Create issue templates

---

src/controllers/accounts/AccountController.cpp

Fixes the remove button '''crash''' #1226

---

src/providers/twitch/IrcMessageHandler.cpp
src/providers/twitch/TwitchChannel.hpp
src/widgets/splits/SplitHeader.cpp

I added a missing checkbox for follower only mode.
This fixes #1121

Add a switch for follower only mode

---

resources/contributors.txt

Added myself as a contributor to resources/contributors.txt

Added myself as a contributor

---

src/widgets/dialogs/UserInfoPopup.cpp

This PR adds a copy button for user IDs in user cards.

Add copy button for user ids

---

update_filelist.py

This PR sorts the acquired sources and headers list before writing it to the project file.
This should prevent unwanted diffs and guarantee consistent output.
To test, checkout this branch and run `python3 update_filelist.py`. If everything works correctly, no diffs should be produced in the `chatterino.pro` file.

Sort File Names When Updating File List

---

src/providers/twitch/TwitchMessageBuilder.cpp

More Global Badge tool-tip Changes

---

CONTRIBUTING.md

Fixed some spelling mistakes I found while reading CONTRIBUTING.md.

UPDATED CONTRIBUTING.md

---

src/BaseTheme.cpp
src/providers/twitch/PubsubClient.cpp
src/providers/twitch/TwitchMessageBuilder.cpp

Removed unused variables that fix compiler warning [C4189](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4189?view=vs-2019).
Fixed a typo in the `PubSubClient::ping()`.
I'm not familiar with Chatterino code base. That being said, I'm not sure whether leaving those variables as it is were intended for future usage.
This is my first PR for this project. My apologies if I messed up anything.

Removed unused variables

---

src/widgets/dialogs/UserInfoPopup.cpp

Just removed the mod button

---

src/widgets/settingspages/GeneralPage.cpp

Typo in Settings

---

src/providers/twitch/TwitchMessageBuilder.cpp
src/providers/twitch/TwitchMessageBuilder.hpp
src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp

Apa stack bits3

---

chatterino.pro
lib/boost.pri
lib/fmt.pri
lib/rapidjson.pri
lib/websocketpp.pri

Better support for compiling with system libraries

---

src/widgets/dialogs/LogsPopup.cpp
src/widgets/dialogs/LogsPopup.hpp

Logviewer has been returning Cloudflare 521 for a while

Remove getLogviewerLogs from LogsPopup

---

src/widgets/dialogs/EmotePopup.cpp

Fixes #1478
Please try the artifacts (or build it yourself) and ensure it works for you

Add the ability to tab through the emote menu

---

README.md

Update LLVM download version

---

.github/workflows/build.yml

This prevents Conan from redownloading the packages every time

Cache conan packages

---

src/providers/twitch/TwitchAccount.cpp
src/widgets/dialogs/EmotePopup.cpp

Closes #1494 
Will sort:
- Global Twitch Emotes
- Twitch Emotes
- Global Bttv Emotes
- Bttv Channel Emotes
- Global FFZ Emotes
- FFZ Channel Emotes

Emote picker sorting

---

src/widgets/splits/SplitHeader.cpp

Show the toggle mod mode button when mod buttons are enabled.

---

src/widgets/splits/SplitInput.cpp

Closes #1533, but there are a few other shortcut suggestions in there that would nice along with this one.

Control + End scrolls to the bottom of chat

---

src/controllers/highlights/HighlightModel.cpp
src/util/StandardItemHelper.hpp

Make pre-defined highlight columns unselectable

---

src/providers/irc/AbstractIrcServer.cpp
src/providers/irc/AbstractIrcServer.hpp
src/providers/irc/IrcServer.cpp
src/providers/irc/IrcServer.hpp
src/providers/twitch/TwitchIrcServer.cpp

Fixes #1575 
Will investigate a quickie before undrafting this - might be a better solution to this

Fix repeated signal connects on reconnect in irc server

---

src/providers/twitch/TwitchChannel.cpp

Don't set game to game id, always wait for the game name to be resolved

---

src/widgets/helper/ChannelView.cpp

Execute commands with moderation buttons

---

src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp
src/widgets/splits/SplitHeader.cpp

option to hide viewer count and duration of the stream when you hover on the split

---

.github/workflows/build.yml

also use a mirror since it's more stable than qt's official repo

use v2 of qt installer

---

src/widgets/Scrollbar.cpp

Resolves the issue with scrollbar not being able to move by user dragging it.
Closes #1654

Fix scrollbar

---

src/providers/twitch/TwitchMessageBuilder.cpp

removed more debug output for #1601

remove biggest debug output hogger

---

CHANGELOG.md
chatterino.pro
src/controllers/commands/CommandController.cpp
src/util/Twitch.cpp
src/util/Twitch.hpp
src/widgets/helper/ChannelView.cpp

Opens twitch usercard on middle mouse button on a username in chat

open twitch usercard on middle mouse

---

.github/workflows/build.yml

The chocolatey package has been updated to the latest version
https://chocolatey.org/packages/conan

🔧 Switch back to conan from chocolatey

---

src/providers/twitch/TwitchChannel.cpp
src/singletons/Toasts.cpp
src/widgets/splits/Split.cpp
src/widgets/splits/SplitHeader.cpp

It appears that twitch has changed the popout player url and that the previous url does not work. I've updated chatterino2 to reflect that :)

Fix popout player url

---

docs/ENV.md
src/common/Aliases.hpp
src/common/Env.cpp
src/common/Env.hpp
src/providers/bttv/BttvEmotes.cpp
src/providers/bttv/BttvEmotes.hpp
src/providers/ffz/FfzEmotes.cpp
src/providers/twitch/TwitchChannel.cpp
src/util/NuulsUploader.cpp

closes #1720
I have updated chatterino so that it shows the authors name for both bttv and ffz on hover.

Display authors name on hover

---

src/widgets/splits/SplitHeader.cpp

Added missed line break to header with empty thumbnail.

---

.github/workflows/build.yml

use cache v2 (and bust cache)

---

src/providers/twitch/TwitchMessageBuilder.cpp

Fixes crash when receiving inline whispers with the setting "Highlight received inline whispers" enabled.
Closes #1756

Fix highlighted whisper crash 

---

BUILDING_ON_WINDOWS.md

Update OpenSSL download links.
Updates links for OpenSSL installations, and includes a disclaimer for when the links do not work.

Update OpenSSL links in Windows build readme

---

src/widgets/settingspages/GeneralPage.cpp

I fixed a spelling mistake
That is all.

Fix a spelling mistake

---

src/messages/MessageElement.cpp

Added IRC text/word wrapping
Fixes #1781 
Dependant on #1794

Add proper IRC text/word wrapping

---

CHANGELOG.md
src/widgets/helper/SearchPopup.cpp

[SearchPopup] CTRL+F now focuses the search input

---

CHANGELOG.md
src/widgets/splits/Split.cpp
src/widgets/splits/Split.hpp
src/widgets/splits/SplitHeader.cpp

Added a "Open in browser" option to the whisper split. Don't think there's much more to it... 🚀

Add an "Open in browser" option to whisper split

---

resources/contributors.txt

I messed up and had to make a new PR for this.

added self to contributor list

---

CHANGELOG.md
src/widgets/AttachedWindow.cpp

Added support for Brave browser for the native messaging extension.

added brave browser to supported NM list

---

BUILDING_ON_LINUX.md

On my system, pkg-config was required in order to detect openssl.

Update NixOS build instructions

---

CHANGELOG.md
lib/settings.pri

This version handles symlinks properly
Fixes #1856

Update version of settings library

---

.cirrus.yml

Add CI for FreeBSD, using CirrusCI since GitHub Actions doesn't support FreeBSD at the moment.

Add CirrusCI

---

.cirrus.yml
chatterino.pro
lib/qtkeychain.pri

Since FreeBSD has packages of qtkeychain, use those when possible.

use packaged qtkeychain on FreeBSD

---

README.md

Just a "nice to have" thing, if you're interested.

add build status badges to README

---

BUILDING_ON_WINDOWS.md

fixed the link going to Openssl it was g but they moved to h now

Updated BUILDING_ON_WINDOWS.md

---

src/common/NetworkResult.hpp
src/common/SignalVectorModel.hpp
src/providers/twitch/TwitchMessageBuilder.hpp
src/widgets/dialogs/switcher/NewTabItem.hpp
src/widgets/dialogs/switcher/SwitchSplitItem.hpp

Fixed some easy compile warnings with GCC 10 and Clang 11, check commit messages for more info

Compiler warnings

---

resources/contributors.txt

I changed my name some time ago

contributors.txt name change

---

CHANGELOG.md
src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp

Changed some default settings

---

.github/FUNDING.yml

This will add a link to the chatterino repo for donations. Can also add a sponsor button if fourtf is signed up to sponsors

Add a funding file for donations

---

CHANGELOG.md
src/singletons/Settings.hpp
src/widgets/dialogs/UserInfoPopup.cpp
src/widgets/settingspages/GeneralPage.cpp
src/widgets/settingspages/GeneralPage.hpp

Added back settings for last message line style

---

README.md

All other links in that section have a hyperlink at the end, and this is useful if someone who isn't familiar with Twitch but finds this project on GitHub is interested in what this client is built for.

Adds link to Twitch on the README

---

.github/workflows/build.yml

[CI] Disable mirror

---

resources/tlds.txt

Adds new .gay domain to the top level domain list
https://www.ohhey.gay/
https://icannwiki.org/.gay

add .gay top level domain

---

.github/dependabot.yml

Will check for github actions updates and submodule updates on a daily basis

Add dependabot to update ci & submodules

---

README.md

This pr adds the chocolatey badge on the readme

Add chocolatey badge + information to the readme

---

resources/contributors.txt

Add y0dax to contributors.txt

---

.CI/CreateDMG.sh
.CI/dmg-settings.py

update ci to fix macos builds

---

CHANGELOG.md
resources/qss/settings.qss
src/widgets/settingspages/GeneralPage.cpp
src/widgets/settingspages/GeneralPageView.cpp
src/widgets/settingspages/GeneralPageView.hpp

edited general settings categories

---

src/PrecompiledHeader.hpp
src/widgets/helper/ChannelView.cpp
src/widgets/helper/ChannelView.hpp

Fix various warnings

---

CHANGELOG.md
src/singletons/Updates.cpp

Updates are not checked if the version you're using is a nightly version
(denoted by a nightly line in the modes file located in the same folder as the application binary)
Fixes #2163

Apply nightly update logic to macOS and Linux too

---

CHANGELOG.md
src/widgets/helper/ChannelView.cpp

Use the main window as the parent to all user cards on macOS

---

chatterino.pro

Won't affect places where ccache isn't available, but speeds up build where it is.

Add ccache to the build where possible

---

CHANGELOG.md
src/widgets/dialogs/ChannelFilterEditorDialog.hpp
src/widgets/settingspages/FiltersPage.cpp

The ChannelFilterEditorDialog was missing a parent.
Fixes #2202

Add parent to ChannelFilterEditorDialog

---

CHANGELOG.md

~~- [ ] `CHANGELOG.md` was updated, if applicable~~ N/A
Typo

Changelog typo fixes

---

.github/ISSUE_TEMPLATE/bug_report.md

- ~~[ ] `CHANGELOG.md` was updated, if applicable~~ N/A 
Added a link to the chatterino wiki for commonly known/solved issues to lower the amount of issue reports opened

 Added Chatterino wiki source to bug report issue template

---

.CI/CreateAppImage.sh
.github/workflows/build.yml

[CI] Add missing dependencies to Ubuntu packaging step

---

CHANGELOG.md
src/providers/LinkResolver.cpp
src/widgets/helper/ChannelView.cpp

- ~~[ ] `CHANGELOG.md` was updated, if applicable~~
Bug introduced after last stable release
I am really sorry for introducing yet another bug :(
Fixes #2243

Fixed thumbnails merging with link info without thumbnails

---

BUILDING_ON_WINDOWS.md

Most people are using windows 10 nowadays, I've just updated the link to move to the windows 10 section.

Update path help link

---

src/messages/MessageElement.hpp

Use correct include path to ImageSet.hpp

---

.github/workflows/build.yml

[CI:build] Only run push checks on master.

---

src/widgets/helper/NotebookTab.cpp

Don't pollute global namespace with boost bind placeholders

---

tests/src/HighlightPhrase.cpp

[Tests] Make tests build again (ctor of HighlightPhrase changed)

---

CMakeLists.txt
src/common/Common.hpp
src/common/NetworkPrivate.cpp
src/common/NetworkPrivate.hpp
src/common/NetworkRequest.cpp
src/common/NetworkResult.hpp
src/controllers/filters/FilterRecord.hpp
src/controllers/filters/parser/Tokenizer.hpp
src/providers/twitch/TwitchCommon.hpp
src/providers/twitch/api/Helix.hpp
src/util/QObjectRef.hpp
tests/.clang-format
tests/src/NetworkRequest.cpp
tests/src/main.cpp

- Add missing includes
- Update .clang-format for tests to match src/.clang-format
- Add network request tests

Add Network tests

---

.github/workflows/test.yml
CMakeLists.txt

Run tests in CI

---

.gitmodules

Move away from libcommuni fork

---

.github/workflows/build.yml
CHANGELOG.md

Build multiple Qt versions in CI

---

.github/workflows/build.yml

- don't run tree anymore
- fix asset path for uploading release assets

[CI] Fix release artifact uploading

---

CHANGELOG.md
src/controllers/notifications/NotificationController.cpp
src/singletons/Settings.hpp
src/singletons/Toasts.cpp
src/widgets/settingspages/GeneralPage.cpp
src/widgets/settingspages/NotificationPage.cpp

Closes #2325, all relevant discussion is in there.
~~If a maintainer is reading this, please merge in #2316 first, so I'll have it easier to resolve merge conflicts.~~ thanks pajlada :+1:

Added Live Notification suppression to Streamer Mode

---

CHANGELOG.md
src/messages/SharedMessageBuilder.cpp

- Check if user is anonymous before adding username to self-highlight phrase
Fixed #2156

Fix anonymous Twitch user ping

---

src/controllers/commands/CommandController.cpp
src/providers/twitch/TwitchAccount.cpp
src/util/StreamLink.cpp
src/widgets/dialogs/LoginDialog.cpp
src/widgets/settingspages/FiltersPage.cpp

No changelog entry is needed
Replaced all occurrences of "occured" with "occurred"

Fixed some spelling mistakes across files

---

src/providers/twitch/TwitchChannel.cpp

Removed empty liveStatusChanged connect signal

---

.github/workflows/build.yml
.github/workflows/test.yml
CHANGELOG.md
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/api/Helix.cpp
src/providers/twitch/api/Helix.hpp
src/providers/twitch/api/Kraken.cpp
src/providers/twitch/api/Kraken.hpp
src/providers/twitch/api/README.md

Migrated getChannel to Helix

---

.github/workflows/build.yml
lib/qtkeychain.pri

Bump QtKeychain version

---

_.travis.yml

Closes #2383.
Related to #2393.
Reverts #1328.

Removed obsolete macOS builds workaround

---

CHANGELOG.md
src/widgets/helper/ChannelView.cpp

Fixed hidden tooltips when always on top is active

---

BUILDING_ON_WINDOWS.md

Fixes https://github.com/Chatterino/chatterino2/issues/2415

Update OpenSSL download link

---

.gitmodules
CHANGELOG.md
chatterino.pro
lib/humanize.pri

Remove humanize submodule

---

src/controllers/filters/parser/Types.hpp

Fix test compilation

---

src/messages/MessageElement.cpp

Remove bad asserts from IRC text wrapping code

---

.github/workflows/build.yml
.github/workflows/test.yml

Use new version of aqtinstall in jobs

---

.github/workflows/test.yml

Re-enable tests

---

tests/src/Emojis.cpp

they are a C++20 feature, we aim to support C++17.

Don't use designated initializers

---

.github/workflows/lint.yml
.prettierignore
.prettierrc.toml
BUILDING_ON_FREEBSD.md
BUILDING_ON_LINUX.md
BUILDING_ON_MAC.md
BUILDING_ON_WINDOWS.md
CONTRIBUTING.md
README.md
src/providers/twitch/api/README.md

Add lint github action

---

src/controllers/notifications/NotificationController.cpp
src/singletons/Settings.hpp
src/singletons/Toasts.cpp
src/widgets/settingspages/GeneralPage.cpp

xd
~~- [ ] `CHANGELOG.md` was updated, if applicable~~

Fixed spelling of Suppress

---

src/widgets/dialogs/ChannelFilterEditorDialog.cpp
src/widgets/dialogs/SelectChannelFiltersDialog.cpp

Fixes inconsistencies in the Filter menu. No changelog entry needed I'd say. 
Closes #2467

Fix filter inconsistency

---

.github/workflows/check-formatting.yml

Stop double-running "check formatting" action

---

.CI/CreateDMG.sh
.github/workflows/build.yml

Fix macOS building with qt6 by default

---

.github/workflows/push-aur.yml

Add Arch Linux builder & AUR syncer workflow

---

.github/workflows/build.yml

Always build CI regardless of changes

---

CHANGELOG.md

This PR is cleanup for a previous PR (#2503) where the PR ID was not appended to the changelog entry. No code changes made.

Append PR ID to changelog entry

---

resources/com.chatterino.chatterino.appdata.xml

Update app description in appdata.xml

---

src/widgets/helper/Button.cpp
src/widgets/splits/SplitHeader.cpp

Always update the menu when pressing the split hamburger button to account for changes because of mod/live status change.

always update dropdown on split button press

---

BUILDING_ON_LINUX.md

- Updated required packages on Arch GNU/Linux ![It's me Leon, not mm pepeLaugh](https://cdn.betterttv.net/emote/5fd0d7898c4e2c46195d6e27/1x)
- Updated required packages on Ubuntu
I think ti's safe to assume this closes #2577

Updated building docs regarding CMake update

---

.gitmodules
CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt

These can be enabled using the SANITIZE_{ADDRESS,MEMORY,THREAD,UNDEFINED} cmake flags

Add sanitizers for cmake

---

.github/workflows/build.yml

bump conan cache

---

CHANGELOG.md
src/controllers/commands/CommandController.cpp

Closes #2582 
This **does not** allow running custom commands in custom commands.

Allow for usage of builtin Chatterino commands in custom commands.

---

src/providers/ffz/FfzEmotes.cpp

Removed unnecessary debug output

---

CMakeLists.txt

Update chatterino version in CMakeLists.txt

---

resources/com.chatterino.chatterino.appdata.xml

Update the appdata.xml file

---

CHANGELOG.md
src/widgets/helper/ChannelView.cpp

Added image links to the badge context menu

---

src/messages/MessageBuilder.cpp
src/messages/MessageBuilder.hpp
src/providers/twitch/IrcMessageHandler.cpp

No change log entry needed, just code clean-up

Remove ban reasons because they are not a thing in IRC anymore

---

CHANGELOG.md
src/Application.cpp
src/messages/layouts/MessageLayoutContainer.cpp
src/messages/layouts/MessageLayoutElement.cpp
src/messages/layouts/MessageLayoutElement.hpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp

Add an option to remove spaces between emotes

---

src/widgets/settingspages/IgnoresPage.cpp

No changelog entry is needed
Fixed spelling of "unblock" command description in Settings -> Ignores -> Users

Fixed a spelling mistake 

---

src/providers/chatterino/ChatterinoBadges.cpp
src/providers/chatterino/ChatterinoBadges.hpp
src/providers/ffz/FfzBadges.cpp
src/providers/ffz/FfzBadges.hpp
src/providers/twitch/TwitchAccount.cpp
src/providers/twitch/TwitchAccount.hpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/widgets/dialogs/UserInfoPopup.cpp
src/widgets/settingspages/IgnoresPage.cpp

Haven't tested yet because I am going to bed ![peepoBed](https://user-images.githubusercontent.com/6320036/116156392-b0e11b00-a6eb-11eb-92b4-048d2df2acc4.gif)

some concurrency additions

---

.github/workflows/push-aur.yml

Disable pushing commits to `chatterino2-git` AUR repo

---

CHANGELOG.md
src/providers/twitch/IrcMessageHandler.cpp

Fixed login expired message highlight every tab

---

CHANGELOG.md
src/providers/twitch/IrcMessageHandler.cpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/providers/twitch/TwitchMessageBuilder.hpp

Closes #2655
Also makes live and offline messages clickable.

Added clickable hosting messages

---

CHANGELOG.md
src/singletons/NativeMessaging.cpp
src/singletons/NativeMessaging.hpp
src/widgets/settingspages/GeneralPage.cpp

added try catch in nm

---

src/BrowserExtension.cpp
src/providers/chatterino/ChatterinoBadges.hpp
src/providers/ffz/FfzBadges.hpp

Add missing includes for those not using precompiled headers

---

ISSUE_TEMPLATE.md

We use issue templates from `.github/ISSUE_TEMPLATE` now, this is obsolette.

Remove unused legacy issue template file

---

src/widgets/Window.cpp

Makes tab direction setting work for popup window
Fixes #2496

Fix tab direction not applying to popup window

---

CHANGELOG.md
src/widgets/splits/Split.cpp

Search for users in viewer list by contained term instead of searching for a prefix

Search in viewer list by contained term

---

src/providers/IvrApi.cpp
src/providers/twitch/TwitchAccount.cpp

Fixed a crash introduced in 2f568b8 (#2856)

---

src/widgets/settingspages/FiltersPage.cpp

Fixes #2906
~- [ ] `CHANGELOG.md` was updated, if applicable~ N/A

Fix 'Filter Info' url

---

CHANGELOG.md
src/widgets/settingspages/ExternalToolsPage.cpp
src/widgets/settingspages/GeneralPage.cpp

smol PR that just moves the setting ppL

Moved image uploader confirmation setting to external tools page

---

src/controllers/commands/CommandController.cpp

Removed `/logs` command

---

resources/tlds.txt

We've done last update in #2345
Source: https://data.iana.org/TLD/tlds-alpha-by-domain.txt
Version 2021062700, Last Updated Sun Jun 27 07:07:01 2021 UTC

Updated TLDs

---

resources/resources_autogenerated.qrc
src/autogenerated/ResourcesAutogen.cpp
src/autogenerated/ResourcesAutogen.hpp

Updated autogenerated resources

---

chatterino.pro
resources/update_filelist.py
tools/update_filelist.py

Also moved the script to :/resources and made it executable (just like ./generate_resources.py)
Maybe we should at least reflect those changes in CMakeLists.txt or write a script for updating filelist there

Updated filelist in chatterino.pro

---

src/widgets/settingspages/HighlightingPage.cpp

Only restrict Highlight color for whispers in messages tab

---

CHANGELOG.md
src/controllers/filters/parser/FilterParser.cpp

Respect founder badge in `author.subbed` filter

---

resources/contributors.txt

Add Talen to contributors

---

src/messages/SharedMessageBuilder.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/util/Helpers.cpp
src/util/Helpers.hpp

This removes some duplicate code and makes possible to impelement a fix for https://github.com/Chatterino/chatterino2/pull/2967#discussion_r664605390

Moved getRandomColor method to util/Helpers.cpp

---

src/common/CompletionModel.cpp
src/util/Helpers.cpp
src/util/Helpers.hpp
src/widgets/helper/ChannelView.cpp
src/widgets/splits/SplitInput.cpp
tests/CMakeLists.txt
tests/src/Helpers.cpp

Overengineered helper function to format a user mention

---

src/providers/twitch/PubsubClient.cpp
src/providers/twitch/PubsubClient.hpp
src/util/DebugCount.hpp

Add count for topics we're currently listening to

---

src/widgets/BaseWindow.cpp
src/widgets/FramelessEmbedWindow.cpp

Removed checks for no longer supported Qt 5.11

---

CHANGELOG.md
src/Application.cpp

Make single deletion messages for moderators obey the setting

---

src/providers/twitch/TwitchMessageBuilder.cpp
src/providers/twitch/TwitchMessageBuilder.hpp

removes some weird 20 lines of code that are actually two lines of normal code

Rewrite logic for when to show moderation buttons next to messages

---

CHANGELOG.md
src/widgets/splits/SplitInput.cpp

Duplicate spaces now count towards the display message length

---

CONTRIBUTING.md
src/controllers/commands/CommandController.cpp
src/providers/twitch/IrcMessageHandler.cpp

Update Usage messages to conform to new Usage message contributor guidelines

---

CHANGELOG.md
src/controllers/nicknames/Nickname.hpp
src/controllers/nicknames/NicknamesModel.cpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/widgets/settingspages/NicknamesPage.cpp

Added regex option to nicknames as well as case sensitivity option which is enabled by default when creating an object.
Regex now support the \1.

Added regex option to Nicknames

---

.github/workflows/build.yml
CHANGELOG.md
src/CMakeLists.txt

Not worth adding 12 extra builds for this
Fixes #3320

Add GitHub action to test builds with precompiled headers disabled

---

resources/contributors.txt

I noticed that the avatars URL has changed + new users have a jfif avatar format (as demonstrated [here](https://avatars.githubusercontent.com/1xelerate)).

Update contributors guide

---

CHANGELOG.md
src/providers/irc/IrcMessageBuilder.cpp

Fix IRC actions not being colored properly

---

src/common/SignalVectorModel.hpp

- Add protected `rows()` function to SignalVectorModel
- make getModelIndexFromVectorIndex public
- Refactor getModelIndexFromVectorIndex parameter naming
- Make getModelIndexFromVectorIndex const

Refactor parts of SignalVectorModel

---

CHANGELOG.md
src/providers/twitch/IrcMessageHandler.cpp
src/providers/twitch/TwitchMessageBuilder.cpp

Fixed the first link being broken in `/mods` and `/vips`

---

CHANGELOG.md
src/widgets/Window.cpp
src/widgets/splits/ClosedSplits.hpp
src/widgets/splits/SplitContainer.cpp

Fixed splits losing filters when closing and reopening them

---

src/widgets/helper/ChannelView.cpp

I thought of one and then I just decided to look for more, also I alphabetized it.

Add more ignored channels for context menu twitch links

---

CHANGELOG.md
src/providers/twitch/TwitchMessageBuilder.cpp

Now shows prediction outcomes in badges. Closes #2989

Show picked outcome in prediction badges.

---

CHANGELOG.md
src/providers/irc/IrcChannel2.cpp

Fixed Chatterino attempting to send empty messages in IRC

---

CHANGELOG.md
src/providers/irc/IrcServer.cpp

just move triggerHighlights under build (where highlights are parsed)
fixes #3367

Fix IRC server messages not triggering sounds properly

---

resources/contributors.txt

Add acdvs to contributor list

---

BUILDING_ON_WINDOWS.md

Previous one is now 404.
Related #3198
Addresses #3406

Updated OpenSSL 1.1 link in building docs

---

src/widgets/settingspages/GeneralPage.cpp

Add link to Privacy Policy and Terms of Service under the Link Previews section

---

CHANGELOG.md
src/providers/twitch/TwitchMessageBuilder.cpp

Fixes #3425
Originally @zneix's solution, but cut out of PR #3421 to make the PR smaller

Make mods, vips, joined/parted messages searchable

---

.github/ISSUE_TEMPLATE/a_make_a_report.yml

Updates the issue template, i've made to be a little more precise
https://github.com/Mm2PL/testingxdd/issues/new?assignees=&labels=issue-report&template=a_make_a_report.yml

Update issue template to be more precise

---

CHANGELOG.md
src/widgets/helper/ChannelView.cpp

Fixed crash that could occur when the user closes the Settings dialog

---

src/controllers/hotkeys/ActionNames.hpp
src/widgets/Window.cpp

- Use NDEBUG instead of C_DEBUG to figure out debug build state
- Add misc message with founder badge

Fix debug hotkeys not showing up in debug builds

---

CHANGELOG.md
src/controllers/commands/CommandController.cpp

This is an expert debug feature. I do not expect any non-developers to ever use this command. It makes for easy testing of highlights and such.
Example:
```
/fakemsg @badge-info=subscriber/18;badges=moderator/1,subscriber/12,glhf-pledge/1;color=#DAA520;display-name=Mm2PL;emotes=300196486:6-10;first-msg=0;flags=;id=9c94cac9-9fab-4494-bfb8-e82546c9b6ce;mod=0;room-id=11148817;subscriber=1;tmi-sent-ts=1641127552558;turbo=0;user-id=117691339;user-type= :mm2pl!mm2pl@mm2pl.tmi.twitch.tv PRIVMSG #pajlada :-tags pajaM this is a totally real message pajaLaugh 
```

Add /fakemsg command

---

src/widgets/helper/ChannelView.cpp

Add login to Context Menu ignoreList

---

src/RunGui.cpp
src/widgets/BaseWindow.cpp

Also fix path for where to find the icon

Set window icon in the whole application instead of in BaseWindow

---

.github/workflows/build.yml

#3586 broke the CI, hopefully this PR fixes that

:construction_worker: Fixed qt caching attempt 2

---

CHANGELOG.md
src/util/IncognitoBrowser.cpp

All work fine by default except for librewolf, it's registry entry is not formatted properly.
[I opened a PR for librewolf to fix it and align it with upstream](https://gitlab.com/librewolf-community/browser/windows/-/merge_requests/21)
Before:
After:

Added librewolf, icecat, and waterfox incognito support.

---

BUILDING_ON_WINDOWS.md

Links were broken, seems like there is no live exe for `1.0.2u`, so I swapped it over to an archive, there is a zip, although I kept it this way to avoid any re-documenting

Fixed and updated OpenSSL Windows links in building docs

---

CHANGELOG.md
src/providers/twitch/IrcMessageHandler.cpp
src/widgets/Window.cpp

Fix announcement rendering

---

src/providers/twitch/TwitchCommon.hpp

Just adds /announce to the list.
I feel like this change is small enough to qualify for no changelog Hmmm

Add tab-completion for the /announce Twitch command

---

resources/tlds.txt

Last update was #2930
New: Version 2022040300, Last Updated Sun Apr  3 07:07:01 2022 UTC

chore: update TLDs

---

resources/contributors.txt

I've added myself to the contributions list

Added myself to Contributors

---

.github/workflows/homebrew.yml

I committed invalid bash when I made the homebrew workflow - dank moment.
Dankness fixed, will run homebrew update task manually.

fix(ci): dankness removed from homebrew CI

---

.github/ISSUE_TEMPLATE/a_make_a_report.yml

Super niche change, but if it helps even one person update before they open an issue then I think it's worth it.
If #3653 is resolved before this PR is merged I'll update this one, otherwise I'll open a new one another day.
also merge this last b/c no reason to waste ci checks on it or any other PR.

Update Issue Template version placeholder to 2.3.5

---

CHANGELOG.md
src/Application.cpp

Fix automod crash

---

src/widgets/dialogs/UserInfoPopup.hpp

Left over from #1982. Isn't referenced anywhere else in the codebase and worked on my system when I compiled it.

Removed unused `refreshButton` pointer

---

src/providers/twitch/api/Helix.cpp
src/providers/twitch/api/Helix.hpp

This allows it to be mocked for any future unit tests

Make Helix an interface

---

CHANGELOG.md
src/providers/LinkResolver.cpp

Fix links with no thumbnail having previous link's thumbnail

---

src/Application.cpp
src/Application.hpp

Function is `getIApp` for now
This should be preferred where possible for new code to make mocking possible in the future

Make an IApplication interface

---

.gitignore

Adds 4 new, visual studio specific files to git ignored under editors and cmake
- .vs main folder
- [.editorconfig](https://editorconfig.org/#overview) 
- [CMakeSettings.json](https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=msvc-170)
- [CMakePresets.json](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-json-reference?view=msvc-170)
suggest no changelog

Add Visual Studio stuff to .gitignore

---

.github/workflows/test.yml
tests/README.md
tests/src/NetworkRequest.cpp

This reduces the likelyhood of our CI failing due to the connection
between the CI machine and the internet-hosted httpbin.org website being
down

Run httpbin docker image locally in CI

---

BUILDING_ON_WINDOWS.md

It was on an older beta version :)

Updated boost convenience link

---

BUILDING_ON_WINDOWS.md

Fixed broken openssl link

---

CHANGELOG.md
benchmarks/src/Highlights.cpp
src/controllers/highlights/HighlightController.cpp
src/controllers/highlights/HighlightController.hpp
tests/src/HighlightController.cpp

- Add failing tests
- Fix benchmarks not compiling
- Fix showInMentions not forwarding properly
- Include showInMentions for user highlights
- Add ostream operator for HighlightResult

Fix highlights not showing in mentions

---

src/singletons/Toasts.cpp

New version: 5e441fd03543b999edb663caf8df7be37c0d575c from 2021-07-30
Old version: ce441336ef057576dfb377be754bc5357a04ff85 from 2018-08-02
May close #3817

Update WinToast to the latest version available at 2022-06-25

---

BUILDING_ON_WINDOWS.md

Windows OpenSSL link update

---

.github/workflows/build.yml
src/providers/twitch/TwitchMessageBuilder.cpp

- Only run clang-tidy on PRs
- test on pr

Only run clang-tidy CI Action on PRs

---

CHANGELOG.md
src/controllers/filters/parser/FilterParser.cpp
src/controllers/filters/parser/Tokenizer.hpp

Documentation update PR: https://github.com/Chatterino/wiki/pull/226

Add AutoMod message flag filter

---

src/CMakeLists.txt
src/providers/twitch/TwitchIrcServer.cpp
src/widgets/helper/ChannelView.cpp

- Treat `reorder` warnings as errors
- Fix `reorder` warnings

Treat `reorder` warnings as errors

---

CHANGELOG.md
src/common/NetworkPrivate.cpp
tests/src/NetworkRequest.cpp

- Forward network reply body to errors
- Add test to ensure the data is included for errors

Include network response body in errors

---

CHANGELOG.md
src/controllers/commands/CommandController.cpp
src/providers/twitch/api/Helix.cpp
src/providers/twitch/api/Helix.hpp
tests/src/HighlightController.cpp

Migrates `/ban` and `/timeout`.
Closes #3960.
Closes #3979.

Migrate `/ban` and `/timeout` to Helix API

---

.github/workflows/build.yml
.github/workflows/post-clang-tidy-review.yml

Swap back to main branch of ZedThree's clang-tidy-review

---

resources/contributors.txt

Update 1xelerate contributors github link

---

src/controllers/filters/parser/FilterParser.cpp
src/widgets/helper/ResizingTextEdit.cpp
src/widgets/settingspages/ModerationPage.cpp

Prevent copying QString type in iterations
Prevent copying while binding to a temporary

Prevent copying in a couple places

---

CHANGELOG.md
src/controllers/commands/CommandController.cpp
src/providers/twitch/IrcMessageHandler.cpp
src/singletons/Settings.hpp
src/widgets/settingspages/GeneralPage.cpp

Added Setting to disable inline whispers while streamer mode is enabled.
My first Pull Request.
Close #2730

Hide inline whispers in streamer mode

---

.clang-tidy
src/messages/layouts/MessageLayoutContainer.hpp

- Don't complain about private members for now :-)
- Remove `centered` and `enableCompactEmotes` fields

Remove unused values from MessageLayoutContainer

---

BUILDING_ON_LINUX.md

I do not have Fedora or NixOS so I've left it the way it was. Thank you pajlada, Mm2PL and jammehcow for helping me in Discord. I assume you wanted me to do a PR from Leons message. If I have to I might set up a VM for Fedora and/or NixOS after work to check there.

Copied and adjusted BUILDING_ON_LINUX.md from SevenTV

---

src/messages/Image.cpp
src/util/PostToThread.hpp

Add helper function for ensuring a function is run in the GUI thread

---

src/providers/seventv/SeventvEmotes.cpp

Grammar: Alias to -> Alias of

---

.github/workflows/build.yml
.github/workflows/test.yml

Update `jurplel/install-qt-action` GitHub Action from v2 to v3

---

CHANGELOG.md
src/widgets/helper/ChannelView.cpp

This reverts commit 05008214fa4a39ed8cdeaab2962d590269caa2dd.
Fixes #4110

Revert "Fix Twitch-specific filters not being applied (#4107)"

---

src/widgets/settingspages/AboutPage.cpp

Fix RapidJSON link not being https

---

CHANGELOG.md
src/controllers/commands/CommandController.cpp
src/providers/twitch/api/Helix.cpp
src/providers/twitch/api/Helix.hpp

Can be tested & verified with the `/test-chatters` command

Fix chatters recursion not working

---

CHANGELOG.md
src/messages/search/MessageFlagsPredicate.cpp

Add `is:redemption` search predicate

---

CHANGELOG.md
src/messages/search/MessageFlagsPredicate.cpp

Add `is:reply` search predicate

---

.github/workflows/build.yml

Update `pajlada/create-release` action to v2.0.4

---

CHANGELOG.md
src/CMakeLists.txt
src/singletons/NativeMessaging.cpp
src/singletons/Updates.cpp
src/singletons/helper/LoggingChannel.cpp
src/util/IncognitoBrowser.cpp
src/widgets/AttachedWindow.cpp
src/widgets/BaseWindow.cpp
src/widgets/StreamView.cpp
src/widgets/Window.cpp
src/widgets/dialogs/EmotePopup.cpp
src/widgets/dialogs/NotificationPopup.cpp
src/widgets/dialogs/ReplyThreadPopup.cpp
src/widgets/dialogs/SettingsDialog.cpp
src/widgets/helper/EditableModelView.cpp
src/widgets/helper/EffectLabel.cpp
src/widgets/helper/SearchPopup.cpp
src/widgets/splits/Split.cpp
src/widgets/splits/SplitHeader.cpp
src/widgets/splits/SplitInput.cpp
src/widgets/splits/SplitOverlay.cpp

This PR will disable use of obsolete Qt APIs (deprecated in <= 5.15) in new code, while we are preparing for Qt6 upgrade in future.
Cmake macro [`QT_DISABLE_DEPRECATED_BEFORE`](https://doc.qt.io/qt-5/qtglobal.html#QT_DISABLE_DEPRECATED_BEFORE) is set to `5.15.0` and minor compilation errors that arose are resolved (summary below).
Minimal supported Qt version stays the same at 5.12.
Summary of all changes (old -> new):
- 19x `QLayout::setMargin(int)` [docs](https://doc.qt.io/qt-5/qlayout-obsolete.html#setMargin) -> `QLayout::setContentsMargins(int, int, int, int)` [docs](https://doc.qt.io/qt-5/qlayout.html#setContentsMargins)
- 2x `QProcess::startDetached(QString)` [docs](https://doc.qt.io/qt-5/qprocess-obsolete.html#startDetached-2) -> …

Disable use of Qt APIs deprecated in 5.15.0 and earlier versions

---

src/providers/twitch/IrcMessageHandler.cpp
src/providers/twitch/TwitchChannel.cpp

Should help debug this rare crasherino we sometimes get

Add debug output to channel point reward callbacks

---

tools/clang-format-all.sh

Have `clang-format-all.sh` also reformat test files

---

CHANGELOG.md
docs/make-release.md
resources/com.chatterino.chatterino.appdata.xml
src/common/Version.hpp

- Update make-release.md documentation
- Update changelog
- Update `com.chatterino.chatterino.appdata.xml` version
- Update `Version.hpp`

Release v2.4.0

---

.github/workflows/homebrew.yml

Fix Homebrew cask update workflow

---

.github/workflows/build.yml

- Add missing `libfuse2` library to Ubuntu build
- Remove empty whitespaces

Fix Ubuntu CI builds

---

CHANGELOG.md
src/widgets/settingspages/ExternalToolsPage.cpp

Discussed in another PR but never merged due to conflicts with adding functionality.
This PR only adds the link to the documentation.

Add docs link for streamlink `--args`

---

.github/workflows/build.yml

For a consitently build. Chatted with pajlada in Discord [here](https://discord.com/channels/253897423439659008/459650160658481152/1050000444988072007)

Change ubuntu-latest to ubuntu-20.04 in CI builds

---

src/widgets/settingspages/GeneralPage.cpp

I believe I remembered to test every setting, to make sure nothing like #4225 happens again 🦒

Add even more tooltips when hovering settings

---

.github/workflows/test.yml

Retry tests 3 times to lessen chance of complete job failure due to flaky tests

---

CHANGELOG.md
src/widgets/Window.cpp

fixes #4247
added connection to local signalHolder

Fix tab direction change crash

---

src/CMakeLists.txt
src/util/ThreadGuard.hpp
src/widgets/helper/ChannelView.cpp
src/widgets/helper/ChannelView.hpp

- Add ThreadGuard class
- Use ThreadGuard when accessing a ChannelView's messageSnapshot

Add Thread Guard for debugging simple threading issues

---

CHANGELOG.md
src/main.cpp

- remove protocol from organization domain
Fixes #4253

Remove protocol from organization domain

---

CHANGELOG.md
src/providers/emoji/Emojis.cpp

Remove another implicit this-capture for C++20 migration

---

CHANGELOG.md
CMakeLists.txt

Disable LTO by default
CI already handles this in PR builds vs main branch builds, but I think the average developer does not need LTO for testing their features

Disable LTO by default

---

src/providers/twitch/TwitchIrcServer.cpp

The link was broken, it is now not broken.

Fix link to the "connecting to the Twitch IRC server" guide

---

CHANGELOG.md
CMakeLists.txt
src/controllers/nicknames/NicknamesModel.cpp
src/controllers/nicknames/NicknamesModel.hpp
src/providers/colors/ColorProvider.hpp
src/providers/emoji/Emojis.hpp
src/providers/seventv/eventapi/SeventvEventAPISubscription.cpp
src/providers/twitch/TwitchAccountManager.hpp
src/providers/twitch/TwitchCommon.hpp
src/providers/twitch/TwitchEmotes.cpp
src/providers/twitch/api/Helix.cpp
src/providers/twitch/api/Helix.hpp
src/util/Helpers.hpp
src/util/QStringHash.hpp
src/util/RatelimitBucket.hpp
src/widgets/splits/ClosedSplits.hpp
src/widgets/splits/InputCompletionItem.hpp
src/widgets/splits/InputCompletionPopup.hpp

- Add `<functional>` include to QStringHash.hpp
- Add missing includes to `src/providers/twitch/TwitchAccountManager.hpp`
- Move explicit HelixChatters constructor to the source file
- Remove unused includes & add used includes to NicknamesModel.hpp
- NicknamesModel.hpp: Remove `virtual` when `override` is used
- Add missing QStringHash include to TwitchEmotes.cpp
- Add missing includes to various files
- Print Qt version in cmake step

Massage includes some more

---

.cirrus.yml
CHANGELOG.md

Also sneak in a print of the compiler version used & compiler commands for debugging

Bump Cirrus CI FreeBSD image from 12.1 to 13.1

---

CHANGELOG.md
src/CMakeLists.txt
src/common/FlagsEnum.hpp
src/widgets/dialogs/ColorPickerDialog.hpp
src/widgets/dialogs/EditHotkeyDialog.hpp

- Fix `inconsistent-missing-override` warnings
- Fix `final-dtor-non-final-class` warnings
- Fix `ambiguous-reversed-operator` warnings

Fix various small warnings

---

resources/contributors.txt

I never cared enough to add myself, but I gotta get some form of identification so these streamers will listen 👺 
Omitting a PFP due to the fact that I don't have permission from T1* to use Faker's likeness

Add Felanbird to contributors list

---

resources/contributors.txt

In an attempt to highlight people who keep this application going, mm2pl and I discussed bumping each-other to Collaborator(s).
This prompted me to include those who are currently active Contributors who have contributed a lot, and who have added themselves to this list prior.
If you are a contributor who has not yet added themselves to the list, but would likely fall under the Collaborator label, open a PR as normal and I'll bump you in that PR
If you see this PR in the future and are a former-active contributor who has contributed a lot and would like to be bumped, open a PR and I'll approve+merge it.

Mark big strong contributors as Collaborators

---

CHANGELOG.md
lib/semver/README.md
lib/semver/include/semver/semver.hpp
resources/licenses/semver.txt
src/CMakeLists.txt
src/common/Version.hpp
src/singletons/Updates.cpp
src/singletons/Updates.hpp
src/widgets/settingspages/AboutPage.cpp
tests/CMakeLists.txt
tests/src/Updates.cpp

Version checking used to fail when it came to beta/rc/alpha versions where it treated updates as non-updates.

Fix version checking

---

.github/workflows/build.yml
.github/workflows/post-clang-tidy-review.yml

- clang-tidy action: Exclude lib & tests dir for clang-tidy CI checks
- clang-tidy-action: Disable the LGTM comment

Clean up clang-tidy action checks

---

CMakeLists.txt

Disable translation building

---

.github/workflows/test.yml

Change pubsub test server from master branch to the latest stable tag

---

.CI/CreateUbuntuDeb.sh
.github/workflows/build.yml

- Ensure both Ubuntu 20.04 and Ubuntu 22.04 .deb packages are uploaded
- also upload the windows debug symbols

Upload both Ubuntu .deb packages & Windows .pdb symbols in releases

---

.CI/CreateUbuntuDeb.sh
.github/workflows/build.yml

Fix .deb & pdb release uploads

---

BUILDING_ON_LINUX.md

Me and my brother just compiled Chatterino on his Arch Linux this morning where I noticed the Qt Multimedia and Gst Stuff being in that file. Now I noticed it being even in systems where I did not test it yet too and thought I'd remove them too.

Improve Linux build instructions

---

CHANGELOG.md
CMakeLists.txt
resources/com.chatterino.chatterino.appdata.xml
src/common/Version.hpp

This release is mostly to ensure we're fully Helix-migrated. This was the intention behind the v2.4.0 release but we missed the moderation actions in the User Card.

Release v2.4.1

---

.github/workflows/build.yml

Install conan v1.58.0

---

CHANGELOG.md
src/CMakeLists.txt
src/providers/ffz/FfzBadges.cpp
src/providers/ffz/FfzEmotes.cpp
src/providers/ffz/FfzUtil.cpp
src/providers/ffz/FfzUtil.hpp

Fix Handling of FFZ CDN URLs with https already appended

---

.github/workflows/lint.yml

Prettier CI prints the diff now. It annoyed me too much

CI: Make prettier print the diff on error

---

resources/contributors.txt

Add ScrubN to contributors list

---

BUILDING_ON_WINDOWS.md

Just a bit cleaner, no need for props when using `Inovke-RestMethod`, and swapped regex replace to string replace, since no regex was used.

docs: Windows, better natvis script

---

.github/pull_request_template.md

Remove the "Pull request checklist" from the template

---

.github/workflows/build.yml
BUILDING_ON_MAC.md

Tested on my mac mini running macOS 13

Update macOS build instructions & fix release artifacts

---

.github/workflows/build.yml
CHANGELOG.md

Mark builds as experimental

---

README.md

Revert test change to README.md

---

resources/com.chatterino.chatterino.appdata.xml

Update appdata file imgur screenshot link

---

CHANGELOG.md

Update changelog for reality

---

CHANGELOG.md
src/CMakeLists.txt
src/common/ChatterSet.hpp
src/common/enums/MessageOverflow.hpp
src/providers/colors/ColorProvider.cpp
src/singletons/Settings.hpp
src/singletons/Updates.cpp
src/widgets/settingspages/GeneralPage.cpp
src/widgets/splits/SplitInput.cpp
src/widgets/splits/SplitInput.hpp

This button is off by default, and can be enabled with the "Show send message button" setting
Fixes #2279

Add a Send button that can be used to send messages

---

src/providers/twitch/api/README.md

- pubsub <-> eventsub documentation & clarification
- Update Get Chatters documentation

Document our pubsub usage & eventual eventsub usage

---

resources/contributors.txt

Adding myself to `resources/contributors.txt` as first time contributors(#4638), thanks again for all the feedback <3

add 'olafyang' to contributors.txt

---

resources/contributors.txt

add 4rneee to contributors.txt

---

CHANGELOG.md
src/widgets/Window.cpp

Fix streamer mode button being always visible on Windows

---

.github/workflows/test.yml

Run tests on Qt 5.12.12 & Qt 6.2.4 in CI

---

.github/workflows/build.yml
.github/workflows/check-formatting.yml
.github/workflows/lint.yml
.github/workflows/test.yml

random ci test things

---

CHANGELOG.md
src/controllers/hotkeys/ActionNames.hpp
src/widgets/splits/SplitHeader.cpp

Replace viewer list with chatter list externally. This is 1/2 tasks for issue 4640

fix: change viewer list to chatter list

---

CHANGELOG.md
src/widgets/dialogs/ReplyThreadPopup.cpp

Fix: Incorrect tab focus in reply threads

---

.clang-tidy
.sanitizers/asan-suppressions
.sanitizers/lsan-suppressions
.sanitizers/tsan-suppressions
.sanitizers/ubsan-suppressions
mocks/include/mocks/EmptyApplication.hpp
src/providers/twitch/PubSubActions.hpp
src/providers/twitch/PubSubManager.hpp
src/providers/twitch/pubsubmessages/AutoMod.hpp
src/providers/twitch/pubsubmessages/Whisper.hpp
tests/CMakeLists.txt
tests/src/BasicPubSub.cpp
tests/src/BttvLiveUpdates.cpp
tests/src/Emojis.cpp
tests/src/SeventvEventAPI.cpp
tests/src/TestHelpers.hpp
tests/src/TwitchMessageBuilder.cpp
tests/src/TwitchPubSubClient.cpp

- Add a few pre-made sanitizer suppressions
- Test Sanitization: Fix threading issues
- Test Sanitization: Allow deletion of PubSub
- Test Sanitization: Fix some memory leaks

Fix memory leaks & data races in tests

---

src/widgets/settingspages/NicknamesPage.cpp

<details>
<summary>Details</summary>
made you look
</details>

Mention filters in the note for features that nicknames don't work with

---

BUILDING_ON_LINUX.md

fix fedora build dependencies

---

CHANGELOG.md

changelog was before the change in approach

Update changelog entry for 4854

---

README.md

Fix Chatterino logo in readme

---

src/controllers/filters/lang/FilterParser.cpp
src/controllers/filters/lang/FilterParser.hpp

- Make explainIllType anonymous/static
- Comment constructor

refactor: FilterParser

---

src/widgets/settingspages/KeyboardSettingsPage.cpp
src/widgets/settingspages/KeyboardSettingsPage.hpp

- refactor: KeyboardSettingsPage
- refactor: Make tableCellClicked source-static

refactor: KeyboardSettingsPage

---

CHANGELOG.md
src/controllers/commands/builtin/twitch/Unban.cpp

feat: `/unban` and `/untimeout` by id

---

CHANGELOG.md
src/controllers/commands/builtin/twitch/Ban.cpp

- fix: duplicate ban when banning by id
- update changelog entry

fix: /banid and /ban id: performing duplicate bans

---

src/providers/twitch/IrcMessageHandler.cpp

Remove unused parseMessage function

---

.github/workflows/test.yml

ci: Build benchmarks on Ubuntu 22.04 runner

---

src/controllers/hotkeys/HotkeyController.cpp

fix: typo in debug log for hotkeys

---

.github/workflows/test-macos.yml
CHANGELOG.md

When I tested it on my own fork, both macOS tests succeeded. Hopefully those work here too.

Migrate tests on macOS to the same way tests are run on windows

---

resources/contributors.txt

Just adding myself to the contributors list

chore: add SputNikPlop to the contributors list

---

CHANGELOG.md
mocks/include/mocks/EmptyApplication.hpp
src/Application.cpp
src/Application.hpp
src/controllers/highlights/BadgeHighlightModel.cpp
src/providers/twitch/TwitchBadges.cpp
src/providers/twitch/TwitchBadges.hpp
src/providers/twitch/TwitchMessageBuilder.cpp
src/widgets/dialogs/BadgePickerDialog.cpp

refactor: Move TwitchBadges to Application

---

src/Application.hpp
src/controllers/commands/CommandController.cpp
src/controllers/commands/builtin/twitch/SendWhisper.cpp
src/messages/Image.cpp
src/messages/MessageBuilder.cpp
src/messages/MessageElement.cpp
src/providers/twitch/TwitchAccount.cpp
src/providers/twitch/TwitchChannel.cpp
src/widgets/dialogs/EmotePopup.cpp

refactor: make Application::emotes private

---

.github/workflows/build.yml
BUILDING_ON_WINDOWS.md
CHANGELOG.md
CMakeLists.txt

Reported by @Leppunen - thanks!

chore: Build with Qt6 by default on Windows

---

BUILDING_ON_WINDOWS.md
CHANGELOG.md
conanfile.py

From https://github.com/Chatterino/chatterino2/pull/5155#issuecomment-1926689191

chore: Use OpenSSL 3 by default in conan

---

.CI/full-ubuntu-build.sh

chore: update the ci full build script

---

CHANGELOG.md
docs/chatterino.d.ts

Update chatterino.d.ts for the ChannelRef change

---

.CI/full-ubuntu-build.sh

Disable tests & benchmarks on ubuntu 20.04 docker builds

---

.github/workflows/build.yml
.github/workflows/test-windows.yml

chore(deps): update sccache version comments

---

.github/workflows/test-macos.yml

Disable homebrew auto updating

---

CHANGELOG.md
src/controllers/completion/sources/UserSource.cpp

fix: Don't attempt to put the broadcaster username at the top

---

CHANGELOG.md
lib/lua/CMakeLists.txt
src/controllers/plugins/LuaAPI.cpp
src/controllers/plugins/LuaAPI.hpp
src/controllers/plugins/LuaUtilities.cpp
src/controllers/plugins/LuaUtilities.hpp
src/controllers/plugins/Plugin.cpp
src/controllers/plugins/PluginController.cpp
src/controllers/plugins/api/ChannelRef.cpp
src/controllers/plugins/api/IOWrapper.cpp

Nothing should have broken from this :sunglasses:

fix: Compile Lua as a C library

---

tests/src/main.cpp

- **fix(tests): Only log chatterino debug stuff**
- **fix(tests): Don't output settings dir**

fix: output less qt debug stuff in tests

---

CHANGELOG.md
src/singletons/StreamerMode.cpp

fix: check broadcast binaries without case sensitivity

---

CHANGELOG.md
docs/plugin-meta.lua
scripts/make_luals_meta.py
src/controllers/plugins/LuaAPI.hpp
src/controllers/plugins/api/ChannelRef.hpp

The previous generator had some bugs that would require keeping a lot more state or having more duplicate code when doing it line-by-line. Mainly, classes with methods weren't defined globally and some enums weren't read correctly.
I refactored it to fix the bugs. It should be a bit easier to extend the generator. ~~Furthermore, triple-slash comments are now supported.~~ Triple slash comments aren't supported anymore, they're doxygen-only now.
There were some issues in the definitions which I fixed as well.

refactor: improve LuaLS generator

---

CHANGELOG.md
src/widgets/helper/ChannelView.cpp

Adds more missing updates. Calling `update` here is fine since it will only rerender if the view is visible.
Fixes #5281.

fix: missing rerender on clear

---

src/controllers/filters/lang/Filter.cpp
src/widgets/settingspages/GeneralPage.cpp

- **add comments for the new reward filters**
- **slightly improve documentation of r9k values**

Fix some documentations & comments

---

CHANGELOG.md
src/providers/twitch/TwitchEmotes.cpp

fix: use 3x scale factor for base size multiplier

---

.CI/chatterino-installer.iss
CHANGELOG.md
CMakeLists.txt
docs/make-release.md
resources/com.chatterino.chatterino.appdata.xml
src/common/Version.hpp

Release v2.5.0-beta.1

---

.github/workflows/build.yml
.github/workflows/test-windows.yml

fix: use openssl3 on qt6 windows builds

---

.CI/chatterino-installer.iss
CHANGELOG.md
CMakeLists.txt
resources/com.chatterino.chatterino.appdata.xml
src/common/Version.hpp

Bugfix release :-)
I plan to merge this in tomorrow (Sunday) morning & have the release be made that day.
If anyone notices any other big bugs, let me know *now*

Release v2.5.1

---

tests/README.md

Otherwise it will be recognized as a local path in the repository

docs: fix typo

---

CHANGELOG.md
CMakeLists.txt
src/CMakeLists.txt

build: add doxygen target

---

.github/workflows/build.yml
.github/workflows/create-installer.yml
.github/workflows/test-windows.yml
CHANGELOG.md

Update Windows Qt6 version from 6.5.0 to 6.7.1

---

CHANGELOG.md
src/util/IncognitoBrowser.cpp

Added brave browser to the incognito list.
Fixes #5451

fix: Add brave & google-chrome-stable to incognito browser list

---

.github/workflows/build.yml

fix: git permission errors in Ubuntu builds

---

CHANGELOG.md
docs/plugin-meta.lua
docs/wip-plugins.md
src/controllers/plugins/LuaAPI.hpp
src/controllers/plugins/api/HTTPRequest.hpp

Closes: #5493
- fixed `plugin-meta.lua` file
- updated docs with corrected code examples

fix plugin http types & docs

---

CHANGELOG.md
mocks/include/mocks/Logging.hpp
src/common/Channel.cpp
src/common/Channel.hpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchChannel.hpp
src/singletons/Logging.cpp
src/singletons/Logging.hpp
src/singletons/Settings.hpp
src/singletons/helper/LoggingChannel.cpp
src/singletons/helper/LoggingChannel.hpp
src/widgets/settingspages/ModerationPage.cpp

Added option to log streams by their ID, allowing for easier "per-stream" log analyzing

---

src/Application.cpp
src/Application.hpp

fix: only use IApplication::instance instead of Application::instance

---

CHANGELOG.md
src/common/FlagsEnum.hpp
tests/src/FlagsEnum.cpp

feat: add `FlagsEnum::isEmpty` for checking if a FlagsEnum is empty

---

CHANGELOG.md
src/CMakeLists.txt
src/common/Channel.hpp
src/controllers/highlights/HighlightController.hpp
src/messages/Message.hpp
src/messages/MessageFlag.hpp
src/messages/layouts/MessageLayoutContainer.hpp
src/widgets/helper/ChannelView.hpp

refactor: Move MessageFlag(s) to its own file

---

CHANGELOG.md
benchmarks/src/Highlights.cpp

fix: benchmarks segfaulting

---

CHANGELOG.md
benchmarks/src/RecentMessages.cpp
src/Application.cpp
src/Application.hpp
src/providers/pronouns/Pronouns.cpp
src/providers/pronouns/Pronouns.hpp
src/providers/pronouns/alejo/PronounsAlejoApi.cpp
src/providers/pronouns/alejo/PronounsAlejoApi.hpp
src/widgets/dialogs/UserInfoPopup.cpp

- **nit: remove unused pronoun definition in benchmarks**
- **nit: make App::pronouns a unique ptr**
- **nit: newline**
- **nit: refactor Pronouns.hpp/cpp**
- **chore: refactor PronounsAlejoApi**
- **nit: rename pronouns to userPronoun**

chore: clean up some of the pronoun implementation

---

.github/workflows/lint.yml

finally Closes #5152 
thanks neri

deps(ci): update actionsx-prettier to node 20

---

CHANGELOG.md
src/singletons/StreamerMode.cpp

I don't know how I missed this... 🤦 
Fixes #5623.

fix(streamer-mode): access timer from correct thread

---

src/providers/twitch/IrcMessageHandler.cpp

ref: https://github.com/Chatterino/chatterino2/pull/5668#issuecomment-2426392590

refactor: remove unused ReplyContext.highlight

---

.github/workflows/test.yml

fix: codecov v5

---

CHANGELOG.md
src/main.cpp

fix: output --version to stdout

---

CHANGELOG.md
src/messages/MessageBuilder.cpp

fix: automod username placement

---

CHANGELOG.md
src/providers/twitch/TwitchIrcServer.cpp
src/providers/twitch/pubsubmessages/AutoMod.cpp
src/providers/twitch/pubsubmessages/AutoMod.hpp

fix: stop blocked terms from showing up more than once

---

CHANGELOG.md
CMakeLists.txt
resources/com.chatterino.chatterino.appdata.xml
src/common/Version.hpp

Release v2.5.2

---

CHANGELOG.md
src/controllers/plugins/api/HTTPRequest.cpp
src/controllers/plugins/api/HTTPRequest.hpp

Fix: Take Lua HTTP callbacks as sol::main_protected_function

---

.github/workflows/winget.yml

chore: bump winget-releaser action

---

docs/make-release.md

Update release docs

---

.github/workflows/winget.yml

fix: update winget repo url

---

.github/workflows/winget.yml

fix: winget url fix

---

CHANGELOG.md
src/singletons/Updates.cpp

fix: don't block with update prompt on macos/linux

---

.gitmodules
CHANGELOG.md
src/controllers/sound/MiniaudioBackend.cpp
src/providers/liveupdates/BasicPubSubManager.hpp
src/providers/twitch/PubSubHelpers.hpp
src/providers/twitch/PubSubManager.cpp
src/providers/twitch/PubSubManager.hpp

From https://github.com/Chatterino/chatterino2/issues/5766#issuecomment-2541876735

fix: support boost 1.87

---

.prettierrc
docs/chatterino.d.ts
docs/plugin-meta.lua
src/providers/twitch/TwitchChannel.hpp

Update chatterino.d.ts to match plugin-meta.lua

---

tests/src/IrcMessageHandler.cpp

chore(tests): don't use variants 😠

---

CHANGELOG.md
src/controllers/commands/builtin/chatterino/Debugging.cpp
src/messages/MessageBuilder.cpp
src/messages/MessageBuilder.hpp
src/providers/twitch/TwitchIrcServer.cpp
src/util/ChannelHelpers.hpp

adds a "server received time" to incoming Ban/Unban actions from PubSub so they can properly merge again

fix: properly stack/merge PubSub & IRC timeouts again

---

.github/workflows/build.yml

doc(ci): explain ubuntu docker image stuff

---

.github/workflows/test.yml
lib/twitch-eventsub-ws/ast/requirements-dev.txt
lib/twitch-eventsub-ws/ast/requirements.txt

chore(eventsub): run pytest in ci

---

CHANGELOG.md
mocks/include/mocks/Helix.hpp
src/providers/twitch/api/Helix.cpp
src/providers/twitch/api/Helix.hpp
src/providers/twitch/eventsub/Controller.cpp
src/providers/twitch/eventsub/Controller.hpp

Does some smaller refactors too, removing some xds and some xDs and even some XDs

feat(eventsub): properly unsubscribe once no more handles are interested

---

CHANGELOG.md
lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp
lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp
src/providers/twitch/eventsub/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.hpp
tests/snapshots/EventSub/channel-moderate/shared-unban.json
tests/snapshots/EventSub/channel-moderate/unban.json

Towards #5908. This adds support for `(shared_chat_)unban`s.

feat(eventsub): implement unban

---

CHANGELOG.md
src/providers/twitch/eventsub/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.hpp
tests/snapshots/EventSub/channel-moderate/emoteonly-off.json
tests/snapshots/EventSub/channel-moderate/emoteonly.json
tests/snapshots/EventSub/channel-moderate/followers-0s.json
tests/snapshots/EventSub/channel-moderate/followers-off.json
tests/snapshots/EventSub/channel-moderate/followers.json
tests/snapshots/EventSub/channel-moderate/slow-off.json
tests/snapshots/EventSub/channel-moderate/slow.json
tests/snapshots/EventSub/channel-moderate/subscribers-off.json
tests/snapshots/EventSub/channel-moderate/subscribers.json
tests/snapshots/EventSub/channel-moderate/uniquechat-off.json
tests/snapshots/EventSub/channel-moderate/uniquechat.json

Towards #5908.
Implements
- followers (we didn't handle this in PubSub)
- followersoff (we didn't handle this in PubSub)
- emoteonly
- emoteonlyoff
- slow
- slowoff
- subscribers
- subscribersoff
- uniquechat
- uniquechatoff

feat(eventsub): implement mode changes

---

CHANGELOG.md
lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp
lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp
src/providers/twitch/eventsub/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.hpp
tests/snapshots/EventSub/channel-moderate/mod.json
tests/snapshots/EventSub/channel-moderate/unmod.json

Towards https://github.com/Chatterino/chatterino2/issues/5908. Uses the same message that's used with PubSub.

feat(eventsub): implement (un)mod

---

CHANGELOG.md
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchChannel.hpp
src/providers/twitch/eventsub/Connection.cpp
src/providers/twitch/eventsub/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.hpp
tests/snapshots/EventSub/channel-suspicious-user-update/monitored.json
tests/snapshots/EventSub/channel-suspicious-user-update/no-treatment.json
tests/snapshots/EventSub/channel-suspicious-user-update/restricted.json
tests/src/EventSubMessages.cpp

This should be the last event that we _need_ to handle.

feat(eventsub): implement suspicious user update

---

.github/workflows/test-macos.yml
CHANGELOG.md
lib/twitch-eventsub-ws/tests/src/string.cpp
src/messages/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.hpp
src/providers/twitch/eventsub/MessageHandlers.cpp
src/util/Helpers.cpp
src/util/Helpers.hpp

I started this PR with just attempting to fix the compilation, but without some of the further fixes the snapshot tests failed due to outputting garbage strings instead of the real strings.
Something with Qt 6.4.3's QStringBuilder is broken, so I'm using these changes as a temporary fix until we don't support Qt 6.4.3 anymore.

fix: Qt 6.4.3 build

---

CHANGELOG.md
src/singletons/Settings.hpp
tests/src/TwitchPubSubClient.cpp

this should let us get some more eyes on the implementation and make sure it doesn't misbehave

fix: enable Twitch EventSub by default

---

CHANGELOG.md
mocks/include/mocks/DisabledStreamerMode.hpp
src/messages/layouts/MessageLayout.cpp
src/providers/twitch/eventsub/MessageBuilder.cpp
src/singletons/Settings.hpp
src/singletons/StreamerMode.cpp
src/singletons/StreamerMode.hpp
src/singletons/WindowManager.cpp
src/widgets/settingspages/GeneralPage.cpp
tests/snapshots/EventSub/channel-suspicious-user-message/restricted-emote.json
tests/snapshots/EventSub/channel-suspicious-user-message/restricted.json

draft waiting for previous PR to be merged in

feat: Hide messages from suspicious users in streamer mode

---

CHANGELOG.md
lib/twitch-eventsub-ws/benchmarks/src/parse.cpp
lib/twitch-eventsub-ws/src/session.cpp
lib/twitch-eventsub-ws/tests/src/parse.cpp
tests/src/EventSubMessages.cpp

Fixes a bug introduced in #6058 where the connection wasn't closed.

fix(eventsub): close connection after timeout

---

CHANGELOG.md
src/singletons/WindowManager.cpp
src/util/InitUpdateButton.cpp
src/widgets/AccountSwitchPopup.cpp
src/widgets/AccountSwitchPopup.hpp
src/widgets/BaseWindow.cpp
src/widgets/BaseWindow.hpp
src/widgets/DraggablePopup.cpp
src/widgets/dialogs/UpdateDialog.cpp
src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp

this renames some features BaseWindow already had and moves some functionality from AccountSwitcherPopup to BaseWindow

refactor: some mini feature changes in BaseWindow

---

CHANGELOG.md
src/providers/twitch/eventsub/Connection.cpp
tests/snapshots/EventSub/channel-suspicious-user-message/restricted-bad-type.json
tests/snapshots/EventSub/channel-suspicious-user-message/restricted-ban-evader.json

- **add some more tests**
- **output to info if a low trust status message is ignored**
- **chore: add changelog entry**

chore(eventsub): some more tests & print if message is ignored

---

CHANGELOG.md
lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp
lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp
src/providers/twitch/eventsub/Connection.cpp
src/providers/twitch/eventsub/MessageBuilder.cpp
src/providers/twitch/eventsub/MessageBuilder.hpp
tests/snapshots/EventSub/channel-moderate/unban-request-approve-message.json
tests/snapshots/EventSub/channel-moderate/unban-request-approve.json
tests/snapshots/EventSub/channel-moderate/unban-request-deny-message.json
tests/snapshots/EventSub/channel-moderate/unban-request-deny.json

These are the last actions that we didn't handle yet. They're moderation actions and shown as `<MODERATOR> {approved/denied} the unban request from <USER>[: <MESSAGE]`.

feat(eventsub): handle unban requests

---

resources/contributors.txt

add jacob-thompson to contributors list

---

resources/contributors.txt

add Jujufrost as a contributor

---

CHANGELOG.md
src/widgets/helper/Button.cpp
src/widgets/splits/SplitInput.cpp
src/widgets/splits/SplitInput.hpp
tests/src/NetworkResult.cpp

fix: make reply-cancel button less coarse-grained

---

CHANGELOG.md
src/messages/layouts/MessageLayout.cpp
src/messages/layouts/MessageLayoutContext.cpp
src/messages/layouts/MessageLayoutContext.hpp
src/singletons/Settings.hpp
src/singletons/WindowManager.cpp
src/widgets/settingspages/GeneralPage.cpp

Fixes #3545 Allow disabling fading recent messages

---

CHANGELOG.md
src/widgets/settingspages/GeneralPage.cpp

fix: missing space char in settings

---

CHANGELOG.md
src/widgets/splits/SplitInput.cpp

fix: don't clear message when closing reply

---

CHANGELOG.md
src/widgets/settingspages/FiltersPage.cpp
src/widgets/settingspages/FiltersPage.hpp

feat: make filters searchable with Settings dialog search

---

CHANGELOG.md
src/common/Aliases.hpp
src/providers/twitch/TwitchAccount.cpp
src/providers/twitch/TwitchAccount.hpp

refactor(TwitchAccount): mostly include cleanup

---

CHANGELOG.md
src/Application.cpp
src/singletons/WindowManager.cpp
src/singletons/WindowManager.hpp
tests/src/MessageLayout.cpp
tests/src/Scrollbar.cpp
tests/src/SplitInput.cpp

refactor(WindowManager): remove some `getApp` uses

---

CHANGELOG.md
mocks/include/mocks/TwitchIrcServer.hpp
src/Application.cpp
src/Application.hpp
src/providers/twitch/TwitchIrcServer.cpp
src/providers/twitch/TwitchIrcServer.hpp

refactor: move event api initializations to TwitchIrcServer

---

BUILDING_ON_WINDOWS.md

The visualizers moved to their own repo: https://github.com/qt-labs/vs-debugtools.

docs: update natvis repo

---

CHANGELOG.md
lib/twitch-eventsub-ws/src/session.cpp
src/providers/twitch/eventsub/Controller.cpp

fix: send weak ptr to session's checkKeepalive timer

---

src/providers/twitch/TwitchIrcServer.cpp

we no longer ignore the connections

chore: remove bad event api init comments

---

CHANGELOG.md
src/Application.cpp
src/messages/Image.cpp

i also snuck in a mini Application.cpp refactor, no one will know

fix: don't construct images after we're quitting

---

CHANGELOG.md
src/Application.cpp
src/Application.hpp
src/RunGui.cpp
src/common/network/NetworkPrivate.cpp
src/messages/Image.cpp
src/providers/recentmessages/Api.cpp
src/providers/seventv/SeventvEmotes.cpp
src/providers/twitch/ChannelPointReward.cpp
src/providers/twitch/TwitchChannel.cpp
src/providers/twitch/TwitchIrcServer.cpp
src/providers/twitch/TwitchIrcServer.hpp
src/providers/twitch/eventsub/Connection.cpp
src/providers/twitch/eventsub/Controller.cpp
src/util/Helpers.cpp
src/widgets/helper/NotebookButton.cpp
src/widgets/splits/SplitHeader.cpp

will be rebased into multiple PRs where possible
- https://github.com/Chatterino/chatterino2/pull/6188
- https://github.com/Chatterino/chatterino2/pull/6194
- https://github.com/Chatterino/chatterino2/pull/6197
- https://github.com/Chatterino/chatterino2/pull/6198
- https://github.com/Chatterino/chatterino2/pull/6203
- https://github.com/Chatterino/chatterino2/pull/6204
- https://github.com/Chatterino/chatterino2/pull/6213

attempt to fix crashes on exit

---

CHANGELOG.md
src/CMakeLists.txt
src/common/Channel.hpp
src/common/TimeoutStackStyle.hpp
src/singletons/ImageUploader.cpp
src/singletons/Settings.hpp

from https://github.com/Chatterino/chatterino2/pull/6162

refactor: move `TimeoutStackStyle` to its own file

---

src/controllers/plugins/Plugin.cpp
src/controllers/plugins/Plugin.hpp
src/controllers/plugins/SolTypes.cpp

refactor: remove Application.hpp dependency in Plugin.hpp

---

.github/workflows/eventsub-test.yml
.github/workflows/test.yml

Move EventSub Python test to a separate GitHub Actions workflow

---

src/providers/twitch/TwitchEmotes.cpp
src/singletons/ImageUploader.cpp
src/widgets/Window.cpp
src/widgets/settingspages/GeneralPage.cpp
src/widgets/settingspages/ModerationPage.cpp

fix(clang-tidy): modernize-raw-string-literal

---

CHANGELOG.md
src/widgets/buttons/SvgButton.cpp
src/widgets/buttons/SvgButton.hpp

Not a clean solution, but it works & given that we cache the output it feels ok

feat(SvgButton): Allow custom color

---

CHANGELOG.md
src/widgets/splits/SplitContainer.cpp

fix: stop resize when ctrl is released

---

CHANGELOG.md
src/messages/MessageBuilder.cpp
tests/snapshots/IrcMessageHandler/clearmsg-non-truncated.json
tests/snapshots/IrcMessageHandler/clearmsg-truncated.json

This PR aims to fix an issue where "A message from X was deleted" messages aren't being logged to chatterino's file logs. This was caused by the text being used by the logger (`Message.messageText`) not being set, so an empty string was being logged. I've also set the `searchText` so they show up in searches.
Fixes #6464.
Post-fix screenshot of log:

fix: log deletion messages to file log

---

CHANGELOG.md
src/widgets/PluginRepl.cpp

fix: use qsizetype zerovalue instead of `0LL`
