Chatterino/chatterino2

- messages/limitedqueue.h
- messages/limitedqueuesnapshot.h
Deleted unnecessary variables (a std::vector pointer and the length).
Reserving the space for all messages instead of default constructing them when creating the vector.
> Cleaned up LimitedQueue and its Snapshot class

- accountmanager.cpp
- accountmanager.h
- settingsmanager.cpp
- settingsmanager.h
- widgets/accountpopup.cpp
- widgets/chatwidgetview.cpp
Initialize them when they are needed, not on startup. This is THREAD-SAFE since C++11.
Chatterino2 now runs on Linux again
> Make runnable again

- src/widgets/chatwidget.cpp
- src/widgets/notebookpage.cpp
- src/widgets/scrollbar.cpp
the _currentValue should fix scrollbar (atleast it does for me), without it cannot scroll with mousewheel plus dragging the scrollbar with mouse is kinda bugged too
> fix wrong variable name, openChannelNameDialog on ctrl+t, give focus to new split

- src/messages/messagebuilder.cpp
Now inserts "https://" to links that previosly didn't have a scheme.
> Added support for non http/https links.

- src/channel.cpp
- src/channel.hpp
- src/ircmanager.cpp
- src/widgets/chatwidget.cpp
- src/widgets/chatwidget.hpp
- src/widgets/chatwidgetheader.cpp
- src/widgets/chatwidgetheader.hpp
Checks if a channel is live every 60s and changes the name in header to reflect the status. Tooltip on hover over the chatwidgetheader shows the same info that it did in the old Chatterino.
Also adds the correct Twitch-API v5 id to the channel.
Adds a viewer list contextmenu option in the header. Viewer list is dockable and and has a live search field.
> Adds viewer list + livechecks

- chatterino.pro
- dependencies/libcommuni.pri
Just a simple convenience fix.
> Made libcommuni show as 'libcommuni' in Qt Creator instead of 'src'

- src/ircmanager.cpp
- src/ircmanager.hpp
- src/messages/messagebuilder.cpp
- src/messages/messagebuilder.hpp
- src/twitch/twitchmessagebuilder.cpp
Changed the way timestamps are appended.
The current solution of making sure there are no duplicate messages isn't very pretty. It could misbehave if the partChannel would actually part.
> Implemented loading recent messages.

- src/widgets/tooltipwidget.cpp
It fixes the issue of the new "window" in the taskbar.
At least in Linux
> Added Qt::X11BypassWindowManagerHint to the WindowFlags of ToolTipWidget

- src/widgets/split.cpp
fixes #244 
and another bug where you still got notified of new messages in a closed split in a tab
> Remove the Twitch Channel when closing the split

- src/singletons/emotemanager.cpp
not entirely sure why the whole thing with FillInFFZEmoteData is the way it is so not sure if this is the best solution, but at least now a Channel FFZ Emote is a Channel FFZ Emote again instead of giving everything Global FFZ Emote on calling that function
> actually display channel ffz emotes as channel ffz emotes

- README.md
source (minigw is basically mini GCC so it applies)
https://wiki.gentoo.org/wiki/MAKEOPTS
For example, with the old tip a 4600k with 4 cores and 4 threads would spawn 8 jobs which is a waste of ram. (and slows it down a little) https://blogs.gentoo.org/ago/2013/01/14/makeopts-jcore-1-is-not-the-best-optimization/
>  correct -j flag

- README.md
I have been using these flags while compiling without any problems so I
thought I'd share them. [Here is a really long source on GCC
optimization](https://wiki.gentoo.org/wiki/GCC_optimization) -O3 might
work with Chatterino however there might be no speed gains (even
negative in some cases (and also it increases compilation time)) so that's why I use -O2
> Aditional compile flags

- src/providers/twitch/twitchchannel.cpp
- src/providers/twitch/twitchchannel.hpp
- src/widgets/helper/splitheader.cpp
It wasn't updating the info text properly because it never changed the state again after since it would always return before.
> Fixed live status not updating when channel is online.

- src/singletons/emotemanager.cpp
when copying FFZ emotes such as "4House ZreknarF Keepo"
the name of the emote ( Image::getName() ) returns the "code + \<br>Global/Channel ffz emote" instead of just the code of the emote
-> "4House\<br/>Channel FFZ Emote ZreknarF\<br/>Global FFZ Emote Keepo "
this fixes correct tooltiping the emote
(and is now in sync with bttv and twitch emotes in the same file)
> fix copying <br>Global/Channel ffz emote after copying a ffz emote

- src/providers/twitch/twitchmessagebuilder.cpp
Currently it uses "Twitch Bits(x)". Changed to "cheer x" to be consistent with Twitch text overlay.
> Changed bit badge overlay text to be consistent with Twitch

- BUILDING_ON_MAC.md
You can easily install qt with brew, so last 3 entries are taken from linux instructions.
Tested on macOS High Sierra (but should work on all macOS versions supported by brew/qt)
> Update macOS instructions

- src/widgets/helper/channelview.cpp
Currently you can only copy the emote link into clipboard.
This change allows you the additional option to directly open it instead.
> Add the option to either copy / open an emote link

- src/widgets/logindialog.cpp
- src/widgets/settingspages/accountspage.cpp
Previously it just stayed behind. i only tested this in windows since I don't have any OSX/Linux vms but raise() should just work on them.
> Make the 'add account' popup box go to foreground

- src/widgets/helper/channelview.cpp
this should fix the broken tooltip sizes when you hover over Word s
> Adjust tooltip size

- src/widgets/accountswitchpopupwidget.cpp
In reference to issue #515 
This fixes it for me on Linux.
Not sure if this breaks anything on Windows. Needs some testing.
> Fix Account Switcher Popup Widget On Linux

- src/widgets/settingspages/ModerationPage.cpp
Not implemented: full link on hover
This fixes some issues when the file-url is too long and messes up the width of the settings window.
> The file-url for logging is now displayed as a smaller link

- src/providers/bttv/BttvEmotes.cpp
- src/providers/ffz/FfzEmotes.cpp
As recommended by pajlada [here](https://github.com/fourtf/chatterino2/issues/595#issuecomment-403852365).
> Fix new emotes not loading properly because of cache

- src/widgets/Window.cpp
Fixes the issue when trying to make the chatterino window smaller with long usernames
#528
> Minimum window size is limited by the user name

- src/common/LinkParser.cpp
- src/messages/MessageBuilder.cpp
- src/widgets/helper/ChannelView.cpp
Supports hyperlinking spotify: links such as
> spotify:search:omg%2bwtf%2b%ef%a3%bf%c3%9f%e2%88%82%2bbbq
> 
> spotify:track:3oN2Kq1h07LSSBSLYQp0Ns
> 
> spotify:album:6I58XCEkOnfUVsfpDehzlQ
> 
> spotify:artist:6MF9fzBmfXghAz953czmBC
> 
> spotify:user:radiofy.se:playlist:50aHxwoLzq2fvo5g97c2T2
> 
> spotify:user:radiofy.se
> Add support for spotify hyperlinking

- src/common/LinkParser.cpp
Right now it's matching links even if they have garbage text in front of it. For example, `sahttp://www.google.com`
This change fixes that. Requiring the matching to start at the beginning of the string.
> Fix match linking

- src/widgets/helper/ChannelView.cpp
- src/widgets/splits/SplitHeader.cpp
Fixes issues where channel split header, right click menu, room options were showing up partially cut off by the screen when using them near the edge of the screen.
Fixes #517 
Fixes #571 
Fixes #572
> Fix QMenus from starting out of screen boundaries. Fixes #517 #571 #572

- src/widgets/dialogs/EmotePopup.cpp
There was two instances of Global BTTV emotes in the Emote Popup global tab.
Changed the second instance to Global FFZ emotes.
> Fix Global FFZ emotes in Emote Popup

- src/widgets/splits/SplitInput.cpp
I found out that if I just press 'Enter' (send empty message) or send messages with spaces, they will be stored in the message history.
I think it doesn't have to work that way.
> Don't add empty messages to message history.

- src/providers/twitch/TwitchMessageBuilder.cpp
- src/widgets/dialogs/UserInfoPopup.cpp
This small change makes correct case of nicknames in UserInfoPopup window and right-click mentions.
At first I wanted to add some getDisplayName/setDisplayName methods, but then I realized there was easier way.
As far as I could see in code and test behaviour of program, it doesn't break anything.
> Set displayName to UserInfo link as value.

- src/widgets/helper/ChannelView.cpp
At the moment, if `linksDoubleClickOnly` option is enabled, emotes from Emote Popup are not added to the input field.
At first sight it seems that line `this->linkClicked.invoke(link);` should be added to `mouseDoubleClickEvent` to fix problem.
But I think `linksDoubleClickOnly` should be ignored, because double click on emotes to add them is not obvious.
> Fixed double click in emote popup.

- src/messages/Link.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/widgets/helper/ChannelView.cpp
I improved work of the right click on nickname a little. 
Now, if you right click on user that whispered to you, `/w` is automatically added to input field to answer him.
(And finally dynamic_cast is collapsed to condition!)
> Added right-click on nickname to reply on whisper.

- src/widgets/settingspages/KeyboardSettingsPage.cpp
- src/widgets/splits/SplitInput.cpp
- src/widgets/splits/SplitInput.hpp
I dunno why it hasn't been done yet, but I added hotkey `Ctrl+E` to open the Emote menu.
If I have option `Show input box when empty` disabled, then I can open the Emote menu only if I write something. If I want to send one smile, I need to insert space to see button for the Emote menu. 
So I think hotkey here is very suitable.
I hope you have nothing against adding hotkey.
> Added hotkey for Emote menu.

- src/widgets/Scrollbar.cpp
- src/widgets/Scrollbar.hpp
- src/widgets/helper/ChannelView.cpp
Every new feature must has issues. 
So "Clear messages" has one issue too! =)
If user has highlights in scrollbar, they will be shown even after the chat has been cleared.
So this PR just clears highlights in scrollbar with messages.
> Clear highlights scrollbar with messages.

- src/widgets/splits/SplitInput.cpp
This PR slightly improves insertion of emotes from popup.
If there is character before cursor, space is automatically inserted before emote.
> Improved insertion of emotes from popup.

- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
Can't figure out why `const Communi::IrcMessage *ircMessage` variable is passed, so I conclude that this is just a useless argument.
> Removed useless arg from appendTwitchEmote().

- src/widgets/helper/ChannelView.cpp
Scrollbar highlights in `/mentions` tab is pretty useless thing. 
Any message that appears there will be highlighted on the scrollbar, so whole scrollbar is always red and it doesn't make sense.
> Dont add scrollbar highlights in /mentions.

- src/widgets/splits/SplitInput.cpp
This tiny PR fixes focus issue with opened Emote popup.
> Activate opened emote popup.

- src/widgets/helper/NotebookTab.cpp
- src/widgets/helper/NotebookTab.hpp
Implements a Chatterino 1 feature. This could also be saved in the settings as well but in my opinion it shouldn't. If that is something people want then I can implement it.
Also disables switching tabs if right clicking on another tab as that is just annoying if you don't want to switch tabs yet still want to change the tab highlighting rule.
Fixes #699
> Option to disable highlight of tab; disabled switching tabs by only right clicking

- src/widgets/settingspages/LookPage.cpp
Just a simple one-character typo fix.
> Fix typo: "authority badges"

- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitHeader.hpp
So basically the `loadEmotes` function from twitchaccount seems perfectly capable of reloading all the subscriber emotes long after init, it even clears the list nicely, its just never done in the current program. This pr just adds a convenient button for it under reload channel emotes.
From my brief testing it seems to work perfectly fine and doesn't break anything, quite convenient for gift subs nanHead
> add menu option to reload subscriber emotes

- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
- src/messages/Selection.hpp
- src/messages/layouts/MessageLayout.cpp
- src/messages/layouts/MessageLayout.hpp
- src/messages/layouts/MessageLayoutContainer.cpp
- src/messages/layouts/MessageLayoutContainer.hpp
- src/messages/layouts/MessageLayoutElement.cpp
- src/messages/layouts/MessageLayoutElement.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/ChannelView.hpp
Also fixes an unrelated bug(was already happening in earlier versions) which messed up the drawing of the selection box as seen in [this gif](https://i.imgur.com/7Ka2NFO.gifv).
Fixes #559
> Adds selecting the hovered word by double-clicking

- src/RunGui.cpp
- src/util/WindowsHelper.cpp
- src/util/WindowsHelper.hpp
Added a winapi-call to OleFlushClipboard before exiting the application. This fixes #639 
I don't know if the call is on the right location in `RunGui.cpp` - maybe there's a better function that gets triggered before exiting chatterino?
> added winapi-call to flush clipboard

- chatterino.pro
- src/widgets/Window.cpp
- src/widgets/splits/ClosedSplits.cpp
- src/widgets/splits/ClosedSplits.hpp
- src/widgets/splits/Split.cpp
since ctrl+shift+t is already used to open a new tab, the hotkey is ctrl+g atm
when you close a split, you can reopen it with ctrl+g and it opens in the correct tab and also selects it into foreground
when you closed the tab, the split gets open on currently selected tab
> ClosedSplits feature (ctrl+shift+t in browsers)

- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/widgets/helper/ChannelView.cpp
After @pajlada added a Live status indicator, `tabHighlightRequested` signal in `TwitchChannel` became unused and can be safely removed.
> Removed unused signal in TwitchChannel.

- src/widgets/splits/SplitContainer.cpp
right now it is not used anywhere, but while trying out a feature i wanted to implement, this was a problem
> correct getSplitCount

- src/messages/ImageSet.cpp
- src/messages/MessageElement.cpp
The emote scale slider now works again.
It also contributes to the image set calculations, which figures out which of the images we should load from the image set
> Fix emote scale

- src/widgets/splits/SplitInput.cpp
Should stop messages sent with ctrl+enter from being left out of history(#810), from brief testing it seems to do just that.
> save messages sent with ctrl enter to history as well

- src/messages/MessageElement.cpp
Fixes #817.
Now doesnt scale badges at all, instead of scaling half of them.
> fixed badges scaling with emote scale slider #817

- chatterino.pro
- src/providers/ffz/FfzModBadge.cpp
- src/providers/ffz/FfzModBadge.hpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
Fixes #819.
It works, but the code is quite lidl.
Using Image::pixmap() always returns boost::none for some reason.
> [WIP] custom ffz moderator badges #819

- src/widgets/dialogs/LogsPopup.cpp
Second getLogviewerLogs() call causes the QMessageBox double open.
Call should only occur when the ID is successfully received.
> Removed second unnecessary getLogviewerLogs() call.

- src/widgets/dialogs/LogsPopup.cpp
This PR allows user to close LogsPopup window with one click on QMessageBox, as the logs can not be found and window becomes useless.
Of course this PR works only with this: https://github.com/fourtf/chatterino2/pull/835.
Because second QMessageBox will try to close already closed window and chatterino2 will just crash.
> Added closing LogsPopup with QMessageBox.

- src/widgets/dialogs/LogsPopup.cpp
- src/widgets/dialogs/LogsPopup.hpp
1. Removed getting channel ID from third party service and placed getting ID with own implementation which Chatterino2 has already.
2. `roomID_` is only used in one place, so there is no need to have it in header, better to pass it as argument. Together with this removed useless casts `QString -> int -> QString` of `roomID`.
3. TwitchChannel dynamic cast is used in three places only to get `channelName`, I collapsed dynamic cast and placed it in one place.
There will probably be a conflict with my previous PR, because I separated fix, feature and refactor into several PR's. ¯\_(ツ)_/¯
> Refactored LogsPopup.

- src/widgets/helper/NotebookTab.cpp
even if 'enable highlighting on new message' is disabled #800
> Properly displays mentions in splitheader-tabs

- src/widgets/helper/ChannelView.cpp
Fixes the intended 1s pause when hovering over a message (if enabled in settings). fixes #527
> Fixed pause on mouse hover

- src/widgets/dialogs/SettingsDialog.cpp
from what I can tell this is what saves all the preferences correctly, seems to work after clicking Ok and closing client abruptly (kill, turn off computer etc)
> save settings after clicking ok

- src/widgets/BaseWindow.cpp
There's a pretty unobvious bug here. Windows only.
If user maximize window by drag and drop to top of screen, 'Unmaximize' button starts working only after second click.
The easiest way I've found to fix this bug is to simply change the condition from `this->windowState()` to `_maxButton->getButtonStyle()`.
> Fixed Unmaximize button in title bar for Windows.

- src/widgets/splits/SplitInput.cpp
checking it like this makes it worth with both ctrl+enter and ctrl+numlock enter, not entirely sure why it worked before with == at all
fixes #832
> fix ctrl not registering with numlock enter

- src/widgets/dialogs/LogsPopup.cpp
This fixes https://github.com/fourtf/chatterino2/issues/863 .
By the way crash occurred not only in the channels that supported online logs.
> Replaced caller in LogsPopup.cpp.

- src/providers/twitch/TwitchMessageBuilder.cpp
- src/widgets/settingspages/GeneralPage.cpp
Turbo badge was in the global authority enum, moved to vanity
> Moved turbo badge to vanity

- src/messages/MessageBuilder.cpp
> If bold usernames was ticked it wouldn't show who the automod caught

- src/widgets/AccountSwitchPopupWidget.cpp
needed for some tiling wms to stop tiling this popup window, similar to the UserInfoPopup, which does work fine.
> add account switcher popup flag for linux

- src/widgets/settingspages/GeneralPage.cpp
The settings page got changed at some point but these fully functional settings were never added back, this merely adds checkboxes for those existing settings back.
will close #907
> add back settings for hiding buttons

- src/providers/LinkResolver.cpp
Don't make any requests to get link info while the setting isn't enabled, resolves #988
> disable requests to resolve link info when its disabled

- src/messages/layouts/MessageLayoutContainer.cpp
See #906 
I had this patch enabled for a few months now and really the only thing it breaks is the reconnected/etc messages. I think those messages being misaligned is preferable to every emote being cut off, personally.
This is the same as #906 but as requested by @Ckath into `pajlada-dev` for testing/development purposes.
> stop emotes from being cut off (pajlada-dev)

- src/widgets/helper/ChannelView.cpp
- src/widgets/settingspages/ModerationPage.cpp
Allows users to use `{channel}` in moderation actions
Also this might be a good opportunity to add `{uuid}` maybe so you can make a /delete moderation action?
> Mod action channel replacement

- src/singletons/Settings.hpp
- src/singletons/Theme.cpp
- src/singletons/Toasts.cpp
- src/widgets/settingspages/NotificationPage.cpp
I kinda messed up with my committing so I guess this is two changes in one .....
First change:
Implements #710
Added options for opening streams from clicking the toas notficiation: (according to options in splits)
- open in browser
- open player in browser
- open in streamlink (needs to be tested, but should in theory work, since I only use the already existing function)
- don't open the stream (in case someone wants to prevent opening streams "by accident")
Second change:
Quick fix for #939 
Hidden setting introduced in PR #744 was setting a "default" highlight color. 
I changed it so the defaults depends on the basic hue of the theme. The hidding setting will only overwrite if it is populated in settings.json.
As mentioned in #703 a proper theme support for this should be implemented …
> Opening streams from toast + quickfix highlights in light theme

- src/providers/twitch/TwitchChannel.cpp
Related to https://github.com/fourtf/chatterino2/pull/1019 . This character (\uE0000) appears to be not visible to users that had \u2800 visible.
> Change to new character to make duplicate message error bypass work again

- src/widgets/splits/SplitContainer.cpp
Lets respect Retina screens a little more.
This PR sets `ChatMedium` font for drawing text in empty tabs.
Before/After for Mac.
Before/After for Win.
> Fixed display of text message in empty tabs for Retina screen.

- .travis.yml
This PR adds Travis CI for OS X.
Previous linux content in `.travis.yml` was never used so it was removed.
This PR also closes #418.
> Edited .travis.yml to add compilation and deployment for OS X.

- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
1. before saving the window-layout a backup will created to avoid corruption due to crashes while saving
2. when starting chatterino and the window-layout file returns an empty window layout (due to corruption) the backup will be read and the layout will be build from this data
(worked with the file I managed to corrupt and a proper backup file, but it's hard to test 100% since the issue is not as easily reproducable. also works with "non-existing" file if backup file exists)
> implemented fallback logic for corrupted window layout 

- BUILDING_ON_LINUX.md
Checked Chatterino2 on [NixOS](https://nixos.org/). Builds and works quite well. Here are instructions just in case.
May I also contribute Chatterino2 to https://github.com/nixos/nixpkgs so it's available to everybody who uses NixOS?
> Add NixOS Building Instructions

- src/messages/Message.hpp
- src/messages/MessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/widgets/helper/ChannelView.cpp
Added additional parameter for moderation buttons as requested in #851
Implemented new variable messageText in message-class, since searchText also holds preceding username and colon. (set in src/providers/twitch/TwitchMessageBuilder.cpp )
```c++
this->message().searchText = this->userName + ": " + this->originalMessage_;
```
Also updated src/messages/MessageBuilder.cpp where searchTexts is set, so messageText is not empty.
>  Added {message} parameter for moderation buttons 

- chatterino.pro
- src/singletons/Settings.hpp
- src/singletons/Toasts.cpp
- src/singletons/Toasts.hpp
- src/widgets/helper/CommonTexts.hpp
- src/widgets/settingspages/NotificationPage.cpp
- src/widgets/settingspages/NotificationPage.hpp
- src/widgets/splits/SplitHeader.cpp
I think I kinda combined suggestions 2&3 from last merge:
2. Keep two maps (one map<enum class, string>, one map<string, enum class>) in parallel 
3. Make two functions, one for converting an enum class to string with a  simple switch-case, one for converting a string to an enum class with  some if/elseif stuff
Please review and maybe squash commits (?)
> Refactored "open from toasts"-implementation

- src/messages/MessageBuilder.cpp
- src/messages/MessageBuilder.hpp
we now only use the ctor that takes an explicit SystemMessageTag
> Remove unused messagebuilder constructor

- src/widgets/helper/ChannelView.cpp
Unfortunately, "More messages below" button is unreadable.
Before/After.
> Fixed display of text in Go to Bottom button for Retina screen.

- src/widgets/helper/SearchPopup.cpp
- src/widgets/helper/SearchPopup.hpp
close #997
Method `setChannel` moved unchanged in declaration order (as in header file).
> Close search popup window on Escape pressed

- src/providers/twitch/TwitchMessageBuilder.cpp
seems this is the place localized name is in, works out since it makes the search text name + localizedname: message
fixes #1046 
PS: I have no clue where to make prs to but I use the nightly personally so I'm just throwing all small fixes to that
> make it possible to search localized names

- README.md
I think we should change the download link from beta to nightly, since I feel that 90% of problems/questions people have with/about beta are answered with "download latest nightly" anyway.
> Changed Download link

- src/widgets/helper/ResizingTextEdit.cpp
- src/widgets/helper/ResizingTextEdit.hpp
fixes Chatterino#635
prepares for future implementation of Chatterino#79
Was a little bit hard to find the right combination for now. Pasting images from clipboard surpasses the check for dragging images in canInsertFromMimeData OMGScoots
> overrides QTextEdit insert methods

- src/widgets/splits/SplitHeader.cpp
Supa quick fix for #1100
Looks like this bug may come back in other places where we use `TooltipWidget`. For a permanent fix we have to go through all of the places that touch `TooltipWidget` and check if they clean the preview
image correctly.
It would be better to merge TooltipPreviewImage and TooltipWidget together and change `TooltipWidget::setText` to be
```c++
void TooltipWidget::setText(const QString &text, ImagePtr image = ptrnull);
```
But it's impossible right now, because TooltipWidget is located in appbase and `ImagePtr` is not visible there (it's located in the main chatterino repo). Plus we also need an access to `getApp()->windows->gifRepaintRequested`.
First step in implementing the permanent fix would be moving TooltipWidget to chatterino from appbase.
Any thoughts on the …
> (#1100) Clean TooltipPreviewImage on SplitHeader enterEvent

- resources/contributors.txt
- src/widgets/splits/Split.cpp
I realized, if you float the user list as a pop-up, it only looks half as horrible and people will be able to find the "close" button easier. 
This should be a little improvement until the actual refactoring happens.
default:
floated:
It will open in the middle of your chatterino, like this:
(which I think is tolerable)
> Make viewer list float

- src/messages/Message.cpp
- src/messages/Message.hpp
- src/messages/layouts/MessageLayout.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
Inline whispers will be displayed with background color used for highlighting
Should fix #881 & #1068
New Flag was needed to differentiate between normal whisper (highlighted) and whisper with mention.
New Setting: (default value: off)
New behaviour: (first whisper: off; second: on; third: whisper with mention)
> Added setting and functionality to highlight inline whispers

- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitHeader.cpp
Added the option to visit the subscription page of a channel from chatterino. 
Non affiliate & non partner link will automatically redirect to the channel page for now. I don't know if and how we should prevent this. As far as I can tell from [here](https://dev.twitch.tv/docs/v5/reference/channels/) the channel type ("affiliate", "partner" or "") can only be accessed via oauth token.
New menu entry:
Will open following page:
> Added Subscribe option to split menu

- appveyor.yml
- chatterino.pro
- conanfile.txt
Appveyor will now use Conan to install the OpenSSL library
To update the OpenSSL lib, replace the version number in `conanfile.txt` to a version available here: https://bintray.com/conan-community/conan/OpenSSL%3Aconan
> 👷 Manage OpenSSL libs with conan

- .travis.yml
The current dmg is inconvenient for updates of Chatterino. =(
So I changed the way of dmg file creation ([create-dmg](https://github.com/andreyvit/create-dmg)) and added `/Applications` symlink.
Also this PR adds icon for Chatterino volume.
Before and after patch.
> Improved dmg creation.

- src/widgets/Notebook.cpp
- src/widgets/Notebook.hpp
- src/widgets/Window.cpp
This simple PR brings a Chromium browser behavior pattern that allows us to open the last tab with `Ctrl + 9`.
UPD.
I added another commit to avoid a possible conflict from a new PR.
The second commit replaces the repetitive code of Ctrl+1-8 hotkeys with a single loop.
> Added ability to open last tab with Ctrl+9.

- .travis.yml
Accidentally removed the before_deploy step from Travis
> 🐛 Fixed Travis build tagging

- src/widgets/Notebook.cpp
- src/widgets/Window.cpp
- src/widgets/splits/SplitInput.cpp
Currently, the tab switching hotkeys are in two places –– in `Notebook.cpp` (for empty tabs) and in `SplitInput.cpp` (with double casting =( ).
I don't see any reason to have such a complicated implementation of the switching tabs, so I moved the `Ctrl(+Shift)+Tab` hotkeys to one place next to the other tab hotkeys.
> Moved to one place and simplified hotkeys of switching tabs.

- src/widgets/Window.cpp
Unfortunately, Qt still has a [bug](https://bugreports.qt.io/browse/QTBUG-8596), so to solve [this](https://github.com/Chatterino/chatterino2/issues/1176) issue we need to add the shortcuted actions to the QMenuBar. This will cause the hotkeys to be repaired.
> Added new submenu in menu bar for OS X to switch tabs with hotkeys.

- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
This PR adds a new setting to colorize usernames who have not set own color like Twitch does.
It is not always convenient to communicate with gray users. =(
Different colors can help you find the right user faster.
To implement this feature I created a new singleton `UsernameColors` class  that stores the colors of all gray users in the `std::map<int, QColor>`.
I'm not quite sure about the implementation, so I need your opinion.
By the way, as far as I could test, a `if (iterator != this->tags.end())` condition never becomes false and a `iterator.value().toString()` just returns an empty string.
> Added setting to colorize usernames who have not set own color.

- .travis.yml
- appveyor.yml
This PR adds a build date in the title for CI builds.
I think it's much clearer for users to see how old their version is.
I didn't test it on Linux, but I believe `date +%d.%m.%Y` will work in the same way on Linux.
Windows.
OS X.
> Added build date in Chatterino title for all platforms of CI.

- .travis.yml
I accidentally found that [one](https://github.com/Chatterino/chatterino2/pull/1172) of my previous commits broke the dmg creation, sorry. =(
At the moment a size of the dmg file is 3.4 MB, so the app does not contain Qt dependencies. And it works if the user updates the previous version, but a clean install does not work.
So, we have to use the `macdeployqt` again.
This PR fixes the mac deployment in some tricky way — we call `macdeployqt` to create the dmg file with dependencies and after this we call `create-dmg` to create the final user-friendly dmg.
It may seem that this is an overhead deployment, but I think it's not a big problem while we use the CI.
> Fixed dmg Travis deployment.

- src/widgets/dialogs/SettingsDialog.cpp
- src/widgets/settingspages/AboutPage.cpp
Hi! A while ago I saw streamer @rexim contributed to this project. I like the idea and although I'm not a C++ developer I wanted to contribute to chatterino as well. My changes are small and related to UI.
- Move "About" tab to make vertical margins consistent
- Increase settings window width to prevent creating horizontal scroll (It is caused by last line in "Attributions" group)
- Fix "show license" link width by using QLabel instead of custom SignalLabel (I couldn't find what's issue in SignalLabel)
> Fix Settings UI inconsistencies

- lib/appbase/BaseTheme.cpp
Fixes the following compiler warning:
```
../lib/appbase/BaseTheme.cpp: In member function ‘virtual void chatterino::BaseTheme::actuallyUpdate(double, double)’:
../lib/appbase/BaseTheme.cpp:65:16: warning: variable ‘bg’ set but not used [-Wunused-but-set-variable]
65 |         QColor bg =
|                ^~
```
Test compile with GCC 9 succeeded
> Remove unused variable

- src/widgets/splits/SplitHeader.cpp
This simple PR removes extra empty lines or ` - ` symbols when stream has no title or category.
> Improved stream header creation.

- src/widgets/AccountSwitchPopupWidget.cpp
This commit fixes the unresponsiveness of the "Manage Account" button (described in #1188).
Apparently, focus was lost when pressing down the mouse button. This is circumvented by setting the focus policy of the button to `Qt::NoFocus`.
The button then works as expected and opens the "Accounts" page in the preferences.
> Fix "Manage Accounts" button

- src/common/CompletionModel.cpp
- src/singletons/Settings.hpp
- src/widgets/helper/ResizingTextEdit.cpp
- src/widgets/settingspages/GeneralPage.cpp
At the moment, tab completion only considers emotes that start with the same prefix that is currently under the cursor.  This PR makes tab completion look for the current prefix at any position in emote names. This functionality has been requested in https://github.com/Chatterino/chatterino2/issues/591#issuecomment-431911018 and I certainly find it useful.
Note that this does not change the way username completion works. In order to complete a username, you will still have to type the actual start of the username. (**lada** would not complete to **pajlada**, for example.) 
I would prefer to keep it that way as user names generally don't really follow a pattern like emote names often do. (Like dance emotes often ending on "Pls".)
Only minimal changes were required since Qt provides us with …
> Make Emote Tab Completion Search for Substrings

- src/providers/irc/AbstractIrcServer.cpp
- src/providers/irc/AbstractIrcServer.hpp
- src/providers/twitch/TwitchServer.cpp
- src/providers/twitch/TwitchServer.hpp
I send the connection itself as a parameter to onConnected now since TwitchServer could not access readConnection, the other alternatives/additions I can think of are:
keep current solution, but rename onConnected to onReadConnectionConnected
replace current solution, make readConnection protected so TwitchServer can access it
Fixes #1229
> manually send req, this ensures we send it before JOIN

- src/providers/bttv/BttvEmotes.cpp
- src/providers/bttv/BttvEmotes.hpp
- src/providers/twitch/TwitchChannel.cpp
I didn't find the global emotes API so that still uses BTTV V2 API.
Fixes #1275
> Use BTTV V3 API for channel emotes

- src/controllers/highlights/HighlightModel.cpp
- src/controllers/highlights/HighlightPhrase.hpp
- src/controllers/highlights/UserHighlightModel.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/widgets/settingspages/HighlightingPage.cpp
This PR adds a setting that allows users to choose whether a highlight phrase should check for case or not. Works for Regex and regular substring patterns.
The default behavior is to match case-insensitively.
Fixes #1289.
> Add Setting for Case-Sensitivity in Highlights

- .github/ISSUE_TEMPLATE/bug_report.md
- chatterino.pro
- src/common/Version.cpp
- src/common/Version.hpp
- src/widgets/Window.cpp
- src/widgets/settingspages/AboutPage.cpp
This PR adds information about the program version to the "About" page.
As the program's version is also displayed in the window title (and to avoid code duplication), I put the "information parsing logic" in its own class at `common/Version.cpp`. Not sure whether this is the best solution.
The text in the version information box is copyable so that users can easily paste it when filing bug reports.
Also kind of related to #874.
> Add Version Information to "About" Page

- appveyor.yml
Fixes #1321
* Now downloads Conan using choco instead of pip (Temporary uses my Conan NuGet repo because the [version on chocolatey](https://chocolatey.org/packages/conan) still hasn't been updated)
* Runs `conan user` after installing
> 🐛 Fixed Conan failing to install the packages in appveyor

- src/common/Version.cpp
This is a follow-up to #1315.
The `CHATTERINO_NIGHTLY_VERSION_STRING` defines differ on Windows and macOS/Linux for some reason.
(See `appveyor.yml` and `travis.yml`, respectively.)
Therefore, the Windows version string looked really messed up.
I "fixed" this issue by splitting the define on spaces and only considering the first element of the split.
**Before:**
**After:**
> [Bug Fix] Fix Version String on Windows

- .travis.yml
Workaround for #1327.
This PR just adds a `sed` command to convert the wrong `-framework\` flags to the correct `-framework` flags. I think we should merge this until we can figure out what's actually wrong.
> [Workaround] "Fix" macOS Travis Builds

- src/widgets/helper/ChannelView.cpp
When opening channel "/mentions", after being pinged, old messages would be highlighted.
**Before**
> [Bug fix] Highlights in /mentions

- tools/clang-format-all.sh
I hope that this isn't depended on the `find` version (similar to how #1309 used to be) but when I run the `clang-format-all.sh` script, only `.cpp` files are operated on. Please check on your own systems.
I confirmed this when replacing the `-exec` part with a `-print`: It does not find any header files.
In this PR, I changed the expression to a regex that matches `.cpp` and `.hpp` files.
> Fix clang-format Only Reformatting .cpp Files

- src/widgets/helper/ChannelView.cpp
While tab-completing user names already respected the setting for mentions with commas, right-clicking user names did not.
This PR adds the missing check in `ChannelView::handleMouseClick`.
Fixes #1352.
> Fix Bug Regarding Mentions with Comma

- src/widgets/helper/ChannelView.cpp
Removes some dead code that prevented tooltips on badges etc. from showing while holding the control/alt modifiers.
Fixes #1292
> Fix tooltips in chat not showing on ctrl hover.

- conanfile.txt
The OpenSSL version needs to be the same as described here: https://wiki.qt.io/Qt_5.13_Tools_and_Versions
Otherwise, chatterino2 fails to connect with the message `this platform does not support OpenSSL`
> 🐛 Fixed OpenSSL version

- src/messages/layouts/MessageLayoutContainer.cpp
> Fix first line of emotes in emote picker window being shifted.

- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/widgets/splits/SplitHeader.cpp
**Description**
This PR solves issue #1264 
The format of the offline tooltip text is different so it can be easily distinguished when a stream is live. Timer for title update is currently set to 15 sec, it might be too low.
**Screenshots**
> Show the title when offline

- src/providers/twitch/IrcMessageHandler.cpp
Before checking show joined users would show parted and joined.
Now it only shows joined.
Parted will not show parted users before it didn't do anything!
Fixes #1367
> Now show joined setting doesn't also show parted and parted shows parted

- src/providers/twitch/TwitchBadges.cpp
Currently Chatterino uses the description from the global badge api, which has actively caused "issues" because whomever does this always seems to make a minor or major mistake on the descriptions.
Previously the Bit Leader badges and Direct Relief - Charity 2018 badges were blank because the description fields were blank but they were fixed via a ticket I put in to have them fixed.
It would also fix the 1000 Gifted Subs badge, as well the recently added founders badge. 
Twitch Admin and Staff as well would be cleaned up to be Staff and Admin respectively
> Switch Global badge Tool-tips from Description to Title

- README.md
- use a relative link to `.clang-format` in the repo
> fix clang-format file link in README.md

- BUILDING_ON_LINUX.md
- README.md
- rework build workflow for Fedora that uses the commandline
- document info on `gstreamer-plugins-good` being retired in f31
> Clean up build instructions for Fedora

- src/singletons/Theme.cpp
- src/util/StreamLink.cpp
The Microsoft Visual C/C++ compiler crashes when trying to optimize these lines in release mode.
```
"C:\Users\ignaz\git\chatterino2\build\chatterino.vcxproj" (default target) (1) ->
(ClCompile target) ->
C:\Users\ignaz\git\chatterino2\src\util\StreamLink.cpp(202,63): fatal error C1001: An internal error has occurred in the compiler. [C:\Users\ignaz\git\chatterino2\build\chatterino.vcxproj]
C:\Users\ignaz\git\chatterino2\src\util\StreamLink.cpp(202,63): fatal error C1001: (compiler file 'msc1.cpp', line 1529) [C:\Users\ignaz\git\chatterino2\build\chatterino.vcxproj]
C:\Users\ignaz\git\chatterino2\src\util\StreamLink.cpp(202,63): fatal error C1001:  To work around this problem, try simplifying or changing the program near the locations listed above. …
```
> Fixes C1001 compiler error on release builds with MSVC

- src/widgets/helper/NotebookTab.cpp
This PR fixes the possibility to close the tabs in the "Emotes" popup using the middle mouse button.
> Fixed closing tab with middle button when tab management is not allowed.

- src/providers/twitch/TwitchMessageBuilder.cpp
Now shows months in tooltip when hovering over the subscriber badge.
Since ```@badge-info``` only gives ```subscriber/{months}``` according to https://dev.twitch.tv/docs/irc/tags#globaluserstate-twitch-tags we use first index on the tag.
Closes #1418
> Now also shows months subscribed in tooltip

- conanfile.txt
Changes
* Conan now uses the packages from the official [conan-center](https://center.conan.io) 
* Updated openssl to `1.1.1d`
* Updated boost to `1.71.0`
I've tested this PR on windows, everything seems to work without any problems
> 📦 Switch to packages from conan-center && updated packages 

- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchEmotes.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
Fixes #1402 
This pr fixes some issues with the current bits being displayed.
1. Someone types something similiar to what Tetyys types (he's cheered one bit here):
New:
Old:
2. Bits should now display different numbers instead of all being the same
New:
Old:
3. Bits now get calculated how many are left (one bit cheered here)
New:
Old:
4. If the amount that is left is less than the next cheer string it will make it accordingly smaller
E.g: 1500 bits cheered and with the message (total written 1599):
```Cheer1000 Cheer100 Cheer100 Cheer100 Cheer100 Cheer99 Cheer100```
New:
Old:
> Fixing bits

- src/providers/irc/IrcConnection2.cpp
- src/providers/irc/IrcConnection2.hpp
If no PONG was received, force a reconnection.
Fixes #1164
How does this work?
Keep track of sent PINGs and PONGs.
Expect each PING to have a matching PONG.
If a PING does not receive a PONG by the time it's time for us to send another PING message (after 5+ seconds), we stop refreshing the reconnection timer and let it run out on its own (usually after another ~5 seconds).
This way of doing it is a little bit iffy because we have two connections. In the scenario where the entire connection actually dies, both the read and the write connection will die, probably around the same time, and both fire reconnect requests. this will disconnect and reconnect both the read and write connections. But this is not a worse solution than what we already have, it's just not perfect.
> Expect a PONG response to our PINGs.

- src/common/Env.cpp
I experience connection issues similar to these described in #1493 (no messages and users displayed) when running Chatterino in a firewalled environment (outgoing TCP connections to port 6697 blocked). It seems that a breaking change was introduced in PR #1449 (builds before this change worked well on the same machine/environment).
It seems that default Twitch IRC connection port was [accidentally(?) set from 443 to 6697](https://github.com/Chatterino/chatterino2/pull/1449/files#diff-cf97ac2da2381327578c41c94df81a77R62), as opposed to [defaults described in docs](https://github.com/Chatterino/chatterino2/pull/1449/files#diff-17a44c0332fd031df859f133db848ac1R30). Proposed change actually sets the default of `CHATTERINO2_TWITCH_SERVER_PORT` environment value to `443` and hopefully resolves …
> Connect to Twitch IRC server using port 443 instead of 6697

- chatterino.pro
- src/util/Clipboard.cpp
- src/util/Clipboard.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/splits/Split.cpp
Hello!
I'm a pretty heavy user of Middle Mouse click and Shift+Insert on Linux (those shortcuts pull data from the primary selection rather than the clipboard, the difference between them is summarize really well here: https://unix.stackexchange.com/a/139193). And the fact that Chatterino is the only app on my setup that does not sync with the selection makes it really inconvenient for me. So I went ahead and tried to fix it. Maybe the fix will be useful for other Linux users.
Please, let me know what you think.
> Synchronize Clipboard with Primary Selection on Linux when copying

- src/providers/irc/IrcConnection2.cpp
This payload was initialized before main was called, so before the
QApplication was initialized. This broke our portable checker
Fixes #1481
> Fix ping payload not breaking portable mode

- src/widgets/helper/ChannelView.cpp
Since #1320, subscription messages are treated as highlights in order to allow customization. This caused subscription messages to highlight the split(s) the message was received in. This is not intended behavior.
This commit fixes the issue by additionally checking if the `Subscription` flag is set on a highlighted message.
> Fix Subscription Messages Triggering Split Highlights

- src/controllers/highlights/HighlightPhrase.cpp
- src/controllers/highlights/HighlightPhrase.hpp
- src/widgets/settingspages/HighlightingPage.cpp
Fixes #1521, and some other minor changes.
Copying from 78fe404:
> Prior to this commit, the callback for reacting to user input on the
highlight table (namely, `HighlightingPage::tableCellClicked`) only
checked for the row number in order to determine whether preset
highlights (self highlights, whispers, and subscriptions) need to be
updated. Hence, changing rows 0 through 2 in the "User Highlights" tab
would also update the preset highlights.
>
> This commit adds a check to determine whether the callback was triggered
by the "Messages" highlight tab, or not.
> Better Highlights: Fix Unintentional Color Update

- src/common/Channel.cpp
- src/messages/Message.hpp
- src/messages/layouts/MessageLayout.cpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/IrcMessageHandler.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/Settings.hpp
- src/widgets/Window.cpp
- src/widgets/settingspages/GeneralPage.cpp
- src/widgets/settingspages/KeyboardSettingsPage.cpp
Hides (with several options) messages that are too similar and too close either in time, or based on previous messages by that same user
[old settings visual](https://user-images.githubusercontent.com/1310440/72208133-a58ac180-349f-11ea-92b5-7fe1d8359b93.png)
EDIT: new settings visuals
> Makes it possible to hide one man spam

- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
This PR is in response to #1523.
Whispers are now only added to the `/mentions` tab if they also match a user name or phrase highlight. On a related note, the `highlightVisual_` member has been removed as it is no longer necessary.
> Better Highlights: Rework Highlight Parsing Order

- src/common/CompletionModel.cpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
This attempts to fix https://github.com/Chatterino/chatterino2/issues/1552
When the "Only search for username autocompletion with an @" option is enabled, usernames will be omitted from the `CompletionModel` unless there's an "@" prefix
> Add option for username tab completion only with an @ prefix

- CHANGELOG.md
- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
this causes it to behave as it should, and not be scaled when emotes are
scaled. :)
Fixes #1491
> Make ModBadgeElement a descendant of BadgeElement instead of EmoteElement

- src/Application.cpp
- src/RunGui.cpp
- src/messages/Image.cpp
- src/messages/LimitedQueue.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/PubsubClient.cpp
- src/providers/twitch/TwitchAccount.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/NativeMessaging.cpp
- src/util/IncognitoBrowser.cpp
- src/widgets/AttachedWindow.cpp
- src/widgets/BaseWindow.cpp
- src/widgets/Notebook.cpp
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/splits/SplitOverlay.cpp
As mentioned in #1601, many uses of `qDebug()` are artifacts of previous development and no longer serve any real purpose. I tried to gather the uncontroversial ones in this PR.
Removal is split into multiple commits in order to be easier to review (and revert, if needed) but should be squashed on merge.
> Remove Debug Output In Many Different Places

- src/BaseTheme.cpp
- src/BaseTheme.hpp
- src/controllers/highlights/HighlightPhrase.cpp
- src/controllers/highlights/HighlightPhrase.hpp
- src/providers/colors/ColorProvider.cpp
- src/singletons/Theme.cpp
Prior to this commit, no default color was set when an "old" highlight phrase (one added prior to #1320 / 5957551) was deserialized. This commit makes highlight phrases uses the default self-highlight color for these situations. This approach is reasonably sensible since that color is also similar to the old highlight color.
Fixes #1565.
> Better Highlights: Fix Wrong Color for Migrated Phrases

- src/providers/twitch/TwitchMessageBuilder.cpp
Fixes #1612 by adding `cv` emotes to the zero width emote list.
> Hack fix for #1612

- src/widgets/settingspages/GeneralPage.cpp
Fixes #1605. Adds new timestamp options:
- 24 hours with seconds, can change width (`h:mm:ss`)
- 24 hours with seconds, cannot change width (`hh:mm:ss`)
- 12 hours with seconds, can change width (`h:mm:ss a`)
- 12 hours with seconds, cannot change width (`hh:mm:ss a`)
> Bring back seconds in timestamps

- src/providers/ffz/FfzEmotes.cpp
Fixes #1585
ffz currently adds no data in their json for the name of the badge, so it's fine to keep it hardcoded.
e.g https://api.frankerfacez.com/v1/room/id/43309508
> Changed text to moderator

- src/singletons/Settings.hpp
- src/widgets/settingspages/ExternalToolsPage.cpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitHeader.cpp
This PR adds a new simple external tool for opening streams directly in any video player that has built-in Twitch support and has own URI Scheme.
Sample use case:
- Install mpv+youtube-dl.
- Add a custom protocol for mpv to the system (`my-super-protocol://`).
- Add it to the chatterino settings.
- Open and watch any stream without streamlink.
<details>
</details>
> Added ability to open stream in external video player via URI scheme.

- src/messages/MessageBuilder.cpp
- src/providers/twitch/TwitchChannel.cpp
In web chat you get better timeout messages when you're the target. You also get to know the reason you were banned or timed out.
This makes it so you always subscribe to the pubsub topic providing this data, regardless of moderator status.
Fixes #962
> Get better timeout messages for self

- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
- src/widgets/dialogs/EmotePopup.cpp
- src/widgets/dialogs/EmotePopup.hpp
This attempts to fix https://github.com/Chatterino/chatterino2/issues/662
Emote popup position is stored in "window-layout.json". `closeEvent` is reimplemented in `EmotePopup` so that the popup position is saved through `WindowManager`.
> Make emote popup remember last position

- src/widgets/dialogs/EmotePopup.cpp
Currently, repeated launch of emote popup causes it to "drift". Use `offset=false` for `moveTo` so that emote popup does not shift positions on every launch.
> Fix emote popup position

- src/controllers/highlights/HighlightModel.cpp
- src/widgets/settingspages/GeneralPage.cpp
Previously the highlight setting said that the Redeemed highlights were bought with Bits
However, they're actually redeemed by Channel Points, so I updated the text.
> Clarified that Redeemed Highlights are from Channel Points, not Bits

- src/messages/Link.cpp
- src/messages/Link.hpp
- src/widgets/helper/Button.cpp
- src/widgets/helper/ChannelView.cpp
Fixes #1506
Now links can be opened with middle mouse button, the scroll cursor won't activate on links anymore.
> Handle middle mouse button on links differently

- src/providers/twitch/PubsubClient.cpp
- src/providers/twitch/PubsubHelpers.cpp
- src/providers/twitch/PubsubHelpers.hpp
A new moderator added pubsub event was added, which fires from web chat and from chatterino.
The old moderator added pubsub event was still there, slightly old syntax, but only fired from chatterino. We now only listen to the new moderator added pubsub event
> Only listen to new pubsub "moderator added" syntax

- src/main.cpp
I've started using dwm and wanted to make a special rule for the chatterino classname to all go to the same tag (Desktop). But chatterino doesn't right now provide a WM_CLASS variable in X11 for those windows. This will add that and a little more info about the application.
> Added chatterino as the application 

- src/widgets/helper/ChannelView.cpp
fixes #1656
Looks like this now
> move pause-icon to the left and increase size and visibility

- CHANGELOG.md
- src/singletons/Updates.cpp
- src/util/InitUpdateButton.cpp
On macOS, checking the web API for an update would always result in the "Failed to load version information" message. Also, the update message dialog could sometimes be off-screen to the left making the message unreadable.
Chatterino expected a JSON field "portable_download" for both Windows and macOS, but the web API only provides that field for the `/win/` endpoint. This results in macOS Chatterino always complaining that it couldn't check for an update.
Screenshot before:
Screenshot after: (I locally bumped version to test)
> macOS update checker fix

- src/widgets/BaseWindow.cpp
Moves the tooltip so it can no longer land under the mouse.
fixes #1683 
And it looks something like this:
> move tooltip when no space is left on the screen to opposite side of cusor

- src/providers/bttv/BttvEmotes.cpp
- src/providers/bttv/BttvEmotes.hpp
- src/providers/ffz/FfzEmotes.cpp
- src/providers/ffz/FfzEmotes.hpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/SplitHeader.cpp
Upon joining a channel or pressing F5, BTTV and FFZ emotes are
(re)loaded. This change adds visual feedback of the network requests and
their outcome, in the form of a system message in the associated
channel's chat window. These are the 8 possible system messages that can
be shown:
BTTV: emotes reloaded.
BTTV: this channel has no emotes.
BTTV: failed to fetch emotes. (timed out)
BTTV: failed to fetch emotes. (unknown error)
FFZ: emotes reloaded.
FFZ: this channel has no emotes.
FFZ: failed to fetch emotes. (timed out)
FFZ: failed to fetch emotes. (unknown error)
> Show visual feedback when BTTV and FFZ emotes are loaded

- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitHeader.hpp
Fetches a thumbnail for a stream on twitch and puts it into the splitheader tooltip.
This is the only thing I miss from only running streamlink
Issues right now:
- ~You have to hover over the header twice before it actually displays the thumbnail.~
- ~I think it downloads the thumbnail every time you hover it~
- Setting in general for disabling it because of data usage
How it currently looks:
> Thumbnails for stream inside of the splitheader tooltip

- src/widgets/BaseWindow.cpp
This fixes the "Always on top" setting on macOS. Previously, it only worked on Windows. It would be great if someone could check if this implementation also works on Linux.
Closes #1166
> Fix "Always on top" setting for macOS

- docs/ENV.md
- src/common/Env.cpp
- src/common/Env.hpp
- src/util/NuulsUploader.cpp
Nuuls' uploader software accepts `attachment` as a name of an image form field, but some other hosts don't accept that and use other names.  
This PR makes it possible to change that value with enviroment variable and with this change I can upload images to other uploaders that use multipart form data (like my server).
Since the URL of uploader can be changed with EVs, I thought it would be cool to have this small thing changeable as well.  
This PR also adds a missing newline in docs about changeable uploader's URL.
> Added possibility to change image uploader's form body with Enviroment Variables

- src/widgets/AttachedWindow.cpp
Fixed extension positioning. Fixes https://github.com/Chatterino/chatterino2/issues/1562
Tested in chrome on old twitch layout - works just fine. Tested in firefox on new twitch layout - works in theatre mode, is bugged in regular mode; this is an unrelated pr though.
> Fixed extension positioning

- src/util/NuulsUploader.cpp
- src/util/NuulsUploader.hpp
Closes #1678  
Added logging upload information to a file located in `{messageLogDirectory}/ImageUploader.csv`
I am not sure if the path I chose is okay, since `messageLogDirectory` contains logged messages in general, but there was no better existing path for that.  
Maybe creating another directory for misc logs can be an alternative, but I don't think this is necessary (as for now).
Logged stuff is comma-separated and in following format.
Tell me if the order and types of logged information are okay
1. Path to original file (may be empty on clipboard uploads)
2. Link to uploaded image
3. Current timestamp
4. Current channel's name
I also added uploader's responses to system messages that are being generated and send in current channel upon successful file upload - makes it possible to …
> Added logging for uploaded images

- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitHeader.hpp
It was unnecessarily taking too much space.
Before https://cdn.zneix.eu/EF8zEL8.png
I eventually removed it entirely after fourtf's comment.
~~After https://cdn.zneix.eu/6eRX2ze.png~~
~~![](https://cdn.zneix.eu/6eRX2ze.png)~~
We were talking about it with supinic on his stream and there was a suggestion to disable / remove this completely. Having an option to "disable help / tooltips" would be nice, but there's not so many of those things currently - maybe something could be added in the future if chatterino will have more help tooltips.
> Removed annoying help tooltip for splits

- src/main.cpp
When using `chatterino --version` it now also outputs commit (and date of build if on nightly), just like in Settings -> About:
I think it's a useful addition, especially when you work with nightly builds and want to quickly identify version without having to launch the app and going to settings.
> Made --version argument output consistent with AboutPage

- BUILDING_ON_FREEBSD.md
- README.md
Build succeeded and worked on FreeBSD 12.1 (see underneath). I felt like documenting the dependencies from the ports collection.
This has been tested under the following conditions:
```
$ uname -apKU
FreeBSD triton 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64 amd64 1201000 1201000
```
It may also work on older versions and (should definitely) on FreeBSD 13.0-CURRENT. Other processor architectures might support chatterino as well depending on the tier (and thus ports availability). See [https://www.freebsd.org/platforms/](https://www.freebsd.org/platforms/)
> Document FreeBSD build instructions

- src/controllers/commands/CommandController.cpp
adds completion for `/usercard`, `/follow`, `/unfollow`, `/ignore`, `/unignore`
> Add missing tab completion for commands

- src/controllers/commands/CommandController.cpp
- src/widgets/dialogs/UserInfoPopup.cpp
Closes #1750 
- /usercard command doesn't close the popup imidiatelly
- removed "Dialog" window flag. It seems to be unnecessary and causes issues - on left-clicking user name it sometimes didn't render unless I clicked 2-3 times. With that window flag removed there were no issues with left-clicking user names at all.
> Fixed usercard on linux

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/ChannelView.hpp
This ensures that the layout will survive for the lifetime of the menu,
so any of the menu actions can with confidence do things with the
layout, not having to worry whether it's dead or not.
This means that the user, while having the message menu open, could have
one extra MessageLayout alive. I have ensured that when the menu dies
the reference to the shared pointer dies with it.
Fixes #1783
> Message menu now holds a shared pointer to a layout

- src/widgets/settingspages/KeyboardSettingsPage.cpp
Added:
- Zoom out/in
- Reset zoom
- Reopen last closed split
- Select last tab
Also updated `Alt + arrows`, so its a bit more readable
Before: https://cdn.zneix.eu/ojr9PW9.png
After:
> Added missing Keybinds to settings page

- src/widgets/dialogs/EmotePopup.cpp
- src/widgets/splits/SplitInput.cpp
Moved `setStayInScreenRect` into `EmotePopup` constructor to avoid `moveIntoDesktopRect` early return.
> Fix emote popup remember last position 

- src/providers/twitch/TwitchMessageBuilder.cpp
With recent Twitch's changes for higher tier subs the sub badge tooltip was also updated in webchat and I though it would be a nice idea to have that behaviour in chatterino:
Webchat https://cdn.zneix.eu/XmR2hR6.png
Chatterino https://cdn.zneix.eu/6z3X5yX.png
> Added higher tier information to sub badge tooltip

- CHANGELOG.md
- docs/ENV.md
- docs/IMAGEUPLOADER.md
- src/common/Env.cpp
- src/common/Env.hpp
- src/common/NetworkRequest.cpp
- src/common/NetworkRequest.hpp
- src/singletons/Settings.hpp
- src/util/NuulsUploader.cpp
- src/widgets/settingspages/ExternalToolsPage.cpp
- src/widgets/splits/Split.cpp
I wanted to extend #1709 and #1712 by adding more config options for image uploader and changing CSV logs to JSON.
1. Aside from changing form field, I added an option to add extra header(s) defined by user, so it is possible to use hosts like imgur / s-ul, which need an authentication header.  
I decided that it will be the best to parse headers as a string. I know this may look wrong, but usually it is only one auth header and redesigning Settings page for handling names and values separetly is not worth it imo - it would also look too complicated.
2. I added handling JSON responses from those servers, so it is possible to tell chatterino where image link is in the JSON object.
3. Some services, especially imgur, support "deletion links", so I also added an option to specify those in …
> More image uploader services and json logging

- src/messages/MessageElement.cpp
The \x0f character unsets the current foreground and background colors
as well as other formatting which is currently not interpreted by Chatterino
> Adds support for \x0f formatting character in IRC.

- CHANGELOG.md
- docs/ENV.md
- src/common/Env.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/util/FormatTime.cpp
- src/util/FormatTime.hpp
> Handle conversion of historical CLEARCHAT messages to NOTICE messages in Chatterino instead of relying on the Recent Messages API to handle it for us

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
This makes it so that we consistently start with the same values after
having cleared a ChannelView.
Example place where this happens: UserInfoPopup when user messages are
loaded and refreshed
Fixes #1789
> Reset the lastMessageHasAlternateBackground{Reverse} values when clearing all messages in a ChannelView.

- CHANGELOG.md
- src/widgets/dialogs/SettingsDialog.cpp
- src/widgets/dialogs/SettingsDialog.hpp
CTRL+F now selects the Find text input in the Setting Dialog (and selects all text if there is any)
Fixes #1806
> [SettingDialog] CTRL+F now selects the Find input

- src/messages/MessageElement.cpp
Changed text-wrapping behavior. Removed the linebreak after wrapped text elements to improve the readability of messages containing wrapped words. 
Before:
After:
> removed linebreak after wrapped TextElements

- src/widgets/TooltipWidget.cpp
This patch specifically affects Linux, and aims to solve #1647 .
I haven't noticed any non-sway issues with this patch.
> Try simplifying tooltip flags

- src/singletons/NativeMessaging.cpp
- src/widgets/AttachedWindow.cpp
- src/widgets/AttachedWindow.hpp
I added support for moving the chat when using the Chatterino Native Host extension.
Extensions like BTTV allow you to swap sidebars, moving the chat div to the left side of the screen. Currently, Chatterino doesn't support this feature as it uses a static determination for where to put the chat (right side of window - chat width). 
Together with Chatterino/chatterino-browser-ext#19 , this solves that problem. Without the changes in the extension, the behavior defaults to the current behavior.
Current behavior:
With these changes:
> Added support for chat relocation when using Chatterino extension

- docs/ENV.md
recent-messages was recently switched to a rewritten "version 2" of the original service, which also meant that it finally got a proper website, which we can now link to. The website bundles information that was previously spread out over a ton of different places.
> update recent messages env documentation

- src/singletons/Settings.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/settingspages/GeneralPage.cpp
This attempts for fix https://github.com/Chatterino/chatterino2/issues/1820.
Apply `userPopup->setActionOnFocusLoss(BaseWindow::Delete);` only when the user has enabled the setting to "automatically close user popup when it loses focus". This will not close user popups created before toggling the option.
> Added setting to auto close user popup

- chatterino.pro
- src/Application.cpp
- src/messages/Message.hpp
- src/messages/MessageBuilder.hpp
- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
- src/messages/layouts/MessageLayout.cpp
- src/messages/layouts/MessageLayout.hpp
- src/providers/twitch/ChannelPointReward.cpp
- src/providers/twitch/ChannelPointReward.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/PubsubClient.cpp
- src/providers/twitch/PubsubClient.hpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- src/singletons/WindowManager.cpp
- src/util/RapidjsonHelpers.cpp
- src/util/RapidjsonHelpers.hpp
- src/widgets/Window.cpp
- src/widgets/helper/ChannelView.cpp
Adds parsing and showing of channel point rewards in channels.
Currently there is still one unfixable drawback: We can't get the channel point icon. Twitch uses their gql endpoint for the image and we can't/shouldn't access that.
> Channel point rewards

- src/messages/MessageElement.hpp
- src/messages/layouts/MessageLayoutContainer.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
Fixes the styling of the channel point reward message text by removing margin from the top of the reward text.
Example:
> Fix styling of channel point reward message text.

- src/widgets/AttachedWindow.cpp
Browser extension makes Chatterino crash, when the extension is running on Microsoft Edge. The logic for which browsers are allowed, **are hardcoded.** This fix adds `msedge.exe` to the logic in AttachedWindow..
**The crash itself when it does fail the logic *is not* fixed...** Or rather, I don't think Chatterino should crash when [it fails.](https://github.com/KararTY/chatterino2/blob/f83645382f14e6f4e0747d634056a760cce4a6ee/src/widgets/AttachedWindow.cpp#L187)
> fix: Crash on MS Edge browser ext connection

- CHANGELOG.md
- src/BaseTheme.cpp
- src/BaseTheme.hpp
- src/singletons/Settings.hpp
- src/widgets/Notebook.cpp
- src/widgets/Notebook.hpp
- src/widgets/Window.cpp
- src/widgets/helper/NotebookTab.cpp
- src/widgets/helper/NotebookTab.hpp
- src/widgets/settingspages/GeneralPage.cpp
Adds the option to use vertical tabs on the left side of the screen. Tabs fill from top to bottom and wrap into another column if necessary. 
Closes #388
<details>
<summary>Screenshots</summary>
</details>
> Vertical tabs

- CHANGELOG.md
- src/widgets/helper/CommonTexts.hpp
- src/widgets/splits/SplitHeader.cpp
Fixed the issue causing the whisper split to show "Open stream in browser" instead of "Open in browser"/"Open whispers in browser" - https://github.com/Chatterino/chatterino2/commit/8661c833123d06e2b8229fa3609487996a57911d
> Fix open in browser button for whisper split

- src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp
- src/widgets/dialogs/switcher/QuickSwitcherPopup.hpp
Fixes #1854.
Adds basic support for light themes in the Quick Switcher popup.
Don't think it's worth adding an own category in the `Theme` singleton for it. Correct me if you think otherwise.
> Quick Switch: Add support for light themes

- CHANGELOG.md
- resources/contributors.txt
- src/controllers/commands/CommandController.cpp
__I'm not sure if changes like this really deserve a changelog entry. Thoughts?__
Minor bugfix:
Opening a usercard via the `/usercard someone` command will now respect the "Automatically close user popup" setting.
> Usercard command fix

- lib/warnings.pri
The check for clang fails when `clang++` is installed as `c++`. This fixes it for me.
> fix clang check when clang++ is called c++

- CHANGELOG.md
- src/Application.cpp
- src/widgets/Window.cpp
- src/widgets/Window.hpp
On macOS, trying to display a dialog before showing the main window (like when starting minimized) leads to a crash. The dialog will now show before the main window is opened, preventing this issue.
As far as I know, this issue only existed on macOS.
> Changelog crash fix (macOS)

- CHANGELOG.md
- src/widgets/dialogs/UserInfoPopup.cpp
Don't make follow requests based on the check follow response.
This is done by deliberately setting and reading the enabled state of
the widget whenever the stateChanged event happens.
If the stateChanged event happens while the widget is not enabled, we
know the event must have been triggered by our "check user follow state"
event, and then we don't act upon that event
> Don't make follow requests based on the check follow response

- CHANGELOG.md
- chatterino.pro
- src/common/WindowDescriptors.cpp
- src/common/WindowDescriptors.hpp
- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
- src/widgets/splits/SplitContainer.cpp
- src/widgets/splits/SplitContainer.hpp
Previously, we were creating UI elements at while we were reading the window-layout.json file.
We now read the window-layout.json file fully first, which results in a
WindowLayout struct which is built up of a list of windows with a list
of tabs with a root node which contains containers and splits.
This WindowLayout can then be applied.
This will enable PRs like #1940 to start Chatterino with Window Layouts
that aren't defined in a json file.
This commit has deprecated loading of v1 window layouts (we're now on v2). If a v1 window layout is there, it will just be ignored and Chatterino will boot up as if it did not have a window layout at all, and on save that old window layout will be gone.
> Split up Window Layout loading into a loading and application stage

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
Middle click scrolling caused `QGuiApplication::screenAt(this->pos())` to return null and crash on Linux Mint 20, easy fix.
> fix a crash using middle click scroll on chat window

- src/widgets/dialogs/UserInfoPopup.cpp
~~`CHANGELOG.md` was updated, if applicable~~
VIP/un-VIP buttons that were added in #1996 will now only show if you are the broadcaster (like the mod/un-mod buttons).
> Only show VIP buttons if broadcaster

- CHANGELOG.md
- src/messages/MessageBuilder.cpp
- src/messages/MessageBuilder.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/util/IrcHelpers.hpp
Fixes inconsistent timestamps on messages received through the recent-messages API. 
Closes #1286
> Recent messages timestamp fix

- .gitignore
- CHANGELOG.md
- src/widgets/dialogs/SettingsDialog.cpp
Currently commands are only saved on exiting chatterino. I shutdown my computer without closing chatterino beforehand and always lose my new commands because of that.
With this PR commands are saved once you press the Ok Button in the Settings, similar to the rest of the settings.
> Commands are now saved upon pressing Ok in the settings window

- CHANGELOG.md
- src/messages/Link.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/widgets/helper/ChannelView.cpp
The message display when an OAuth token expires repeatedly lead to users asking about what they should do in order to fix it. This PR changes the error message in order to clarify that users need to re-add their account. Additionally, a link to the "Accounts" page is included in the message (see video).
Video: https://i.nuuls.com/v0qWI.mp4
> Improve "Login expired!" message

- CHANGELOG.md
- chatterino.pro
- src/main.cpp
- src/providers/IvrApi.cpp
- src/providers/IvrApi.hpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Kraken.hpp
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/UserInfoPopup.hpp
﻿We are using Leppunen's API here to determine user's subage to the current channel and since that API call also returns followage information I decided to utilize that and save ourselves an extra Helix API call.
I also added new files specifying new class and methods for Ivr API, which can be very easily expanded with new methods in the future if we ever have to do that.
Examples: 
<details>
<summary>Debian 10 with i3</summary>
</details>
<details>
<summary>Debian 10 with KDE Plasma</summary>
</details>
When I was coding I also saw couple unnecessary nitpicks which I fixed :)
Closes #1122 
Closes #1145
Closes #1946
> Added subage and followage to usercard

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
Fixes #2008.
Basically, different behavior happens because, in chat, emotes don't have a link, but in `EmotePopup` they do. So we need to check if its emote or not.
> Fix tooltip not showing in `EmotePopup`

- CHANGELOG.md
- src/providers/twitch/TwitchMessageBuilder.cpp
> Fixed missing timestamps on point redemption messages

- src/common/WindowDescriptors.cpp
~~`CHANGELOG.md` was updated, if applicable~~
(fixes bug in unversioned change)
Fixes a small bug introduced in #1964. "Moderation mode" would be written to the settings file but wouldn't be loaded. 
Closes #2032
> Make "moderation mode" setting persist

- CHANGELOG.md
- src/widgets/dialogs/EmotePopup.cpp
Made the current channels emotes appear at the top of the emote picker popup. This makes them easier to find and the user no longer has to scroll down the picker to get them. The remaining are ordered as nornal.
> Made the current channels emotes appear at the top of the emote picker

- CHANGELOG.md
- src/widgets/settingspages/GeneralPage.cpp
Prior to this commit, adding a `ColorButton` to a `SettingsLayout` via `SettingsLayout::addColorButton` lead to the button not respecting search queries. This is because they are not added to the layout in a `Group`.
This commit fixes the behavior, causing color buttons to behave like every other settings widget.
> Fix: ColorButtons in settings don't respect search

- CHANGELOG.md
- src/widgets/splits/EmoteInputPopup.cpp
- src/widgets/splits/SplitInput.cpp
Added emote completion with `:` to the whispers channel. It is limited to Twitch emotes and emojis. Global bttv and ffz emotes would be feasible, but require much more refactoring.
Closes (#2075)
> Added emote completion with `:` to the whispers channel

- CHANGELOG.md
- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitHeader.hpp
> Reset the timer & refresh thumbnail when changing split channel

- CHANGELOG.md
- src/widgets/settingspages/KeyboardSettingsPage.cpp
- src/widgets/splits/SplitInput.cpp
- Scroll up and down one 'page' with PageUp and PageDown
- Add PageUp and PageDown information on the Keybindings settings page
Fixes #2070
> Scroll in selected split with PageUp and PageDown

- src/common/Args.cpp
~~`CHANGELOG.md` was updated, if applicable~~
Fixes the "unknown option 'parent-window'" error that Windows users experience when using the browser extension by simply ignoring the command line option.
Fixes Chatterino/chatterino-browser-ext/issues/41
> Add parent-window option

- src/widgets/helper/ChannelView.cpp
~~`CHANGELOG.md` was updated, if applicable~~
(fixes bug from #1748)
This PR makes sure that messages retain their proper flags when being added to a `ChannelView` by copying the message flags before applying the `DoNotLog` flag. 
Fixes #2086
> Copy message flags to preserve highlights

- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/UserInfoPopup.hpp
- ~~`CHANGELOG.md` was updated, if applicable~~
not applicable, bug was introduced before stable release
- Split everything into 2 separate labels, so we won't have any issues with dank dpi (like pajlada had) and no resizing to minimum size is required (which was apparently broken on Windows xd)
- Decided to remove line between follow / sub age and other elements, which was rather not visible / very small and couldn't be seen anyway
- Added nice unicode characters for follow and sub label just to reflect webchat even more and look nicer
- Removed unnecessary QLabel include (which I believe was also introduced by me by an accident)
Previews:
<details>
<summary>Debian 10 with i3</summary>
</details>
<details>
<summary>Windows 10</summary>
</details>
Closes #2033, …
> Fixed some stuff regarding usercard

- BUILDING_ON_LINUX.md
- ~~`CHANGELOG.md` was updated, if applicable~~
not applicable
I tried compiling chatterino on completely clean arch linux today and I got some openssl error while running `qmake ..`. Turns out `pkg-config` was failing, because there was no such command.
Also added thread number to make since some users might not know about `-j` argument.
> Updated required packages for arch

- CHANGELOG.md
- chatterino.pro
- src/Application.cpp
- src/Application.hpp
- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
- src/messages/layouts/MessageLayout.hpp
- src/providers/ffz/FfzBadges.cpp
- src/providers/ffz/FfzBadges.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- src/singletons/Settings.hpp
- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
- src/widgets/helper/ChannelView.hpp
- src/widgets/settingspages/GeneralPage.cpp
Add support for FrankerFaceZ badges, partially solving #1658 (issue requested BTTV too).
1. Introduce badge provider,
2. Refactor `MessageElementFlag`s to be `int64_t` instead of `int` as there wasn't space for a new flag there, 
3. Add `MessageElementFlag::BadgeFfz`,
4. Create showBadgesFfz (`/appearance/badges/ffz`) setting, default is true,
5. Introduce checkbox for the `showBadgesFfz` setting,
6. Add a MessageLayoutElement for ffz badges, to color them properly.
> Add support FrankerFaceZ badges.

- src/controllers/highlights/HighlightModel.cpp
Fixes #2134.
This was an error introduced in ec94869 / #2036. Instead of the `Qt::CheckStateRole`, which stores the state represented in the table view, the `Qt::DisplayRole` was used. As per the [documentation], this always returns `false` in our use case.
[documentation]: https://doc.qt.io/qt-5/qvariant.html#toBool
> fix: showInMentions attribute is now serialized correctly

- CHANGELOG.md
- src/common/FlagsEnum.hpp
- src/controllers/commands/CommandController.cpp
- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
- src/widgets/AccountSwitchPopup.cpp
- src/widgets/BasePopup.cpp
- src/widgets/BaseWindow.cpp
- src/widgets/BaseWindow.hpp
- src/widgets/Notebook.cpp
- src/widgets/Window.cpp
- src/widgets/dialogs/ColorPickerDialog.cpp
- src/widgets/dialogs/ColorPickerDialog.hpp
- src/widgets/dialogs/QualityPopup.cpp
- src/widgets/dialogs/QualityPopup.hpp
- src/widgets/dialogs/SelectChannelDialog.cpp
- src/widgets/dialogs/SettingsDialog.cpp
- src/widgets/dialogs/SettingsDialog.hpp
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/UserInfoPopup.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/DebugPopup.hpp
- src/widgets/settingspages/AboutPage.cpp
- src/widgets/settingspages/GeneralPageView.cpp
- src/widgets/settingspages/HighlightingPage.cpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/SplitHeader.cpp
This should hopefully fix a lot of issues people run into using tiling window managers.
There are a few more places that should start using BaseWindow with the Dialog flag or BasePopup instead, but that can come later. For now, this is in a testable phase.
The windows that should work better now are:
* Streamlink quality popup (Can temporarily be accessed by typing /xd in a split)
* Emote input popup (The one that pops up if you type `:fors` and that suggests `forsenE`)
* Emote menu (Cccessed by pressing the smiley face in the bottom right of a split or pressing CTRL+E)
* Channel changer dialog (Accessed by pressing CTRL+R or pressing the slim hamburger menu and clicking "Change Channel")
* Settings dialog (Accessed by pressing CTRL+P or pressing the cogwheel button)
* Tutorial videos …
> Use Qt's dialog where applicable

- src/widgets/dialogs/SettingsDialog.cpp
- ~~[ ] `CHANGELOG.md` was updated, if applicable~~
Fixed a bug introduced after last stable release
Since there was a navigation section added to `Settings -> General` there was an annoying horizontal scrollbar because the window wasn't wide enough and since it was bothering me so much I decided to make a quick fix for that.
Before:
https://cdn.zneix.eu/cuIZ3Os.png
After:
https://cdn.zneix.eu/mOgd1re.png
> Fixed settings dialog size

- CHANGELOG.md
- src/providers/twitch/TwitchMessageBuilder.cpp
Fixes #2125 
Because an empty pattern always has a match, it'll endlessly populate `originalMessage_` with `replace` string, so simply move the `isEmpty` check.
> Fix `runIgnoreReplaces` fall into infinity loop

- CHANGELOG.md
- src/BaseTheme.cpp
- src/BaseTheme.hpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- ~~[ ] `CHANGELOG.md` was updated, if applicable~~
not applicable
I applied some suggestions about placeholder text being a bit too 'easily readable' and made it slightly lighter to not mix with color of system messages and message timestamps.
I also read that tooltip might've been causing some issues on non-twitch channels, so I removed it (though, it only makes sense in twitch channels anyway).
> Improved textEdit placeholder

- CHANGELOG.md
- src/providers/twitch/api/Kraken.hpp
- src/widgets/dialogs/UserInfoPopup.cpp
Added a simple fix that also updates `nameLabel` in usercard to a proper display name if user is resolved correctly. It's a nice thing making usercard a little bit more useful :)
> Ensure Twitch username in UserCard uses display name from API

- CHANGELOG.md
- src/widgets/helper/SearchPopup.cpp
- src/widgets/helper/SearchPopup.hpp
- src/widgets/splits/Split.cpp
Fixes #2154. This is a follow-up to #1843 where we missed to also adjust the `SearchPopup`.
I have only tested this change on sway and while it is unlikely for other OS/WM to break existing behavior with this, we should probably test them regardless.
> [Fix] Make SearchPopup a BasePopup

- CHANGELOG.md
- src/providers/ffz/FfzEmotes.cpp
Apparently, the FFZ API can return `null` values for emote URLs. This PR treats `null` values the same as if they were missing from the JSON response.
See https://github.com/Chatterino/chatterino2/issues/2191#issuecomment-728278070 for more info
Fixes #2191
> Fix FFZ emote assertion crash

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
(**Note**: I also included the initial attempt at fixing this issue (#2090) in order to make the development process more trackable.)
Fixes #2195, fixes #2196.
This PR can be seen as a follow-up to https://github.com/Chatterino/chatterino2/pull/2090.
Apparently, `boost::optional` did not make a proper copy of the message flags when just using the assignment operator. This commit is explicit about copying, and preserves the message flags.
> [Fix] Use copy instead of reference for overriding message flags

- src/singletons/Paths.cpp
Fixes a `QDir::mkpath: Empty or null file path` error on startup.
> check path is not empty

- BUILDING_ON_FREEBSD.md
- BUILDING_ON_LINUX.md
- BUILDING_ON_MAC.md
- BUILDING_ON_WINDOWS.md
- CHANGELOG.md
- chatterino.pro
- Updated minimum required and latest Qt versions
- Added Qt version check to chatterino.pro
As discused on Chatterino Discord, we now have methods in our code such as [QOalette#placeholderText](https://doc.qt.io/qt-5/qpalette.html#placeholderText) in https://github.com/Chatterino/chatterino2/blob/master/src/widgets/splits/Split.cpp#L321-L322 which were introduced in Qt 5.12.0, updated documentation to reflect those changes.
> Updated minimum required Qt versions

- src/widgets/dialogs/ChannelFilterEditorDialog.cpp
Undo's the order change in aa4326f which broke the value dropdown
> Fixes the dropdown order in channel filter dialog

- CHANGELOG.md
- src/providers/twitch/TwitchMessageBuilder.cpp
Made "raw-mentions" consistent with @mentions in setting bold usernames and being able display usercard by clicking. To achieve that, I added a second, simple regex; similar to `mentionRegex`.
https://cdn.zneix.eu/2LdNrGt.png
I also decided to add colon to special characters that will not have influence on not resolving usercard, because many chatters often use "Copy full message" from message context menu and paste that in chat, which has format similar to `13:37 zneix: message xd` and it is pretty convenient to have it resolve to mention as well.
> Fixed "raw mentions" not being clickable with special characters appended to them

- CHANGELOG.md
- src/widgets/settingspages/KeyboardSettingsPage.cpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitHeader.cpp
Added a keyboard shortcut (Ctrl+F5) for "Reconnect"
> Add Ctrl+F5 as a shortcut for reconnect()

- CHANGELOG.md
- src/providers/twitch/TwitchEmotes.cpp
- src/widgets/helper/ChannelView.cpp
As discussed on pajlada's stream earlier today, I added a link to context menus pointing to `twitchemotes.com/emotes/%1`. I am aware that links might sometimes not work in some weird edge-cases (e.g. event emotes from qa_tw_partner), but I don't think we have any other alternative than twitchemotes.com for Twitch emote links and I think it's decent in general and I was missing similar functionality to quickly get emote link with some more imformation than just a .jpg file from regular sizes links.
> Added links to twitchemotes.com to Twitch emotes' context menus

- CHANGELOG.md
- src/providers/twitch/TwitchMessageBuilder.cpp
This fixes an issue that could happen when using the "Ignore & Replace" functionality of Ignore.
If a Twitch emote followed a replaced phrase and the replaced phrase differed in length from the replacement phrase, the Twitch emote position data was not fully updating, causing the Twitch emote searching code to get stuck in an endless loop.
> Fix freeze in Ignore & Replace if replacement followed by emote

- CHANGELOG.md
- src/messages/Link.hpp
- src/messages/SharedMessageBuilder.cpp
- src/widgets/helper/ChannelView.cpp
The `#channel` part in `/mentions` tab is a link and as fourtf once said, it was supposed to take you to the channel and message that you were mentioned in - very similar to how it is done on Discord, but it wasn't working properly and even shown those bugged URL links on some environments (See #2087).
I looked at code from channel switcher and in a pretty similar way added it here. And while channel switcher opens up a new channel when the target channel is closed, I assumed that messages in `/mentions` come always from already open channels and there's no real need to make this function open a new channel because I assume that the split with a channel will still be open.
While switching current SplitContainer and the Split itself works flawlessly, I wasn't really …
> Made #channel link in /mentions jump to #channel split

- CHANGELOG.md
- src/widgets/dialogs/LoginDialog.cpp
- src/widgets/dialogs/LoginDialog.hpp
- src/widgets/settingspages/AccountsPage.cpp
Another followup to #1843, this time regarding the `LoginWidget` spawned when adding a new account.
> fix: make LoginWidget child of AccountsPage

- CHANGELOG.md
The changelog was not correctly updated for v2.2.1 and v2.2.2 so I introduced sections for those versions and placed the relevant entries under the appropriate version.
I also added a "new" changelog entry for v2.2.2 since no description previously existed for that change.
> doc/fix: version previously unversioned changelog entries

- CHANGELOG.md
- src/PrecompiledHeader.hpp
- src/providers/twitch/TwitchChannel.cpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- src/widgets/settingspages/GeneralPageView.cpp
- src/widgets/settingspages/GeneralPageView.hpp
This pull request adds a setting to limit the amount of historical messages to fetch from the Recent Messages API.
Fixes #2250
> Add setting to limit number of historical messages to load on connect

- .github/workflows/changelog-check.yml
This GitHub Actions workflow checks whether a PR includes a change to the `CHANGELOG.md` file. The changelog check can be disabled via a label: `no changelog entry needed` (needs to be creates separately by a repository admin)
I recommend that the admin also set the changelog check as "Required" in the branch protection settings to prevent PRs from being merged without either having a changelog entry or that have been marked as "no changelog entry needed".
> Enforce changelog entry via CI

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-suggestion.md
- .github/ISSUE_TEMPLATE/something-completely-different.md
Also, delete the label for existing issues here: https://github.com/Chatterino/chatterino2/issues/labels
> Remove "needs triage" issue label

- CHANGELOG.md
- src/widgets/splits/SplitContainer.cpp
- Use ManagedConnect instead of barebones connect
Fixes #2249
> Fix crash when moving splits across windows and closing parent tab

- CHANGELOG.md
- src/providers/twitch/api/Helix.hpp
- src/providers/twitch/api/Kraken.cpp
- src/providers/twitch/api/Kraken.hpp
- src/providers/twitch/api/README.md
- src/widgets/dialogs/UserInfoPopup.cpp
Since Helix API now has `created_at` field exposed in API response, I decided to migrate properties from Kraken call to Helix. Since method calling old API wasn't used anywhere else, I straight up purged it.
It's also worth to mention that because of this we now make 1 less API call while opening a usercard, which should speed this process up a little.
> Migrated Kraken's getUser to Helix

- CHANGELOG.md
- src/widgets/helper/SearchPopup.cpp
Closes #2166 
Adds special cases for `/whispers`, `/mentions` and empty tabs, and an apostrophe in the titles.
> Improve search popup window titles

- CHANGELOG.md
- src/messages/Link.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/widgets/helper/ChannelView.cpp
Closes #2110 
- *You were forced off the channel, try reconnecting* message
- *You have been banned* message
- `Link::Reconnect`
- nothing
- How the *You are banned message* is handled.
An unexpected `PART` doesn't exactly mean being banned. If you get banned you get a Pubsub message saying that you were  after the `PART`.
> Improve the "You are banned" message

- CHANGELOG.md
- src/widgets/Window.cpp
- src/widgets/dialogs/EmotePopup.cpp
Added Ctrl + 1/2/3/... shortcuts to Emote Popup window. To keep consistency with shortcuts from main window, I decided to add Ctrl + 9 (selecting rightmost tab) as well. I thought it could be a nice enchancement which won't break anything, but will make some crazy keyboard shortcut nerds like me happy.
> Added Ctrl+1/2/3/... shortcuts to Emote Popup

- CHANGELOG.md
- src/providers/bttv/BttvEmotes.cpp
- src/providers/bttv/BttvEmotes.hpp
- src/providers/ffz/FfzEmotes.cpp
- src/providers/twitch/TwitchChannel.cpp
Before, only tooltips for FrankerFaceZ emotes used displayName. After having displayName methods for current channel implemented in #2189, I decided to make use of those and made BetterTTV emote tooltips consistent with FrankerFaceZ ones.
Also made a split between channel emotes (created by broadcaster) and actual shared emotes (that were created by others).
Related: #1765, Feature originally implemented in #1721
> Made emote tooltips use author's displayName consistently

- CHANGELOG.md
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitInput.cpp
- Added an event listener for `channelChanged` signal to ensure placeholder is preserved when changing channels.
- Moved entire function related to applying placeholder's color to SplitInput.cpp to ensure it will be applied in all cases, preventing random edge cases listed in #2253.
- While I was at it, in `SplitInput.cpp` I also changed `QPalette::Foreground` enum to `QPalette::WindowText` due to [deprecation warning](https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum) since Qt 5.13.
Closes #2253
> Further placeholder text fixes

- .github/workflows/changelog-check.yml
We now also ignore dependabot labels in the changelog enforcer
> Bump changelog enforcer to v1.6.1

- CHANGELOG.md
- src/common/ChannelChatters.cpp
- src/common/ChannelChatters.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
> Color mentions to match the mentioned users color

- src/common/ChannelChatters.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
The color mentions PR #2284 introduced a crash when receiving whispers.
We save user colors in the relevant twitch channels, but whispers don't have one, so we crash because `this->twitchChannel` is a `nullptr`.
Fix: don't save the color for whispers. Another possible fix would be to save colors globally instead of per-channel.
> Fix crash when receiving whisper

- src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp
This patch removes a redundant `using namespace` declaration that was introduced by an earlier PR of mine (#1588) .
> chore: remove a redundant `using namespace` declaration

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/TwitchAccount.cpp
- src/providers/twitch/TwitchAccount.hpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- src/providers/twitch/api/README.md
- src/widgets/dialogs/UserInfoPopup.cpp
Moved place of declared Kraken methods from `TwitchAccount` class to `Helix` class. Updated api documentation accordingly
> Migrated follow and unfollow methods to Helix API

- src/common/NetworkPrivate.cpp
No changelog entry needed
Fixes deprecation warning on compiling tests, example of this warning: https://github.com/Chatterino/chatterino2/pull/2316/checks?check_run_id=1613724673#step:8:50
> Fixed compilation warning on tests

- CHANGELOG.md
- src/messages/MessageElement.cpp
> Fix a crash bug that occurred when the "Limit message height" setting was enabled and a message was being split up into multiple lines. IRC only.

- CHANGELOG.md
- src/widgets/helper/CommonTexts.hpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitHeader.cpp
Adds an extra button to the split context menu to open the moderation view for a channel when the account selected has moderator permissions.
Using anonymous mode: ![](https://i.imgur.com/xOSTigQ.png)
Using an account with moderator permissions: ![](https://i.imgur.com/EjF2oKZ.png)
> Add 'open in mod view' button to split context menu

- CHANGELOG.md
- src/providers/irc/AbstractIrcServer.cpp
- src/providers/irc/AbstractIrcServer.hpp
- src/providers/irc/IrcConnection2.cpp
- src/providers/twitch/TwitchIrcServer.cpp
- Add helper function do add a global system message to all channels of an IRC server
- Reconnect both read and write connections when receiving a RECONNECT message on either connection
> Try to improve Twitch IRC network stability

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
As described in #2343, this is meant to replicate BetterTTV extension's behavoir and make use of the `chatter_count` property we're reciving while fetching data from TMI API. If the approach I chose isn't the best, let me know how can I change it.
While I was at it, I replaced deprecated `QString::SkipEmptyLines` with corresponding updated version from `Qt` namespace
Closes #2343
> Added /chatters command

- src/common/NetworkCommon.hpp
- src/common/NetworkPrivate.cpp
- src/common/NetworkPrivate.hpp
- src/common/NetworkRequest.cpp
- src/common/NetworkRequest.hpp
- tests/src/NetworkRequest.cpp
This patch adds an additional callback to `NetworkRequest` instances. This callback will execute regardless of whether the request failed or succeeded and it will always be executed after the `onSuccess` and `onError` callbacks.
This allows for code de-duplication in some cases (e.g. when unlocking a mutex or updating a timestamp) and can thus reduce the potential of human programming errors. For example, the timestamping logic of #2271 could be simplified with this feature.
> feat: add a `finally` callback to NetworkRequests

- CHANGELOG.md
- src/widgets/splits/SplitHeader.cpp
Changed signal connection to QAction::setVisible() to prevent Chatterino from crashing, sorry for a silly bug ;p
> Removed `liveStatusChanged` signal connection to fix a crash

- CHANGELOG.md
- src/common/Args.cpp
- src/common/Args.hpp
- src/main.cpp
- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
Fix CLI arguments not being respected. This happened due to the addition of category-based logging (`--help`, `--version`) and changes to the window loading ( `--channels`), respectively.
When handling `--channels`, I took the liberty to refactor the previous version of window description (which relied on generating JSON) to directly building the `WindowLayout`.
Closes https://github.com/Chatterino/chatterino2/issues/2190.
> fix: properly handle CLI arguments

- BUILDING_ON_MAC.md
- CHANGELOG.md
- chatterino.pro
Right now minimum macOS version is 10.13. For example some external libraries (boost, openssl) have brew formulas only for 10.14 (Mojave). 
Also it would introduce full C++17 (currently used) support for apple clang, which will be useful for example in https://github.com/Chatterino/chatterino2/pull/2368#pullrequestreview-573454781
Maybe it should be bumped to only 10.14 for more compatibility, let me know if you think so.
> Bump macOS minimum version to 10.14

- src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp
- src/widgets/dialogs/switcher/SwitchSplitItem.cpp
- src/widgets/dialogs/switcher/SwitchSplitItem.hpp
There were two ways to create a SwitchSplitItem:
a) A Container only: This would let the user switch to a Tab only, but not change which split in the focus was focused
b) A split only: This would programmatically fill in the container (by querying the split) and let the user switch to the Tab and change focus to the split
Since split had no way to programmatically get its container, we can
instead require that the container is always filled in. Where this class
is used (QuickSwitcherPopup.cpp:97 and QuickSwitcherPopup:108) we do
have the container pointer already, so the logic for creating a
SwitchSplitItem has now changed to:
a) A container but no split
b) A container and a split
> Ensure SwitchSplitItem container can never be null

- src/widgets/settingspages/GeneralPageView.hpp
This has been introduced in 0ecea8ad838de7039b3f74e3982d5d1ed9316f3b, I made [a comment](https://github.com/Chatterino/chatterino2/commit/0ecea8ad838de7039b3f74e3982d5d1ed9316f3b#r43544815) about it but I think nobody saw it. I believe it was an overlooked mistake and more of a debug artifact. It logs a shitton of `QSize`'s upon resizing settings page, ultra annoying.
> Clean up debug output

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/util/StreamLink.cpp
Usage: /streamlink [channel], use "channel" literally to open current channel in streamlink.
I am not so sure about using 'channel' for opening the current channel in streamlink, it's just a concept and I may change it to just `/streamlink` opening the current channel.
> Added /streamlink command

- src/common/Channel.hpp
This doesn't seem to be used in `Channel.cpp`, probably some old artifact that someone forgot to remove. I wasted 3 minutes of my life because of this 🙂
> Removed unnecessary declaration

- CHANGELOG.md
- src/providers/twitch/TwitchMessageBuilder.cpp
This should fix the bug described in #2479  
Closes #2479
> Fixed emote pasting bug with multiple spaces

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/util/Helpers.cpp
- src/util/Helpers.hpp
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/splits/SplitHeader.cpp
Added a simple utility function for using Qt's [`QLocale.toString()`](https://doc.qt.io/qt-5/qlocale.html#toString-6) and making all the things like viewerCount, followerCount be separated with commas, dots or spaces, depending on user's system locale settings.  
I tried to add it whereever applicable, but let me know if I forgot about something.
> Localized all relevant numbers visible to end-user

- src/providers/twitch/IrcMessageHandler.cpp
This fixes a case, where your timeout is smaller than 1 second and your timeout message would appear as `You are timed out for .`
> Fixed remaining timeout message

- .github/workflows/build.yml
Added newly required `libxcb-randr0-dev` to packages we need to install. Hopefully this fixes builds on Ubuntu :)
> Fix workflow builds on ubuntu

- CHANGELOG.md
- src/providers/twitch/TwitchChannel.cpp
This PR fixes/adds the ability to hover over a cheer emote and display a tooltip. This is because no tooltip is set on the cheer emotes when they are parsed/created - failing a check in [ChannelView.cpp#L1406](https://github.com/Chatterino/chatterino2/blob/master/src/widgets/helper/ChannelView.cpp#L1406) where a tooltip must be present in order to show.
This aims to fix #2434
**Steps to reproduce:**
1. Find/create a cheer message containing a cheer emote
2. Hover over the emote
**Expected result:**
Emote tooltip displays with a larger version of the emote as well as the text value of the emote
**Actual result (prior to this PR):**
No tooltip is displayed.
_NOTE: I'm not a proficient C++ dev, nor do I have much experience with QT so if it looks weird just comment on …
> Implement missing cheer emote tooltip

- src/messages/MessageElement.cpp
- src/messages/layouts/MessageLayoutContainer.cpp
- src/messages/layouts/MessageLayoutElement.cpp
- src/widgets/Label.cpp
- src/widgets/helper/NotebookTab.cpp
Reference: https://doc.qt.io/qt-5/qfontmetrics-obsolete.html#width
Replaced with [`QFontMetrics::horizontalAdvance`](https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance)
> Fixed deprecated method QFontMetrics::width

- CHANGELOG.md
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/UserInfoPopup.hpp
Ever since #1982 we refresh messages on the usercard automatically, without any need to click the button anymore, so I decided to remove it and it seems that nothing broke.
> Removed refresh label from usercard

- src/controllers/highlights/HighlightModel.cpp
- src/widgets/helper/NotebookButton.cpp
- src/widgets/helper/SignalLabel.hpp
Reference: https://doc.qt.io/qt-5/qflags-obsolete.html#QFlags-3
> Fixed deprecated method QFlags::Zero

- src/widgets/settingspages/GeneralPageView.hpp
Reference: https://doc.qt.io/qt-5/qcombobox-obsolete.html#currentIndexChanged-1
> Fixed deprecated method QComboBox::currentIndexChanged

- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
no changelog entry needed LOOOOOOOOOOOOL
After I checked out to `cmake-build` branch, I saw many deprecation warnings and most of them\* can be fixed, so I went ahead and did just that.
\* We can't replace `QString::SkipEmptyParts` with newer `Qt::SkipEmptyParts` since the second method was added just in Qt 5.14, so it would not work on our minimal supported version (Qt 5.12). I also left a couple warnings that I didn't understand how to fix, perhaps I could fix them later on.  
I believe there should be no conflicts with both qmake builds and cmake ones, since migration to cmake builds doesn't touch code at all 😎
Edit: @pajlada wanted me to split changes from this pull request to multiple PRs (#2508, #2509, #2510, #2511, #2512)
This pull request specifically fixes …
> Fixed deprecated method QTime::elapsed

- src/util/StreamLink.cpp
Reference: https://doc.qt.io/qt-5/qprocess-obsolete.html#finished-1
> Fixed deprecated method QProcess::finished(int)

- CHANGELOG.md
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/UserInfoPopup.hpp
Added a context menu to avatar in usercard. It opens on right-clicking the avatar in usercard. ![hi Leon and mm pajaHey](https://cdn.zneix.eu/Sqq6ka7.png)
I am not sure if something else can be added to the actions.
> Added avatar context menu to usercard

- .github/workflows/build.yml
- src/widgets/dialogs/UserInfoPopup.cpp
What we also ended up doing was ensuring that the chatterino2.exe file is actually present before continuing with uploading the artifact.
unfortunately, using `cmd` means we don't get any actual error codes, so this is the check we'll have to do.
If we were able to use powershell for the build command that'd be neater, but there's no clean way I know of to load the vcvars file from powershell
> Fix windows build not compiling

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
There was a request for clearing messages through a command.
Syntax `/clearmessages`, it has no arguments.
Thank you @zneix for the code. (Which also means you can blame him for it ![image](https://user-images.githubusercontent.com/13697809/109489611-69416880-7a87-11eb-8379-54032ae39399.png))
> feat: /clearmessages command

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/widgets/splits/Split.cpp
Fixes #2527.
Clip creation via the `Alt+X` shortcut failed for the `/mentions` and `/whispers` channel. This happened because `Channel::isTwitchChannel` returns `true` for these channels. (Internally, the types are `Channel::Type::TwitchMentions` and `Channel::Type::TwitchWhispers` in anticipation of supporting more platforms in the future.)
This lead to a false assumption in the clip creation logic: Not all channels that display "Twitch content" are able to create clips.
The employed fix checks the channel type in more detail. Clip creation is only allowed if the channel is `Channel::Type::Twitch` or `Channel::Type::TwitchWatching`. This makes sure that there always is an associated channel to generate a clip from.
Additional note: Clip creation did not crash when …
> fix: no longer crash on clip creation in "special" channels

- CHANGELOG.md
- src/widgets/settingspages/GeneralPage.cpp
This PR aims to fix chatterino's app data directory not opening on macOS when pressing the "Open AppData..." button. When pressing the button on Windows/Linux the relevant directory is opened in the file explorer. When attempting to do this on macOS Finder does not open up the expected directory of `$HOME/Library/Application Support/chatterino`. 
This is caused by macOS requiring `file://` prior to the path in order for it to be opened in finder.
Fixes #2531
> Fix app data dir not opening on macOS when "Open AppData" button pressed

- CHANGELOG.md
- src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp
The quick switcher was using a `QSet` instead of a order-respecting collection type when fetching the user's tabs. By replacing `QSet` with `QList` we keep the order of tabs.
See #2519 for more details and test setup.
> Fix quick switcher not ordering based on tab order

- CHANGELOG.md
- resources/com.chatterino.chatterino.desktop
- [ x ] `CHANGELOG.md` was updated, if applicable
This adds the StartupWMClass property to the desktop file, which window managers can use to determine when chatterino has opened and which window belongs to it.
GNOME uses this property, so this will fix #1863. You can test this by applying this patch to the desktop file of an existing install.
> Add StartupWMClass property to desktop file

- CHANGELOG.md
- src/providers/emoji/Emojis.cpp
Copied from commit:
Some unified emoji codes are up to 7 bytes. This patch raises the unicodeBytes array size to 7 in addition to using .at() to catch possible future overflows early. May be worthwhile looking into why some unified codes are 7 bytes in the first place.
=================================================================
==4158928==ERROR: AddressSanitizer: global-buffer-overflow on address 0x562ebb5cd1f0 at pc 0x562eba0f5e72 bp 0x7ffc2705e830 sp 0x7ffc2705e820
WRITE of size 4 at 0x562ebb5cd1f0 thread T0
#0 0x562eba0f5e71 in parseEmoji /home/yoitsu/Git/chatterino2/src/providers/emoji/Emojis.cpp:94
#1 0x562eba0f71ae in chatterino::Emojis::loadEmojis() /home/yoitsu/Git/chatterino2/src/providers/emoji/Emojis.cpp:158
#2 0x562eba0f6a71 in …
> fix buffer overflow in parseEmoji

- CHANGELOG.md
- src/widgets/dialogs/EmotePopup.cpp
Added Page Up and Page Down shortcuts for scrolling up and down in the emote popup, to be consistent with the same shortcuts in channel views.
Closes #2410
> Add PgUp / PgDown for scrolling in the emote popup

- src/BaseSettings.cpp
- src/common/Args.cpp
- src/common/Channel.cpp
- src/common/ChatterinoSetting.cpp
- src/controllers/highlights/HighlightPhrase.cpp
- src/messages/layouts/MessageLayout.cpp
- src/messages/layouts/MessageLayoutElement.cpp
- src/providers/colors/ColorProvider.cpp
- src/providers/twitch/TwitchAccount.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Kraken.cpp
- src/singletons/TooltipPreviewImage.cpp
- src/util/PostToThread.hpp
- src/widgets/AttachedWindow.cpp
- src/widgets/Label.cpp
- src/widgets/StreamView.cpp
- src/widgets/dialogs/NotificationPopup.cpp
- src/widgets/helper/Button.cpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/SearchPopup.cpp
Previous PR split into multiple parts, part 1.
std::move added where applicable as per suggested by clang-tidy, and 1 case removed where it was added in error to a trivially copyable object. These are "confident" changes, as applying std::move to non-trivially copyable objects should only result in less temporary copies -> lower overhead -> higher perfomance, unlike const& which can also change code semantics (according to Pajlada's feedback, as apparently const& can degrade perfomance in lambda contexts).
> clang-tidy: use std::move where applicable

- CHANGELOG.md
- src/providers/twitch/IrcMessageHandler.cpp
- src/util/Helpers.cpp
- src/util/Helpers.hpp
We didn't handle those messages before, now we do.
Example of how it looks (thanks @KararTY  for testing):
Examples of how it looks in webchat:
> Handle bits badge tier notification messages

- .github/workflows/build.yml
This uses https://github.com/ilammy/msvc-dev-cmd to setup the MSVC environment, and https://github.com/AnotherFoxGuy/conan-onefile for the installation of conan
-----------------------------------
> 🐛 Fixed windows CI not reporting exitcodes correctly

- src/controllers/commands/CommandController.cpp
Added `/vips`.
By the way, we do include standard moderator commands in `TWITCH_DEFAULT_COMMANDS` define, but not the ones available to channel editors (such as `/commercial`, `/host`, `/raid`). Should we add those?
> Added missing default twitch commands

- CHANGELOG.md
- chatterino.pro
- src/CMakeLists.txt
- src/messages/search/ChannelPredicate.cpp
- src/messages/search/ChannelPredicate.hpp
- src/widgets/helper/SearchPopup.cpp
See #2299 for more information.
This PR adds a search predicate (according to #1237) that allows filtering messages based on the channel they were sent in, meant for usage in /mentions. 
This is also inspired by the similar filter in [Discord](https://support.discord.com/hc/en-us/articles/115000468588-Using-Search).
Example usage:
`in:fourtf` would show messages originally sent in fourtf channel.
`in:fourtf,pajlada` would show messages originally sent in either fourtf or pajlada channels.
The things I'm not completely sure about now are:
1. Currently the filter works everywhere, but is only useful in /mentions. If used in a regular split it will either show all messages or none, depending on whether or not the channel list includes the current channel. I'm …
> Added in:<channels> search predicate

- chatterino.pro
- src/CMakeLists.txt
- src/common/NetworkCommon.cpp
- src/common/NetworkCommon.hpp
- src/common/NetworkRequest.cpp
- src/common/NetworkRequest.hpp
- src/util/NuulsUploader.cpp
- tests/CMakeLists.txt
- tests/src/NetworkCommon.cpp
> Add a function in NetworkCommon `parseHeaderList` which parses a header list as a string into a vector of header pairs

- CHANGELOG.md
- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
- src/providers/ffz/FfzEmotes.cpp
- src/providers/ffz/FfzEmotes.hpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
> Added custom FrankerFaceZ VIP badges

- CHANGELOG.md
- src/singletons/WindowManager.cpp
- src/widgets/splits/SplitContainer.cpp
- src/widgets/splits/SplitContainer.hpp
Temporarily disables layouting while splits are being loaded. Also brings loading splits from O(N²) to O(N) I guess.
> fix size of splits not loading properly

- CHANGELOG.md
- src/widgets/dialogs/EmotePopup.cpp
Closes #1125
Closes #1735
Partialy resolves #2138
> Added missing context menu entries to emote popup

- CHANGELOG.md
- src/messages/MessageElement.hpp
- src/providers/twitch/TwitchBadge.cpp
- src/singletons/Settings.hpp
- src/singletons/WindowManager.cpp
- src/widgets/settingspages/GeneralPage.cpp
This makes predictions badges being acknowledged as an actual separate message element on its own, thus making it possible to configure those (which I also added in this PR).
Examples of messages with those badges: 
```
@badge-info=predictions/No;badges=predictions/pink-2,vip/1;color=#DAA520;display-name=Somso2e;emotes=;flags=;id=cc518b04-801a-473d-85c4-af139d7dd520;mod=0;room-id=99631238;subscriber=0;tmi-sent-ts=1619164205224;turbo=0;user-id=153573952;user-type= :somso2e!somso2e@somso2e.tmi.twitch.tv PRIVMSG #zneix :-tags
```
```
@badge-info=predictions/Yes;badges=predictions/blue-1;color=#0000FF;display-name=Hpixpoke;emotes=;flags=;id=02cfc1c1-8ce8-4d7b-b9e7-64b6d8da1a30;mod=0;room-id=99631238;subscriber=0;tmi-sent-ts=1619164206713;turbo=0;user-id=108748290;user-t …
```
> Add ability to hide Twitch Prediction badges

- src/providers/bttv/BttvEmotes.cpp
This should elimnate the BTTV Channel Emote loading timeout, often reported by many users. Originally brought up by jammehcow in https://github.com/Chatterino/chatterino2/pull/2677#issuecomment-826249993
That seems like an ancient typo introduced in https://github.com/Chatterino/chatterino2/commit/c768bd9bd9d696c86a7525eabefffebf046d66c3#diff-b626f88008195f94729ebb0738b8c7c883fb01f0d4aceb7bc55f137ee6a24a38R131
> Raised bttv emote timeout value

- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/NotebookTab.cpp
And some other method that's also replaced with QWheelEvent::angleDelta
Reference: https://doc.qt.io/qt-5/qwheelevent-obsolete.html#delta and https://doc.qt.io/qt-5/qwheelevent-obsolete.html#orientation
Change from `event->delta()` to `event->angleDelta().y()` makes it, so you can no longer scroll horizontally (with trackpad / touchpad) to select next/previous tab (until now, you were able to do it, but I believe this is wrong anyways).
> Fixed deprecated method QWheelEvent::delta

- src/Application.cpp
Worth considering adding this since accessing getApp() from another thread as the gui thread can lead to parallelism issues. Didn't assert in my quick test.
> adds assertInGuiThread to getApp()

- CHANGELOG.md
- chatterino.pro
- src/CMakeLists.txt
- src/messages/search/MessageFlagsPredicate.cpp
- src/messages/search/MessageFlagsPredicate.hpp
- src/widgets/helper/SearchPopup.cpp
This PR adds a search predicate that allows filtering messages based on some of their flags.
Usage: `is:<flags>` where flags is a comma seperated list of one of the following currently supported options:
- `deleted`: Checks for `MessageFlag::Disabled`
- `sub` or `subscription`: Checks for `MessageFlag::Subscription`
- `timeout`: Checks for `MessageFlag::Timeout`
- `highlighted`: Checks for `MessageFlag::Highlighted`
- `system`: Checks for `MessageFlag::System`
Examples:
`is:deleted` would show deleted (disabled) messages
`is:sub,timeout` would show messages that are either a subscription message or a timeout message
Obviously if this is added I'm open to changes and additions to the current options and their naming (these are just the options that I initially …
> Added is:<flags> search predicate

- CHANGELOG.md
- src/widgets/splits/SplitHeader.cpp
Simple fix, based on https://github.com/Chatterino/chatterino2/blob/9c41adca2efcdd633998ddc5b06db90fb2bbff15/src/widgets/splits/Split.cpp#L157-L159
> Made left-clicking splitheader focus split

- CHANGELOG.md
- src/messages/MessageBuilder.cpp
- src/providers/twitch/PubsubClient.cpp
- src/providers/twitch/PubsubClient.hpp
Automod didn't work properly but this is now fixed.
Closes #2682
The steps to reproduce the bug are discussed in the issue.
Otherwise:
1. Enable automod to level 4 (for simplicity)
2. Use some account and type something vulgur
3. As a moderator see that the message was held up
4. Click Approve or Deny
5. See that nothing happened to the AutoMod message that was shown when it's supposed to fade to gray
This also fixed automod pubsub messages in general.
Some notes for devs:
When I implemented it 
```
chatterino.pubsub: moderationActionHandlers delete_blocked_term
chatterino.pubsub: moderationActionHandlers delete_permitted_term
chatterino.pubsub: channelTermsActionHandlers add_permitted_term
chatterino.pubsub: channelTermsActionHandlers add_blocked_term …
```
> Fix automod messages not being parsed/showing up properly

- CHANGELOG.md
- src/Application.cpp
- src/messages/MessageBuilder.cpp
- src/messages/MessageBuilder.hpp
- src/providers/twitch/PubsubActions.hpp
- src/providers/twitch/PubsubClient.cpp
- src/providers/twitch/PubsubClient.hpp
**Requires #2742**
Closes #2626
Now shows when a message is being held by automod through pubsub.
Sent two profane messages and then accepted the first and denied the second. (There are badges and stuff so it looks good but I have them disabled and forgot to enable them for this screenshot)
(I don't know why formatting failed I have clang-format version 11.1.0)
> Messages held by automod are now shown to the user

- CHANGELOG.md
- src/providers/twitch/TwitchBadges.cpp
> Fix a deadlock that would occur when loading Twitch badges

- CHANGELOG.md
- src/providers/twitch/api/Helix.cpp
Work towards #2767 so that at least up to 100 blocked users are returned rather than the default 20
> Load 100 blocked users instead of default 20

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
- src/widgets/splits/SplitInput.hpp
Fixes #2780
At the moment the handler can be called twice when the user types a character because both the text input updates and cursor changes position. If anyone has a good way to block one of the events when the other is triggered please suggest.
> Fix word backspacing not closing/updating colon emote picker

- src/providers/twitch/TwitchChannel.cpp
- src/widgets/helper/ChannelView.cpp
Fixes deprecation notices introduced in #2748
Behavior is untouched (left master, right this PR):
Reference: https://doc.qt.io/qt-5/qt.html#DateFormat-enum
Replacement: https://doc.qt.io/qt-5/qlocale.html#FormatType-enum
> Fixed deprecated method Qt::SystemLocaleLongDate

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
Adds the `#channel` prefixed to messages in `/mentions` (`MessageElementFlag::ChannelName`), to messages displayed in usercards and search popups opened from  `/mentions`.
> Add #channel in mentions usercard and search popup 

- CHANGELOG.md
- src/providers/ffz/FfzEmotes.cpp
Updates parsing of Global FFZ emotes to be the same as channel emotes to fix #2807.
> Fix FFZ emote links for global emotes

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
This PR adds moderation buttons to messages in a search popup opened from a split where moderation mode is active.
While this does seem to work for the cases I tested, I'm not really sure about the implementation and would like some input:
With the way the existing imlementation of adding the `MessageElementFlag` works, the `ChannelView` object "queries" the parent widget (by `dynamic_cast`), expecting it to be a split and checking for moderation mode in that split. The addition here is checking if the parent widget is actually a search popup, fetching the parent of the search widget which should be a split, and using that split to determine moderation mode. I'm just not sure if this is a good way of going about it. (A similar thing applies to determining the …
> Add moderation buttons in search popup

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
When using `/setgame` the first game returned by Helix is used. This PR aims to fix the shotty behaviour of `/setgame` by attempting to match the user's input with the games returned. It would be nice if this matching could also do some kind of fuzzy search but that's beyond the scope of this PR.
Fixes #2636
> Match game names exactly when using /setgame

- BUILDING_ON_WINDOWS.md
- Fixed OpenSSL 1.1.1 version (j => k)
- Switched to sourceforge downloads from bintray as it has been shutdown. Sourceforge is officially linked on [boost's website](https://www.boost.org/users/download/) (under "Prebuilt windows binaries")
> Fix links on Windows building docs

- CHANGELOG.md
- src/providers/twitch/TwitchEmotes.hpp
Using v2 paths is required for animated emotes, as can be seen in the following example.
Example of an animated emote:
https://static-cdn.jtvnw.net/emoticons/v1/303999817/3.0
https://static-cdn.jtvnw.net/emoticons/v2/303999817/default/dark/3.0
https://static-cdn.jtvnw.net/emoticons/v2/303999817/static/dark/3.0
> Switch to Twitch v2 emote API for animated emote support

- CHANGELOG.md
- src/providers/twitch/TwitchChannel.cpp
Moment when I reconnected, I switched to anonymous mode
This also gets rid of mentioned notice upon sending an empty message (usually happens upon executing a command while being anonymous)
> Refactored system message received upon trying to send a message while anonymous

- CHANGELOG.md
- src/providers/irc/AbstractIrcServer.cpp
- src/providers/irc/AbstractIrcServer.hpp
- src/providers/irc/IrcConnection2.cpp
- src/providers/irc/IrcConnection2.hpp
Ready for review/feedback. There's a lot of room for (additional) refactoring on the connection logic, but I figured I'd at least fix the issue first.
Chatterino currently does not handle disconnects of the write connection, which
causes messages to remain buffered until you manually reconnect, after which it
will send all messages at once.
This patch addresses the lack of reconnection specifically, and attempts to
refactor some of the reconnection logic to make it more robust. Backoff behavior
is introduced to *both* read/write cons to avoid reconnection loops.
To replicate the issue, simply lose your (write) connection to TMI. This can be
"simulated" using something like:
tcpkill -i eth0 host 44.226.36.141 or host 34.217.198.238 or host 100.20.159.232
An …
> Fix write connection reconnection issues

- CHANGELOG.md
- src/common/Channel.cpp
- src/common/Channel.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
Closes #1155.
Adds a notice for when a message gets deleted.
> Make deletions show like timeouts/bans.

- CHANGELOG.md
- src/providers/IvrApi.hpp
- src/providers/twitch/TwitchAccount.cpp
Added a helper vector of vectors and some logic that splits QStringList that we receive as a function parameter to avoid getting 400's from Ivr API as it supports fetching 100 emote sets at max.
One unrelated change: updated a link to Ivr API endpoint we're using because it has changed.
P.S. Thanks @talneoran for helping to come up with the solution ![Okayga](https://cdn.frankerfacez.com/emote/287489/1)
> Split list of emote sets into bunches when performing Ivr API reqeusts

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/util/IncognitoBrowser.cpp
- src/util/IncognitoBrowser.hpp
Add a `/openurl <URL>` built-in command that allows opening URLs through chat.
This is mostly useful for usage in custom commands, for example a command `/report` with the definition `/openurl twitch.tv/{1}/report` can be used to open the user report page of the user given as the first argument.
Closes #2461.
> Add /openurl command

- CHANGELOG.md
- src/controllers/moderationactions/ModerationAction.cpp
Limits the duration displayed in timeout moderation buttons to the max timeout duration, 2 weeks.
Initially I wanted to cut down the duration inputted by the user, but with the current implementation, that will require changing the inputted action after it has already been saved, which I'm not sure about. 
Instead I opted for simply displaying `>2w` in the button when the duration exceeds the max duration, without changing the underlying action. I would like to hear if anyone has better ideas, or thinks that editing the action somehow is still the right way to go.
Fixes #2865
> Fix large timeout duration in moderation buttons

- src/widgets/splits/SplitInput.cpp
Fixes a bug where the completion popup (both emote and username) is still shown when the cursor is before a completion prefix, if the cursor position is the first position (beginning of the input). 
Example of the bug (by jeffboys123#6969 in Chatterino discord):
https://user-images.githubusercontent.com/43518924/123544362-9cf17e00-d75b-11eb-9ca3-55bd6c3369ba.mp4
> Hide completion popup when cursor is at first position

- CHANGELOG.md
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
Makes the channel name in `<channel> has gone offline. Exiting host mode.` messages clickable.
Implements missing functionality from #2752 which was described in #2655.
> Add clickable usernames in host offline messages

- CHANGELOG.md
- src/widgets/dialogs/ColorPickerDialog.cpp
Fixes #2939. See there and the commit message for additional context.
Original commit message:
> Before this change, it was checked whether the text of the HTML color
picker line edit represents a valid color. Since the HTML color syntax
allows the format `#RGB` (see [1]), this lead to the lambda setting the
color edit to the full format string (`#RRGGBB`) whenever three
characters have been entered.
Due to the QValidator set up for the line edit, attempts to change the
text again would be rejected.
>
> With this change, validity of the color is only checked when the
`QLineEdit::editingFinished` signal is emitted. (At the time of writing,
this corresponds to "Return" being pressed or a focus loss of the line
edit.) Since the signal is only emitted when the …
> fix: provide better UX for HTML color picker edit

- src/messages/Image.cpp
Fixes an integer overflow when checking for the maximum image ram usage
> fix overflows in the max image size code

- CHANGELOG.md
- src/providers/twitch/TwitchMessageBuilder.cpp
In title.
Implements part of #2673
> Make usernames clickable in reward redemption messages

- src/widgets/dialogs/LoginDialog.cpp
Fixes some capitalization and removes explanation for the "Get user ID from username" button which no longer exists.
> Fix text mistakes in advanced login dialog

- CHANGELOG.md
- src/providers/irc/IrcMessageBuilder.cpp
Closes #1780. Usercards still don't have IRC-specific behavior.
> Fix usercards showing all messages in IRC channels

- .CI/CreateUbuntuDeb.sh
- .github/workflows/build.yml
- CHANGELOG.md
TODO: 
- this is what was installed when i installed chatterino (from totally clean chroot without graphical env installed)
```
adwaita-icon-theme at-spi2-core dbus dbus-user-session dconf-gsettings-backend dconf-service dmsetup file fontconfig fontconfig-config fonts-dejavu-core gir1.2-glib-2.0 glib-networking glib-networking-common glib-networking-services gsettings-desktop-schemas
gtk-update-icon-cache hicolor-icon-theme humanity-icon-theme krb5-locales libapparmor1 libargon2-1 libasyncns0 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libavahi-client3 libavahi-common-data libavahi-common3 libbrotli1 libbsd0 libcairo-gobject2
libcairo2 libcap2 libcolord2 libcryptsetup12 libcups2 libdatrie1 libdbus-1-3 libdconf1 libdevmapper1.02.1 …
```
> Add Ubuntu packaging script

- CHANGELOG.md
- src/providers/irc/IrcMessageBuilder.cpp
- src/providers/irc/IrcServer.cpp
- src/util/IrcHelpers.hpp
Use `tmi-sent-ts` if it's present for timestamp value. This will make timestamp values equal for everyone - before, it used `QTime::currentTime()`, which could vary by around 100-200ms for everyone and was rather inconsistent (as opposed to recent-messages, where timestamp value is equal to everyone).
We check for IRCv3's [server-time](https://ircv3.net/irc/#server-time), which is according to its specification a message tag `"time"`, containing a proper ISO date (in UTC format). If the tag is available, we use it instead of `QTime::currentTime();`.
> Use server time in received IRC messages where available

- CHANGELOG.md
- src/widgets/splits/InputCompletionPopup.cpp
- src/widgets/splits/SplitInput.cpp
In #2999 I didn't include Global third-party (I think it's due to a fauly resolve of a merge conflict). Confirmed it works now 👍
In #2951 I introduced a crash upon trying to bring up `InputCompletionPopup`. Confirmed it doesn't crash now.
Also made it, so `InputCompletionPopup` is brought up while typing in special Twitch channels other than `#/whispers`. So it's basically an extension of #2999.
Closes #3032
> Fix crash and completion in other special channels than /whispers

- CHANGELOG.md
- src/common/CompletionModel.cpp
- src/util/Helpers.cpp
- src/util/Helpers.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/ResizingTextEdit.cpp
- src/widgets/helper/ResizingTextEdit.hpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitInput.cpp
- src/widgets/splits/SplitInput.hpp
- tests/CMakeLists.txt
- tests/src/Helpers.cpp
Fixes issue described in #2918. As discussed with other people in chat, I've also went ahead and made right-clicking "username links" follow the same format of appending comma after the username only if it's the first word.
> Fixed comma appended to username completion when not at the beginning of the message

- .gitmodules
Just so silly dependabot won't try to remove our cmake stuff
> Pin down libcommuni's branch we're using

- CHANGELOG.md
- CMakeLists.txt
- chatterino.pro
- src/CMakeLists.txt
- src/controllers/ignores/IgnoreController.cpp
- src/controllers/ignores/IgnoreController.hpp
- src/messages/SharedMessageBuilder.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
Dev note:
Because a channel point message is contextless (i.e. has no channel attached), we have to attach the relevant parameters to the function call itself. The alternative to this would be to make the function non-static, but we'd have to rework TwitchMessageBuilder and SharedMessageBuilder to work with a null ircmessage which is not something I want to do.
Fixes #3098
> Check for ignored phrases/users in channel point redemptions

- CHANGELOG.md
- src/controllers/filters/FilterRecord.hpp
- src/controllers/filters/FilterSet.hpp
- src/controllers/filters/parser/FilterParser.cpp
- src/controllers/filters/parser/FilterParser.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/SearchPopup.cpp
Reason for crash was a deadlock; we were already inside the channel lock while trying to lock it again to find the channel.
Instead of finding the channel again, we pass the channel all the way down to the filter.
Dev: Removed `FilterRecord::filter(message)` function as it was unused and would've required more changes.
Fixes crash introduced in #3092 
Fix #3108
> Fix filter crash introduced in #3092

- CHANGELOG.md
- src/providers/irc/AbstractIrcServer.cpp
- src/providers/twitch/TwitchIrcServer.cpp
- Remove JOINs on write connection
By not joining on the WRITE connection, we:
a) save some bandwidth
b) reduce the amount of JOINs we do, allowing users to have more initial splits open for now until we add proper rate limiting
Works toward fixing #3107
> Remove JOINs from write connection

- CHANGELOG.md
- chatterino.pro
- src/CMakeLists.txt
- src/providers/irc/AbstractIrcServer.cpp
- src/providers/irc/AbstractIrcServer.hpp
- src/util/RatelimitBucket.cpp
- src/util/RatelimitBucket.hpp
- tests/CMakeLists.txt
- tests/src/RatelimitBucket.cpp
Added experimental rate-limitting for outgoing JOIN messages with some imitation of Leaky bucket rate limitting. Huge thanks to @leon-richardt for helping me figure out the theory.
Tested it out and Twitch does not kill our connection - we conform to Twitch's 20 JOIN messages / 10s limit by sending at most 18 JOIN messages per 10.5s.
This might not be the best solution and I believe there could be a better one, but after about 24 hours of thinking this is the most sane solution I could come up with and given how important this bug is I think it's better than nothing.
~~There's still debug prints in the code, to make it easier for reviewers to test. After approving the PR I'll remove them.~~ already removed.
Closes #3107
> Rate limit outgoing JOIN messages

- CHANGELOG.md
- src/widgets/splits/Split.cpp
Respect moderation mode status and active filters when opening a split as a popup.
Fixes #3113
> Handle moderation mode and filters in split popup

- src/providers/twitch/api/Helix.cpp
Result of the API call inside of `Helix::getEmoteSetData` might sometimes skip some (or all) given emotesets and return an empty array. This is a Twitch bug and is being tracked in twitchdev/issues#445.
Regardless, we now add a check which ensures that we don't attempt to access the first element of the QJsonArray if it doesn't exist which fixes some assert magic inside of QJsonArray class.
This isn't anything that crashes Chatterino, but just a "warning" that's popping up while compiling Chatterino on Windows sometimes.
Example below:
> Fix QJsonArray assert failing while attempting to index an empty array

- CHANGELOG.md
- src/widgets/settingspages/HighlightingPage.cpp
Seems to have been caused by all badge highlights sharing the same color instance.
Not 100% sure about the cause and fix though so would like someone else to look at it.
Fixes #3132
> Fix badge highlights using the same color

- CHANGELOG.md
- chatterino.pro
- src/widgets/splits/SplitInput.cpp
Current stable debian Linux is Buster, which still ships Qt 5.11.3, so I've had this patch to build chatterino locally, for the last several months.
Since `QPalette::placeholderText` seems to be the only codebase feature depending on QT 5.12, the build has been running perfectly fine.
The Qt docs say
> Before Qt 5.12, the placeholder text color was hard-coded in the code as QPalette::text().color() where an alpha of 128 was applied.
and based on my testing, theme changes look just fine.
> Allow building against Qt 5.11

- CHANGELOG.md
- src/providers/twitch/TwitchEmotes.cpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/settingspages/AboutPage.cpp
- Remove attribution to twitchemotes.com API as we now pull data from Helix directly
- Remove "Open TwitchEmotes emote link" and "Copy TwitchEmotes emote link" menu options when right-clicking Twitch emotes
Fixes #3114 
Fixes #2745
Fixes #3126
> Remove twitchemotes.com-related functionality

- .github/ISSUE_TEMPLATE/config.yml
Taken from ![osu!lazer](https://github.com/ppy/osu/blob/master/.github/ISSUE_TEMPLATE/config.yml)
This is what it looks like:
https://github.com/ppy/osu/issues/new/choose
Makes a link to discussions when trying to create an issue when you should instead create an enhancement.
> Added links to discussions when trying to create an issue

- CHANGELOG.md
- CMakeLists.txt
- src/CMakeLists.txt
Renamed variables of QT5KEYCHAIN to just QTKEYCHAIN due to how qt keychain library changes its target name from `qt5keychain` to `qt6keychain` if we build against Qt6.
⚠ Important note: qtkeychain already uses `BUILD_WITH_QT6` CMake parameter, so I thought it would be convenient to just reuse that. No idea if that's a bad practice to use one variable/option that affects multiple things at once, but pretty sure that in this scope it wouldn't change anything.
Required for Chatterino/libcommuni#2
> Prepare CMake for Qt6

- CHANGELOG.md
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchAccount.cpp
- src/providers/twitch/TwitchAccount.hpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitHeader.hpp
This PR aims to display a system message when reloading subscriber emotes. This behaviour is in line with the BTTV/FFZ emote reload behaviour. 
I've passed through the channel to `loadEmotes` which might be ugly to some people but it ensures you get a 'reloaded' messages when the reloading has started instead of when the method was called. Also kept the old `loadEmotes()` overload around for the call in `IRCMessagehandler`.
> Show system message when reloading subscriber emotes

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
Strip the leading `@` from the username when using the `/user` and `/usercard` commands. Fixes a minor annoyance when these commands are used along with the *Only search for username autocompletion with an @* option.
> Strip leading @ and trailing , from /user and /usercard commands

- CHANGELOG.md
- src/widgets/splits/Split.cpp
Changes the 3rd party uploader popup text to use capital "Chatterino" instead. it kept bugging me
Before:
After:
> Change 3rd party uploader popup text capitalization

- CHANGELOG.md
- src/providers/twitch/TwitchChannel.cpp
Whenever a message starts with `/` or `.` we need to ignore first space as it is not treated as the message content by Twitch. Be it either a command starting with these characters or an escaped message, like `. .foo bar`.
Look at the examples below (for better visibility, spaces were replaced with underscores)
"Goes through" is based on whether sending 2 identical messages in a row through Chatterino works or not.
|Message|Message content<br>(as interpreted by Twitch)|Goes through on master?|Goes through on PR?|
|-|-|-|-|
|`foo`|`foo`|✔️|✔️|
|`foo_bar`|`foo_bar`|✔️|✔️|
|`.foo_bar`|`bar`|❌|✔️|
|`.foo__bar`|`bar`|❌|✔️|
|`.foo_bar_baz`|`bar_baz`|❌|✔️|
|`.foo_bar__baz`|`bar__baz`|❌|✔️|
|`._foo`|`foo`|❌|✔️|
|`._.foo`|`.foo`|❌|✔️|
|`._foo_bar`|`foo_bar`|❌|✔️| …
> Fix /me not going through upon sending an identical message

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
> Enable backup for commands

- src/util/StreamLink.cpp
- src/widgets/BasePopup.cpp
- src/widgets/BasePopup.hpp
- src/widgets/dialogs/QualityPopup.cpp
- src/widgets/dialogs/QualityPopup.hpp
- Add helper functions to BasePopup for handling Escape/Enter with button boxes
- use BasePopup helper functions to handle Enter/Return
Supersedes #2643
> Keyboard integration for Streamlink quality confirmation

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/z_browser_extension.md
Made the chatterino extension issue template a url instead.
(I just copied what was in the md file to the config)
> Make the browser extension issue template properly redirect

- CHANGELOG.md
- lib/lrucache/lrucache/lrucache.hpp
- src/common/ChannelChatters.cpp
- src/common/ChannelChatters.hpp
- tests/CMakeLists.txt
- tests/src/ChannelChatters.cpp
Definitely memory fuckery involved - The comment from @lubieerror https://github.com/Chatterino/chatterino2/issues/2822#issuecomment-897252673 is finally what led me to adding tests and hopefully fixing this.
- fix(lrucache): Ensure max_size is maintained in move ctor & operator=
- Add tests for ChannelChatters/chatterColors_
Fixes #2822
> Fix color @usernames sometimes not working at all

- src/providers/irc/IrcCommands.cpp
It didn't have space in between actual command and parameters, making it impossible to use it.
Fixes a mistake from 765a75f15.
The commit is almost 2 year old and the fact that nobody noticed it was broken until now makes me think that a changelog entry is not needed for this one.
> Fixed away command in IRC

- CHANGELOG.md
- src/providers/irc/IrcChannel2.cpp
Adds a link onto the username which opens a usercard, `messageText`/`searchText`, `loginName`/`displayName`.
Closes #1422
> Fix missing information in locally-generated IRC messages

- CHANGELOG.md
- src/providers/irc/AbstractIrcServer.cpp
This basically ensures we will actually join all the channels just fine - in some rare cases, even with ratelimitting logic, our JOINs can get lost in a limbo.
Even though we use the "18 JOINs / 10.5s" system now, sometimes sending messages to IRC can hit a small lagspike and (as quoted by @Felanbird, who also keeps getting this issue): "if the lag ends up being over .5s then eventually it will catch up to you and you'll be joining slightly faster than 10s and Twitch say NO". I got this issue a couple times myself as well.
> Raise ratelimit cooldown for JOIN messages

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
Applies to both username and emote completion using the completion menu.
Could probably change to `position - 1` in line 567 instead but this way it's consistent with `SplitInput::updateCompletionPopup`.
Fixes #3225
> Fix completion menu completing from wrong position

- CHANGELOG.md
- src/controllers/filters/parser/FilterParser.cpp
- src/controllers/filters/parser/Tokenizer.hpp
Adds `flags.reward_message` variable for filtering on channel point reward messages.
> Add `flags.reward_message` filter variable

- CHANGELOG.md
- src/RunGui.cpp
On macOS, programs are contained in ".app" application bundles. When chatterino restarts on a crash, it currently just looks for the executable path obtained via `QApplication::applicationFilePath()` and starts that again, which for macOS is the underlying unix executable inside of the application bundle. Unfortunately, for macOS those 2 are absolutely different, resulting in i.e. a second chatterino icon being added to the dock, due to the OS not recognizing that it is the same application.
This PR changes the restart logic for macOS to use Apples CoreFoundation API to get the path of the application bundle, and open this using the built-in "open" command. For every other OS, just starting the executable directly is, at least afaik, perfectly fine.
> Restart the application bundle instead of the underlying executable when crashing on macOS

- src/widgets/Scrollbar.cpp
There might be a warning due to us having a float variable in the loop end-stage https://wiki.sei.cmu.edu/confluence/display/c/FLP30-C.+Do+not+use+floating-point+variables+as+loop+counters but we don't use it as the counter, so we are good.
> Flatten the scrollbar highlight iteration

- CHANGELOG.md
- src/messages/Message.cpp
- src/widgets/Scrollbar.cpp
- src/widgets/helper/ScrollbarHighlight.cpp
- src/widgets/helper/ScrollbarHighlight.hpp
Added const method `isFirstMessageHighlight()` to check if a highlight is a first message highlight similar to `isRedeemedHighlight()`. Considered this new method and whether or not first message highlights were enabled in the settings while painting scrollbar highlights.
Bug can be reproduced by looking at a chat with first message highlights, going into the settings and disabling first message highlights and then observing that the scrollbar still shows the highlights for the first messages.
Closes #3317
> Fix 'First Message' scrollbar highlights not being disabled

- CHANGELOG.md
- src/providers/twitch/TwitchChannel.cpp
If you add a command that contains a new line in the message, it does not correctly send the message. It will only send the first line of the command. The issue does not occur if you manually input the message with new lines into the chat box and hit send. This behavior only seems to occur with commands.
For example, if you have a command set to the following (including the new line):
```
This line will be sent.
This line should not send.
```
The solution I found was to remove the new line characters from the message. Instead of removing it from the command itself when users add or update a command, it might be best to do so prior to sending the message as done in this PR. Also, I wasn't sure if messages would have a difference between `\n` and `\r\n` depending on …
> Clean up chat messages of special line characters prior to sending

- CHANGELOG.md
- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
Allow the inner `textElement_` for a EmoteElement to be reset with a text color if it is available upon creation of the EmoteElement. When emplacing EmoteElement's with a TextElement `color_` available, use it.
To reproduce this bug, disable emotes in settings and use /me with any emote. The text will not be colored accordingly.
Closes #3201
> Fix underlying text from disabled emotes not being colorized after using /me

- src/widgets/helper/ChannelView.cpp
Noticed in #3309 - both `/drops` and `/inventory` re-direct to `/drops/inventory`
Note: if we were to alphabetize these, in their current state the `};` would move to 1938 and save us 1 line ‼️
> Add "drops" as an ignoredUsername for context menu twitch links

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/IrcMessageHandler.cpp
Closes #3241 
Turns out that delete errors generally don't have a message.
> Make `/delete` errors a bit more verbose

- CHANGELOG.md
- src/providers/irc/IrcMessageBuilder.cpp
- src/providers/irc/IrcMessageBuilder.hpp
Adds emoji support that behaves like Twitch for IRC.
My test message:
```
3test🕹😂
```
This doesn't add support for emoji in the client-side echo message.
> Add support for Emoji in IRC.

- src/widgets/splits/Split.cpp
Fun fact: This is a very uncommon typo, there is only 6 other instances of this typo in public github repositories, (one of which was committed yesterday.) https://github.com/search?q=placeheolder&type=code
> Fix comment typo

- CHANGELOG.md
- src/common/ChannelChatters.cpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
Also I renamed `TwitchMessageBuilder::modsOrVipsSystemMessage` to `listOfUsersSystemMessage` because I wanted to reuse it. Part of #2673
> Make join and part messages have user links

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
I wonder if I :b: roke something. I don't think so but you can never be truly sure.
Closes #3361
> Fix Split Input hotkeys not being available when input is hidden

- src/controllers/highlights/HighlightModel.cpp
- src/messages/SharedMessageBuilder.cpp
- src/singletons/Settings.hpp
This PR adds "missing" code for `HighlightTaskbar` & `HighlightSound` for the `First Message` highlight. 
Standard comes from the above code for `Highlights Redeemed with Channel Points`
I also added a technically unrelated comment in SharedMessageBuilder.cpp because I was in there to make sure this actually works and I remembered wanting that comment last time I played around with first-msg sounds.
> Add some commented First Message code for consistency

- src/common/ChannelChatters.cpp
- src/common/ChannelChatters.hpp
- src/common/DownloadManager.cpp
- src/common/DownloadManager.hpp
- src/controllers/commands/CommandController.cpp
- src/controllers/filters/parser/Tokenizer.cpp
- src/messages/search/MessagePredicate.hpp
- src/providers/irc/IrcMessageBuilder.cpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/widgets/settingspages/ModerationPage.cpp
- src/widgets/splits/SplitContainer.cpp
- ~~[] `CHANGELOG.md` was updated, if applicable~~ Not applicable
I've made a few code refactors to try and reduce build warnings. I understand there has been a previous attempt by someone else that got rejected because a number of the changes were solely aimed at reducing warnings without caring about readability. So I only tried to fix those warnings I can find a justification for.
- Resolve "C4189: local variable initialized by not referenced" warnings
- Delete `twitchChannel` local variable in `CommandController.cpp`
- Delete `pos` local variable in `IrcMessageBuilder.cpp`
- Delete `direction` local variable in `SplitContainer.cpp`
- Delete `app` local variable in `ModerationPage.cpp`
- Resolve warning: C4457: declaration of 'text' hides function parameter
- …
> Refactor: fix build warnings

- CHANGELOG.md
- src/providers/irc/IrcCommands.cpp
If the user tries to use /kick with less than the 2 required parameters (channel and client), we would crash.
> Fix crash on missing parameters with IRC /kick command

- CHANGELOG.md
- src/providers/irc/IrcMessageBuilder.cpp
- src/providers/irc/IrcMessageBuilder.hpp
- src/providers/irc/IrcServer.cpp
- Normalize NOTICE message parsing for IRC
This fixes color parsing for NOTICE messages
Fixes #1782
NOTE: This does *NOT* fix color parsing for unhandled IRC messages.
When we promote a message type from Unhandled to Handled, we would make sure it used the standard path, thus enabling color parsing for free.
> Fix IRC colors not being applied correctly to NOTICE messages

- CHANGELOG.md
- src/messages/layouts/MessageLayoutContainer.cpp
Prevents trailing zero-width emotes from individually line breaking by considering their width as 0 instead of the calculated width of a space. For example, typing `LUL cvHazmat` will result in only the width of `LUL`, with `cvHazmat` completely disregarded. This in turn also prevents zero-width emotes from being shifted out of bounds to the left when individually line broken.
One side effect of this change is that stacked zero-width emotes (e.g., `cvHazmat cvHazmat cvHazmat`) will run out of bounds to the right if at the end of a line since they would now only be considered overflow from the base emote (e.g., `LUL`).
Fixes #3147
> Fix zero-width emotes sometimes wrapping lines incorrectly

- CHANGELOG.md
- src/singletons/helper/LoggingChannel.cpp
This PR moves to relocate `/live` logs to it's own directory, as it is a special channel.
This change as expected will cause users who use `/live` to have 2 different logging files, but from what I've seen, this channel is nowhere near as used as `/mentions` or `/whispers`, and coupling that with how many users do not log, this change shouldn't be too disruptive.
That being said, I've included said information in the changelog entry, and included a changelog entry for that reason.
> Move '/live' logs to its own subDirectory

- CHANGELOG.md
- src/common/ChannelChatters.cpp
Sorted usernames in these messages alphabetically. While I was at it, I noticed that `messageText` and `searchText` properties were missing, so I've also added them here. Sorted out some code and added an early-out.
Fixes #3420
> Sorted usernames in "Users joined/parted:" messages

- CHANGELOG.md
- src/providers/irc/IrcServer.cpp
- Mentions in IRC channels now get put into the /mentions split
The /mentions split is technically categorized both in our code and in the "new split" dialog as under Twitch, however the description indicates that it should show mentions from **all** channels, not just all Twitch channels.
This solution works but it's not super pretty in the code as we're importing and using the Twitch server to fetch the special mentions channel.
I have tested clicking the channel name and it finds the split correctly.
I have tested not having any Twitch channels open, and it still works as expected.
Fixes #3381
> Fix IRC mentions not showing up in the /mentions split

- .github/workflows/changelog-check.yml
With #3436, changelog enforcer action updates to v3; according to their [changelog](https://github.com/dangoslen/changelog-enforcer/blob/master/CHANGELOG.md#v300) `actions/checkout` is no longer required.
Related chatterino/api#256
> Remove actions/checkout from changelog check action

- CHANGELOG.md
- src/widgets/settingspages/HighlightingPage.cpp
Added the capability to highlight messages from sub or founder badges as they were missing to begin with. FWIW Founder badge highlighting does not fall under the subscriber badge. For example, 1/3/6/etc month sub would highlight via the Subscriber badge highlight, but you would have to have a separate highlight for Founder badge highlighting.
> Add subscriber and founder badge highlighting

- CHANGELOG.md
- src/widgets/Notebook.cpp
- src/widgets/Notebook.hpp
- src/widgets/dialogs/EmotePopup.cpp
This parameter is true by default, and when set to false ensures that
the page that was just selected will not be focused.
> Notebook::select now takes the optional parameter "focusPage".

- CHANGELOG.md
- src/widgets/dialogs/EmotePopup.cpp
- src/widgets/dialogs/EmotePopup.hpp
- src/widgets/splits/SplitInput.cpp
A search bar at the top of the emote popup that filters all emotes across every tab as you type. Uses a new ChannelView to combine all emote sets and is initially hidden until something is typed.
[1]: https://cdn.betterttv.net/emote/60477a2f306b602acc599abf/1x
> Add search to emote popup

- CHANGELOG.md
- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitHeader.hpp
Rate limit is per split but i can't see anyone using >30 splits to reload emotes fast enough for this to be an issue. Closes #3402.
> Removed ability to reload emotes really fast

- CHANGELOG.md
- src/CMakeLists.txt
- src/common/Version.cpp
- src/widgets/settingspages/AboutPage.cpp
Fixes #3430.
Relevant commit message:
> The date of build has previously been provided via a define supplied by
the CI runner. During the migration to GitHub Actions, this seems to
have been missed.
>
> This fix relies on CMake generating and providing the timestamp itself,
and passing it to the binary. Note that the timestamp will be of the
date when the **build files** were generated, i.e., not when the project
was compiled! For CI runs, however, the date of build file generation
should be consistent with the date of compilation so this approximation
is "good enough" for our purpose.
**Note that this only works for CMake-based builds so the QMake builds are out of luck**. I won't bother figuring out how to supply the information platform-independently (Windows, …
> fix: re-add build date to "About" page

- src/controllers/hotkeys/HotkeyController.cpp
This forces a save of settings after hotkeys have been saved into memory. I can't really reproduce the bug so this is the best fix I can do rn.
> Fix edge case where hotkeys would be empty after a crash, causing Chatterino to be unusable unless the user reset their hotkeys

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
> Implement workaround for combined emoji

- CHANGELOG.md
- src/messages/MessageBuilder.cpp
- src/widgets/helper/ChannelView.cpp
Following up 675f99e9c, added a check whether result of dynamic_cast is not a `nullptr` to prevent any other crashes caused by faulty badge elements.
Also fixed the AutoMod badge and made it an actual instance of `BadgeElement` which is what it should've been from the beginning, instead of `ImageElement`.
Fixes #2969
> Don't crash upon right-clicking automod badge

- .gitignore
While compiling with `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES` cmake can create a bunch of files in `.cache/`, indexing all codebase, allowing coc.nvim to make use of it, giving full rich autocompletion with all definitions etc. on NeoVim
credits to amazing @mm2pl who found this.
> Add .cache to gitignore

- .github/workflows/build.yml
This PR aims to remove the deprecated win2016 runner from the build matrix. See [this GH blog post](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/)
According to @pajlada this was required due to some cmake/qt build issue, but I've been unable to reproduce on my fork. Tested build pipeline using `windows-latest`/`windows-2022`, executable ran and connected without issue.
> fix: remove deprecated windows-2016/vs-2017 action runner from build matrix

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/util/StreamLink.cpp
Note: we could perhaps also show feedback when opening stream fails (e.g. channel is offline and/or child process quits with 1), but that's for another PR.
Fixes #3488
> Show feedback upon opening a channel in streamlink in more places

- CHANGELOG.md
- src/widgets/dialogs/EmotePopup.cpp
- src/widgets/dialogs/EmotePopup.hpp
I encased all Twitch-specific functionality in a check for a Twitch channel.
Closes #3526
> Made emote search not crash in non-Twitch channels.

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
Fixes #3531
While investigating #3531, I have found that `/popout` had same issue.
This PR should fix both issues.
> Disabled `/popout` and `/streamlink` from working in non-twitch channels (e.g. /whispers) when supplied no arguments

- CHANGELOG.md
- src/messages/MessageBuilder.cpp
- src/messages/layouts/MessageLayout.cpp
I added appropriate flags to AutoMod messages and made the hideModerationActions setting ignore Untimeout (unban) messages. Fixes #3547.
Note: this does not hide messages notifying users that their message was held, just the moderation variants.
> Fixed automod and unban messages showing when moderation actions were disabled

- src/controllers/commands/CommandController.cpp
- src/util/Twitch.cpp
- src/util/Twitch.hpp
- tests/CMakeLists.txt
- tests/src/UtilTwitch.cpp
- move stripUserName and stripChannelName to `util/Twitch.hpp`
- Add tests to stripUserName and stripChannelName
> Add tests to Twitch User/Channel name strip functions

- .github/workflows/build.yml
As per the expected changes from actions/virtual-environments#4856 - we have been randomly bumped to windows-2022, but our pre-compiled headers fail to build against this.
see: https://github.com/Felanbird/chatterino2/actions/runs/1856697316 
or https://github.com/Chatterino/chatterino2/actions/runs/1889705271
This PR moves to downgrade us back to windows-2019 as a workaround, so our windows builds actually build.
> Downgrade back to windows-2019

- BUILDING_ON_LINUX.md
Building on Ubuntu 18.04 no longer works as documented
```
CMake Error at lib/settings/CMakeLists.txt:132 (message):
GCC version must be at least 8.0 if using std filesystem
```
I verified the build instructions on Ubuntu 20.04 and they work as advertised.
> Updated build instructions

- .github/workflows/build.yml
- conanfile.txt
Fixed the CI build with `windows-latest`
The first build will now take around 30 min, but subsequential builds will be faster once the cache has been created
> :construction_worker: Fix CI build with VS 2022

- .github/workflows/build.yml
Due to a recent update to `actions/cache`, relative paths are no longer working (see https://github.com/Chatterino/chatterino2/runs/5365112238?check_suite_focus=true#step:49:2)
This PR fixes it by simply installing qt in the workspace instead of a directory higher
> :construction_worker: Fixed qt caching

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
Fixes #3593
Fixes #3604
Changed the order of setStylesheet and setPalette.
I believe setStylesheet was overriding setPalette's settings therefore placeholder text color was the same as normal text color.
Tested on arch with `qt-5.15.3`.
> Fixed SplitInput placeholder color

- .github/workflows/build.yml
- CHANGELOG.md
This PR aims to replace the hardcoded `-j8` make flag with a logical core count lookup. 
Ubuntu uses nproc (available on Linux), whereas macOS has to use a sysctl call. Could also use `getconf _NPROCESSORS_ONLN` as it returns the same result on both platforms.
> chore: use system logical core count for Ubuntu/macOS builds

- src/Application.cpp
- src/Application.hpp
- src/common/CompletionModel.cpp
- src/controllers/commands/CommandController.cpp
- src/controllers/filters/parser/FilterParser.cpp
- src/controllers/notifications/NotificationController.cpp
- src/providers/irc/IrcServer.cpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/NativeMessaging.cpp
- src/singletons/WindowManager.cpp
- src/util/StreamerMode.cpp
- src/widgets/FramelessEmbedWindow.cpp
- src/widgets/Window.cpp
- src/widgets/dialogs/EmotePopup.cpp
- src/widgets/dialogs/SelectChannelDialog.cpp
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/switcher/NewTabItem.cpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/splits/InputCompletionPopup.cpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/SplitInput.cpp
This PR aims to replace usages of `Application#twitch` with `Application#twitch2` as it was marked as obsolete. The name of `twitch2` has been changed to `twitch` for clarity.
> chore: replace usages of obsolete twitch struct with backing field

- CHANGELOG.md
- src/singletons/Settings.hpp
- src/widgets/Notebook.cpp
- src/widgets/Notebook.hpp
- src/widgets/helper/NotebookTab.cpp
Gives users the ability to lock their tabs on Chatterino to prevent accidental movement.
https://user-images.githubusercontent.com/6964154/159972762-331d7f15-3baa-4f8d-b007-5ff848b4d5d4.mp4
I'm not sure if it would be better practice to rely only on the `ChatterinoSetting` rather than also using a private variable `lockNotebookLayout_`. Would appreciate some guidance.
> Add the ability to lock NotebookTab layout

- CHANGELOG.md
- src/controllers/hotkeys/ActionNames.hpp
- src/widgets/splits/SplitInput.cpp
See #3628
Adds a new action to Split Input which selects the word under the cursor. There is no default binding, you have to add a hotkey yourself.
> Add an action to select the word under the cursor

- src/singletons/WindowManager.cpp
before;
after:
I put the `\n` in the same spot the formatter already broke the line at.
> Add newline to dontSaveSettings error

- src/providers/twitch/TwitchAccount.cpp
- src/providers/twitch/TwitchAccount.hpp
This PR aims to fix #3644 by re-adding the system message.
> fix: re-add missing Twitch emote reload message

- CHANGELOG.md
- src/controllers/notifications/NotificationController.cpp
- src/providers/twitch/api/Helix.hpp
Fixes #3646
* Add `userLogin`, `gameName` to `HelixStream`
* Store `userLogin` instead of `userName` from streams response
* Lookup lowercase `name` in `liveStreams` set
> Use login name for NotificationController lookup

- CHANGELOG.md
- src/messages/MessageBuilder.cpp
Added quotation marks around the automod phrases when they are added/removed from filter so it'll read like:
User added "phrase" to automod rather then User added phrase to automod. This allows for it to be far clearer
> Added quotation marks to automod phrases

- CHANGELOG.md
- src/widgets/splits/SplitHeader.cpp
Small and medium stream thumbnails are 16:9, but large stream thumbnails are 2:1 (360×180px). Adjust the large thumbnail to closer to 16:9 (360×203px) instead.
(yes, this is really stupidly minor but it annoys me every time I notice it)
> Adjust large stream thumbnail to 16:9

- src/Application.cpp
[`MessageBuilder(BanAction, uint32_t)`](https://github.com/Chatterino/chatterino2/blob/3afdb3367f8d318abad1eee8de093c28819b5539/src/messages/MessageBuilder.cpp#L281) calls [`getApp()`](https://github.com/Chatterino/chatterino2/blob/3afdb3367f8d318abad1eee8de093c28819b5539/src/Application.cpp#L427) which is required to run in the GUI thread.
I'm not sure if it's safe to just [add the `action` to the captures](https://github.com/Nerixyz/chatterino2/blob/6d205057ce17836004df7c1478b07142576a74c0/src/Application.cpp#L272) but since it's done for the [`automodMessage`](https://github.com/Nerixyz/chatterino2/blob/6d205057ce17836004df7c1478b07142576a74c0/src/Application.cpp#L343) as well, it should be okay.
> fix: build user timeout/ban message in GUI thread

- CHANGELOG.md
- src/providers/twitch/TwitchChannel.cpp
Removes unnecessary helix call (`getGameById`) now that `HelixStream` contains `gameName` (follow-up from https://github.com/Chatterino/chatterino2/pull/3648#issuecomment-1086924644)
> refactor(TwitchChannel): remove getGameById call

- CHANGELOG.md
- src/widgets/settingspages/AboutPage.cpp
This uses QSysInfo to get the pretty name of the OS and adds the kernel version. If the OS is unsupported, it will be displayed. I took the liberty of switching to using multi-arg in the existing version string. This should probably also show if Chatterino is running from an AppImage.
Needs testing on Windows and Mac.
Closes #3653
> Include user's operating system information in the About page

- CHANGELOG.md
- src/widgets/Notebook.cpp
- src/widgets/settingspages/FiltersPage.cpp
- src/widgets/settingspages/GeneralPage.cpp
- src/widgets/splits/Split.cpp
This PR gives parent ptr to poor orphaned children, preventing them from appearing behind main chatterino window when _Always on top_ is used. 
tested on windows only
closes #3672
> Add missing parent pointer to few QMessageBox and QFontDialog 

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
closes #3684
leaveEvent is fired only when mouse leaves whole listview, so no performance impact.
do we want changelog for this?
> Add missing tooltip hide on ChannelView leave event

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
- src/widgets/splits/Split.cpp
Adds the number of chatters to each category label in the viewer list.
> Add chatter count for each category in viewer list

- CHANGELOG.md
- src/messages/search/MessageFlagsPredicate.cpp
Lets you search for first messages with the "is:" predicate
> Added `is:first-msg` search option

- CHANGELOG.md
- src/widgets/helper/SettingsDialogTab.cpp
closes #755
icon scale was missing in text padding calculation 
|  | Before | After |
| ------------- | ------------- | ------------- |
| High DPI  | ![b1](https://user-images.githubusercontent.com/28986062/165867391-b2072f24-e227-4638-97cc-011a26b956ef.png)  | ![a1](https://user-images.githubusercontent.com/28986062/165867456-ec60d841-f91e-4cc7-a6e4-762037c608aa.png)  |
| 96 DPI  | ![b2](https://user-images.githubusercontent.com/28986062/165867426-1185d014-ba3d-4ddc-b808-acfc2ab7f252.png)  | ![a2](https://user-images.githubusercontent.com/28986062/165867475-8d2b3710-0102-4d39-b2b1-d9735ee3aad8.png)  |
> Fix incorrect spacing of settings icons at high DPI

- CHANGELOG.md
- src/providers/twitch/IrcMessageHandler.cpp
Twitch returns display names when you use the /vips command so usernames that start with uppercase letters get placed before names that start with lowercase letters.
> sort /vips output

- CHANGELOG.md
- src/util/IrcHelpers.hpp
- tests/CMakeLists.txt
- tests/src/IrcHelpers.cpp
When an irc tag has multiple escaped characters in a row, the current `parseTagString` function fails to see the 2nd `\` due to the extra `i++` (since the loop declaration already has `i++` and the string replacement eats two characters)
Example: `system-msg=DefectiveCloak\s\sgifted\sa\sTier\s1\ssub\sto\saliiscrying!` (weird case where their display name has a trailing space)
> fix: parse irc tags with consecutive escapes

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
Chatterino tries to refocus an existing emote popup instead of opening a new one, which works fine until the existing emote popup is now behind some other application. In that case chatterino still focuses the existing emote popup, but doesn't actually bring it to the front, resulting in no visible window being focused (since the main application has now lost focus) and you having to search for the emote popup somewhere on your desktop.
It seems like the issue is macOS specific since on other platforms/WMs you apparently just can't hide the emote popup behind something else as long as chatterino is focused, so this change should not affect any of them.
[felanbird]: here's his `.mov` showing the issue that github doesn't like https://i.nuuls.com/PgiHt.mp4
> fix: raise existing emote popups from behind other windows (macOS)

- src/messages/MessageBuilder.hpp
- src/util/LayoutCreator.hpp
These lines are formatted differently between clang-format 10 (on CI) and clang-format 11+ (on most dev systems)
This ensures dev systems don't start formatting them, and that our CI doesn't complain about them
> Disable formatting on "contested lines"

- CHANGELOG.md
- src/providers/twitch/PubSubManager.cpp
The `automod_rejected` action over moderator actions pubsub is sent to mods when automod catches an offending message (`automod_message_rejected`, on the other hand, is sent to the offending user, so we do not disable that).
However, we also use the (better) `automod-queue` topic for this info in [Application](https://github.com/Chatterino/chatterino2/blob/65301a3359aacc8a570e848b1fc4d2dd276f0e56/src/Application.cpp#L335-L425), resulting in a duplicated event handler. 
Fixes #3133
> fix: disable duplicate automod caught message handler

- CHANGELOG.md
- src/Application.cpp
- src/providers/twitch/PubSubManager.cpp
- src/providers/twitch/PubSubManager.hpp
Calls `unlistenAutomod` on `currentUserChanged`
Edit: confirmed fixed by badoge, related to #3133
> fix: unlisten to automod on user change

- src/controllers/hotkeys/Hotkey.hpp
This fixes compilation under GCC 12.1.0 by adding a missing `<vector>` header
> Add missing vector header

- src/providers/twitch/PubSubActions.hpp
Fixes compilation on Qt 5.12.x without precompiled headers. Found in https://github.com/Chatterino/chatterino2/runs/6420848248?check_suite_focus=true#step:18:256
> Add missing QDebug header

- CHANGELOG.md
- src/widgets/splits/Split.cpp
changelog
Currently the viewer list isn't able to be closed using the escape key like the rest of the popups. This PR adds the PopupWindow hotkeys to the viewer list QDockWidget so that you can close it with the escape key and use the search hotkey to select the search field.
Closes #3569
> Fixed viewer list not being closable with the escape key

- src/common/Env.cpp
- src/common/Env.hpp
- src/controllers/commands/CommandController.cpp
This is a follow-up to GH-2905, this code should've been removed back then.
I forgot how to use git when I made GH-3742
> Remove unused Env member for emoteset resolver url

- CHANGELOG.md
- src/providers/ffz/FfzBadges.hpp
- src/widgets/splits/SplitContainer.hpp
So for whatever reason apple-clang on macOS needs additional imports to successfully compile without precompiled headers. This issue does not exist when using gcc on ubuntu, which is what chatterinos CI is doing. I only just noticed it myself when compiling locally.
<details>
<summary>Compile errors</summary>
```
[ 22%] Building CXX object src/CMakeFiles/chatterino-lib.dir/common/Args.cpp.o
In file included from /Users/lassepetzel/code/chatterino2/src/common/Args.cpp:5:
In file included from /Users/lassepetzel/code/chatterino2/src/singletons/WindowManager.hpp:10:
/Users/lassepetzel/code/chatterino2/src/widgets/splits/SplitContainer.hpp:260:10: error: no template named 'unordered_map' in namespace 'std'
std::unordered_map<Split *, pajlada::Signals::SignalHolder> …
```
> fix: compilation on macOS without precompiled headers

- .github/workflows/build.yml
- .github/workflows/check-formatting.yml
- .github/workflows/lint.yml
- .github/workflows/push-aur.yml
- .github/workflows/test.yml
This PR aims to fix #3701 where updates to a PR did not cancel previous PR workflow runs. This is solved by using GitHub Actions' `concurrency` control option where each concurrent workflow is tagged with its name + the PR reference.
Video breakdown:
- Start with a PR that has kicked off some workflows
- Close the PR (workflows continue running, not sure how to solve that)
- Reopen the PR (new action, same as a push to source branch)
- Old workflows are cancelled and new workflows are created in place
Video:
https://user-images.githubusercontent.com/4962764/168783377-75d13c0b-fca6-4b89-bdc2-a685da5bbf19.mp4
> ci: cancel previous runs on PR update

- cmake/FindRapidJSON.cmake
- cmake/FindWebsocketpp.cmake
- vcpkg.json
PR fixes 2 problems found when testing recently merged vcpkg building, on clean VM run without global cache. #3634
- `FindRapidJSON.cmake` and `FindWebsocketpp.cmake` find modules were update to use `_INCLUDE_DIR` result variable instead of `_INCLUDE_DIRS`. [Cmake docs](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#standard-variable-names) state singular form vars should be used as return values. This change fixes problem where only these 2 dependencies would not be found in hinted /lib folder with vcpkg toolchain. Issue was reproduced on Cmake 3.23.0 and 3.20.21032501-MSVC_2, so seems like some vcpkg specific. Other find modules already use that return var for `find_path()` so don't expect problems, but we gonna find out :D
- Added missing …
> Fix vcpkg manifest and finding RapidJSON and Websocketpp modules

- README.md
As per fabZeef's experience after Windows reinstall, both .exe's from links from current README didn't work and he had to install the 'all' version. I think it's better. The new permalink link points to "VCRedist 2015-2022", which ensures you get everything you might need.
The new permalink is taken from Micro$oft's downloads page: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
Left out link to 2013 version just in case, but maybe it's old enough we can remove it as well(?).
I considered replacing it with what's on downloads page (https://aka.ms/highdpimfc2013x64enu), but it seemed to provide an older version, so maybe it's better to not change that.
> Updated link to VCRedist in README

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/TwitchCommon.hpp
Opens the current channel's reward queue, can also take an input to open some other channel's queue.
> added /requests command

- .github/workflows/test.yml
- .gitmodules
- CMakeLists.txt
- tests/CMakeLists.txt
We need GMock which is part of the same library, but there are no premade CMake constructs to include it unless we require CMake 3.20+, which we realistically cannot do.
Because of this, I've added the `googletest` submodule which contains both projects, and a few lines for building it if `BUILD_TESTS` is checked.
> Build GoogleTest & GoogleMock as submodules

- CHANGELOG.md
- src/controllers/commands/Command.cpp
- src/controllers/commands/Command.hpp
- src/controllers/commands/CommandModel.cpp
- src/controllers/commands/CommandModel.hpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/ChannelView.hpp
- src/widgets/settingspages/CommandPage.cpp
The command page will receive a checkbox column that will allow for a user to specify whether they want that command to appear on the message context menu. Upon right clicking a message, if there are any commands available that were checked to appear, you will receive an additional menu action to execute a command. It will take the text of the message you selected, either the whole message or only the selected portion if there is one, and pass it into the command like normal.
For example:
The command /google: `/openurl https://www.google.com/search?q={1+}` will allow you to quickly google the whole or a selected portion of a chat message.
Closes #3603
Closes #2058
> Feature: execute commands on chat messages using the context menu

- CHANGELOG.md
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchChannel.hpp
- src/providers/twitch/TwitchIrcServer.cpp
- src/providers/twitch/TwitchIrcServer.hpp
On startup, each channel currently individually make an api call to update its own live status on `roomId` change, this behavior will be unchanged.
Instead of having a timer for each individual channel to call to refresh its own live status, we will have a single timer in `TwitchIrcServer` that will update the live status of every channel at once in a single api call. Currently I have this set on a 30 second interval. This will be updated faster than the current 60 second interval, but since we are only making a single api call it will still result in an overall performance gain.
Similar logic for `NotificationController::fetchFakeChannels()` mentioned in the connected issue was already done in PR #3442 
Closes #3009
> Batch checking live status for all channels after startup.

- CHANGELOG.md
- src/providers/twitch/TwitchIrcServer.cpp
Use O(1) getChannelOrEmpty instead of O(n) getChannelOrEmptyByID in bulkRefreshLiveStatus
> perf: use constant time live channel lookup

- resources/_generate_resources.py
The `resources/generate_resources.py` script would not place newlines at the end of the generated files. This adds the newlines to the generation.
I don't think that a changelog entry is necessary for this change.
- ~`CHANGELOG.md` was updated, if applicable~
> Automatically place newlines at end of generated files

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
It simply copies provided arguments to clipboard.
See [GH-3761](https://github.com/Chatterino/chatterino2/discussions/3761#discussioncomment-2799759) for more context
Since I was at it I've added some missing newlines between `registerCommand` calls, it makes jumping between in editor these a bit easier ;p
> Added /copy command

- src/controllers/highlights/HighlightBadge.cpp
- src/messages/Message.hpp
- src/messages/SharedMessageBuilder.cpp
- src/messages/SharedMessageBuilder.hpp
- src/providers/twitch/TwitchBadge.cpp
- src/providers/twitch/TwitchBadge.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- tests/CMakeLists.txt
- tests/src/TwitchMessageBuilder.cpp
https://paste.ivr.fi/raw/marehysiwo
https://paste.ivr.fi/raw/ocidamuxyq
https://paste.ivr.fi/raw/opeponetyg
https://paste.ivr.fi/raw/icejijiqaq
tl;dr: we should split by slash only its occurrence instead of every occurrence.
It's been discovered that elements of the comma-separated list (taglist) in "badge-info" tag can have slashes in their values.
For example, "foo/bar/baz,tri/hard" can be a valid badge tag
In that case, valid map content should be:
`{"foo": "bar/baz", "tri": "hard"}`
With old logic of just splitting elements of the taglist by (every) slash it would be instead:
`{"foo": "bar" "baz", "tri": "hard"}`
Here, the "foo" element of the taglist would be considered invalid and skipped (because the amount of substrings after `QString::split` operation was …
> Corrected the way we parse comma-separated "list tags" in PRIVMSGs

- src/widgets/splits/SplitInput.cpp
Without it, you could "execute html" for yourself in the input box, which had no use
https://i.nuuls.com/sxpyU.png
> Use `setPlainText` when finishing a completion

- BUILDING_ON_WINDOWS.md
In #3390 we updated the build docs to support VS2022, but in Boost Step 3, the folder name was changed to the folder name that is already handled by Step 2.
See #3793 - While the user may have ran into more or less the same issue, they may have noticed the problem sooner if the Step 3 covered the correct `lib64-msvc-14.3` over Step 2 's `boost_1_79_0_b1_rc1`
This change reverts to the old variation of this line, but bumps it to `14.3`
> Update Windows build docs to rename the correct folder

- cmake/GIT.cmake
- src/CMakeLists.txt
This can be done by setting the `CHATTERINO_SKIP_DATE_GEN` and `CHATTERINO_SKIP_GIT_GEN` environment variables
> Add the ability to skip generation of git and date data

- CHANGELOG.md
- src/providers/twitch/api/Helix.hpp
- src/providers/twitch/api/README.md
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/dialogs/UserInfoPopup.hpp
Twitch removed the 'total views' counter from the channel page, dashboard, and I am certain the number isn't being updated anymore. [Announcement of total views being deprecated](https://discuss.dev.twitch.tv/t/get-users-api-endpoint-view-count-deprecation/37777)
> Removed total views from the usercard

- benchmarks/src/Highlights.cpp
- src/Application.hpp
- src/messages/SharedMessageBuilder.cpp
- tests/src/HighlightController.cpp
Added `getHighlights()` method pointing to underlying `highlights` member.
Switched from `getApp()` to `getIApp()` in `SharedMessageBuilder` to advantage of newly added `getHighlights()` in benchmark code.
Updated benchmark and test code accordingly to "upstream" changes in the `Application` class.
This fixes crash in Highlights benchmark:
> Added interface for highlights to Application

- .github/workflows/build.yml
- .github/workflows/test.yml
- Attempt to fix caching in test workflow, Acomplishes similar thing as #3586 and #3587
- Try to bump qt 5.12 version and see if it breaks
- Experiment with `workflow_dispatch` which allows us to manually trigger an action, see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow and https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch - however for this to work, it needs to be in the default branch.
Requires admin merge + required workflow update.
> Bump Qt 5.12.10 to 5.12.12

- CHANGELOG.md
- src/CMakeLists.txt
macOS CMake build doesn't include bundle icon
[felanbird]: Fixes #3210
> Add icon in the CMake macOS bundle

- src/controllers/highlights/HighlightModel.cpp
- src/controllers/highlights/HighlightModel.hpp
- src/widgets/settingspages/HighlightingPage.cpp
Changes hardcoded index values for the message highlights to a value set in the header file. All indexes except for WHISPER_ROW were hardcoded
> Moved highlight row index numbers to enum

- CHANGELOG.md
- src/common/Channel.cpp
- src/common/Channel.hpp
- src/widgets/Notebook.cpp
- src/widgets/helper/ChannelView.cpp
- src/widgets/helper/ResizingTextEdit.cpp
- src/widgets/helper/ResizingTextEdit.hpp
- src/widgets/splits/Split.cpp
- src/widgets/splits/Split.hpp
- src/widgets/splits/SplitContainer.cpp
- src/widgets/splits/SplitHeader.cpp
- src/widgets/splits/SplitInput.cpp
- src/widgets/splits/SplitInput.hpp
- Make IndirectChannel::get const
- Fix split focusing being broken in certain circumstances when the "Show input when it's empty" setting was disabled.
Fixes #2844 
Fixes #2714
> Fix split focusing being broken in certain circumstances when the "Show input when it's empty" setting was disabled

- BUILDING_ON_WINDOWS.md
To combat the ever updating versions of OpenSSL, I've gone ahead and done the following:
- Added a screenshot to show exactly what area of `slproweb` to find the newest version 
- Updated the additional help to remove suggestions that a newer version of `1.0.2_` can be found on `slproweb` - they no longer support said versions [see #3622]
- I'm aware it was discussed in that PR that looking into whether or not we still need the section for `1.0.2_`, but either way the paragraph will need to be updated. 
In it's current state if the archive link dies, we would like to know about it and it will give us (if needed) the push to have somebody actually look into it.
- Bumped the courtesy link to version `p` [mainly to match the screenshot I've added]
> Updated Building On Windows OpenSSL information

- CHANGELOG.md
- src/widgets/splits/Split.cpp
Previously, the title of the containing tab was only updated when a split's channel was set through the SelectChannelDialog. This lead to the bug described in #3845.
With this commit, the refresh action is moved into the Split::setChannel method, unifying the behavior.
**Note:** The changes in this PR were previously a part of #3848.
Fixes #3845
> fix(Split): always refresh tab when channel is set

- src/controllers/commands/CommandController.cpp
- src/singletons/WindowManager.cpp
- src/singletons/WindowManager.hpp
- src/widgets/dialogs/switcher/NewPopupItem.cpp
This PR unifies the two places in the code where a "new" channel was opened in a popup (opposed to opening an existing Split/SplitContainer in a popup) by introducing the method `WindowManager::openInPopup(ChannelPtr)`.
> ref: unify Split popup logic

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/widgets/Window.cpp
When restoring a split, the split would be appended to the split container but would not be selected. When accessing the selected split upon running the `/clearmessages` command as shown in the bug report, `nullptr` would be returned resulting in a segfault.
This PR fixes the underlying issue of the split not being selected and also adds a check for `nullptr`.
Fixes #3846
> Fix crash when closing and quickly opening a split, then running `/clearmessages`

- CHANGELOG.md
- src/widgets/helper/SearchPopup.cpp
This PR aims to fix #3870 where search predicates that act on system messages (ie. bans, timeouts) would not show system messages. This was caused by an oversight in the multi-channel search filtering logic that attempted to filter out duplicate messages (meant to catch the same channel in multiple splits) but ended up treating the ID-less system messages as duplicates.
*NOTE: it looks like the channel name isn't prepended to system messages, I'll create a separate fix for this*
Behaviour prior to fix (banned in 2 channels):
Post-fix:
> fix: prevent system messages from being ignored in multi-channel search

- CHANGELOG.md
- src/messages/MessageBuilder.cpp
This PR aims to fix #3692 where Twitch would add an extra `\s` to the end of anon sub messages, causing it to wrap an "empty" line in the gift message when hitting the window's width. By skipping empty words when splitting the message, no extra whitespace is added to system messages when the `TextElement`s are rejoined.
> Drop trailing whitespace from Twitch system messages

- CHANGELOG.md
- src/singletons/helper/GifTimer.cpp
- src/singletons/helper/GifTimer.hpp
Currently the check for the next animated frame is every 30ms which happens to be too slow for the gif standard, the maximum speed of a gif is 20ms per frame.
An edge case would be when a gif only has 2 frames
| Frame Number | Frame delay|
|:-:|:-:|
| 1 | 20ms | 
| 2 | 20ms |
The total frame duration is 40ms
In the current implementation, if we start at a 0 offset
| Offset | Offset mod 40 | Time Passed| Frame Displayed |
|:-:|:-:|:-:|:-:|
| 0 | 0 | 0ms | 1 |
| 33 | 33 | 30ms | 2 |
| 66 | 26 | 60ms | 2 |
| 99 | 19 | 90ms | 1 |
| 132 | 12 | 120ms | 1 |
As you can see the frames are duplicated when they shouldn't be. 
Its like a train station with trains ever 30ms and we are only ready to board every 20ms, and since we are impatient we miss our train. 
Perhaps a …
> Reduce GIF frame window from 30ms to 20ms

- CHANGELOG.md
- src/common/Channel.cpp
it used to read garbage from Channel data, it doesn't anymore
test:
```
$ LD_PRELOAD=/usr/lib/faketime/libfaketimeMT.so.1 FAKETIME='@2022-08-10 23:59:50' path/to/build/bin/chatterino
```
> Fix weird IRC channels causing crashes due to bad cast

- CHANGELOG.md
- src/common/Channel.cpp
- src/messages/MessageBuilder.cpp
- src/messages/MessageBuilder.hpp
* When the current user is timed out once no link was added.
* When the current user is timed out again a link to the user `You` was added.
> fix: Mentions of "You" in timeouts will link to your own user now instead of the user "You"

- .github/workflows/build.yml
Recently, nightly builds stopped working on macOS with outdated versions (I guess this is caused by the `macos-latest` being `macos-11.0`).
<details><summary>Popup</summary>
</details>
That makes me sad.
Let's support macOS Catalina for a while.
> Added minimal supported macOS version to CI builds.

- CHANGELOG.md
- src/common/Channel.cpp
When loading recent messages upon reconnecting, we would blindly assume that the channel already had at least one message in it. However, in the case that it somehow doesn't, we would index out of bounds of our `snapshot` and crash. 
This PR adds checks for empty channels (and empty loaded recent messages).
Fixes #3930
(Note: I haven't verified this _actually_ fixes the crash because I can't reproduce it on my own. However, the stack trace provided by Felanbird strongly suggests this should fix the crash).
> Fix crash when adding recent messages to empty Channel

- CHANGELOG.md
- src/Application.cpp
- src/messages/Emote.hpp
- src/providers/bttv/BttvEmotes.cpp
- src/providers/ffz/FfzEmotes.cpp
- src/providers/twitch/TwitchChannel.cpp
- src/providers/twitch/TwitchIrcServer.cpp
- src/providers/twitch/TwitchIrcServer.hpp
- src/singletons/Settings.hpp
- src/widgets/dialogs/EmotePopup.cpp
- src/widgets/settingspages/GeneralPage.cpp
In preparation to adding 7TV support, which users should be able to turn off, this PR adds settings to turn toggle BTTV/FFZ global/channel emotes.
> feat: add settings to toggle BTTV/FFZ global/channel emotes

- .github/workflows/build.yml
- .github/workflows/post-clang-tidy-review.yml
This supports the split workflow logic which makes it work on fork PRs
> Switch to dev branch of clang-tidy-review

- src/providers/twitch/TwitchEmotes.hpp
The mutex was initially used to limit access to the twitchEmotesCache_ member
but it's no longer necessary since it's been made a UniqueAccess type
> Remove unused mutex from Emotes

- CHANGELOG.md
- src/controllers/nicknames/NicknamesModel.cpp
Fixed issue #3887. Added whitespace trim to nickname string in NicknamesModel.cpp
> Filtering trailing/leading whitespace in username field in nicknames.

- .github/workflows/build.yml
This can just be slapped in on Sunday or whenever the last weekend commit is pushed, no need to block other PRs with a comment removal.
> Remove comment suggesting `Build Qt` is a Linux only build step

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
When clicking `Reply to message` the input text is replaced with `@{displayName} `, this PR attempts to retain any input that was typed before (i.e. the text is replaced with `@{displayName} {input} `).
> fix: retain text from input when replying

- CHANGELOG.md
- src/Application.cpp
Disabled `autoInvoke` because when this is first invoked, the room-id's aren't loaded yet - resulting in an error message (first introduced in #3935).
> fix: disable `autoInvoke` for emote settings

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- src/providers/twitch/api/README.md
- src/util/Twitch.cpp
- src/util/Twitch.hpp
- tests/src/HighlightController.cpp
- tests/src/UtilTwitch.cpp
This PR migrates the `/color` chat command to use the Helix API.
This migration does not necessitate any time-gating as the functionality is essentially the same except:
- ~~The pre-defined colors have changed names~~ This is no longer a concern to users as we accept both the old and new names. We will, however, only show the new names to users.
- The user has to re-authenticate to get the required scope on their token.
In addition to migrate the command, I've also added some documentation for how to add support for new Helix endpoints in the `/providers/twitch/api/README.md` file
Fixes #3963
> Migrate /color command to Helix API

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- tests/src/HighlightController.cpp
- Closes #3962 
- Implemented a new Helix func `deleteChatMessages` - this can be used for both `/delete` and `/clear `commands as they call the same Twitch Helix endpoint under the hood.
- Adds command handler for `/clear`, defined as a lambda function as I will come back in a followup PR to hook up the same lambda to `/delete` too.
> Migrate /clear command to Helix API

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- Fixes #3965
- Adds support for `/delete` to forward traffic to the equivalent [Helix endpoint](https://dev.twitch.tv/docs/api/reference#delete-chat-messages)
No endpoint addition needed, reusing the same logic from #3994
> Migrate /delete command to Helix API

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- tests/src/HighlightController.cpp
- Fixes #3970 
- Adds support for `/mod` command on Helix API, including all edge cases that I could think of - including trying to mod people in other channels.
> Migrate /mod command to Helix API

- src/singletons/Toasts.cpp
gotta give the users them SECURE links
Fixes #4004
> Fix windows toast notifications opening as http

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- tests/src/HighlightController.cpp
- Adds `removeChannelModerator` to Helix API
- Adds support to send `/unmod` through Helix API
Tested locally, couldn't find any edge cases - let me know if I missed anything.
[felanbird]: Fixes #3972
> Migrate /unmod command to Helix API

- .clang-tidy
Clang-tidy warning can be found here:
https://releases.llvm.org/10.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cert-err58-cpp.html
> Ignore cert-err58-cpp clang-tidy warning

- src/providers/twitch/api/Helix.cpp
Updates debug text on addChannelModerator success without status 204
> chore: fix debug text on non-204 add mod success

- CHANGELOG.md
- src/widgets/splits/InputCompletionPopup.cpp
- src/widgets/splits/SplitInput.cpp
The emote completion popup wasn't shown in irc channels and it had no emojis added. Note that emojis in sent message use the system's emojis (see #4020).
Fixes #3550.
> fix: Show Emoji Completion in IRC Channels

- CHANGELOG.md
- src/controllers/highlights/HighlightModel.cpp
- src/controllers/highlights/HighlightModel.hpp
- src/controllers/highlights/HighlightPhrase.cpp
- src/controllers/highlights/HighlightPhrase.hpp
- src/messages/Message.cpp
- src/messages/Message.hpp
- src/messages/layouts/MessageLayout.cpp
- src/providers/colors/ColorProvider.cpp
- src/providers/colors/ColorProvider.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/singletons/Settings.hpp
- src/util/SampleData.cpp
- src/widgets/Scrollbar.cpp
- src/widgets/helper/ScrollbarHighlight.cpp
- src/widgets/helper/ScrollbarHighlight.hpp
Added Basic Elevated Message Support via the existing standard of First Messages.
While this approach obviously is missing the main concept of this feature which is the "pinned message", it allows for users to not be left out of the loop, and allows moderators to properly moderate said messages. 
`(e.g. A message that might have gotten past if it was a normal message may gain additional scrutiny if it is an Elevated Message)`
TODO:
> Add Basic Elevated Message support

- CHANGELOG.md
- src/controllers/filters/parser/FilterParser.cpp
- src/controllers/filters/parser/Tokenizer.hpp
Added the `flags.elevated_message` filter variable
Relies on #4016
> Add `flags.elevated_message` filter variable

- CHANGELOG.md
- src/messages/search/MessageFlagsPredicate.cpp
Added the `is:elevated-msg` search predicate.
Relies on #4016
> Add `is:elevated-msg` search predicate

- CMakeLists.txt
Currently, trying to build the tests on Windows (with MSVC), you get a lot of nice linker errors, a lot of them like `error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'`.
[Googletest mentions in their readme](https://github.com/google/googletest/blob/main/googletest/README.md#visual-studio-dynamic-vs-static-runtimes) that you should set `gtest_force_shared_crt`. It has to be set before gtest is added to cmake.
> fix: set `gtest_force_shared_crt` in tests

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
For commands affected by the timegating, they will continue to use their IRC command equivalent until **the 11th of February, 2023**.
This is one week before the actual migration is supposed to start. The wording of the date is shaky, so we start a bit before to be sure.
Any highly affected commands will have a temporary setting at the bottom of the General settings page to override the timegating functionality.
Any commands that are affected will also have their changelog entry updated to notify of the timegating.
> Enable Helix timegating

- CHANGELOG.md
- src/providers/twitch/api/Helix.cpp
Clang-tidy had comments right near 401 so that's probably why we missed it
before:
after:
> Add missing 403 handling for /unban

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- tests/src/HighlightController.cpp
This migrates _both_ `/w` and `.w` to the Helix API since `.w` wasn't sent directly to IRC.
Closes #3986.
Also some parts of #1163 will be fixed.
> Migrate `/w` to Helix API

- CHANGELOG.md
- src/controllers/highlights/HighlightController.cpp
- src/controllers/highlights/HighlightController.hpp
- src/controllers/highlights/HighlightModel.cpp
- src/controllers/highlights/HighlightModel.hpp
- src/controllers/highlights/HighlightPhrase.cpp
- src/controllers/highlights/HighlightPhrase.hpp
- src/messages/Message.hpp
- src/messages/MessageThread.cpp
- src/messages/MessageThread.hpp
- src/messages/SharedMessageBuilder.cpp
- src/providers/colors/ColorProvider.cpp
- src/providers/colors/ColorProvider.hpp
- src/providers/twitch/IrcMessageHandler.cpp
- src/providers/twitch/IrcMessageHandler.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- tests/src/HighlightController.cpp
This PR removes the leading mention in a reply message ~~(currently without a setting)~~.
This aligns Chatterino's reply threads more with the way Twitch displays them in web-chat (See #4044).
As this removes highlights on reply threads, I've added a new highlight that will be active on all threads a user participated in (maybe this should be in another PR?).
Left: new, right: old.
Closes #4044.
> refactor: Remove Leading Mention in Replies and Highlight Participated Threads

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- tests/src/HighlightController.cpp
This PR aims to migrate the IRC server-side handling of the `/vips` command to a client-side Helix API call as part of the IRC command migration initiative. This feature is now broadcaster-only so care needs to be taken on how that's presented to the user :( 
Closes #3984
> chore: migrate /vips command to Helix call

- CHANGELOG.md
- src/providers/twitch/IrcMessageHandler.cpp
- Fix potential out-of-range access of at when stripping reply mention if the message contained nothing other than the username
- Update changelog entry
Example crash scenario
Content: `@pajlada`
Tag `reply-parent-display-name`: `pajlada`
content.at(1+displayName.length()) would look for the character after the username `pajlada`, but since there was no more text it would throw an exception or something
> Fix rare reply mention crash

- .cirrus.yml
It's now available in two flavours: qtkeychain-qt5 and qtkeychain-qt6
We change our dependency from qtkeychain to qtkeychain-qt5 to keep things working
> Fix FreeBSD Cirrus CI build

- CHANGELOG.md
- src/widgets/dialogs/ReplyThreadPopup.cpp
- src/widgets/dialogs/UserInfoPopup.cpp
- src/widgets/helper/SearchPopup.cpp
Added needed `MessageFlag::DoNotLog` override flags to messages being added to `Channel`s for user info and reply thread popups to avoid those messages getting rewritten to the file log.
This was also happening to the search popups but was going to a separate logging folder "Other". This is because the proxy `Channel` made for the SearchPopup `ChanneView` is of type `None` which doesn't have an associated `platformName` logging channel/folder as opposed to these channel-based popups which are of type `Twitch`/`Irc` so it was just being sent to a default "Other" folder.
Closes #4046
> Fix channel-based popups rewriting messages to file log

- CHANGELOG.md
- src/widgets/dialogs/EmotePopup.cpp
I'm currently merging chatterino2 into chatterino7 and I noticed something missing. ~~I might find something else, that's why this is only a draft for now.~~ This was the only difference.
> fix: missing global emotes in popup

- CHANGELOG.md
- src/widgets/helper/ResizingTextEdit.cpp
- src/widgets/helper/ResizingTextEdit.hpp
- src/widgets/splits/SplitInput.cpp
**Cycling through messages:**
* Send `foo`
* Type `PogCham`
* Press `Tab` (to complete the emote)
* Go to the previous message (`Up` by default)
* Press `Tab` _This will complete `foo` to `PogChamp`._
**Replying:**
* Type `PogCham foo`
* Move cursor behind `PogCham`
* Press `Tab` (to complete the emote)
* Right click any message and select `Reply to message`
* Press `Tab` _This will complete `foo` to `PogChamp`._
This only happens when cycling through messages and replying. It doesn't happen in other places calling `setPlainText`.
> fix: Invalid/Dangling completion after updating input

- src/providers/IvrApi.cpp
- src/providers/IvrApi.hpp
- Migrated `IvrApi::getSubage` function to use v2 version of its API.
- Updated link to the endpoint's documentation.
- Since this was the last endpoint from this provider to use a v1 route, base url for the API and its usages have been updated accordingly.
- Also applied some copying removal (not sure if it's correct though, pls correct me if that's a bad move).
> Migrated `getSubage` to v2 version of the API

- src/providers/twitch/IrcMessageHandler.cpp
Removed `the` because it's not necessary
`consider setting Abc to penis in your Chatterino settings`
`consider setting the Abc to penis in your Chatterino settings`
> Update IRC whisper error

- src/providers/twitch/TwitchMessageBuilder.cpp
Text Elements normally have the `MessageElementFlag::Text` flag, reply text does not.
This is needed in #3958 to properly order reply text.
> Add missing Text tag to reply message text

- src/util/NuulsUploader.cpp
`parseJson` will return an empty object if the body is not a valid JSON string.
We currently try to read:
`.error` as an error string, of which we include a maximum of 300 characters.
`.code` as any type of value, of which we include a maximum of 20 characters.
Fixes #4095
> Include more error messaging for failed image uploads

- CHANGELOG.md
- src/messages/MessageElement.cpp
- src/messages/MessageElement.hpp
- src/messages/layouts/MessageLayoutContainer.cpp
- src/messages/layouts/MessageLayoutElement.cpp
- src/messages/layouts/MessageLayoutElement.hpp
- src/singletons/Settings.hpp
Improves the overall appearance of the reply curve. Related: #4009
Curve drawing parameters are defined here and can be tuned if people feel that some other value set would look better:
https://github.com/dnsge/chatterino2/blob/cf1c994cb4c5bae40c27af172e233965e84ca016/src/messages/MessageElement.cpp#L687-L690
New Appearance:
The vertical expanding nature of the reply curve has been removed from this PR. I will create another PR for the logic.
Improves the overall appearance of the reply curve. Related: #4009
1. Uses linear horizontal and vertical parts with a curve in the top left (much like discord)
2. Fully extends downwards to the element below
The vertical growth works as follows:
1. All elements are laid out, as usual, line by line
2. We iterate through every …
> Improve Appearance of Reply Curve

- CHANGELOG.md
- src/providers/twitch/api/Helix.cpp
Had a false sense of confidence that SURELY this call had been made, but the `hasModRights` check will return false for the first check. We should delay the initial call until the USERSTATE message has come in and we know whether they're a moderator or not
> Fix recursive fetchChatters call

- src/messages/layouts/MessageLayout.cpp
- src/messages/layouts/MessageLayout.hpp
There have been so many changes to the reply thread changelog entry (and this is a bugfix to a bugfix) that I really don't care if we don't add this PR to the changelog.
#4092 Introduced the following bug: 
The reply text is improperly rendered in the reply thread popup.
This PR fixes the bug. The bug itself is my fault because, during the (extensive) changes made to my original reply threads PR, I changed around how hiding the reply message elements worked. This change eliminates the `setRenderReplies` method which became unused at some point.
Also: sorry for the unrelated change of extracting the accessing of setting values. I just couldn't leave the repeated calls that could easily be reused.
> Fix Reply Text Showing In Reply Thread Popup

- conanfile.txt
#4098 updated the convenience link for OpenSSL, so here we'll try the new versions in CI.
A note on boost: This updates boost on Windows to 1.80, but it should be noted, that the Ubuntu-CI is still on [1.74](https://packages.ubuntu.com/jammy/libboost-dev), macOS should be on 1.80.
> deps[conan]: update openssl and boost on Windows

- CHANGELOG.md
- src/widgets/helper/ChannelView.cpp
Twitch-specific filters, like `channel.live` were never applied because the channel context sent was a Channel created to contain the filtered messages, not the actual underlying channel
> Fix Twitch-specific filters not being applied

- src/widgets/helper/ChannelView.hpp
```
==38498== Conditional jump or move depends on uninitialised value(s)
==38498==    at 0x6F966C: chatterino::ChannelView::drawMessages(QPainter&) (ChannelView.cpp:1262)
==38498==    by 0x6F9206: chatterino::ChannelView::paintEvent(QPaintEvent*) (ChannelView.cpp:1215)
==38498==    by 0x4B8C3C3: QWidget::event(QEvent*) (qwidget.cpp:8824)
==38498==    by 0x4B55B1B: QApplicationPrivate::notify_helper(QObject*, QEvent*) (qapplication.cpp:3637)
==38498==    by 0x5B85F97: QCoreApplication::notifyInternal2(QObject*, QEvent*) (qcoreapplication.cpp:1064)
==38498==    by 0x4B8034A: QWidgetPrivate::sendPaintEvent(QRegion const&) (qwidget.cpp:5477)
==38498==    by 0x4B816A5: QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, …
```
> Fix uninitialized read in `ChannelView`'s `highlightedMessage_`

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- tests/src/HighlightController.cpp
Migrated the commercial command to the new helix API. Functionality is timegated so the command uses the IRC functionality as long as possible. I yoinked this PR from pajlada with his permission, approximately 57.8% of this PR's code is his :nerd_face: !
Closes #3964
> Migrate /commercial command to the Helix API

- CMakeLists.txt
- cmake/CodeCoverage.cmake
- src/Application.cpp
- src/Application.hpp
- src/CMakeLists.txt
- src/common/SignalVector.hpp
- src/providers/twitch/TwitchEmotes.cpp
- src/providers/twitch/TwitchEmotes.hpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- src/singletons/Emotes.hpp
- src/widgets/dialogs/switcher/QuickSwitcherModel.hpp
- tests/src/HighlightController.cpp
- tests/src/TwitchMessageBuilder.cpp
Messages I tested with
`/fakemsg @emotes=84608:9-10 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`
`/fakemsg @emotes=84608:0-0 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`
`/fakemsg @emotes=84608:0-1 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`
`/fakemsg @emotes=84608:0-15 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`
`/fakemsg @emotes=84608:15-2 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`
`/fakemsg @badge-info=;badges=glhf-pledge/1;client-nonce=5d2627b0cbe56fa05faf5420def4807d;color=#1E90FF;display-name=oldcoeur;emote-only=1;emotes=84608:0-7;first-msg=1;flags=;id=7412fea4-8683-4cc9-a506-4228127a5c2d;mod=0;room-id=62300805;subscriber=0;tmi-sent-ts=1623429859222;turbo=0;user-id=139147886;user-type= …
> Harden emote parsing

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/TwitchMessageBuilder.cpp
- src/providers/twitch/TwitchMessageBuilder.hpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
- src/singletons/Settings.hpp
- src/widgets/settingspages/GeneralPage.cpp
- tests/src/HighlightController.cpp
closes #3971 
Modeled after the /chatters migration PR #4088.
/mods command no longer uses the irc command and now makes a helix api request.
mod list is paginated just like chatter list.
> Migrate /mods command to helix API

- .CI/CreateUbuntuDeb.sh
- .github/workflows/build.yml
Test release can be found here: https://github.com/pajlada/chatterino2/releases/tag/nightly-build
I also made the deb-creation script fall back to version `0.0.0-dev` in case no git tag was found - useful for forks that have no tags
> Switch to ncipollo/release-action for generating our Nightly releases

- vcpkg.json
introduced changes to match recent canon update #4100:
- update vcpkg baseline to https://github.com/microsoft/vcpkg/commit/5ba2b95aea2a39aa89444949c7a047af38c401c1, bumping boost to 1.80
atm there is no newer openssl 1.1,1 to pin
- manifest formated with its own cmd tool `vcpkg format-manifest vcpkg.json`
suggest no changelog
> chore: update vcpkg baseline

- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
- src/providers/twitch/api/Helix.cpp
- src/providers/twitch/api/Helix.hpp
Removed client side check for valid commercial lengths and instead let the commercial api endpoint to handle it. They actually do not throw an error back for an invalid length but instead find the closest appropriate length value and returns that length in the response. Sending `/commercial 0` does return an error though treating it as a missing required parameter which this is now being handled.
> Allow Commercial API endpoint to handle commercial lengths

- CHANGELOG.md
- src/messages/layouts/MessageLayoutContainer.cpp
- src/messages/layouts/MessageLayoutElement.cpp
changed ``0x200F`` unicode to ``0x202B`` for better [font support](https://github.com/Chatterino/chatterino2/pull/3958#issuecomment-1310792964),
and cases like ``الStyles`` (it's broken even in twitch, ال should be on the right and Styles on the left)
it has a minor issue with something like ``سلام 1-2``
thanks to @mohad12211 for the hard work
> change unicode for better font support and fix some cases

- CHANGELOG.md
- src/messages/Image.cpp
While looking at #4145 I found that images that are rejected because they are too large or have an invalid format are never marked as empty. This PR fixes that. It also has the consequence that for emote-tooltips where the 3x variant is too large, the 2x or 1x variants eventually get shown.
> fix: Mark Bad or Invalid Images as Empty

- CHANGELOG.md
- src/widgets/Notebook.cpp
#3925 had a slight error that I'm surprised I didn't manage to spot: when calculating the number of tabs per column when using a vertical tab layout, we would not account for the ~1 px space between tabs. This would lead to improper wrapping with many tabs (note cut off tab at the bottom):
And with this fix:
> Fix tab wrapping with vertical tab layout

- CHANGELOG.md
- src/providers/ffz/FfzBadges.cpp
- src/providers/ffz/FfzBadges.hpp
- Ensure users cannot have the same FrankerFaceZ badge more than once
> Fix users being assigned duplicate FrankerFaceZ badges

- BUILDING_ON_WINDOWS.md
Initially I wanted to enable ASan in tests as well, but this just won't work (which is really sad), because [ASan doesn't like the Settings](https://github.com/Nerixyz/chatterino2/actions/runs/3491324277/jobs/5843820385). At least it can be documented how one enables ASan with MSVC now, since `sanitizers-cmake` doesn't cover MSVC.
> docs: add documentation for AddressSanitizer on MSVC

- CHANGELOG.md
- src/messages/layouts/MessageLayoutContainer.cpp
- src/messages/layouts/MessageLayoutContainer.hpp
This is an attempt at fixing the crash.
Currently, the ellipsis is misplaced (since it's not really added):
It should be added at the first position (like it's done in browsers if the `direction` is `rtl`).
Fixes #4166. Thanks to @mohad12211 for making the ellipsis adding simple.
```
واحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنينواحد اثنين 
```
```
واحد اثنين ثلاثه اربعه one two three four واحد اثنين ثلاثه اربعه one two three four واحد …
```
> fix: Limiting the height of a message that contains some RTL text causes a crash

- CHANGELOG.md
- src/singletons/NativeMessaging.cpp
When the extension sends multiple messages with the same channel, Chatterino will always set the channel and thus dispatch a channel-changed signal (which causes a re-layout) even if the channel was already set.
Maybe this could be done in `IndirectChannel::reset` instead?
https://github.com/Chatterino/chatterino2/blob/3924861a3da6308cd8ee5e108c4c21884cfc81b3/src/common/Channel.cpp#L453-L459
> fix: `/watching` channel jumping around

- .github/workflows/build.yml
- CHANGELOG.md
- src/controllers/commands/CommandController.cpp
In a previous life, the IRC `/vips` response returned the `loginName` of said VIPs. One day we woke up and Twitch suddenly started sending us the `displayName`'s of those VIPs.
The problem with this was the fact that display names containing Asian language characters are of no use to us in Chatterino, as Twitch has no way of looking up a user, by these names.
Due to the migration of the `/vips` command to the Helix API, this fix will only help broadcasters (after the Timegate), but I do think it's better for them to be able to use the usercard feature in Chatterino, from the VIPs response.
Also suggested as a fix in https://github.com/Chatterino/chatterino2/pull/4053#discussion_r990955144
Fixes #3524
> Fix issue with VIPs who have Asian Language display names

- CHANGELOG.md
- src/widgets/splits/SplitInput.cpp
- src/widgets/splits/SplitInput.hpp
By default, a `QWidget` will [ignore the `mousePressEvent`](https://github.com/qt/qtbase/blob/5.12.12/src/widgets/kernel/qwidget.cpp#L9539-L9554). Before #3838, `SplitInput` had a handler for this event and thus didn't ignore the event. But the PR [removed the event handler](https://github.com/Chatterino/chatterino2/pull/3838/files#diff-28a2425a552a515ae2556b51b50f4e3102c012c67dfa291cd13b52e1406e2417).
This PR adds the handler back, and only calls the parent handler if the input is hidden. This has the effect that the context menu of the `ResizingTextEdit` is shown again, so that's what I mentioned in the changelog.
Fixes #3844.
> fix: don't ignore `mousePressEvent` in `SplitInput`

- src/CMakeLists.txt
If you looked through the build logs in CI, you might have noticed a warning on almost all files from `cl`: `Command line warning D9025 : overriding '/W3' with '/W4'`. This is because some project (I suspect websocketpp) is adding `/W3` to `CMAKE_CXX_FLAGS`.
We're doing the same fix here that [googletest does](https://github.com/google/googletest/blob/9c332145b71c36a5bad9688312c79184f98601ff/googletest/cmake/internal_utils.cmake#L49-L51) (just with `CMAKE_CXX_FLAGS`, as that's enough).
> chore(msvc): replace /W3 with /W4

- CHANGELOG.md
- src/singletons/WindowManager.cpp
Motivated by #4179, attempts to fix #3863 and fix #4180.
Need someone to test this as I don't have access to a Windows machine. This is not an ideal fix in my opinion. It would have been better if it was possible to parent windows on Windows and have them show up in the task bar regardless. However, I was not able to figure out how to do that or whether it is possible at all. Thus, aiming for this bandaid solution for now.
> fix: don't parent popup windows on Windows OS

- CHANGELOG.md
- src/widgets/Notebook.cpp
- src/widgets/Notebook.hpp
- rename any tab in main window to something unique like "asd"
- popout window (ctrl+n), can be any chat or empty tab
- open quick switch (ctrl+k) and search for "asd"
- click it to select and crash
QuickSwitcher has 2 types of search result: split (specific channel) or container (whole notebook page), tab rename above was used as simply way for container result which is focus of this crash.
Clicking on result invokes  `selectSplitContainer` signal:
https://github.com/Chatterino/chatterino2/blob/9d1b8b0a93a5d8df10ea6ea55159efbbe3bd65e1/src/singletons/WindowManager.cpp#L326
with callback declared here:
https://github.com/Chatterino/chatterino2/blob/9d1b8b0a93a5d8df10ea6ea55159efbbe3bd65e1/src/widgets/Notebook.cpp#L1071
Each poped out window adds own callback, so …
> Fix crash happening when QuickSwitcher is used with popout window

- CHANGELOG.md
- src/messages/layouts/MessageLayoutContainer.cpp
- src/messages/layouts/MessageLayoutContainer.hpp
If a text has RTL, and some line starts with neutral words (like emotes), it won't follow previous words (whether the previous was reversed or not) and that will result in wrong ordering across multiple lines.
before (wrong): 
after (correct): 
Test String: 
`واحد اثنين one two Kappa KKona three four `
> fix neutral elements order in multiple lines

- CHANGELOG.md
- src/widgets/BaseWindow.cpp
changes:
- use `-1` margins passed to `DwmExtendFrameIntoClientArea` to effectively disable invisible window borders, which caused white border to appear around maximized windows (visible on 2nd monitor)
- tiny refactor of `WM_NCCALCSIZE` handling
fixes #2205
tested on:
> Fix white border appearing around maximized window
