README.md
Clang-format version 11 is no longer satisfactory for us, as it does not support `CaseSensitive:`, which was added in #4172
The current latest-release of clang-format is `15.0.6`, but it does not have a win64 asset, so `15.0.5` it is.
Quick testing seems to show this version works as expected for our use case: https://github.com/SevenTV/chatterino7/pull/159#issuecomment-1335661136
=> Bump suggested clang-format version to `15.0.5`

CHANGELOG.md, src/widgets/AccountSwitchPopup.cpp, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/DraggablePopup.cpp, src/widgets/FramelessEmbedWindow.cpp, src/widgets/TooltipWidget.cpp, src/widgets/TooltipWidget.hpp, src/widgets/dialogs/ColorPickerDialog.cpp, src/widgets/dialogs/NotificationPopup.cpp, src/widgets/dialogs/QualityPopup.cpp, src/widgets/dialogs/SelectChannelDialog.cpp, src/widgets/dialogs/SettingsDialog.cpp, src/widgets/dialogs/UpdateDialog.cpp, src/widgets/dialogs/WelcomeDialog.cpp, src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp, src/widgets/helper/SearchPopup.cpp, src/widgets/settingspages/AboutPage.cpp, src/widgets/splits/InputCompletionPopup.cpp
`BaseWindow` is forcing delayed layout save
at every resizeEvent
https://github.com/Chatterino/chatterino2/blob/22bd78e3b3dd6721db5f75d3456e3876185f0f3d/src/widgets/BaseWindow.cpp#L543
and moveEvent
https://github.com/Chatterino/chatterino2/blob/22bd78e3b3dd6721db5f75d3456e3876185f0f3d/src/widgets/BaseWindow.cpp#L575
TooltipWidget and other subclasses unnecessarily triggers both of above.
PR adds new BaseWindow flag `DisableLayoutSave` to fix that
Tested movement and resizing of tooltips (after preview images load) and everything works as expected.
=> fix: prevent unnecessary layout saves

CHANGELOG.md, src/providers/twitch/TwitchCommon.hpp, src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp
PR fixes problems with message overflow highlight, feature added in #3418
current issues:			
- selecting all (ctrl+a) on overflowed input and typing, will keep red color
- pressing up arrow on overflowed input, will keep red color on history messages
- removing characters at <500 position wont move red overflow marking, which can be useful when trying to edit message to fit
- hidden recursion in `setCharFormat()` re-emiting `QTextEdit::textChanged()`
PR introduced changes to fix above:
- always mark characters up to 500 with default color 
- add blocking of unwanted signals
=> Fix red text color persisting from message overflow highlight

CHANGELOG.md, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/Split.hpp, src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp
Previously, pressing CTRL + C would attempt to copy from the original split (→ and its channel view) instead. This PR fixes the bug.
Fixes #4208.
=> fix: Copy Shortcut Not Working In Reply Thread Popup

CHANGELOG.md, src/controllers/highlights/HighlightController.cpp, src/controllers/highlights/HighlightModel.cpp, src/controllers/highlights/HighlightModel.hpp, src/messages/SharedMessageBuilder.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/HighlightingPage.cpp, src/widgets/settingspages/SettingsPage.hpp
As discussed in #1540, this clears up the highlight settings for sounds:
<details><summary>Without custom default sound</summary>
</details>
Closes #1540.
=> Clear up Highlight sound settings

CHANGELOG.md, src/widgets/helper/EditableModelView.cpp, src/widgets/helper/EditableModelView.hpp, src/widgets/settingspages/KeyboardSettingsPage.cpp
Pressing `Add` button above tables in settings window adds new row at the bottom. 
When table has scrollbar, new rows are not visible right away and its not clear if Add button even worked.
changes introduced in PR:
- new rows are automatically selected (and scrolled to when not visible) in all settings tables
- removed now redundant selections in Hotkeys (`KeyboardSettingsPage`)
- unnecessary `EditableModelView::selectRow(int row)` is removed and `QTableView::selectRow(int row)` is used internally instead. Functionality is still exposed via existing public api: `EditableModelView::getTableView()->selectRow()`
=> feat: Automatically select newly added table rows

src/providers/twitch/TwitchMessageBuilder.cpp, src/providers/twitch/TwitchMessageBuilder.hpp
Move Twitch reply/thread parsing & building to its own function
=> Move thread parsing & building to its own private function

src/widgets/settingspages/GeneralPage.cpp
Purely a cosmetic issue, as the checkbox changes based on what setting you already had, but it would cause confusion when reading the setting, if not fixed.
Accidentally implemented in #4213
=> Fix accidental change of `stripLeadingMentions` setting

.github/workflows/push-aur.yml
The action will always use the (upstream) master branch and never actually build the PR itself. 
It's not really clear from the name of the action what it will do - maybe it should be renamed?
=> fix: don't run `push-aur.yml` on pull requests

src/widgets/dialogs/EmotePopup.cpp, src/widgets/dialogs/EmotePopup.hpp
Flatten the anonymous namespace
Make the `loadEmojis` functions static
Make the `filterEmoteMap` function static
Return an EmoteMap from `filterEmoteMap` instead of an EmoteMap*
Other misc cool changes :-)
=> Refactor the EmotePopup file

src/common/CompletionModel.cpp, src/common/CompletionModel.hpp
- Refactor CompletionModel
- Use a shared mutex for CompletionModel's items mutex
=> Clean up CompletionModel

.clang-tidy, src/widgets/splits/InputCompletionPopup.cpp, src/widgets/splits/InputCompletionPopup.hpp, src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp
Mainly flattening anon namespaces & respecting clang-tidy
=> Clean up/refactor InputCompletionPopup

.cirrus.yml, CMakeLists.txt
=> Update qtkeychain to `e5b070831cf1ea3cb98c95f97fcb7439f8d79bd6`

.github/workflows/build.yml, CHANGELOG.md, CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
This is disabled by default, and can be enabled by passing `-DCHATTERINO_LTO=On` to your cmake invocation.
I plan on enabling only for 1 of the PR builds, and for all PR builds on the main branch to not slow down CI too much
=> Enable LTO support for Chatterino builds

.clang-tidy, src/CMakeLists.txt, src/singletons/WindowManager.cpp, src/widgets/Window.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/switcher/NewTabItem.cpp, src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp, src/widgets/dialogs/switcher/QuickSwitcherPopup.hpp, src/widgets/helper/NotebookButton.cpp, src/widgets/helper/NotebookTab.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/splits/DraggedSplit.cpp, src/widgets/splits/DraggedSplit.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/SplitContainer.cpp, src/widgets/splits/SplitContainer.hpp
- Remove unused include util/Helpers.hpp
- SplitContainer::setTag fix parameter naming
- autofy/constify where possible
- Make SplitNode::Type an enum class
- Make SplitNode::Type an enum class
- Move QuickSwitcherPopup includes from header to source file
- Remove unused DropRegion code
- use empty() instead of size() == 0
- Add curly braces everywhere
- More const auto ptr magicifying
- Remove useless reinterpret_cast
- Clarify that the connect is QObject::connect
- SplitContainer::setSelected fix parameter naming
- Rename function variables to remove unneccesary underscore
- emplace_back where possible
- Name parameters
- Remove ineffective const from return type
- Make node getters const
- Flatten Node::releaseSplit
- Rename in-function variable to match code …
=> SplitContainer refactor

CHANGELOG.md, src/widgets/helper/ResizingTextEdit.cpp
Tries to be a bit smarter for when to just paste regular old text instead of an image
Needs some thorough testing with mixed clipboards
Fixes #4245
To test:
1) Open excel/openoffice
2) Copy 1 or more cells
3) Paste into Chatterino with an image uploader configured. It should, atm, post an image of it
4) Disable your image uploader and paste it into Chatterino again. Before this PR it would just not paste anything, after this PR it should paste the text of the cells
Tested on Windows, macOS, Linux X11
Not tested on Wayland, someone can do that and make another PR if this breaks it (although I don't think it would)
=> Only try to extract images if the image uploader is enabled

BUILDING_ON_LINUX.md
=> Add `qt5-imageformats` to Fedora dependency list

CHANGELOG.md, src/widgets/dialogs/SelectChannelDialog.cpp
Fixes #4196 
The `eventFilter` if statement meant for the `radio` was returning false and filtering out the `focusIn` event triggered by the line edit.
=> Fix text cursor in open channel dialog

CHANGELOG.md, src/util/StreamerMode.cpp, src/util/WindowsHelper.hpp, src/widgets/AttachedWindow.cpp, src/widgets/BaseWindow.cpp, src/widgets/FramelessEmbedWindow.cpp
**This doesn't remove all unused include directives.** I only checked files that had imports that were only present on Windows (`#ifdef USEWINSDK`). Notably, this removes `gdiplus.h` from `BaseWindow.h` which sometimes relied on the `min` and `max` macros defined through `Windows.h`.
=> fix: Remove Unused Include Directives

CHANGELOG.md, src/messages/Image.cpp, src/messages/Image.hpp
`Image::operator==` and `Image::operator!=` are unused, so I marked them as `delete`.
=> Remove unused operators in `Image`

CHANGELOG.md, src/widgets/Notebook.cpp
Some timers would crash, and actions like CTRL+T that act on "the selected tab" would cause a crash.
This crash was introduced in https://github.com/Chatterino/chatterino2/pull/4187 - and because it has proper reproduction steps, I've tested those after this fix too to ensure we don't regress.
Fixes #4269
=> Fix crash that would occur when performing certain actions after removing all tabs

src/providers/twitch/TwitchChannel.hpp, src/util/Helpers.cpp, src/util/Helpers.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/Split.hpp, src/widgets/splits/SplitHeader.cpp, src/widgets/splits/SplitHeader.hpp
- Flatten static functions in anonymous namespace
- SplitHeader ctor: Rename param
- Header: Remove unnecessary `virtual`s
- auto ptr where possible
- Add curly braces
- Comment twitch room modes
- Treat roomModes->slowMode as an integer
- Remove unused `this` from lambdas
- Add `unsigned int` overload for localizeNumbers
- Move thumbnail max age to a constexpr static & set explicit types
- Explicitly use `QObject::connect`
- Use `empty()` instead of `size()`
- Name unused parameters
- Move moderation action refreshing logic from SplitHeader to Split
The only real code change here was moving the moderation action refresh logic to Split, and splitting that up into its own function for clarity. The previous `enable if enabled` was messy
=> Refactor SplitHeader class

CHANGELOG.md, src/widgets/splits/SplitHeader.cpp
Specifically, if a split was closed after the request for a thumbnail
had been made, but before the request had finished, we'd run into a
use-after-free issue
=> Fix crash that could occur when closing down splits

src/util/IncognitoBrowser.cpp, src/util/IncognitoBrowser.hpp
=> Flatten util/IncognitoBrowser.{h,c}pp

CHANGELOG.md, src/singletons/WindowManager.cpp, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/dialogs/NotificationPopup.cpp, src/widgets/helper/Button.cpp, src/widgets/splits/SplitHeader.cpp
[`QDesktopWidget` is marked as obsolete](https://doc.qt.io/qt-5/qdesktopwidget.html) in Qt 5 and removed in Qt 6. This PR migrates two (similar) usages.
Both used `QDesktopWidget` to check if something is inside the screen or not. [`QDesktopWidget::availableGeometry`](https://doc.qt.io/qt-5/qdesktopwidget.html#screenGeometry-1) used to return the available geometry of the screen the widget was in. Now, [`QGuiApplication::screenAt`](https://doc.qt.io/qt-5/qguiapplication.html#screenAt) is used.
Fixes #1926
=> Remove Deprecated `QDesktopWidget`

CHANGELOG.md, src/widgets/Scrollbar.cpp, src/widgets/Scrollbar.hpp, src/widgets/helper/ChannelView.cpp
If the default channel scrollback limit is changed in settings, more messages will be stored but the original number of highlights are stored in the scrollbar. This PR updates the scrollbar to be consistent with the channel.
Fixes #4270
=> Fix scrollbar highlight colors when changing message history limit

src/CMakeLists.txt
vcpkg handles coping of required dependencies [by itself](https://github.com/microsoft/vcpkg/blob/master/ports/qt5-base/qtdeploy.ps1), PR adds check for VCPKG to skip unnecessary run of windeployqt.exe (which did nothing anyway due to path differences).
suggest no changelog
=> Fix: dont run windeployqt with VCPKG

CHANGELOG.md, src/CMakeLists.txt, src/controllers/logging/ChannelLog.cpp, src/controllers/logging/ChannelLog.hpp, src/controllers/logging/ChannelLoggingModel.cpp, src/controllers/logging/ChannelLoggingModel.hpp, src/singletons/Logging.cpp, src/singletons/Logging.hpp, src/singletons/Settings.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/ModerationPage.cpp
Implemented feature requested in https://github.com/Chatterino/chatterino2/issues/1456 to allow custom selection of channels to log. Added a new setting on Moderation(Logs) page to enable this feature as well as a table to add channels and a checkbox for whether messages for each channel should be logged or not
=> Add feature to select channels to log

CHANGELOG.md, src/controllers/highlights/HighlightController.cpp, src/widgets/settingspages/HighlightingPage.cpp
- Change the highlight order to prioritize Message highlights over User highlights
Fixes #4259
=> Change the highlight order to prioritize Message highlights over User highlights

.cirrus.yml, .clang-tidy, .github/FUNDING.yml, .github/ISSUE_TEMPLATE/a_make_a_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/dependabot.yml, .github/workflows/build.yml, .github/workflows/changelog-check.yml, .github/workflows/check-formatting.yml, .github/workflows/homebrew.yml, .github/workflows/lint.yml, .github/workflows/post-clang-tidy-review.yml, .github/workflows/push-aur.yml, .github/workflows/test.yml, .prettierignore, .prettierrc, .prettierrc.toml, CHANGELOG.md, benchmarks/.clang-format, src/.clang-format, tests/.clang-format
These files were previously ignored by prettier, but to keep a consistent style these should be formatted as well.
I moved the config from TOML to JSON, because the JSON file is easier to read (mainly because of the `overrides`).
=> Format YAML and JSON Files With Prettier

resources/contributors.txt
Removed the mention of `/generate_resources.py` due to it's removal in #4159
Also mentioned that the user is not required to add their avatar, due to the fact that it seems common that new contributors include their PFP, while existing contributors omit it
=> Update `contributors.txt` instructions

.gitmodules, CHANGELOG.md, resources/licenses/miniaudio.txt, src/Application.cpp, src/Application.hpp, src/CMakeLists.txt, src/PrecompiledHeader.hpp, src/common/QLogging.cpp, src/common/QLogging.hpp, src/controllers/notifications/NotificationController.cpp, src/controllers/sound/SoundController.cpp, src/controllers/sound/SoundController.hpp, src/messages/SharedMessageBuilder.cpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/widgets/settingspages/AboutPage.cpp
- Use miniaudio for playing highlights
- Use miniaudio for playing "going live" notifications
- Remove QMediaPlayer includes
1. Open Chatterino
2. Before you receive any mentions, ensure Chatterino shows up in your OS volume mixer. Please screenshot this.
3. Have a mention sound play without a custom sound selected. You should hear the default Chatterino ping. Test this at least 5 times.
4. Set a custom sound either for your highlight or a default fallback sound. Have a mention fire. You should hear the custom sound play. Test this at least 5 times.
5. Remove the custom sound, then have a mention fire again. You should hear the default Chatterino ping.
6. If your volume mixer supports this, reduce the volume of Chatterino, shut down Chatterino, open up Chatterino …
=> Change sound backend from Qt to miniaudio

CHANGELOG.md, resources/qt.conf, src/CMakeLists.txt
Chatterino had only [rudimentary support](https://github.com/Chatterino/chatterino2/blob/5ad8ca791c0498fb39e21d07b3c0e856b3e7677b/src/CMakeLists.txt#L640-L648) for `<build-tool> install` on Windows, because it only copied the `chatterino.exe`.
There were two main issues:
1. No shared libraries such as openssl were copied to `CMAKE_INSTALL_PREFIX`.
2. `windeployqt` never ran, because the command silently failed (cmake's [set](https://cmake.org/cmake/help/latest/command/set.html) joins [multiple arguments](https://github.com/Chatterino/chatterino2/blob/5ad8ca791c0498fb39e21d07b3c0e856b3e7677b/src/CMakeLists.txt#L642) as a semicolon-separated list).
This PR addresses these issues:
1. The [`RUNTIME_DEPENDENCIES`](https://cmake.org/cmake/help/latest/command/install.html# …
=> Add CMake Install Support for Windows

.github/workflows/build.yml, BUILDING_ON_WINDOWS.md, CHANGELOG.md, CMakeLists.txt, conanfile.txt, src/CMakeLists.txt
The [`cmake`](https://docs.conan.io/en/latest/reference/generators/cmake.html) generator is marked as deprecated - [`CMakeDeps`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html) and [`CMakeToolchain`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html) are recommended. This PR migrates to these generators.
0. Make sure you're using at least version 1.33 (Jan-2021).
1. Rerun `conan install`
2. Remove `-DUSE_CONAN` from your CMake arguments, and add `-DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"`.
3. CMake might give you an error similar to `Generator <generator> does not support platform specification...`. If that's the case, set `conf.tools.cmake.cmaketoolchain:generator` in …
=> Use `CMakeDeps` and `CMakeToolchain` as Generators on Conan

CMakeLists.txt, src/CMakeLists.txt
I just noticed in the push-aur-workflow that it failed because of it not finding Qt5Multimedia, so this is my attempt in fixing it. I do not know if it fixes it specifically because I do not know how to test the aur-workflow, but I was able to play a sound after compiling this branch on my local machine.
Here is the error in the workflow I'm talking about:
Here is the version I compiled and tested (by simply pinging myself `#wissididom wissididombot: @Wissididom Testping`):
=> Remove Qt::Multimedia as a dependency from CMakeLists.txt

cmake/GIT.cmake
Some may have wondered why `cmake` prints [`true`](https://github.com/Chatterino/chatterino2/actions/runs/4036940542/jobs/6939893312#step:17:41) when configuring. Turns out, it's the output of `git rev-parse --is-inside-work-tree`. I don't see any reason to include the `true` output, since no context is given. This PR adds the `OUTPUT_QUIET` flag to [`execute_process`](https://cmake.org/cmake/help/latest/command/execute_process.html) to suppress output.
=> Suppress Output of Git Command in CMake

.github/workflows/build.yml
I just noticed it being in the workflow run and because I heard that gstreamer isn't needed anymore after moving to miniaudio, I decided to try removing it. Also I just used the AppImage build from https://github.com/Wissididom/chatterino2/pull/12 to test it working.
=> Removed libgstreamer-plugins-base from build workflow

CHANGELOG.md, src/providers/twitch/TwitchChannel.cpp
Related to https://github.com/Chatterino/chatterino2/issues/3942#issuecomment-1421226657. This attempts to catch a [`std::bad_function_call`](https://en.cppreference.com/w/cpp/utility/functional/bad_function_call). **This doesn't resolve the underlying issue that causes this to be thrown.** Furthermore, there are probably more issues related to this, as some crash reports suggest that no exception is thrown.
=> Attempt to catch `std::bad_function_call` when adding a channel point reward

CHANGELOG.md, src/controllers/commands/CommandController.cpp, src/providers/RecentMessagesApi.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp
Now chatterino will use ZERO WIDTH JOINER when sending messages again.
=> Remove sending part of the multipart emoji workaround

CHANGELOG.md, src/util/IncognitoBrowser.cpp, src/util/WindowsHelper.cpp, src/util/WindowsHelper.hpp
The existing getCommand() in IncognitoBrowser.cpp directly queries undocumented registry keys which could break if Windows decides to change the registry layout (as they have in the past.)
This PR changes getCommand() to instead call AssocQueryString, which smooths out differences between versions of Windows.
=> use AssocQueryString instead of directly querying the registry

CHANGELOG.md, src/widgets/helper/Button.cpp, src/widgets/helper/Button.hpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp, src/widgets/helper/NotebookTab.cpp, src/widgets/helper/NotebookTab.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/Split.hpp, src/widgets/splits/SplitHeader.cpp, src/widgets/splits/SplitHeader.hpp
Qt 6 changed the argument type for [`QWidget::enterEvent`](https://doc.qt.io/qt-6/qwidget.html#enterEvent) from `QEvent` to `QEnterEvent`. I don't think this event is ever used other than passing it on.
This also removes the `virtual` keyword on some declarations as it's unnecessary as `override` is present.
=> Use `QEnterEvent` for `QWidget::enterEvent` on Qt 6

CHANGELOG.md, src/messages/Image.cpp, src/messages/Image.hpp
When running tests on **macOS**, the program finishes with the following error:
`libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument`
This is caused by `ImageExpirationPool` which is indirectly being used in the `Emojis.ShortcodeParsing` test. When the emoji Image objects are destructed, they are removed from the ImageExpirationPool. Despite having a static lifetime, the `ImageExpirationPool` seems to have been destroyed before these `Image` objects, so the `ImageExpirationPool`'s mutex is used after it has been destructed.
The simple solution is to just disable the `ImageExpirationPool` logic during tests.
=> Disable ImageExpirationPool during testing

.github/workflows/build.yml
I noticed the Nightly Build on the master branch failing, so I checked the artifact names of the last run of my deb PR and found differences that I fixed in this PR.
=> Fix Ubuntu builds preventing `create-release` from building

.CI/CreateUbuntuDeb.sh, .github/workflows/build.yml
This PR makes the nightly build workflow update the tag to have up-to-date source code options on the Nightly Release.
References/Proof:
https://github.com/ncipollo/release-action/issues/31
https://i.imgur.com/zkKPrem.png
(felanbird): Fixes #3443
=> Automatically update `nightly-build` tag every nightly release

CHANGELOG.md, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/FramelessEmbedWindow.cpp, src/widgets/FramelessEmbedWindow.hpp
[`QWidget::nativeEvent`](https://doc.qt.io/qt-6/qwidget.html#nativeEvent) in Qt 6 takes `qintptr*` as its last argument ([Qt 5 docs](https://doc.qt.io/qt-5/qwidget.html#nativeEvent)). `qintptr*` doesn't mix well with `long*`, that's why it's ifdef'd.
=> Use `qintptr` in `QWidget::nativeEvent` on Qt 6

.CI/CreateUbuntuDeb.sh
pajlada: "If you want to improve this, I'd rather it be done in a separate PR so we can nitpick over it without blocking the main purpose of the PR" from https://github.com/Chatterino/chatterino2/pull/4374
=> Handle non-versioned annotated tags gracefully when building a Ubuntu .deb package

src/controllers/commands/CommandController.cpp
Fix some microscopic typos in separators used for failure messages, changed them to match the rest (`"something - "`).
=> Fix inconsistent separator usage in command failure messages

CHANGELOG.md, src/widgets/dialogs/UserInfoPopup.cpp
They previously didn't follow the proper "Should we use Helix?" route so
they break when IRC commands are removed.
=> Fix mod, unmod, vip, unvip buttons in User Card

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp, tests/src/HighlightController.cpp
- Only highlight whispers that have the `ShowInMentions` flag
- Add tests for whisper in and out of mentions
=> Stop whispers from showing up in /mentions unless they match another highlight

.github/workflows/build.yml, .github/workflows/homebrew.yml, CHANGELOG.md
It previously tried to bump the version from 2.4.0 to v2.4.1
the action didn't strip the v, but it does now
=> Fix the brew cask action

.github/workflows/build.yml, CHANGELOG.md, CMakeLists.txt, src/CMakeLists.txt, src/PrecompiledHeader.hpp, src/common/LinkParser.cpp, src/controllers/commands/CommandController.cpp, src/controllers/commands/CommandController.hpp, src/controllers/sound/SoundController.cpp, src/providers/bttv/liveupdates/BttvLiveUpdateSubscription.cpp, src/providers/irc/IrcServer.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/util/Helpers.cpp, src/util/Helpers.hpp, src/widgets/Notebook.cpp, src/widgets/dialogs/SettingsDialog.cpp, src/widgets/helper/ResizingTextEdit.cpp, src/widgets/helper/SettingsDialogTab.cpp, src/widgets/settingspages/AboutPage.cpp, src/widgets/settingspages/ModerationPage.cpp, src/widgets/splits/SplitInput.cpp
- Add Qt Core5Compat dependency if building with Qt6
- Add specialization to `localizeNumber` that accepts a `qsizetype`
- Add missing `QFile` include to `SoundController.cpp`
- Add missing `QFile` include to `SettingsDialog.cpp`
- Add missing `QFile` include to `AboutPage.cpp`
- Format IRC username-randomizer in IrcServer using QString arg
- Comment out usage of `setCodec` in `LinkParser.cpp` for Qt6
- Comment out usage of `setCodec` in `AboutPage.cpp` for Qt6
- Store max spaces as a `qsizetype` in `CommandController`
- Use QStringView.split instead of QString splitRef
- `int`ify some usages of `size`
- Replace QStringRef with QStringView in TwitchMessageBuilder
- Replace `QStringRef` with `QStringView` in ResizingTextEdit
- Clarify QPoint constructor in …
=> Fix Qt6 building

CHANGELOG.md, src/RunGui.cpp
As mentioned in #4391, this ensures only the five most recent crashdumps are saved. This uses a similar strategy to how the cache is cleaned up after starting Chatterino.
Fixes #4391.
=> Delete all but the last 5 crash dumps on startup

.CI/CreateAppImage.sh, .docker/Dockerfile-ubuntu-20.04-package, .docker/Dockerfile-ubuntu-22.04-package, .docker/README.md, .github/workflows/build.yml, CHANGELOG.md
We've updated to the latest version of `linuxdeployqt` in this PR & we now upload the Qt 5.12 AppImage instead of Qt 5.15
Fixes #4397
=> Fix AppImage not containing all SSL dependencies

CHANGELOG.md, src/providers/seventv/SeventvBadges.cpp
While looking through the code I found that `SeventvBadges` used a `shared_lock` while writing to the locked data. This wasn't an issue, because the badges are only ever loaded once at the start.
=> Use `unique_lock` when loading 7TV badges

src/widgets/dialogs/EmotePopup.cpp
This PR aims to update the label for 7TV emotes that is shown to users when searching for emotes in the emote picker. When browsing emotes, the section's label uses the `7TV` name; however, when searching for emotes in the same popup window, the name `SevenTV` was used. 
As suggested by the 7TV crew (I believe Anatole was the one who we had this convo with), any user-facing branding should use the name `7TV`. Only code should reference the name `SevenTV`
Thanks for finding it Malachi :)
=> fix: update user-facing emote picker labels to use "7TV" naming

src/util/Helpers.cpp, src/util/Helpers.hpp
=> Templatize localizeNumbers

CHANGELOG.md, src/controllers/commands/CommandController.cpp
With the `/ban` command migrated to Helix, we are no longer able to ban suspended or deactivated accounts because helix `getUsers` is not able to resolve the `user_id` associated with the login name. However, if a moderator already knows the `user_id`, helix `banUser` *is* able to ban the account, even if suspended or deactivated. Thus, this PR adds a `/banid` command to allow banning users by id.
Note: similar concerns apply for timeout/unban, but are not covered by this PR (and are not as important imo)
=> Add ban user by id command `/banid`

CHANGELOG.md, CMakeLists.txt, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
This release exists because after 5 years, FFZ handled the fact that their responses did not contain `https:` - which we had manually been adding to FFZ requests since c2e2dfb577196b74d85d9055f24914ffdfc53b45, so FFZ emotes just don't work anymore hehe. 
Option 1) Merge this PR and have a quick `2.4.2` release
Option 2) Say heck the stable users and wait until later this month when #4117 has to be merged anyway (I started telling people to update tomorrow, so probably not this option)
Option 3) Do nothing and say frick FFZ (probably too late to do this one since I already merged https://github.com/Chatterino/chatterino2/pull/4432)
This cannot use dash to …
=> Release v2.4.2

CHANGELOG.md, src/common/QLogging.cpp
Regression from https://github.com/Chatterino/chatterino2/commit/044dd8a616e0b712eaf6cb954cd7b999aed18b06
Closes #4440
=> Only log debug messages when NDEBUG is not defined

BUILDING_ON_LINUX.md
Couldn't compile on Mint 21 till I installed libsecret-1-dev.
=> Update Debian dependencies to include libsecret

CHANGELOG.md, src/messages/layouts/MessageLayout.cpp, src/singletons/Theme.cpp, src/singletons/Theme.hpp, src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp, src/widgets/helper/NotebookButton.cpp, src/widgets/listview/GenericListView.cpp, src/widgets/splits/SplitContainer.cpp
I mentioned this in #4447 at the beginning a bit: The theme code is hard to read and hard to maintain. This PR attempts to clean this code up (a bit at least). If you see more clean-up possibilities, let me know.
The commits should be reviewable on their own.
=> Cleanup `Theme`-related Code

CHANGELOG.md, src/providers/ffz/FfzEmotes.cpp
This PR adds support for animated FFZ emotes and shows authors for global emotes:
https://user-images.githubusercontent.com/19953266/222955005-3c5dfc09-2162-4745-ad9f-9b355262e89a.mp4
---
I refactored the code a bit to reduce duplicated parsing of channel/global emotes and to make it easier to read (by replacing [`QJsonObject::value`](https://doc.qt.io/qt-5/qjsonobject.html#value) with [`QJsonObject::operator[]`](https://doc.qt.io/qt-5/qjsonobject.html#operator-5b-5d)).
=> Support Animated FFZ Emotes and Authors for Global Emotes

CHANGELOG.md, src/providers/bttv/BttvLiveUpdates.cpp
The JSON payload of the [_User Update_](https://betterttv.com/developers/websocket#user-update) event was always logged as an unhandled event. The payload is really large however and pollutes the log, since it's known that this message is unhandled.
=> Ignore BTTV user-events

CHANGELOG.md, src/common/FlagsEnum.hpp, src/messages/MessageElement.cpp, src/messages/MessageElement.hpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/widgets/helper/ChannelView.cpp
All emotes in a `LayeredEmoteElement` now carry additional flags.
Fixes #4459.
=> Allow each layered image to retain its own flags

CHANGELOG.md, src/widgets/settingspages/GeneralPage.cpp
=> Fix an issue where the "Enable zero-width emotes" setting was showing the inverse state

.github/workflows/build.yml, CHANGELOG.md, src/util/WindowsHelper.hpp
The Windows CI didn't respect the `matrix.pch` setting/option. It now respects it.
=> Respect PCH Setting in Windows CI

CHANGELOG.md, src/singletons/Fonts.cpp
The `QFont::Weight` enum changed its range from `0..99` in Qt 5 to `1..1000` in Qt 6 ([Qt 5 docs](https://doc.qt.io/qt-5/qfont.html#Weight-enum), [Qt 6 docs](https://doc.qt.io/qt-6/qfont.html#Weight-enum)). Since absolute values are used for usernames, this broke the username rendering.
Fixes #4467.
=> Fix Username Font Weight Issue on Qt 6

CHANGELOG.md, src/RunGui.cpp
This PR specifies a color for [`QPalette::PlaceholderText`](https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum) (added in Qt 5.12). This color wasn't used if not specified in Qt 5, but it's an independent color in Qt 6 ([docs](https://doc.qt.io/qt-6/qpalette.html#placeholderText)).
Furthermore, this PR also reorders the colors to make it more readable - all calls specifying a specific [color-group](https://doc.qt.io/qt-6/qpalette.html#ColorGroup-enum) are below the calls that specify a color for all color groups.
Doing this fixes the placeholder text in the `QLineEdit` in the settings dialog:
|Before|After|
|---|---|
| ![before](https://user-images.githubusercontent.com/19953266/227715396-2c426669-580e-4534-8ab3-52228dcaf139.png) | …
=> Add Placeholder Color in Palette

CHANGELOG.md, src/singletons/Settings.cpp, tests/src/HighlightController.cpp, tests/src/main.cpp
- Assert that Settings is initialized when `instance` is called
- Rework HighlightController directory creation/saving to ensure the test directory is written to & cleaned up appropriately
- Ensure settings are default-initialized before any tests are run
=> Ensure tests have default-initialized settings

CHANGELOG.md, src/providers/RecentMessagesApi.cpp
=> Fix memory leak when using the Recent Messages API

CHANGELOG.md, src/common/Channel.cpp, src/widgets/helper/SearchPopup.cpp, tests/src/HighlightController.cpp
PR introduces 2 changes:
- `Channel` messages_ field is initialized to `scrollbackSplitLimit` setting, so it doesnt use default value of 1000.
All code using Channel::getMessageSnapshot() was affected as it returned only up to 1k messages, while `ChannelView` respected custom scrollback setting, so it created at least few problems.
Example: https://i.supa.codes/Fn6J8.mp4 text selection would move up on each new message instead of holding its position. 
- use `scrollbackSplitLimit` for SearchPopup channelView, so all messages for single channel are always searchable.
fixes #4495
Fixes #4324
=> Fix channel search when custom scrollback limit is used

CHANGELOG.md, src/controllers/plugins/LuaAPI.cpp
Fixes a small compilation error (I introduced) that only shows up on Qt 6:
* **MSVC:** _error C3445: copy-list-initialization of 'QDebug' cannot use an explicit constructor_
* **clang:** _Chosen constructor is explicit in copy-initialization - clang(selected_explicit_constructor)_
The `QDebug::QDebug(QString *)` constructor [is marked as `explicit` in Qt 6](https://github.com/qt/qtbase/blob/eb8782cb2ea765080945a775a806b377b5943833/src/corelib/io/qdebug.h#L72) and [was marked as `inline` in Qt 5](https://github.com/qt/qtbase/blob/4ee4fc18b4067b90efa46ca9baba74f53b54d9ec/src/corelib/io/qdebug.h#L115).
=> Fix plugin compilation error when using Qt 6

.github/workflows/build.yml
There are some minor refactorings to the Windows-CI:
* Install `conan` from pip (same as in [pajlada/settings](https://github.com/pajlada/settings/blob/f168c0997fb85789bbc54513fce8bbc212dda2ff/.github/workflows/build.yml#L70-L89)).
* Lock `conan` to a specific version (currently 2.0.2 due to https://github.com/conan-io/conan/issues/13606 - not sure when 2.0.4 will be released, but it will be released on pip earlier).
* Split building and installing/building dependencies.
=> Refactor Windows CI and Conan Usage

src/widgets/Notebook.cpp, src/widgets/splits/SplitHeader.cpp
Note: I am not a c++ developer at all. I don't know if these changes are sound. But they let me build the project, and it seems to work.
Fixes issues of this form: 
```
/home/guipsp/local/chatterino2/src/widgets/splits/SplitHeader.cpp:531:46: error: converting to ‘const std::optional<std::vector<QString> >’ from initializer list would use explicit constructor ‘constexpr std::optional<_Tp>::optional(std::in_place_t, _Args&& ...) [with _Args = {}; typename std::enable_if<__and_v<std::is_constructible<_Tp, _Args ...> >, bool>::type <anonymous> = false; _Tp = std::vector<QString>]’
531 |             notifySeq = h->getDisplaySequence(HotkeyCategory::Split,
|                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
532 | …
```
=> Fix build on latest Fedora

CHANGELOG.md, resources/themes/Black.json
As stated in my previous PR #4140 "This PR sets out to make the current black theme better match other themes. On the current black theme the only thing that is changed is the chat background which has bothered me for a while. So, I decided to try to match the rest of Chatterino Themes with the black theme. I'm open to changes to any of the colours I have changed if you feel something would look better." Now that #4471 has been merged I feel that the request of Pajlada ↓↓ has been met.
> Pajlada commented Nov 12, 2022, 5:45AM CST
> While the thematic changes are good and I think the improvement in looks is nice, how this looks in the code is not maintainable. Some better facility for specifying the colors are needed for me to be ok with merging this in.
‎‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ …
=> Streamline the look of the Black theme

CHANGELOG.md, CMakeLists.txt, benchmarks/CMakeLists.txt, src/messages/Image.cpp, src/messages/Image.hpp, src/messages/ImageSet.cpp, src/providers/emoji/Emojis.cpp, tests/CMakeLists.txt
- Remove Emojis.cpp CHATTERINO_TEST ifdefs
- Remove ImageSet.cpp CHATTERINO_TEST ifdefs
- Remove Image.cpp CHATTERINO_TEST ifdef around forceLayoutChannelViews
- Remove Image.cpp CHATTERINO_TEST ifdefs around gif timers
- Purposefully leak the ImageExpirationPool timer
- Remove ImageExpirationPool CHATTERINO_TEST definition
- Remove CHATTERINO_TEST definitions in the CMakeLists.txt files
Fixes #4524
=> Remove CHATTERINO_TEST definition

CHANGELOG.md, src/singletons/Theme.cpp
In #4471 I removed too much code and accidentally removed code that loaded the icons for the usercard-buttons.
Fixes #4532.
=> Restore missing copy and pin buttons in the Usercard

docs/wip-plugins.md
The documentation for plugins contained the following errors which have now been fixed:
- The authors field in info.json was a string but actually should be an array of strings
- The CommandContext field channel_name was wrongly referred to as channelName
=> Adjust plugin documentation to match implementation

CHANGELOG.md, src/controllers/sound/SoundController.cpp
Fixes a bug where we don't check if the sound device is active before trying to play a sound to it
We fix this by checking its state before every sound we try to play, and if the device is not in the started state we try to restart it.
=> Restart the sound device if it's been stopped

.CI/CreateDMG.sh, .github/workflows/build.yml, CHANGELOG.md, src/singletons/Toasts.cpp
Apple wants the OS to be called macOS, rather than the previously used OSX. This PR changes the artifact names to use `macos`.
The only other uses of `OSX` in the codebase are related to CMake things (which we can't change) and one comment in [Toasts.hpp](https://github.com/Chatterino/chatterino2/blob/517382ebc967f0ab3b512cf3619fa3b1ba213d76/src/singletons/Toasts.cpp#L79).
=> Use `macos` rather than `osx` in filenames

.github/workflows/build.yml, CHANGELOG.md
also manually mark the builds as experimental instead of using a god of
war sed replace
The test for if this works can only be checked in the nightly release once this has been merged into the main branch
=> Mark experimental builds at the start of their filename

.github/workflows/build.yml, CHANGELOG.md
=> Mark builds as experimental

.github/workflows/build.yml, CHANGELOG.md
The current **EXPERIMENTAL** Qt6 builds (at least on Windows) are missing `imageformats/qwebp.dll`, which is not provided by `qtbase` ([`qtimageformats`](https://qt.mirror.constant.com/online/qtsdkrepository/windows_x86/desktop/qt6_650/qt.qt6.650.addons.qtimageformats.win64_msvc2019_64/6.5.0-0-202303290841qtimageformats-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z), [`qtbase`](https://qt.mirror.constant.com/online/qtsdkrepository/windows_x86/desktop/qt6_650/qt.qt6.650.win64_msvc2019_64/6.5.0-0-202303290841qtbase-Windows-Windows_10_22H2-MSVC2019-Windows-Windows_10_22H2-X86_64.7z)). This PR adds `qtimageformats` as a required module.
=> Add `qtimageformats` Module in Qt6 CI Builds

.github/workflows/build.yml
The `EXPERIMENTAL` macOS artifacts ended in `-dmg` instead of `.dmg`. 
We can amend the changelog with this PR but it already has 5? PRs so 🤷
=> fix: experimental macOS artifact extension repaired

CHANGELOG.md, src/common/SignalVectorModel.hpp
This PR fixes the crash described in #4563.
I have no clue why the previous code worked in the first place.
- It's quite clear that both `from` and `to` are row-indices:
https://github.com/Chatterino/chatterino2/blob/6338d09104a3075c21dd7a1ba80e744a544f22d1/src/common/SignalVectorModel.hpp#L322-L323
- [`QAbstractItemModel::index`](https://doc.qt.io/qt-6/qabstractitemmodel.html#index) takes a `row`, `column`, and (optional) `parent` (🤓 actually [`QAbstractTableModel::index`](https://doc.qt.io/qt-6/qabstracttablemodel.html#index) is called, but this doesn't do any fancy things).
- `to` is passed at the second argument - in the position of column 💫 https://github.com/Chatterino/chatterino2/blob/6338d09104a3075c21dd7a1ba80e744a544f22d1/src/common/SignalVectorModel.hpp#L336
- `to` isn't a …
=> Fix Qt6 crash when dragging rows in table views

src/controllers/commands/CommandController.cpp
=> Fix crash when using /unstable-set-user-color without any arguments

resources/com.chatterino.chatterino.appdata.xml
This PR adds a `description` field to the release in the appdata file. This field is used by Linux app stores and Flathub to display release information, e.g. the changes section [here](https://flathub.org/apps/com.chatterino.chatterino).
Maintaining a full changelog there probably doesn't make sense as it would have to be manually updated every release, so I think it's enough to simply have a link to the actual changelog there.
~~EDIT: does this require a changelog entry? :D~~
=> Add changelog link to appdata file

CHANGELOG.md, src/singletons/Fonts.cpp
In #4476 I added a mapping function. It turns out the function isn't ideal and Qt recommends to use [`setLegacyWeight`](https://doc.qt.io/qt-6/qfont-obsolete.html#setLegacyWeight). You can see the differences here: https://www.desmos.com/calculator/igvv6oe9pd. This makes sure the default values for the settings will be as identical as possible.
=> More Accurately Convert Font-Weights in Qt 6

resources/com.chatterino.chatterino.appdata.xml
Unfortunately the changes in #4573 were not actually valid, as you aren't allowed to put urls in `description`, causing Flatpak builds to fail:
```
builddir/files/share/appdata/com.chatterino.chatterino.appdata.xml: FAILED:
• style-invalid         : <release> description should be prose and not contain hyperlinks [<p>See the website for the changelog:</p><p>https://chatterino.com/changelog</p>]
```
This changes the file to link to the release in the `url` field. It doesn't seem to be possible to link to a specific version on https://chatterino.com/changelog, so it's linking to a Github release instead.
=> Fix Linux appdata file

.CI/CreateDMG.sh, .CI/MacDeploy.sh, .github/workflows/build.yml, src/common/Version.cpp
Split up the CreateDMG.sh macos script to two scripts:
MacDeploy.sh - this calls macdeployqt on the built app
CreateDMG.sh - this calls dmgbuild on the built & deployed app
Add a `SKIP_VENV` environment variable to CreateDMG.sh, this can be used to use the system version of dmgbuild
Add the ability to codesign the created dmg and its contents using the `MACOS_CODESIGN_CERTIFICATE` environment variable
Moved the output name logic from CreateDMG to the `OUTPUT_DMG_PATH` environment variable
The nightly release create job also doesn't remove artifacts now, it only replaces artifacts that are conflicting.
The downside to this is that if we change the name of an artifact, we need to manually delete the old artifact.
The upside to this is that we can now upload artifacts that are not handled in …
=> Allow for local macOS signed builds

CHANGELOG.md, resources/qss/settings.qss, src/singletons/Theme.cpp, src/singletons/Theme.hpp, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/dialogs/SettingsDialog.cpp
This reverts commit 642718474c19479208482e08ad61dbf0a42089d2.
The commit is being reverted because it had some consequences that we didn't notice during the PR testing, so we're waiting to include the changes later with some more testing.
=> Revert "Dim disabled items in context menus (#4423)"

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
=> Fix link tooltips showing up blank instead of with text-only

CHANGELOG.md, src/common/NetworkRequest.cpp, src/common/NetworkRequest.hpp, src/singletons/Updates.cpp
Context: https://github.com/SevenTV/chatterino7/issues/219.
* Downloads from the updater now follow redirects.
* A dialog is shown when the HTTP status isn't 200.
* Dialogs are simplified.
(I couldn't think of a good title)
=> Improve error messages when updater fails a download

CHANGELOG.md, src/common/LinkParser.cpp, tests/src/LinkParser.cpp
Domains starting with `http` were previously not parsed (see test-cases).
=> Parse Domains Starting With `http`

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
This fixes a crash that happens if you happen to scroll up really fast in a fast chat like tmiloadtesting2. The scrollbar would want to be out of bounds, the message snapshot would be indexed out of bounds and Chatterino would segfault.
Old behavior:
https://github.com/Chatterino/chatterino2/assets/25011746/19580242-0c5d-4450-b062-ec1a32340d23
New one does not crash :).
=> Fixed crash when scrolling up really fast.

CHANGELOG.md, CMakeLists.txt, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
=> Release v2.4.4

src/common/NetworkPrivate.cpp, src/common/NetworkPrivate.hpp, src/common/NetworkRequest.cpp, src/common/NetworkRequest.hpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp
This PR does many small changes - each commit can be reviewed on its own.
The following changes were made:
* Cleanup unused code (Twitch v5)
* Add `json` methods that simplify sending JSON. This also sets the `Accepts` header, since here, when JSON is sent, only JSON is accepted as a response (this is only done in Helix).
* `Helix`'s `makeRequest` now accepts an HTTP method.
* Cleaned some clang-tidy suggestions in `Network{Request,Private}`. The only suggestions left there are (1) a [`const-cast`](https://github.com/Chatterino/chatterino2/blob/4fa2cc26c9bffd5a6c770380c8a8bceb7368edbf/src/common/NetworkRequest.cpp#LL58C31-L58C41) and (2-5) unused `QFuture`'s from `QtConcurrent::run` calls. (1) should be resolved when #4632 is closed. (2-5) can be resolved by using …
=> Refactor/Cleanup NetworkRequest and Related Code

CHANGELOG.md, src/CMakeLists.txt, src/controllers/commands/CommandController.cpp, src/controllers/commands/builtin/chatterino/Debugging.cpp, src/controllers/commands/builtin/chatterino/Debugging.hpp
This PR adds the `/c2:loggingrules` command. You invoke it like this: `/c2:loggingrules chatterino.*.debug=true chatterino.http.debug=false`. This will apply both rules. I'm not too sure about the command name/prefix/namespace (my thinking was to have this behind a namespace/prefix, so it's clear that this is a Chatterino command).
This command is mainly for debugging release builds without restarting - so that you get more logs when you attach a debugger/console or even a dedicated program capturing logs.
=> Add Command to Set Logging/Filter Rules at Runtime

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp
This is a very simple implementation of something like #4615. This doesn't check if it's a reconnect, just shows the message. There is no setting either, as I don't see why we should add one.
=> Add 'joined channel' system message.

CHANGELOG.md, src/singletons/Paths.cpp, src/singletons/Paths.hpp, src/singletons/Theme.cpp, src/singletons/Theme.hpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.hpp
This loads themes (any .json file) from the <chatterino appdata>/Themes directory on startup and lists those in the settings page.
The custom themes in that directory will have a _Custom:_ prefix to show that they're custom.
In the settingsfile, we save the name of the theme (e.g. 'forsen', no more info).
When the theme is updated or on Chatterino startup, we find the best matching theme with that name, whether it's a built in theme or a custom theme.
There's currently no mechanism for making a theme that has the same name as a built in theme, and they still show up in the menu. IMO we should just not allow duplicate names for simplicity's sake.
There's a few things left to do, and a few things to discuss before taking this step, even though I still deem it to be "pre-production" even …
=> Add the ability to select custom themes in the settings dialog

.github/workflows/build.yml, CHANGELOG.md, src/providers/seventv/SeventvBadges.cpp
Since the [`clang-tidy-review`](https://github.com/marketplace/actions/clang-tidy-review) action runs in Docker, it doesn't have access to all the dependencies outside the container. Packages needed to build can be specified using the `apt_packages` input.
Currently, the `build` folder from the regular build is reused inside the action. This has some conflicts relating to paths changing.
This PR addresses both points by specifying `apt_packages` and (re-)configuring CMake in a different directory. Unfortunately, it doesn't use the Qt version installed by `aqt`, but uses the system's Qt. This shouldn't be much of an issue since the system's Qt is 5.15.3, thus in the supported range.
As a proof, I edited one file to trigger a lint. Without this PR, `clang-tidy` would fail on the `QHash` …
=> Configure CMake for `clang-tidy` separately

CMakeLists.txt, benchmarks/src/Highlights.cpp, benchmarks/src/main.cpp, tests/CMakeLists.txt, tests/src/HighlightController.cpp, tests/src/InputCompletion.cpp, tests/src/NetworkRequest.cpp, tests/src/TwitchPubSubClient.cpp, tests/src/main.cpp
* Windows systems (one of the supported operating systems) doesn't have a `/tmp` directory the same way, e.g. Linux has it. So instead, the tests are now using `QTemporaryDir` - which is cross-platform.
* Running Docker on Windows or macOS effectively runs an entire VM, which is a lot of overhead to _just_ get an HTTP echo server. I added a CMake option to use the public (but less reliable) httpbin server (`CHATTERINO_TEST_LOCAL_HTTPBIN=Off`).
* MSVC (apparently) has a different implementation of a `std::unordered_map` than the one used when writing the input completion tests. Since `unordered_map` doesn't guarantee an ordering (the name explicitly says `unordered`), one can't rely on values being in order in such a map. This map is the underlying data-type for an `EmoteMap`. For the …
=> Make tests more platform agnostic

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp, src/singletons/WindowManager.cpp
Available test channels:
- `$$$` - Fill up scrollback (1000 messages), then add a new message every 500ms
- `$$$:e` - Add a new message every 500ms
- `$$$$` - Fill up scrollback (1000 messages), then add a new message every 250ms
- `$$$$:e` - Add a new message every 250ms
- `$$$$$` - Fill up scrollback (1000 messages), then add a new message every 100ms
- `$$$$$:e` - Add a new message every 100ms
- `$$$$$$` - Fill up scrollback (1000 messages), then add a new message every 50ms
- `$$$$$$:e` - Add a new message every 50ms
- `$$$$$$$` - Fill up scrollback (1000 messages), then add a new message every 25ms
- `$$$$$$$:e` - Add a new message every 25ms
=> Expand upon test channels

src/widgets/listview/GenericListModel.cpp, src/widgets/listview/GenericListModel.hpp
- Change GenericListModel parent type to QObject
- GenericListModel comment typo
- GenericListModel: Mark functions as override where possible
- add reserve method to GenericListModel
- GenericListModel clang-tidy: add braces
- GenericListModel clang-tidy: Comment out unused parameter
- GenericListModel clang-tidy: explicitly use auto \*
- GenericListModel clang-tidy: avoid repeating type
- GenericListModel: add vector include
Initial changes taken from https://github.com/Chatterino/chatterino2/pull/4639
=> Clean up GenericListModel

CHANGELOG.md, src/widgets/settingspages/AboutPage.cpp
I noticed in the About Page that there were two Fluent icon links which seem to do exactly the same, so I thought I'd PR a removal.
See:
I'm not sure if I should make it a Minor or Bugfix entry :thinking:
=> Remove duplicate Fluent icons license

CHANGELOG.md, src/common/Credentials.cpp
If `instance` is an empty JSON-value (e.g. when `credentails.json` doesn't exist), [`object`](https://doc.qt.io/qt-6/qjsondocument.html#object) yields an empty object and thus calling [`find`](https://doc.qt.io/qt-6/qjsonobject.html#find) yields `end` which is basically a null-pointer-`QJsonRef`. Calling `toString` on it will cause an assertion to go off.
This function is called when you add an IRC server.
=> Fix undefined behaviour when loading non-existant credentials

CHANGELOG.md, src/widgets/Window.cpp, src/widgets/dialogs/EmotePopup.cpp, src/widgets/helper/EditableModelView.cpp, src/widgets/helper/SearchPopup.cpp, src/widgets/splits/Split.cpp
Looking at the logs of Chatterino, you sometimes find a `QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout`. [This StackOverflow answer](https://stackoverflow.com/a/25451334/16300717) has a good explanation.
If you have a `QLayout foo(widget)` and a `QLayout bar(widget)`, then the first constructor will set the layout of `widget` to be `foo` - calling [`setLayout`](https://doc.qt.io/qt-6/qwidget.html#setLayout). The second constructor will [try to set the layout as well](https://github.com/qt/qtbase/blob/727b6256c1921bedb7c3f23d49abe866e262ba97/src/widgets/kernel/qlayout.cpp#L101-L116), which will fail, because `widget`'s layout was already set, and you can't overwrite the layout if it already exists. The thing to keep in mind: The constructor of a `QLayout` …
=> Don't add QLayouts to QWidgets that already have one

CHANGELOG.md, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/dialogs/ReplyThreadPopup.hpp
* Open a reply thread popup in a Twitch channel
* Close it
* Switch the current user (make sure no message was sent in that channel after you closed the popup)
* 💥 
1. The reply thread popup creates a virtual channel that displays the messages in that thread: https://github.com/Chatterino/chatterino2/blob/ca9c91a15b550afab2eb28087b45c5b745679eda/src/widgets/dialogs/ReplyThreadPopup.cpp#L141-L146
2. This channel is then part of the `messageAppended` callback: https://github.com/Chatterino/chatterino2/blob/ca9c91a15b550afab2eb28087b45c5b745679eda/src/widgets/dialogs/ReplyThreadPopup.cpp#L174-L175
3. When you close the popup, the connection is destroyed ([`~ScopedConnection`](https://github.com/pajlada/signals/blob/6561aa559ff47cbad4058b8144d4a72fd14edc29/include/pajlada/signals/scoped-connec …
=> Fix crash resulting from a mutex deadlock when switching users

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp
Before PR: 
After PR: 
Spacing issue is solved.
Also fixes the comma "," so that it's to the left of the mention (should be the case since text should be read from RTL)
The change is only in the function `reoderRTL` so LTR only text shouldn't be affected at all since `reoderRTL` is only called when RTL is detected.
=> Fix spacing issue with mentions inside RTL text

CMakeLists.txt, src/CMakeLists.txt
This allows the sanitizers submodule to be omitted if it's not necessary for the developer
=> Make sanitizers truly optional

CHANGELOG.md, src/controllers/highlights/HighlightController.cpp, src/controllers/highlights/HighlightModel.cpp, src/messages/Message.hpp, src/messages/MessageThread.cpp, src/messages/MessageThread.hpp, src/providers/twitch/IrcMessageHandler.cpp, src/singletons/Settings.hpp, src/widgets/DraggablePopup.cpp, src/widgets/DraggablePopup.hpp, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/dialogs/ReplyThreadPopup.hpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/UserInfoPopup.hpp, src/widgets/settingspages/GeneralPage.cpp
There are two changes in this PR. First, the option to change the subscription status of a reply thread is added. Secondly, a pin-button is added, like on user cards:
This adds the concept of a subscribed thread. If one is subscribed to a thread, new messages will be highlighted (requires the _Subscribed Reply Threads_ highlight option). One can subscribe to threads through the popup and by participating in a thread (requires _Subscribe to participated reply threads_).
=> Add option to subscribe to and pin reply threads

CHANGELOG.md, src/controllers/highlights/HighlightController.cpp, tests/src/HighlightController.cpp
After the refactoring in #3399, anonymous users were pinged by the anonymous username `justinfan64537`. This PR fixes the behavior.
See also: #2156, #2352.
=> Fix anonymous users being pinged by `justinfan64537`

CHANGELOG.md, src/controllers/filters/lang/expressions/BinaryOperation.cpp, src/controllers/filters/lang/expressions/ListExpression.cpp
As mentioned in #4700, this fixes comparing filter expressions and creating string lists on Qt 6. In Qt 6, [`QVariant`](https://doc.qt.io/qt-6/qvariant.html) got some changes. Mainly, [`QVariant::Type` is deprecated](https://doc.qt.io/qt-6/qvariant-obsolete.html#Type-enum) and [`QMetaType::Type`](https://doc.qt.io/qt-6/qmetatype.html#Type-enum) should be used. This isn't backwards compatible to Qt 5.
---
Maybe tests should run on Qt 6 as well?
=> Fix partially broken filters on Qt 6

CHANGELOG.md, CMakeLists.txt, mocks/include/mocks/Helix.hpp, src/controllers/commands/CommandController.cpp, src/providers/twitch/TwitchAccount.cpp, src/providers/twitch/TwitchAccount.hpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/widgets/dialogs/UserInfoPopup.cpp
- Fix crash that could occurr if closing the usercard quickly after blocking or unblocking
- Add unrelated `-DUSE_ALTERNATE_LINKER` cmake option
=> Fix crash that could occur if closing the usercard quickly after blocking

CHANGELOG.md, src/common/NetworkPrivate.cpp, src/common/NetworkResult.cpp, src/common/NetworkResult.hpp, src/providers/IvrApi.cpp, src/providers/RecentMessagesApi.cpp, src/providers/bttv/BttvEmotes.cpp, src/providers/ffz/FfzEmotes.cpp, src/providers/seventv/SeventvEmotes.cpp, src/providers/twitch/api/Helix.cpp, src/singletons/Updates.cpp, src/util/NuulsUploader.cpp, tests/CMakeLists.txt, tests/src/NetworkRequest.cpp, tests/src/NetworkResult.cpp
Previously, some network errors would print `0` as their status code. This was because no status code was set for the reply. Instead, the error was in [`QNetworkReply::error`](https://doc.qt.io/qt-6/qnetworkreply.html#error) which wasn't used in error reporting. It's now used - if available, the HTTP status is still preferred.
I couldn't really come up with a good test case for `NetworkRequest` to test that the error is actually set.
=> Improve network error messages

src/CMakeLists.txt, src/common/Literals.hpp, tests/CMakeLists.txt, tests/src/Literals.cpp
To create a string/byte-array at compile-time before this PR, you'd need to use `Q{String, ByteArray}Literal`. These macros would embed the generated data into the executable, so no allocation at runtime would be required. Qt 6.4 introduced the [`Qt::Literals::StringLiterals`](https://doc.qt.io/qt-6/qt-literals-stringliterals.html) namespace, which provides suffixes to create the aforementioned types (and `QLatin1Char`). From the documentation of the `QString` suffix (applies to the others as well):
> The [QString](https://doc.qt.io/qt-6/qstring.html) is created at compile time, and the generated string data is stored in the read-only segment of the compiled object file. Duplicate literals may share the same read-only memory. This functionality is interchangeable with …
=> Add string literal suffixes to create `QString`s, `QByteArray`s, and `QLatin1String(View)`s at compile time

CHANGELOG.md, src/controllers/hotkeys/ActionNames.hpp, src/widgets/DraggablePopup.cpp, src/widgets/DraggablePopup.hpp, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/UserInfoPopup.hpp
=> Add "pin" action to usercards and reply threads

.clang-tidy, CHANGELOG.md, mocks/include/mocks/EmptyApplication.hpp, mocks/include/mocks/Helix.hpp, src/Application.cpp, src/Application.hpp, src/CMakeLists.txt, src/common/QLogging.cpp, src/common/QLogging.hpp, src/controllers/twitch/LiveController.cpp, src/controllers/twitch/LiveController.hpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/providers/twitch/api/README.md, src/widgets/helper/ChannelView.cpp, src/widgets/splits/SplitHeader.cpp
This makes sure live status requests are always batched, including the first one
Titles are also now always batched, and updated frequently rather than just randomly when we hover over the split header.
The display name of a channel is now also updated, if necessary, alongside the livestatus changes. Technically unrelated to the live status-ness but since we have that data in the same request, we might as well update it.
=> Ensure live status requests are always batched

src/common/Version.hpp
Removes dead code I introduced in #4681.
=> Remove dead macro code

CHANGELOG.md, src/controllers/sound/SoundController.cpp, src/controllers/sound/SoundController.hpp
If the sound device is stopped by the OS, we used to restart it.
In certain cases, the start fails because the OS has invalidated the sound device. The solve for this, if the restart fails, we recreate the sound device.
Tested on Arch Linux using Pulseaudio, where it works as expected.
=> Recreate ma_device on failure

CHANGELOG.md, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/Split.hpp
- Disconnect the `displayNameChanged` signal when the split closes
- Store the "raw" display name sent from Twitch
=> Fix crash that could occur when closing a split before its display name was updated

src/Application.cpp, src/BrowserExtension.cpp, src/CMakeLists.txt, src/singletons/NativeMessaging.cpp, src/singletons/NativeMessaging.hpp, src/util/IpcQueue.cpp, src/util/IpcQueue.hpp, src/widgets/AttachedWindow.cpp, src/widgets/AttachedWindow.hpp
In order to implement https://github.com/Chatterino/chatterino2/issues/4146, I wanted to first refactor the native-message-handler. The commits can be reviewed on their own. Some high level changes:
* Moved `boost::interprocess` interactions to new class.
* Created dedicated handlers for message types.
* Resolved clang-tidy warnings.
* Added CMake option to debug native messages.
=> Refactor Native Messages

CHANGELOG.md, src/widgets/helper/ResizingTextEdit.cpp, src/widgets/helper/ResizingTextEdit.hpp
Now moving the cursor in any way will result in the completion being cancelled.
Fixes: #3101
=> Fixed tab completion rarely completing the wrong word.

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp
This adds a previously missing check for blocked users and blocked phrases in USERNOTICEs, both in the recent messages copy (`parseUserNoticeMessage`) and the normal one (`handleUserNoticeMessage`). Deduplicating the code was out of scope for this PR.
Closes #3412
=> Fixed subscriptions and announcements not being blockable

CHANGELOG.md, src/singletons/helper/LoggingChannel.cpp
Closes #4697
The line string is now generated in logging code and search text isn't used.
=> Split log line generation from message search text

CHANGELOG.md, src/CMakeLists.txt, src/providers/RecentMessagesApi.cpp, src/providers/RecentMessagesApi.hpp, src/providers/recentmessages/Api.cpp, src/providers/recentmessages/Api.hpp, src/providers/recentmessages/Impl.cpp, src/providers/recentmessages/Impl.hpp, src/providers/twitch/TwitchChannel.cpp
This exposes internal functions for testing by splitting the implementation & internal API into separate files
=> Refactor recent messages API

CHANGELOG.md, src/CMakeLists.txt, src/common/Channel.cpp, src/providers/recentmessages/Impl.cpp, src/providers/recentmessages/Impl.hpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/IrcMessageHandler.hpp, src/util/ChannelHelpers.hpp
This PR fixes timeouts and bans of users not being shown in their usercard and timeouts not stacking. Previously, `CLEARCHAT`s were converted to `NOTICE`s. This was removed and `CLEARCHAT`s are handled.
The fix is a bit more involved, as the `addOrReplaceMessage` logic now adapts to any buffer. I wasn't very sure where to put the shared logic, so I chose `ChannelHelpers` (analogous to `IrcHelpers`).
Fixes #3030.
=> Show historic timeouts and bans in usercard

src/providers/twitch/api/Helix.cpp
When originally implementing /shoutout, when the user was not a mod Helix would return a 500 with no additional information, at some point this was resolved so this comment can be removed. https://github.com/twitchdev/issues/issues/779#issuecomment-1687039069
500 handling is kept b/c something could break, might as well keep it.
=> Remove comment for incorrect Twitch response

.CI/chatterino-installer.iss, CHANGELOG.md, CMakeLists.txt, docs/make-release.md, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
=> Release v2.4.5

.CI/build-installer.ps1, CHANGELOG.md
I noticed that PowerShell 5 (which is the version used in CI) encodes files using UTF16-LE when doing `echo foo > xd`. This doesn't happen in PowerShell 7 which I used for local testing. For the built installer, that shouldn't change anything, since it ignores lines that contain junk and the release `modes` file is empty.
Since using `Out-File` with `-Encoding Utf8` will result in a file encoded in UTF8 with BOM, I used `ASCII` (which is fine here).
=> Encode `modes` file in UTF8

CHANGELOG.md, src/main.cpp
See #4552. This is a temporary fix, as [`QT_ENABLE_HIGHDPI_SCALING`](https://doc.qt.io/qt-6/highdpi.html#environment-variable-reference) is described as "This variable is intended for testing purposes only, and we do not recommend setting it on a permanent basis.".
=> Set `QT_ENABLE_HIGHDPI_SCALING` to `0` on Qt 6 on Windows

.docker/Dockerfile-ubuntu-20.04-base, .docker/Dockerfile-ubuntu-20.04-build, .docker/Dockerfile-ubuntu-22.04-base, .docker/Dockerfile-ubuntu-22.04-test, .docker/README.md, .github/workflows/test.yml, CHANGELOG.md, tests/src/InputCompletion.cpp
- Tests: Fix InputCompletion tests in Qt6
This is achieved by not checking exact order for certain completion tests
- GitHub actions now run all tests in Ubuntu 22.04 - this is done to be able to use more modern features in tests
We will still support Ubuntu 20.04 in the actual main project
- Update dockerfiles to match this new reality
=> Fix input completion tests on Qt6 & run tests on 22.04

CHANGELOG.md, src/providers/twitch/PubSubClient.cpp
This ensures the close call is posted to the io_service executor
This fixes a data race with the get_con_from_hdl function
=> Fix data race in PubSub

CHANGELOG.md, src/controllers/commands/builtin/twitch/Shoutout.cpp
Tested, confirmed it works as expected
Fixes #4799
=> Fixed `/shoutout` command not working with usernames starting with @'s (e.g. `/shoutout @forsen`)

CHANGELOG.md, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp
I mentioned this in https://github.com/Chatterino/chatterino2/pull/4807#issue-1885699481. Before, all `ChannelView`s are laid out when requested. In active channels, there can be a lot of requests for this (every message -> one layout request). When a `ChannelView` isn't shown it shouldn't need to be laid out, but only once it becomes shown. Parts of the scrollbar implementation relied on the previous behavior, so a lot of testing is needed.
As mentioned in https://github.com/Chatterino/chatterino2/pull/4807#issue-1885699481, this behavior could be a setting.
=> Only layout visible `ChannelView`s

CHANGELOG.md, src/widgets/dialogs/ReplyThreadPopup.cpp
When dragging the reply thread popup and the notification checkbox is shown, the input in the dialog would lose focus (at least on Windows). Changing the focus policy of the checkbox from `ClickFocus` to `NoFocus` resolves that. This means that the checkbox can never be toggled with the keyboard. However, this doesn't change much, since you had to click on the checkbox before in order to toggle it with the keyboard.
=> Fix input in reply thread popup losing focus when dragging

CHANGELOG.md, src/widgets/AccountSwitchPopup.cpp, src/widgets/AccountSwitchPopup.hpp
This PR adds better support for themes in the account switcher.
| | White | Light | Dark | Black |
| ---|---|---|---|---|
|Before | ![chatterino_2023-09-15_12-52-57](https://github.com/Chatterino/chatterino2/assets/19953266/a7519a2a-488a-41d6-9be3-36c8abd5ec0c) | ![chatterino_2023-09-15_12-53-01](https://github.com/Chatterino/chatterino2/assets/19953266/98ad93df-491f-43bd-8d29-19d547fd13c4) | ![chatterino_2023-09-15_12-53-06](https://github.com/Chatterino/chatterino2/assets/19953266/197e16d8-24e7-442a-85c9-5aca6ee65141) | ![chatterino_2023-09-15_12-53-10](https://github.com/Chatterino/chatterino2/assets/19953266/45d1c306-d1d8-4cbd-8e11-ca258ce743d2) |
| After | ![chatterino_2023-09-15_12-51-37](https://github.com/Chatterino/chatterino2/assets/19953266/e41b73c3-f78f-4e48-b32e-b3a1819c275c) …
=> Style account switcher to match the current theme

.github/workflows/changelog-category-check.yml
This ensures the changelog entry added, if any, is under the Unreleased category
This action can be skipped with the `skip-changelog-check` label
=> Add the Changelog Category Check workflow

CHANGELOG.md, src/singletons/WindowManager.cpp, src/singletons/WindowManager.hpp, src/widgets/Window.cpp
This is needed to fix `/clearmessages`. I will replace all usages of `getMainWindow()` in another PR.
Here is a simple fix for `/clearmesages` which can be used to test this.
Fixes #3353. Required to finally close issue #2406. 
<details>
<summary>Patch</summary>
```patch
diff --git a/src/controllers/commands/CommandController.cpp b/src/controllers/commands/CommandController.cpp
index 9ce784ba..68eb2939 100644
--- a/src/controllers/commands/CommandController.cpp
+++ b/src/controllers/commands/CommandController.cpp
@@ -1377,18 +1377,25 @@ void CommandController::initialize(Settings &, Paths &paths)
return "";
});
-    this->registerCommand("/clearmessages", [](const auto & /*words*/,
-                                               ChannelPtr channel) {
-        auto *currentPage = …
```
=> Add `WindowManager::getLastSelectedWindow()` to replace `getMainWindow()`

src/util/WindowsHelper.cpp
This fixes an issue where `OleFlushClipboard` was called when not owning the clipboard (causes an exception) and cleans up the `WindowsHelper` code. I was too scared to make the change from `GetDpiForMonitor` to `GetDpiForWindow` (which is the preferred API), so I added a `TODO`.
=> Cleanup Windows helpers

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutElement.cpp, src/widgets/helper/ChannelView.cpp
This is a continuation of #3080. The same approach is used. 
Because of the reply button being in every message, setting `hasTrailingSpace` on the last element (even the last text element) when building as mentioned in https://github.com/Chatterino/chatterino2/pull/3080#issuecomment-893014909 doesn't work. 
Instead, `hasTrailingSpace` is set on the last _layout_ element. With the button enabled, a trailing space is copied (as that space is visually selected). Without the button, no trailing space is copied. When selecting multiple lines, having no delimiter after a message is bad, so a newline is added (over a space to distinguish lines).
Fixes #2449.
Additionally, this fixes the issue of copying emotes when they're not selected (e.g. in `a 🅰` with `a ` selected, Chatterino would copy `a …
=> Fixed too much text being copied when copying chat messages

CHANGELOG.md, src/widgets/Window.cpp, src/widgets/dialogs/switcher/NewTabItem.cpp, src/widgets/dialogs/switcher/NewTabItem.hpp, src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp, src/widgets/dialogs/switcher/QuickSwitcherPopup.hpp
- fix: QuickSwitcherPopup now pops up in the selected window
- QuickSwitcherPopup: reduce indentation anon namespace
- QuickSwitcherPopup: constexpr the minimum size
- QuickSwitcherPopup: remove redundant virtual from `themeChangedEvent`
=> fix: QuickSwitcherPopup now pops up in the selected window

CHANGELOG.md, src/util/StreamLink.cpp
Windows paths can't have trailing whitespace, currently having trailing whitespace in the path will result in the path not being found
=> streamlink: trim custom paths

CHANGELOG.md, src/messages/Selection.hpp, src/messages/layouts/MessageLayout.cpp, src/messages/layouts/MessageLayout.hpp, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutContainer.hpp, src/messages/layouts/MessageLayoutElement.cpp, src/messages/layouts/MessageLayoutElement.hpp, src/widgets/helper/ChannelView.cpp
After 3265df76619e689e9a738517732fe930fbe2b590, the selection rendering was off. Selecting the trailing newline of a message (upwards) would render the whole last line of a message to be selected. However, when copying the text, only the trailing newline of the message would be included.
This PR refactors the rendering of the selection to be a bit more readable and to reduce `sign-compare` warnings in the code (see https://github.com/Chatterino/chatterino2/issues/4825). In addition, a special case for the newline is added to be consistent with rendering the selection of the "trailing newline" (downwards).
Even though the selection is now correctly rendered, this might not be the exact behavior one would expect. Not including the trailing newline might be desired. Feel free to discuss this …
=> Fix selection rendering

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp
order of the QMargins class differed from the old custom Margins class
Fixes #4838
=> fix: double margin

.CI/build-installer.ps1, .CI/chatterino-installer.iss, CHANGELOG.md
* If the installed VCRT is old enough, the task to install it will be hidden.
* If the version is too low, the installer now shows the installed and shipped version.
For testing, you can change `Bld` to a lower number in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64` and/or rename it (or `Version`) to simulate the case where it's not installed.
---
Aside: The installer currently doesn't have the option to specify the installation directory. I'm not sure if that's intentional. `DisableDirPage=false` can be added to show the page.
=> Check VCRT and show installed/shipped version

CHANGELOG.md, src/controllers/completion/TabCompletionModel.cpp, src/controllers/completion/TabCompletionModel.hpp, src/controllers/completion/sources/CommandSource.cpp, src/controllers/completion/sources/CommandSource.hpp, src/controllers/completion/sources/UnifiedSource.cpp, src/controllers/completion/sources/UnifiedSource.hpp, src/controllers/completion/strategies/CommandStrategy.cpp
Fixes a regression introduced in #4639. When we can't determine the kind of item being tab-completed, we now consider emotes, usernames, and commands.
Fixes #4842
Truthfully I didn't even know you could create a command without a slash 😅 
This fix was a bit more complicated than I had expected due to the `userCompletionOnlyWithAt` setting. When we can't deduce the kind of item being completed, depending on this setting, we either:
1. Complete emotes, usernames, and commands (setting disabled)
2. Complete emotes and commands (setting enabled)
To reduce code duplication, I modified `UnifiedSource` to accept a vector of sources to combine instead of being hardcoded to just combine emotes and usernames.
=> fix: Commands now completable when not starting with /

CHANGELOG.md, src/widgets/Notebook.cpp, src/widgets/helper/Button.cpp, src/widgets/helper/Button.hpp, src/widgets/helper/NotebookButton.cpp, src/widgets/helper/TitlebarButton.cpp
When running with Direct2D on Windows, Chatterino would flicker and print warnings that `EndDraw` failed with `D2DERR_POP_CALL_DID_NOT_MATCH_PUSH`. This was because derived buttons (titlebar & notebook) would call `Button::paintEvent` in their `paintEvent` - creating two painters for a paint device at a time (not permitted - [see `QPainter::begin`](https://doc.qt.io/qt-6/qpainter.html#begin)). This PR fixes that.
The only other "issues" I had with Direct2D was [an exception leaking through the driver](https://forums.developer.nvidia.com/t/poco-notfoundexception-thrown-in-driver-version-531-18/245285) and that text rendering isn't as crisp.
=> Fix flickering when running with Direct2D

CHANGELOG.md, src/controllers/logging/ChannelLog.cpp
Fixes the issue (https://github.com/Chatterino/chatterino2/issues/4835) where logging channels with capitalization wouldn't work, by making channel names lowercase.
I tested the original exe file without my changes and then tested an exe file with my changes and it works.
=> Fix to interpret logger channel names as lowercase

CHANGELOG.md, src/widgets/Notebook.cpp, src/widgets/Notebook.hpp, src/widgets/Window.cpp
This is a fun kind-of-but-not-really concurrency problem. The dialog is shown by using [`QDialog::exec`](https://doc.qt.io/qt-6/qdialog.html#exec), which creates an additional event-loop. This event-loop will handle the dialog events. One event happens when the dialog is activated/shown, which deactivates the last active window. Since the window is created before the dialog is shown, it gets deactivated. Deactivating the main window will cause `Window::event` to be called, which adds a page, since there are no pages at that point.
Technically, the fix could also move the window creation, but the handler for `QEvent::WindowDeactivate` doesn't need to call `getOrAddSelectedPage` in the first place.
Fixes #3571.
=> Fix empty page added when showing OOB dialog

.CI/chatterino-installer.iss, .github/workflows/build.yml, .github/workflows/create-installer.yml, CHANGELOG.md, CMakeLists.txt, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
This cherry-picks changes from v2.4.6 (the security release), making sure nightly build users also get the same security fixes.
This means nightly will also be for windows 10 and above users now - we'll continue distributing an older build but it is unsafe.
=> Update Nightly to 2.4.6 and get qt6-related-changes from 2.4.6

CHANGELOG.md, src/controllers/completion/TabCompletionModel.cpp, src/controllers/completion/TabCompletionModel.hpp
Fixes usernames not being tab-completed without the `@` prefix (and the "Only search for username autocompletion with an @" setting disabled). 
The completion items being returned by the user source always started with an `@`. The candidate for completion of the query `icel` would be `@icelys, ` which is incompatible due to the extra "@".
Fixes #4850
=> fix: Fix username tab completion without @

.github/workflows/build.yml
=> Don't download non-existant qt 5.15 debug symbols for Windows

src/CMakeLists.txt
After boost::random dependency was dropped #4776, vcpkg build started to fail because websocketpp still required it.
Websocketpp fallback to boost polyfill if it cant detect compiler support for C++11 or newer 
https://github.com/zaphoyd/websocketpp/blob/b9aeec6eaf3d5610503439b4fae3581d9aff08e8/websocketpp/common/cpp11.hpp#L48
Detection is based on `__cplusplus` macro, which reports correct values for gcc and clang, but [static and old value for msvc](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170).
This PR adds `/Zc:__cplusplus` compiler option for MSVC, which makes it report actual C++ version instead of `199711L`
=> Fix websocketpp depending on boost::random 

CHANGELOG.md, src/widgets/BaseWindow.cpp
Randomly found that we're hit testing invisible widgets (the update button). I added a check to frameless popups as well (although I don't think there are invisible widgets currently).
Since I made changes in the main hit testing anyway, I reordered the checks, so the largest area (→ most likely location of the cursor) gets tested first.
Fixes #1967.
=> Ignore invisible widgets when hit testing

CHANGELOG.md, src/widgets/BaseWindow.cpp
Adds `WindowDoesNotAcceptFocus` (_Informs the window system that this window should not receive the input focus_). "Removes" `X11BypassWindowManagerHint` (alias to `BypassWindowManagerHint`).
Seems to be what we want. I couldn't test it on macOS, so I would be grateful if anyone could test it there. The only other window using this flag is the tooltip.
Fixes #2211.
=> Adjust `DontFocus` window flags on Windows and macOS

CHANGELOG.md, src/CMakeLists.txt, src/messages/MessageElement.cpp, src/util/Variant.hpp
Previously, only the first parsed element was used. This also adds a helper for Boost's and `std`'s `apply_visitor`/`visit`, which ensures all alternative types from the variants are handled.
Fixes #4874.
=> Display all parsed elements when parsing emojis in replies

BUILDING_ON_WINDOWS.md, CHANGELOG.md, CONTRIBUTING.md
Based on my experience as a first time contributor, I added what I thought would be useful to know for other first time contributors.
I updated the 'BUILDING_ON_WINDOWS.md' file to include more steps for Qt, included how to add to PATH for Qt and conan 2, and added 'cd ..' as a step to build.
I updated the 'CONTRIBUTING.md' file (not really sure where to put general non-code related contribution info) to include what I learned with my contribution (the need to create a specific branch instead of using main, and also to update the 'CHANGELOG.md' file).
=> Update Windows build instructions & contributing docs

CHANGELOG.md, src/controllers/completion/TabCompletionModel.cpp, src/controllers/completion/TabCompletionModel.hpp
We were being a little too clever and trying to cache the emote source for later reuse. Unfortunately, when a new user chats for the first time, their username would not be included in the available completion list until they type something else before attempting a completion again.
The same goes for emotes added via the EventAPI.
Fixes #4878
Fixes #4892
=> fix: Remove tab completion caching of source

src/CMakeLists.txt, src/controllers/filters/lang/expressions/Expression.cpp, src/controllers/filters/lang/expressions/Expression.hpp, tests/src/Filters.cpp
This changes the `make coverage` function to use `gcovr` instead of `lcov`, and to have it generate an html file directly at `coverage/index.html` under the build directory
The only thing this changes, other than adding tests, is making the `Expression` class pure virtual. Every derived class should implement each of the functions
=> Add some more filter tests

tests/CMakeLists.txt, tests/src/Selection.cpp
Adds 100% cover for Selection.hpp
=> Add selection tests

CHANGELOG.md, src/messages/Image.cpp, src/util/DebugCount.cpp, src/util/DebugCount.hpp, src/widgets/helper/DebugPopup.cpp
This PR refactors the debug count/-popup to be able to format large numbers and data sizes properly. The following changes were made in the commits:
* Moved implementation of the methods to the `cpp` file.
* Added `DebugCount::Flag(s)` and `DebugCount::configure(name, flags)`.
* Moved from `QMap` to `std::map` (order is important here).
* Used `QStringBuilder` for concatenations.
* Used `QLocale` for formatting (adds separators).
* Added `DebugCount::Flag::DataSize` for data sizes in bytes (and fixed language to English).
* Used `DataSize` for image sizes (maybe this should be moved somewhere else?).
* Added copy button to popup.
* Fixed Image usage reporting being eight times too large (could be another PR, but honestly it's four characters).
| Before | After |
| --- | --- |
| …
=> refactor: debug count and popup

CHANGELOG.md, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/helper/ChannelView.cpp
I saw that dialog code and couldn't unsee it. This memory leak is really tiny, so almost not worth a changelog entry.
When looking at the menu code, I found the weird `previousMenu` construction(s). They aren't needed, so I replaced them.
=> refactor: Change lifetime of context menus

CHANGELOG.md, src/providers/recentmessages/Impl.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/IrcMessageHandler.hpp
The biggest change this does, is change previously-public API of IrcMessageHandler into internal/static APIs
The PR is best reviewed if you skip changes from https://github.com/Chatterino/chatterino2/pull/4927/commits/d6604de8dcc4d9b1a4c50ad32246ed7b6bec37f7 - potentially even reviewing commit-by-commit
=> refactor: IrcMessageHandler

.github/workflows/check-formatting.yml, CHANGELOG.md, README.md, src/controllers/hotkeys/HotkeyController.cpp, src/controllers/hotkeys/HotkeyController.hpp, src/providers/twitch/TwitchChannel.cpp, src/widgets/splits/SplitContainer.cpp
We now use https://github.com/DoozyX/clang-format-lint-action for running clang-format instead, since it allows us to change which clang-format version to use easier.
=> ci: Use clang-format 16

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
Just use a better QTimer::singleShot variant.
Fixes #4932.
=> Bugfix: Fixed a crash when clicking `More messages below` button in a usercard and closing it quickly.

src/messages/Message.cpp, src/providers/twitch/api/Helix.cpp, src/widgets/AttachedWindow.cpp
this PR was cherry-picked into smaller PRs
With the last remaining changes to `Message` & some other small changes staying here
Message: Remove empty anon namespace
Message: Remove else after return
Message: Avoid repeating type in return
Message: Remove unused includes (there were a few)
Helix: Remove unneccesary `static` for already-static variables
AttachedWindow: Remove unused ForwardDecl.hpp include
=> refactor: Message

.clang-tidy, .github/workflows/build.yml
Add a 10m timeout to the clang-tidy job
=> chore: Add a 10m timeout to the clang-tidy CI job

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/IrcMessageHandler.hpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp
Closes #2432
Closes #3942
Supersedes #4942
Inspired by https://github.com/Chatterino/chatterino2/pull/4943#pullrequestreview-1713956782
Rewrites self-destructing signal usage (that suffered from inadequate value forwarding & use-after-free) with buffer approach that holds redemptions without a corresponding reward until a relevant pubsub message arrives
=> fix: avoid reward redemption crash via buffer refactor

CHANGELOG.md, src/widgets/splits/SplitInput.cpp
When clicking between the Split Input & the Split chat, there was a pixel or two where focus was not being granted to the split. This PR fixes that by adding a `giveFocus` call to the `mousePress` event.
=> fix: Split input sometimes not accepting focus

CHANGELOG.md, src/common/NetworkCommon.hpp, src/common/NetworkPrivate.cpp, src/controllers/notifications/NotificationController.cpp, src/messages/Image.cpp, src/providers/IvrApi.cpp, src/providers/LinkResolver.cpp, src/providers/bttv/BttvEmotes.cpp, src/providers/chatterino/ChatterinoBadges.cpp, src/providers/ffz/FfzBadges.cpp, src/providers/ffz/FfzEmotes.cpp, src/providers/recentmessages/Api.cpp, src/providers/seventv/SeventvAPI.cpp, src/providers/twitch/TwitchAccount.cpp, src/providers/twitch/TwitchBadges.cpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp, src/providers/twitch/api/Helix.cpp, src/singletons/Updates.cpp, src/util/NuulsUploader.cpp, src/widgets/splits/SplitHeader.cpp, tests/src/NetworkRequest.cpp
As explained in the issue, the return value was never used.
Closes #4909.
=> refactor: Remove `Outcome` from network requests

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp
Moderation buttons were not skipped in `getFirstMessageCharacterIndex()` causing triple click to select them,
issue visible on #4960 videos
=> Fix: dont select mod buttons at triple click

CHANGELOG.md, src/CMakeLists.txt, src/messages/MessageElement.cpp, src/providers/emoji/Emojis.cpp, src/providers/emoji/Emojis.hpp, tests/src/Emojis.cpp
There were some bugs regarding spaces and emojis in the reply context (a missing one before an emoji in `abc 😂 def` and an invalid one in `abc😂def`).
This PR fixes the bugs and adds tests for emoji parsing.
---
- Emoji parsing still uses a `boost::variant`, is that still necessary?
- The `EmojiMap emojis` in `Emojis` can be a `std::vector`, since the key is only used in tests and benchmarks.
=> fix: Only display spaces between words in reply context

CHANGELOG.md, mocks/include/mocks/EmptyApplication.hpp, src/Application.cpp, src/Application.hpp, src/providers/seventv/SeventvAPI.cpp, src/providers/seventv/SeventvAPI.hpp, src/providers/seventv/SeventvBadges.cpp, src/providers/seventv/SeventvEmotes.cpp, src/providers/twitch/TwitchAccount.cpp, src/providers/twitch/TwitchChannel.cpp, src/singletons/Settings.cpp, src/singletons/Settings.hpp
* Fixes use-after-free in Settings (when custom settings get destroyed, `getSettings()` would still point to the old instance).
* Fixes a deadlock (or similar?) as loading twitch accounts would init a request to 7TV.
=> fix: deadlock and use-after-free in tests

CHANGELOG.md, benchmarks/src/Emojis.cpp, src/controllers/completion/sources/EmoteSource.cpp, src/providers/emoji/Emojis.cpp, src/providers/emoji/Emojis.hpp, src/widgets/dialogs/EmotePopup.cpp, tests/src/Emojis.cpp
Originally reported by @Nerixyz in #4977
- Make Emojis `emojis` private
- Change `EmojiMap` to a vector
- Remove `EmojiMap` alias - now we use `std::vector<EmojiPtr>`
=> refactor: Remove Emoji's EmojiMap with a vector

CHANGELOG.md, src/common/Credentials.cpp, src/common/Credentials.hpp
- Include full path
- Sort includes
- Move anon namespace out of chatterino namespace
- Use auto * where possible
- disable convert-member-function-to-static check
- no else after return
- Remove empty constructor
- Use std::variant instead of boost::variant
=> refactor: common/Credentials

CHANGELOG.md, benchmarks/.clang-format, cmake/FindMagicEnum.cmake, mocks/.clang-format, src/.clang-format, src/common/ChatterinoSetting.hpp, src/controllers/plugins/LuaUtilities.hpp, src/controllers/plugins/Plugin.cpp, src/providers/seventv/SeventvCosmetics.hpp, src/providers/seventv/eventapi/Message.hpp, src/providers/seventv/eventapi/Subscription.hpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/pubsubmessages/AutoMod.hpp, src/providers/twitch/pubsubmessages/Base.hpp, src/providers/twitch/pubsubmessages/ChannelPoints.hpp, src/providers/twitch/pubsubmessages/ChatModeratorAction.hpp, src/providers/twitch/pubsubmessages/Whisper.hpp, src/widgets/settingspages/GeneralPage.cpp, tests/.clang-format
- Update `magic_enum` from v0.9.3 to v0.9.5
- Fix include path for magic enum
- Update .clang-format to ensure magic enum is caught as a third party library
=> Update magic_enum from v0.9.3 to v0.9.5

.github/workflows/build.yml, .github/workflows/clang-tidy.yml, .github/workflows/post-clang-tidy-review.yml, CHANGELOG.md
This gives a bit more flexibility in ignoring it, its timeout, and repeating failures
The implementaion is the same as before, it runs on the same platform, except:
- timeout has been increased from 10m to 20m
- the build doesn't work, only cmake is ran
=> Move clang-tidy to its own CI job

CHANGELOG.md, src/common/Args.cpp, src/common/Args.hpp, src/controllers/plugins/PluginController.cpp, src/widgets/Notebook.cpp, src/widgets/Window.cpp, src/widgets/settingspages/PluginsPage.cpp
This adds an option that disables plugins (if they were enabled at build time) and forces the preferences icon to show. Original idea was to also disable custom themes, however pajlada decided that is not needed. Should we decide to theme the settings, adding that will be needed.
=> feat: add `--safe-mode` command line option

CHANGELOG.md, conanfile.py
These are used in the Windows build
=> conan: Update Boost to 1.83 & OpenSSL to 3.2.0

CHANGELOG.md, src/widgets/splits/Split.cpp
The value returned from `exec` wasn't really feasible if it changed per platform, so we use [the recommended way](https://doc.qt.io/qt-6/qmessagebox.html#advanced-usage) of comparing button pointers instead.
I have confirmed this works as expected on:
- macOS on Qt6
- Linux on Qt6
I would appreciate a Windows tester making sure that the "Yes, don't ask again" image uploader prompt works as expected with this PR
Fixes #5010
=> Fixed "Yes, don't ask again" image uploader prompt not working on macOS

CHANGELOG.md, src/CMakeLists.txt, src/RunGui.cpp, src/common/Env.cpp, src/controllers/commands/builtin/twitch/Shoutout.cpp, src/controllers/notifications/NotificationController.cpp, src/controllers/sound/MiniaudioBackend.cpp, src/providers/irc/AbstractIrcServer.cpp, src/providers/irc/IrcConnection2.cpp, src/providers/twitch/PubSubManager.cpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/singletons/WindowManager.cpp, src/util/AttachToConsole.cpp, src/widgets/BaseWindow.cpp, src/widgets/Label.cpp, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/NotebookTab.cpp, src/widgets/listview/GenericListView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/settingspages/KeyboardSettingsPage.cpp, src/widgets/settingspages/SettingsPage.cpp, src/widgets/settingspages/SettingsPage.hpp, src/widgets/splits/SplitContainer.cpp, src/widgets/splits/SplitHeader.cpp
I couldn't bear the warnings anymore. The first commits are the most important, as they remove the most spammy warnings. Each commit fixes one category of warnings.
Working towards https://github.com/Chatterino/chatterino2/issues/4825.
=> fix: Fixed some compiler warnings

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp
Resolves #5002 
Shoutout @zneix for making this easy via https://github.com/Chatterino/chatterino2/commit/b614ce1cd8bae4093e88e61f547580965531a9b6
=> fix: show user message on watch streak notice

CHANGELOG.md, src/controllers/commands/builtin/Misc.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/UserInfoPopup.hpp, src/widgets/helper/ChannelView.cpp
Fixes the problem described in #4747 in a different way
=> fix: UserInfoPopup now requires a split as its parent

CHANGELOG.md, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/dialogs/ReplyThreadPopup.hpp, src/widgets/helper/ChannelView.cpp
Fixes the problem described in #4747 in a different way
=> fix: ReplyThreadPopup now requires a split as its parent

.docker/README.md, .github/pull_request_template.md, BUILDING_ON_LINUX.md, BUILDING_ON_MAC.md, BUILDING_ON_WINDOWS.md, BUILDING_ON_WINDOWS_WITH_VCPKG.md, CONTRIBUTING.md, README.md, docs/make-release.md, docs/test-and-benchmark.md, docs/wip-plugins.md, lib/README.md, tests/README.md
These are some minor, (mostly) stylistic changes/fixes to the markdown files.
- Fixed some language ✨stuff✨.
- Added alternative to httpbin.
- Updated expected space requirement on Windows.
- Removed unused VS component on Windows.
- Moved Qt Creator formatting to Windows docs.
- Updated nativs link to Qt 6.
- Added missing language to code blocks.
- Removed `# Description` from PR template and added instructions to fix a GitHub issue.
=> docs: cleanup/polish Markdown files

CHANGELOG.md, src/messages/layouts/MessageLayout.cpp, src/messages/layouts/MessageLayout.hpp, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutContainer.hpp, src/messages/layouts/MessageLayoutElement.cpp, src/messages/layouts/MessageLayoutElement.hpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp
Currently, when animated elements are turned on, a tick from the GIF timer (50x/s) will always trigger a repaint. This isn't needed.
This PR lays the foundation for more work on selective updates from the GIF timer by tracking elements that contain animations.
After this PR, the GIF timer will only trigger an update if at least one element was animated.
=> perf: skip update from GIF timer if no animated elements are shown

CHANGELOG.md, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp
Continuation of #5042.
This PR selectively updates the area in a channel-view that contains animated elements. The area of animated elements is calculated on every full repaint (see comment).
While testing, I noticed go-to-message not working, as it didn't update the widget (pretty sure this was broken if animated emotes were turned off).
You can flip the `#ifdef` to show the updated area.
=> perf: Only update regions with animated elements

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
Previously, only the bottom and the top were checked. This PR adds a check for tall messages (taller than the channel-view).
Fixes #5044.
=> fix: Add check for tall messages

CHANGELOG.md, src/widgets/helper/Button.cpp
`Button::clicked` was emitted when the mouse was released outside the area of the button. This isn't expected. The avatar in usercards and the moderation button both used this.
=> fix: some buttons triggering when releasing mouse outside

CHANGELOG.md, docs/chatterino.d.ts, docs/plugin-info.schema.json, docs/plugin-meta.lua, docs/wip-plugins.md
While trying to add docs for plugins on the wiki, I noticed some issues in the plugin docs:
- The JSON schema didn't allow `$schema` as a key.
- The TypeScript types contained the wrong event type.
- `register_callback` wasn't documented at all.
- No Lua metadata for plugins was present. [LuaLS](https://luals.github.io/) seems to be the most common language server.
=> Improve docs/supplemental files for plugins

CHANGELOG.md, src/controllers/highlights/HighlightModel.cpp, src/widgets/settingspages/HighlightingPage.cpp
Whisper highlights could be configured by manually changing the setting. This PR adds the option to do this through the UI. #1922 mentioned some bug that I couldn't find.
Fixes #1922.
=> Allow customization of whisper colors in settings

CHANGELOG.md, mocks/include/mocks/EmptyApplication.hpp, src/Application.cpp, src/Application.hpp, src/common/Channel.cpp, src/singletons/Logging.cpp, src/singletons/Logging.hpp
It's no longer a singleton
It's now a `unique_ptr` that dies together with the Application
=> refactor: Logging (chat logger)

mocks/include/mocks/EmptyApplication.hpp, src/singletons/Theme.cpp, src/widgets/BaseWidget.cpp, src/widgets/Notebook.cpp, src/widgets/helper/NotebookTab.cpp, src/widgets/helper/NotebookTab.hpp, tests/CMakeLists.txt, tests/src/NotebookTab.cpp
- EmptyApplication: Add asserts to rest of getters (except for getSeventvAPI)
- Theme: make getTheme call getIApp()->getThemes() instead
- Use getIApp() instead of getApp() in a few places
- Add some NotebookTab tests
Related to https://github.com/Chatterino/chatterino2/pull/5068
=> Add some tests for NotebookTab

CHANGELOG.md, src/widgets/helper/NotebookTab.cpp, tests/src/NotebookTab.cpp
`NotebookTab::setHighlightState` wasn't checking if the state changed at all, causing an `update()` for (almost) every message sent (this would also cause some of the parents to repaint like `BaseWindow`).
=> fix: Avoid unnecessary `NotebookTab` updates

CHANGELOG.md, src/widgets/dialogs/SettingsDialog.cpp, src/widgets/dialogs/SettingsDialog.hpp
Running the scale twice invalidated some of the layout. For me, this took about 800ms in debug mode. We can avoid this by setting the fixed widths and heights directly when the elements are created. It's still slow to open, but not as slow. Initializing the general page is the main issue. This takes about 1.1s for me in debug mode.
=> fix: Avoid duplicate scale in settings dialog

CHANGELOG.md, src/widgets/helper/Button.cpp
I noticed this for quite some time, but there doesn't seem to be an issue. If you hover really fast over some buttons, you'll see them remain in a hovered state:
https://github.com/Chatterino/chatterino2/assets/19953266/2c5f0c19-c83c-4e8d-822c-74a2c3e52006
This PR fixes that.
=> fix: button hover state-change not visible in some cases

CHANGELOG.md, src/util/StreamLink.cpp, src/util/StreamLink.hpp, src/widgets/settingspages/ExternalToolsPage.cpp
Solving #5073
Added new QLabel in ExternalToolsPage.cpp.
=> Improve Streamlink documentation

CHANGELOG.md, src/widgets/Notebook.cpp
Fixes #5015. Previously, the first `Split` inside the Notebook was focused. Now, if there is a selected split, this one is used, if not the behavior remains the same.
=> fix: restore focus of last split when restoring

CHANGELOG.md, src/CMakeLists.txt, src/singletons/WindowManager.cpp, src/widgets/splits/Split.hpp, src/widgets/splits/SplitCommon.hpp, src/widgets/splits/SplitContainer.cpp, src/widgets/splits/SplitContainer.hpp, src/widgets/splits/SplitOverlay.cpp, src/widgets/splits/SplitOverlay.hpp
SplitOverlay now doesn't do cross-enum mathematics
=> refactor: SplitOverlay

.clang-tidy
The rationale behind this is: The underscore is not there as a hint that the member is private, the underscore is there to allow for a function to have the "real" name, so it can be used as a getter or something similar in the public API.
We had an ignore on all private members either way, meaning this didn't fire.
Being a bit more flexible here allows us to make private-accessing code that doesn't have a public API to look cleaner.
=> clang-tidy: Make protected & private suffix underscore optional

src/messages/Emote.hpp, src/messages/SharedMessageBuilder.hpp, src/providers/irc/AbstractIrcServer.hpp, src/providers/twitch/PubSubClient.cpp, src/providers/twitch/PubSubClient.hpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp
- Correctly brace it up in Listener construction
- PubSubClient: Pass the listen msg as a const ref
- PubSubClient: auto numListen/numUnlisten size, and cast to int64 for debugcount
- PubSubClient: unused timer
- Split: unused event param
- SharedMessageBuilder: unused param name
- AbstractIrcServer: unused params
- AbstractIrcServer: delete copy & move ctor/assignment operators
- TwitchChannel: delete move/copy ctor/assigners
- Emote: default-initialize zeroWidth to false
- TwitchChannel: make listenSevenTVCosmetics const
- TwitchChannel: named initializer for cheermote loading
- TwitchChannel: remove duplicate mod_ initializer
- TwitchChannel: Forward instead of move ffz custom mod badge/vip badge
- TwitchChannel: Rename roomModes member
- TwitchChannel: named initializer for twitch …
=> refactor: Fix a bunch of minor things

CHANGELOG.md, src/widgets/splits/SplitInput.cpp
For context, before this change there was a difference in the margin of a split input depending on if your theme was dark or light.
This PR makes the margin the same regardless of theme.
Dark mode:
Light mode before this PR:
Light mode with this PR:
Thoughts @treuks ?
=> Use the same input padding between light & dark themes

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp
The channel name can be ignored as stated in the issue.
Fixes #5101.
=> fix: ignore channel name when copying message

CHANGELOG.md, mocks/include/mocks/ChatterinoBadges.hpp, mocks/include/mocks/EmptyApplication.hpp, src/Application.cpp, src/Application.hpp, src/providers/chatterino/ChatterinoBadges.cpp, src/providers/chatterino/ChatterinoBadges.hpp, tests/src/Filters.cpp, tests/src/TwitchMessageBuilder.cpp
- refactor: Make ChatterinoBadges a non-singleton
- Add some mini comments
- remove unused include
- rename variables to remove _
- use named initializers
The request for badges now happen as the class is constructed. I made the class "mockable" to ensure this request doesn't take place in tests.
=> refactor: Make ChatterinoBadges less of a singleton

CHANGELOG.md, conanfile.py
Seems like we can use boost in header-only mode. This saves some time when running `conan install`. However, the OpenSSL dependency still slows the build down. This can be solved by moving the WebSocket clients to boost-beast and using boost-wintls on Windows, which uses the native SChannel (first, all WebSocket clients would need some kind of common wrapper to make the transition easier).
<sub>Yes, `boost::json` works.</sub>
=> deps(conan): use `boost` in header-only mode

CHANGELOG.md, src/Application.cpp
When changing the color of a badge highlight, the highlights of the same badge did not immediately update. This PR fixes that.
=> fix: badge highlights not immediately updating color

CHANGELOG.md, src/common/Args.cpp, src/common/Args.hpp, src/common/WindowDescriptors.cpp, src/common/WindowDescriptors.hpp, src/singletons/WindowManager.cpp
Adds a `-a <channel>`/`--activate <channel>` command line option to activate a tab containing a channel or adding one (the feature request proposed `--active`).
- Only Twitch channels are supported (special channels are not supported)
- Only the main window is searched for tabs.
- If no tab/main window with the channel is found, a new one is added. _When adding a new window, it will show an out-of-bounds warning, but it should be fairly rare that no main window is present (in that case you might as well specify a window-layout with `-c`)._
- Tabs with fewer splits are preferred.
- Splits without filters are preferred.
Fixes #2498.
=> feat: add command line argument to select/add tab with a channel

src/providers/ffz/FfzEmotes.cpp
=> refactor: mini reorganization of FfzEmotes.cpp

CHANGELOG.md, src/messages/layouts/MessageLayout.cpp, src/messages/layouts/MessageLayout.hpp, src/singletons/WindowManager.cpp, src/singletons/WindowManager.hpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp
I wanted to fix a [bug in the 7TV fork](https://github.com/SevenTV/chatterino7/issues/259#issuecomment-1906731105) related to paints and noticed that I needed a way to just invalidate the paint buffers but not do layout (if it's not needed).
This PR adds a signal similar to `layoutRequested` that tells channel-views to discard the paint buffers. This is done by setting a flag when doing (re-)layout.
I noticed two settings that benefit from this: _Alternate background color_ and _Separate with lines_. You can test this PR by toggling the settings.
=> perf: add signal to invalidate buffers without doing layout

CHANGELOG.md, src/widgets/splits/Split.cpp
After this PR commands executed with `Split -> runCommand` ("Split->Run a command") will have the `input.text` placeholder available.
Note that this doesn't transfer to another command being run from this special command execution.
Working hotkey:
```
Category: Split; Action: runCommand
Arguments:
test: {input.text}
```
One that doesn't work by design:
```
Category: Split; Action: runCommand
Arguments:
/useinputtextplaceholder
```
=> Add support for `input.text` in commands run with hotkeys

CHANGELOG.md, src/singletons/Theme.cpp, src/singletons/Theme.hpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.hpp
As explained in https://github.com/Chatterino/chatterino2/issues/2452#issuecomment-1452464154, Qt 6.5 added a signal for the system color scheme. The system theme I added is a dummy theme that resolves to the correct theme once `update` is called.
https://github.com/Chatterino/chatterino2/assets/19953266/4a13c346-3682-4077-91a7-a1fd40597fc5
Closes #2452.
=> feat: add system theme on Qt 6.5 and up

CHANGELOG.md, resources/com.chatterino.chatterino.appdata.xml
According to recent Flathub changes, the `developer_name` of the appdata file now has to be filled.
=> Add developer_name appdata field

CHANGELOG.md, src/messages/Message.hpp, src/messages/SharedMessageBuilder.cpp, src/providers/twitch/TwitchMessageBuilder.cpp
Polluting `MessageFlag` seems better than adding a `QColor textColor` to `Message`.
Fixes #5143.
<sub>Changes in #4962 will be required.</sub>
=> fix: use neutral or username color for reply messages

CHANGELOG.md, src/controllers/commands/builtin/Misc.cpp
Examples:
- /openurl https://twitch.tv/forsen
with the setting "Open links in incognito/private mode" enabled
Opens https://twitch.tv/forsen in private mode
- /openurl https://twitch.tv/forsen
with the setting "Open links in incognito/private mode" disabled
Opens https://twitch.tv/forsen in normal mode
- /openurl https://twitch.tv/forsen --private
with the setting "Open links in incognito/private mode" disabled
Opens https://twitch.tv/forsen in private mode
- /openurl https://twitch.tv/forsen --no-private
with the setting "Open links in incognito/private mode" enabled
Opens https://twitch.tv/forsen in normal mode
=> feat: Allow /openurl to force use private/non-private mode

CHANGELOG.md, src/messages/Message.hpp, src/widgets/helper/ChannelView.cpp
Example output:
```json
{
"flags": "Highlighted|Collapsed|Subscription",
"id": "e099de58-daa1-41c5-bb9b-7ecafe8cb204",
"messageText": "forsen",
"searchText": "testaccount_420(테스트계정420) 테스트계정420 testaccount_420: forsen"
}
```
=> feat: Add "Copy message as JSON" option when shift-right-clicking a message

CHANGELOG.md, src/RunGui.cpp, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp
The issue this fixes is at least similar to https://github.com/Chatterino/chatterino2/issues/5006, but since there aren't any reproduction steps, I don't know for sure if it's the same.
I could reproduce the issue by enabling the _Always on top_ setting, restarting Chatterino and then opening the settings. Afterward, the main window was immovable.
**The underlying issue with `winId`:**
Even though [`QWidget::winId()`](https://doc.qt.io/qt-6/qwidget.html#winId) is `const`, it can _create_ windows. In our case, it can promote child widgets to native windows. Visually, there's no change, but these child windows all handle events on their own and on Windows, the parent only gets info about this through `WM_PARENTNOTIFY` - thus the non-client events aren't sent, and the window appears to be …
=> fix: avoid promoting child widgets to child windows

CHANGELOG.md, src/widgets/BaseWindow.cpp
Just noticed, I made a mistake in #5161 where I accidentally commented out code in the NCCALCSIZE handler.
<sub>While the code isn't ideal (as it changes the window/client size), it should be changed in another PR.</sub>
=> revert: uncomment NCCALCSIZE adjustment

.CI/full-ubuntu-build.sh
The purpose for this is to make it simpler to run a full build with just one script, meaning I can do `docker run local ./.CI/full-ubuntu-build.sh`
=> chore: Add a full-build shell script for use in CI/docker

CHANGELOG.md, src/widgets/BaseWindow.cpp
When clicking the minimize button and restoring the window, the minimize button will remain in a hovered state until the mouse enters the window. This is because we don't receive a `WM_NCMOUSELEAVE` event after the button was clicked. We emulate the event by checking for `SIZE_MINIMIZED` in the `WM_SIZE` handler.
=> fix: minimize button remaining hovered on Windows

CHANGELOG.md, src/controllers/notifications/NotificationController.cpp, src/providers/twitch/TwitchChannel.cpp
This fix for #5158 uses the `TwitchChannel` `roomId()` as the message id when sending live messages (`TwitchMessageBuilder::liveMessage` and `TwitchMessageBuilder::liveSystemMessage`). I wasn't able to replicate the same logic for live messages sent through `NotificationController` (I couldn't find a way to access the `TwitchChannel` from there), so I went with the other option of using a case insensitive string compare. I accept any ideas on how I could do this better, especially the `NotificationController` bit.
(felanbird): Fixes #5158
=> fix: resolve /live channel liveness using their channel ID

CHANGELOG.md, src/providers/twitch/TwitchMessageBuilder.cpp
This fix stops discarding the previous `searchText` when building a message in `TwitchMessageBuilder::appendChannelPointRewardMessage`.
Let me know if any more tests are needed. From what I've seen, regular messages have an empty `searchText` by that point, so the search string doesn't become redundant.
Fixes: #4804
=> fix: searching redemptions that require user input

CHANGELOG.md, mocks/include/mocks/TwitchIrcServer.hpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp, src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp, tests/CMakeLists.txt, tests/src/SplitInput.cpp
- Make getLastUserThatWhisperedMe mockable in TwitchIrcServer
- Use getIApp in SplitInput
- Add test-only:-)-method to set a SplitInput's input text
- Add SplitInput tests
=> feat: add the ability to unit test some aspects of SplitInput

CHANGELOG.md, src/controllers/commands/builtin/Misc.cpp
This allows for commands like `/openurl https://www.deepl.com/en/translator#auto/en/{1+}` that previously worked
Fixes #5196
=> fix: /openurl can now open urls with spaces, assuming the url allows it

CHANGELOG.md, mocks/include/mocks/Helix.hpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
This changes the default way messages are sent to use the Helix API instead of IRC. There's still an option to use IRC.
I decided to use a struct as the parameters to the Helix call to make help callers get the order right (using `{.property = value}`), since it would be four `QString` values in a row.
This augments #4962.
Fixes #5127.
=> feat: Send messages using Helix API

CHANGELOG.md, src/providers/seventv/SeventvEmotes.cpp
As mentioned in #5201, this PR changes the largest image on 7TV to be the 4x version (when available) instead of the 3x version.
=> feat: use 4x images on 7TV instead of 3x

CHANGELOG.md, resources/com.chatterino.chatterino.appdata.xml
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
This is needed so you can launch Chatterino after installing it in an app store.
=> Add launchable attribute to the Linux appdata file

CHANGELOG.md, src/providers/twitch/TwitchBadges.cpp
Broken state:
Fixed state after this PR:
=> fix: correctly load twitch badges in highlights page

CMakeLists.txt, src/CMakeLists.txt, src/providers/twitch/EventSub.cpp
Compiling the library as an object library causes some object files to not be linked to the final executable if it depends on the library transitively. Compiling the library as a static library (like other libraries) solves this. I don't know why the default is an object library.
=> fix(eventsub): compilation issues

CHANGELOG.md, src/messages/MessageElement.cpp, src/messages/MessageElement.hpp, src/messages/layouts/MessageLayoutElement.hpp
- Removed `EmptyElement` <sub>(never used)</sub>
- Removed `text_` in `MessageElement` <sub>-24B in Qt 6 which is about 23% in the base class and 15% in TextElement (most common)</sub>
- Removed `TextLayoutElement::listenToLinkChanges` <sub>(never used)</sub>
- Added `std::move` to `{Circular,Scaling,}ImageElement` constructors taking `ImagePtr` <sub>(technically unrelated, but if you think of it like a cleanup, it's fine)</sub>
=> chore: remove dead message element code

CHANGELOG.md, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.hpp
Fixes #2112
I would appreciate someone other than me testing this out to make sure I've covered everything
You should be able to:
- select one of the predefined fonts and the chat fonts should update
- select "choose" which opens a font dialog & select a custom font
- select "choose" which opens a font dialog & select cancel (which should revert back to your previously chosen font)
=> fix: the font switcher now remembers your previous font

.github/workflows/build.yml, .github/workflows/test-windows.yml
Upstream repo has been updated and satisfies our use case.
As discussed in chat, Github now suggests using hashes for these, but unlike some of our other dependencies which use branches and can silently update on us, this repo only uses tags so it's probably fine to use versioning for this.
✔️ on #5152
=> chore(deps): update ccache-action back to upstream repo

CHANGELOG.md, src/singletons/StreamerMode.cpp
Fixes a bug I introduced in #5216, where the timer wouldn't start when Chatterino was started (as the thread didn't have an event dispatcher yet).
I don't know how I missed this while testing. I probably just toggled the setting.
=> fix(streamer-mode): check setting on startup

CHANGELOG.md, src/controllers/commands/CommandController.cpp, src/controllers/commands/builtin/Misc.cpp, src/controllers/commands/builtin/Misc.hpp, src/providers/twitch/TwitchChannel.cpp
Closes #5199. Try checking with `/debug-update-to-no-stream`.
=> Fix rerun flag not being unset after stream finishes

CHANGELOG.md, src/widgets/TooltipEntryWidget.cpp
This fixes the issue I mentioned in https://github.com/Chatterino/chatterino2/issues/5189#issuecomment-1953158885. When hovering over the split header the first time, the tooltip appears too large. That's because the image label occupies at least 6x16 px. This PR hides the image label by default. There's an explicit `show` in `refreshPixmap`.
=> fix(tooltips): hide image label by default

CHANGELOG.md, src/widgets/splits/SplitHeader.cpp
I believe https://github.com/Chatterino/chatterino2/issues/5189 is a Windows only bug. This PR fixes tooltips of splits appearing in the wrong position [after the first hover(?)] on Windows. The issue might also occur when a streamer goes offline and the thumbnail isn't shown, but I didn't test that.
While debugging, I noticed that even though we call `adjustSize` which, according to the documentation, adjusts the area its children occupy, the tooltip still has a larger size than expected. It's only adjusted when calling `show()` <sub>(if you want to reproduce this, try placing logpoints in `QLayoutPrivate::doResize`, `QWidget::setGeometry`, and `QWidgetPrivate::setGeometry_sys`)</sub>. 
For non-Windows platforms, nothing changes.
On Windows, the tooltip is now shown before it's moved. …
=> fix(windows): show split tooltip before move

CHANGELOG.md, src/common/ChatterinoSetting.hpp, src/controllers/logging/ChannelLog.cpp, src/singletons/Settings.cpp
Most of the changes are done in https://github.com/pajlada/settings/pull/74
This speeds up the "Cancel" option for the settings dialog by a lot
I'm going to merge this in without super much testing to make sure it gets a broad spread of testing.
There's a chance signals don't fire even though they should, so update your settings after this PR has been merged in please. :-)
Fixes #4785
=> fix: compare settings before updating them

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp, src/widgets/splits/Split.cpp, src/widgets/splits/SplitHeader.cpp, src/widgets/splits/SplitHeader.hpp
this also makes sure moderator status is updated whenever possible (so when you type a message).
Fixes #1239
=> Hide chatter list button for non-moderators

CHANGELOG.md, src/providers/irc/AbstractIrcServer.hpp, src/providers/irc/IrcServer.cpp, src/providers/irc/IrcServer.hpp
This is a best-effort fix, it's a bit up to the IRC server to handle the consequences of the message they produce being longer than what we send, imo.
Fixes #2890
=> fix: truncate outgoing IRC messages to ensure we don't send more than 512 bytes

CHANGELOG.md, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp
When setting a channel in a `ChannelView` that has messages, these are copied into the internal message buffer, but aren't added to the backing channel used for search. With this PR, the messages are both added to the backing buffer and to the channel. This also fixes a bug where filters weren't taken into account (non-issue here, as there aren't any set by default).
Seems like this broke in #1748.
Fixes #3861.
---
To help future patches, I commented all channels a view holds onto. It's a bit confusing to have three channels and one always needs to check what they are. In the past, we've made mistakes of using the wrong channel. For example, I missed this in #5123 and even #1748 missed this [when handling `layoutRequested`](https://github.com/Chatterino/chatterino2/blame/e7508332ff1399a894 …
=> fix(channel-view): use `underlyingChannel_` over `channel_`

CHANGELOG.md, src/common/ChatterinoSetting.hpp, src/common/network/NetworkPrivate.cpp, src/common/network/NetworkPrivate.hpp, src/controllers/commands/builtin/twitch/Announce.cpp, src/controllers/plugins/LuaAPI.cpp, src/controllers/plugins/Plugin.cpp, src/controllers/plugins/Plugin.hpp, src/controllers/plugins/PluginPermission.cpp, src/providers/seventv/SeventvEventAPI.cpp, src/providers/seventv/eventapi/Dispatch.cpp, src/providers/seventv/eventapi/Subscription.cpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/pubsubmessages/AutoMod.cpp, src/providers/twitch/pubsubmessages/Base.cpp, src/providers/twitch/pubsubmessages/ChannelPoints.cpp, src/providers/twitch/pubsubmessages/ChatModeratorAction.cpp, src/providers/twitch/pubsubmessages/LowTrustUsers.cpp, src/providers/twitch/pubsubmessages/Whisper.cpp, src/util/QMagicEnum.hpp, src/widgets/helper/ChannelView.cpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.hpp, tests/CMakeLists.txt, tests/src/QMagicEnum.cpp
Since `magic_enum` and `QString` don't really mix well, I adapted it to fit `QString` and `QStringView` in `qmagicenum`. Both `magic_enum` and `qmagicenum` can be used at the same time. In face, `qmagicenum` uses `magic_enum` under the hood. Most stuff is `constexpr` (except creation of `QString`s). Since this is Chatterino code, I used the Chatterino naming convention.
There are still a few `.toLower`s that should be removed in the future.
Only plugins need `magic_enum` (as Lua strings are 8bit).
Hopefully this works on Qt 5 and Ubuntu 20.04.
=> refactor: adapt magic_enum to Qt

BUILDING_ON_LINUX.md
- **fix: minimum qt version if 5.15**
- **fix: prioritize manual builds through terminal**
- **fix: use cmake --build . for building**
- **Update Arch Linux dependencies**
- **Update guide to use Qt6 (and fix Ubuntu instructions)**
=> fix: Update Linux build instructions

CHANGELOG.md, src/providers/twitch/TwitchMessageBuilder.cpp
This removes a `:` from the reply if it's a reply to a `/me` message to keep it consistent with `/me` messages not having a `:`.
=> fix: remove ":" from the message the user is replying to if it's a /me message

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp
- Shows a better message in case the roomID is empty. Previously _Unknown error: Missing required parameter "broadcaster_id"_  would be shown.
- Shows _(empty message)_ if the response from Twitch is empty (I don't know how to trigger that, but I got it at least once in the past).
=> fix(helix-chat): show better error messages

CHANGELOG.md, src/controllers/filters/lang/Filter.cpp, src/controllers/filters/lang/Filter.hpp, src/controllers/filters/lang/Tokenizer.hpp, src/messages/Message.hpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/widgets/helper/ChannelView.cpp
This grows the Message struct by 16 bytes for the `shared_ptr`.
This adds the following filter variables:
- `reward.title`
- `reward.id`
- `reward.cost`
The use cases include having a separate split for high cost rewards that you don't want to miss, showing only some rewards in chat.
(felanbird): #4882 #4883
=> Add `reward.cost` `reward.id`, `reward.title` filter variables

CHANGELOG.md, src/messages/SharedMessageBuilder.cpp
Previously, `ircMessage->nick()` was used to get the login name. This doesn't return the login name for e.g. announcements (`USERNOTICE`). Since we already know the login name at that point, we can use `message().loginName`.
This might trigger more highlights where `loginName` is set, but the nick is unset/invalid, which was probably a bug before too.
Fixes #5294.
=> fix: use login name when parsing highlights

CHANGELOG.md, src/common/network/NetworkManager.cpp
I made a silly mistake in #5254 by not using `deleteLater` and turning off the worker thread before it could process the deletion event of the network access manager. This _could_ result in a failed assertion when closing Chatterino (when network requests were in flight, I think).
=> fix: use `deleteLater` for network objects and order them

CHANGELOG.md, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/splits/SplitHeader.cpp
Disclaimer: This solution is really hacky.
I think https://github.com/Chatterino/chatterino2/issues/5308 is a bug in Qt. I'm not entirely sure what the root cause is (possibly some bad order of queued events). The bug happens when quickly moving the mouse and right-clicking on the split header. When the QMenu is shown, focus is transferred, eventually causing a leave-event to be sent to the focused window. In our case, it's a QWidgetWindow. Usually, the widget to receive the leave-event (and propagate it upwards) is [set to `qt_last_mouse_receiver`](https://github.com/qt/qtbase/blob/ce23c9083f4d06054eb59781c3309b1fcc807a1f/src/widgets/kernel/qwidgetwindow.cpp#L411-L412) - e.g. the QLabel showing the channel info. However, when things go wrong, [`qt_last_mouse_receiver` is set to the newly …
=> fix: hide tooltip on window leave event

CHANGELOG.md, src/singletons/StreamerMode.cpp
We now correctly detect a timeout & show a special error message for it.
I've gone for the approach of possibly posting two streamer-mode messages, instead of sharing a boolean for them.
I've tested this locally on my system in 2 ways
1) Remove pgrep - the original messaging still works
2) Replace pgrep with a script that runs sleep 5 - the new timeout message shows
=> fix: improve error messaging when pgrep fails streamer mode detection

CHANGELOG.md, src/messages/MessageBuilder.cpp
Display the original link text (not the one with the protocol)
Fixes #5322. @pajlada please hold release 2.5.0 until the issue is fixed. This is a really simple fix. I don't think I've made mistakes in this?
=> Fixed links having `http://` added to the beginning in certain cases.

CHANGELOG.md, src/messages/LimitedQueue.hpp, src/widgets/helper/ChannelView.cpp
When adding messages to a ChannelView from an already existing channel and filtering those, the final number of messages will be lower (or equal) than the number of messages actually added. The same can appear if the message snapshot is larger than what `ChannelView::messages_` can hold. If we set the maximum before filtering, it might be higher than the actual amount and most importantly, it might be higher than the capacity of `messages_`, which will cause it to never decrease (and create the observed gap).
I thought it was introduced in #5248, but this doesn't seem to be the case.
Fixes #5327.
=> fix: set maximum of scrollbar after filtering

CHANGELOG.md, src/widgets/BaseWindow.cpp
Changing the topmost value of a non-top-level window on Windows will cause the top-level window to have its value changed too. This would cause bugs when manually setting the topmost status on a window by right-clicking in the notebook and opening a dialog (e.g. the select-channel dialog), which would try to disable the topmost value (as the setting isn't set).
This should only affect Windows as we don't use Qt there, but might be good to test on other platforms as well.
=> fix: don't change the topmost value of child windows

CHANGELOG.md, src/common/Common.hpp, src/providers/twitch/TwitchChannel.cpp, src/singletons/Toasts.cpp, src/widgets/splits/Split.cpp
- This feature removes the unnecessary redirect of `player.twitch.tv` by moving the `channel` and `parent` key around.
- This also makes sure that the URL used in multiple place can be changed in one place.
- Attempts at fixing #5317
=> Change order of query parameters of Twitch Player URLs.

CHANGELOG.md, src/widgets/splits/SplitHeader.cpp
=> fix: Remove "Show chatter list" entry from split header menu for non-mods

CHANGELOG.md, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
I plan to merge this PR in on Sunday
=> Release v2.5.0

CHANGELOG.md, src/common/LinkParser.hpp, src/messages/MessageBuilder.cpp, src/messages/MessageElement.cpp, src/messages/MessageElement.hpp, tests/src/LinkParser.cpp
The link passed to the link resolver is the one that ends up in the return value of `getLink()` (if it wasn't resolved in the meantime).
Calling `setLink` on a `LinkElement` doesn't actually do anything, because it provides its own `getLink`.
Fixes #5343.
<sub>voting for a patch release this week</sub>
=> fix: use the full url when resolving

tests/src/Emojis.cpp, tests/src/LinkParser.cpp, tests/src/TestHelpers.hpp, tests/src/TwitchMessageBuilder.cpp, tests/src/XDGHelper.cpp
- **tests: Add QString/QStringView << operators for std::ostream**
- **tests: clean up toStdString usages**
=> refactor: clean up toStdString usages in tests

.github/workflows/homebrew.yml
```
Warning: bump-cask-pr is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
brew developer off
```
=> fix: warning in homebrew workflow

.github/workflows/build.yml
`macos-latest` now points to `macos-14` which uses ARM, but there are no ARM binaries for Qt 5.
=> ci: pin to macos-13

.github/workflows/winget.yml
This PR adds a workflow to publish to WinGet once a release is made. It's similar to the homebrew action in that it needs a PAT for creating a PR. `WINGET_TOKEN` can probably use the same token as `HOMEBREW_GITHUB_API_TOKEN`. Current WinGet package: https://github.com/microsoft/winget-pkgs/tree/73fb073bca4622d59c445e0799e9a218ae7a3bca/manifests/c/ChatterinoTeam/Chatterino/2.4.6
The action uses https://github.com/russellbanks/Komac under the hood. Invoking it with `komac update -i ChatterinoTeam.Chatterino -v 2.5.0 --urls https://github.com/Chatterino/chatterino2/releases/download/v2.5.0/Chatterino.Installer.exe -o .` generates the following files:
**manifests/c/ChatterinoTeam/Chatterino/2.5.0/ChatterinoTeam.Chatterino.installer.yaml**
```yml
PackageIdentifier: ChatterinoTeam.Chatterino …
```
=> ci: add workflow for WinGet

CHANGELOG.md, src/common/network/NetworkResult.cpp, tests/src/NetworkResult.cpp
When the HTTP status code is 200 OK, but an error was reported by Qt, the error name is now reported (if available) instead of "200".
=> fix: prefer reporting error over status for 200 OK

src/util/AttachToConsole.cpp, src/widgets/helper/TitlebarButtons.hpp
Fixes the following build errors with `-DUSE_PRECOMPILED_HEADERS=OFF` on Windows.
<details>
<summary>TitlebarButtons.hpp</summary>
```
src\widgets/helper/TitlebarButtons.hpp(13): error C2504: 'QObject': base class undefined
src\widgets\helper\TitlebarButtons.cpp(16): error C2614: 'chatterino::TitleBarButtons': illegal member initialization: 'QObject' is not a base or member
```
</details>
<details>
<summary>AttachToConsole.cpp</summary>
```
src\util\AttachToConsole.cpp(16): error C2065: 'stdout': undeclared identifier
src\util\AttachToConsole.cpp(16): error C3861: 'freopen_s': identifier not found
src\util\AttachToConsole.cpp(16): error C2678: binary '=': no operator found which takes a left-hand operand of type 'const std::_Ignore' (or there is no acceptable conversion)
C:\Program Files …
```
=> fix: Missing includes when building with `USE_PRECOMPILED_HEADERS=OFF`

CHANGELOG.md, resources/qss/settings.qss, src/RunGui.cpp, src/main.cpp, src/messages/MessageElement.cpp, src/messages/layouts/MessageLayout.cpp, src/messages/layouts/MessageLayout.hpp, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutContainer.hpp, src/widgets/AttachedWindow.cpp, src/widgets/BaseWidget.cpp, src/widgets/BaseWidget.hpp, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/Label.cpp, src/widgets/TooltipEntryWidget.cpp, src/widgets/dialogs/SettingsDialog.cpp, src/widgets/helper/Button.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/NotebookTab.cpp, tests/src/MessageLayout.cpp
This switches from manual DPI handling to Qt's DPI handling, as Qt 6 disabled the option to opt-out of high DPI scaling through application attributes. Although this PR mainly fixes Windows bugs, it should be tested on all platforms, as the changes will affect everyone.
Windows now mostly uses the display scaling other platforms used.
You can test the scaling for yourself by setting `QT_SCALE_FACTOR` to something other than 1.
~~I'm waiting for https://github.com/Chatterino/chatterino2/pull/3690 to be merged, as that will fix some font-bugs (although I didn't see any on this branch).~~ This PR should be merged first.
- Fixes #4552.
- Fixes #4862.
- Fixes #5048. 
- I'm pretty sure #2348 will be fixed as well.
- #3754 on Windows
- #754 on Windows
- #752 on Windows
- #750 on Windows
- #749 …
=> Use Qt's High-DPI scaling on Windows

CHANGELOG.md, src/widgets/BaseWindow.cpp
https://github.com/Chatterino/chatterino2/pull/4868 added DPI aware functions that only work on Windows 10. When compiling with Qt 5 on Windows, it is now assumed the application will run on older systems. Maybe there should be a warning when running with Qt 5 on Windows 10 to use Qt 6.
Fixes #5390.
---
To make this work on Qt 5 and Windows 10, I'd need to load `user32.dll` and find the export (if it's there). I don't think that's worth the effort.
=> fix: don't use DPI aware functions on Qt 5 (Windows 7/8)

CHANGELOG.md, src/widgets/Scrollbar.cpp
From https://github.com/Chatterino/chatterino2/pull/5334 - minimum might be larger than getBottom() (in that case no scrollbar is shown). `std::clamp` requires the minimum to be smaller than the maximum.
=> revert: use max(minimum, min(bottom, value)) over clamp(..)

CHANGELOG.md, src/controllers/filters/lang/Filter.cpp, src/controllers/filters/lang/Filter.hpp, src/controllers/filters/lang/Tokenizer.hpp
It's a filter for `/me` messages. Just the thing I was looking for to do at 03:00.
=> Added `flags.action` filter variable

CHANGELOG.md, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/dialogs/SettingsDialog.cpp
I wanted to get rid of the duplicate scaling we do, but I noticed that the settings dialog still receives scaling events even though it opted out of custom scaling. This is because of our widget-tree, where the settings window is a descendant of the main window, causing `setScale` to be called on it (~> and its children). That's not desired.
So instead of using Qt's `findChildren`, we're now using a custom recursive loop over all children. Its general structure is [similar to Qt's](https://github.com/qt/qtbase/blob/8d5e7d50d8dbf1ad79bd8ff9f6ef6028eba481c9/src/corelib/kernel/qobject.cpp#L2137-L2148), except that we don't keep a list. This might bite us if any objects are added/removed while iterating (in that case we can dump them into a vector first). If any `BaseWindow` is encountered …
=> fix: don't attempt to scale windows opted out of scaling

CHANGELOG.md, src/widgets/BaseWidget.cpp, src/widgets/BaseWindow.cpp, src/widgets/Notebook.cpp, src/widgets/Notebook.hpp, src/widgets/dialogs/SettingsDialog.cpp, src/widgets/helper/NotebookTab.cpp, src/widgets/helper/NotebookTab.hpp, src/widgets/splits/SplitHeader.cpp
Previously, two scale events were emitted to fix #1266. This PR fixes #1266 by introducing `NotebookTab::normalTabWidthForHeight` which computes the width for the height _after_ scaling (in `NotebookTab::updateSize`). This would previously require two invocations (first one to set the height and second one the width). Furthermore, it gets rid of refreshing the notebook too often (~> performing layout for every tab).
As a next step, this PR checks if the scale has changed at all in `BaseWidget::setScale`. This will probably introduce some bugs, but I think it's better to address these individually instead of spamming scale events (like I did for SplitHeader).
=> fix: get rid of duplicate scale events

CHANGELOG.md, src/widgets/Label.cpp
As anticipated in #5404, there are places expecting `scaleChangedEvent` to be called more often. One such place is `Label` which is used in `UserInfoPopup`. Before, it would jump when follower and subscription data was loaded. This PR fixes that bug. Thank you to @brian6932 for reporting this.
=> fix: usercard jumping when loading data

.github/workflows/build.yml
I've seen windows-latest, Qt 6.5.0 fail in the Dependabot PR and this change seems to solve it, so I thought I'd do a PR into the PR.
I don't know if there has been a reason for the order of the steps how they were before, tho.
My Test PR: https://github.com/Wissididom/chatterino2/pull/27
=> Fix CI for install-qt-action

CHANGELOG.md, docs/plugin-meta.lua, scripts/make_luals_meta.py, src/common/Channel.hpp, src/controllers/plugins/LuaAPI.hpp, src/controllers/plugins/api/ChannelRef.hpp
Based on changes in #5383, I noticed the enums weren't in the `c2` global and nested structs weren't supported. This PR applies the fix from #5383 and moves everything we declare into the `c2` global. The rule of thumb is: everything that gets a declaration in the metadata should be prefixed with `c2` (→ "interfaces" i.e. classes without functions don't have to be in `c2`).
=> fix(luals-meta): generate globals in `c2` and echo @lua commands

CHANGELOG.md, src/widgets/helper/NotebookTab.cpp, src/widgets/helper/NotebookTab.hpp
**Repro steps**
1. duplicate a tab which is not last
2. close duplicated tab (might require 2 attempts)
3. removed tab will leave blank gap, following tab wont start animation to blank space
**Issue**
`positionChangedAnimation_` (QAbstractAnimation) for tabs is kept between animations, 
if `endValue()` of previously run animation match current targetPos - animation won't fire even though it should because current starting position might be different. This results in a gap which will stay until next notebook layout happen (where all tabs are moved again without animation).
There are also a lot of unnecessary Notebook layouts (like creating new tab results in 5x layouts of whole notebook) so that's something to fix too.
**Fix**
1. `endValue` for animation is now only checked for running …
=> Fix: tabs move animation for duplicated tabs

CHANGELOG.md, mocks/include/mocks/EmptyApplication.hpp, mocks/include/mocks/TwitchIrcServer.hpp, src/Application.cpp, src/Application.hpp, src/controllers/commands/builtin/Misc.cpp, src/controllers/commands/builtin/twitch/SendWhisper.cpp, src/controllers/notifications/NotificationController.cpp, src/controllers/plugins/api/ChannelRef.cpp, src/providers/irc/AbstractIrcServer.hpp, src/providers/irc/IrcServer.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/IrcMessageHandler.hpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp, src/singletons/NativeMessaging.cpp, src/singletons/StreamerMode.cpp, src/singletons/WindowManager.cpp, src/widgets/FramelessEmbedWindow.cpp, src/widgets/Window.cpp, src/widgets/dialogs/SelectChannelDialog.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/switcher/NewPopupItem.cpp, src/widgets/dialogs/switcher/NewTabItem.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/splits/Split.cpp
This PR aims to remove all direct uses of `getApp()->twitch`, ensuring we can add tests for anything adjacent to `TwitchIrcServer`
The class and its inheritance is ugly, so this refactor PR is also pretty ugly. To achieve the goal of this PR without making too many changes, I've added `getTwitchAbstract()` alongside `getTwitch()` which returns the `IAbstractIrcServer` of the `TwitchIrcServer`.
=> chore: refactor TwitchIrcServer

.clang-tidy, CHANGELOG.md, src/messages/Image.cpp, src/messages/Image.hpp, src/util/PostToThread.hpp
This PR refactors the image loading (and cleans up some of the code there, so make sure you disable whitespace when viewing the diff). It moves the loading of frames to a worker thread (the one we get from the network request).
Since the only work left is to assign the parsed frames to the image, this can be done in one go (no more queue). Once the frames are loaded, they are immediately pushed.
Technically, if many images load between two gui-thread-event-loop iterations, this could bloat the event-queue. Although I haven't measured, I don't think this is a bottleneck. When notifying channels, however, updates are batched to at most one per iteration.
=> refactor: load images in workers and push immediately

CHANGELOG.md, src/Application.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp
- **fix: manually initialize twitchircserver after rest of singletons are initialized**
- **unrelated nit: remove copy/move ctors/operators of twitchircserver**
Fixes #5434
=> fix: global emotes not loading

CHANGELOG.md, src/Application.cpp, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/providers/twitch/PubSubActions.hpp, src/providers/twitch/PubSubManager.cpp, src/providers/twitch/PubSubManager.hpp
Currently the pubsub topic only contains the moderator user id but not name, so we say `A moderator` did the action (which is still clickable to open their usercard based on id)
Related to #5439
=> feat: notify mods when users are warned

CHANGELOG.md, src/providers/irc/IrcConnection2.cpp, src/providers/irc/IrcConnection2.hpp
When sleeping, both incoming messages and timer invocations are stalled and (kind of) replayed when waking up (i.e. `Communi::IrcConnection::messageReceived` will fire pending events _after_ waking up and `pingTimer_` will fire the pending ping). This leads to a heartbeat.
The logs before are from https://github.com/SevenTV/chatterino7/compare/chatterino7...355acd51ce30f1899ec85fd2231533c91ea3d9db and the logs after are from https://github.com/SevenTV/chatterino7/compare/chatterino7...nerix/rm-logging.
<details><summary>Logs before</summary>
```text
2024-06-14T20:28:15 chatterino.irc: Communi::IrcConnection::messageReceived "PRIVMSG"
2024-06-14T20:28:15 chatterino.irc: Communi::IrcConnection::messageReceived "PRIVMSG"
2024-06-14T20:28:15 chatterino.irc: …
```
=> fix: ignore late pings

CHANGELOG.md, src/Application.cpp, src/Application.hpp, src/controllers/userdata/UserDataController.cpp, src/controllers/userdata/UserDataController.hpp
The `user-data.json` file will save immediately on change, and on exit
(on dtor) if necessary. So we don't need to manually call save
=> chore: unsingletonize UserDataController

CHANGELOG.md, cmake/resources/ResourcesAutogen.hpp.in, src/singletons/Resources.cpp
=> chore: unsingletonize Resources/Resources2

CHANGELOG.md, src/Application.cpp, src/Application.hpp, src/controllers/sound/ISoundController.hpp, src/controllers/sound/MiniaudioBackend.cpp, src/controllers/sound/MiniaudioBackend.hpp
=> chore: unsingletonize SoundController

CHANGELOG.md, mocks/include/mocks/Helix.hpp, src/CMakeLists.txt, src/controllers/commands/CommandController.cpp, src/controllers/commands/builtin/twitch/Warn.cpp, src/controllers/commands/builtin/twitch/Warn.hpp, src/providers/twitch/TwitchCommon.hpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/providers/twitch/api/README.md
=> feat: add `/warn` command

.github/workflows/build.yml
My mac mini now builds the release artifacts for 10.15 using Qt 6.4.3 and for 11+ using Qt 6.7.0, so I'm removing the nightly artifact publishing for the mac CI build
=> dev: remove macos artifact from nightly release

CHANGELOG.md, docs/plugin-info.schema.json
Add new `Network` permission to plugin info schema added in #5383
=> Add `Network` to plugin info schema

CHANGELOG.md, src/CMakeLists.txt, src/common/Version.cpp
The running version can be different from the compiled version, and this should be shown. I know it's in the build string but it makes sense to have the different versions next to each other.
Also properly shows Crashpad enabled builds.
=> show running qt version if it differs from compiled version

CHANGELOG.md, src/util/IncognitoBrowser.cpp
* firefox-devedition
* firefox-beta
* firefox-nightly
* qutebrowser
=> Support more firefox variants for incognito link opening

CHANGELOG.md, src/widgets/Window.cpp, src/widgets/splits/Split.cpp, src/widgets/splits/Split.hpp
=> Fixed splits staying paused after unfocusing Chatterino in certain configurations

CHANGELOG.md, mocks/include/mocks/Logging.hpp, src/Application.cpp, src/common/Channel.cpp, src/common/Channel.hpp, src/common/ChannelChatters.cpp, src/controllers/commands/builtin/chatterino/Debugging.cpp, src/controllers/commands/builtin/twitch/Chatters.cpp, src/controllers/commands/builtin/twitch/GetModerators.cpp, src/controllers/commands/builtin/twitch/GetVIPs.cpp, src/controllers/commands/builtin/twitch/SendWhisper.cpp, src/controllers/notifications/NotificationController.cpp, src/controllers/plugins/PluginController.cpp, src/controllers/plugins/api/ChannelRef.cpp, src/providers/irc/AbstractIrcServer.cpp, src/providers/irc/IrcChannel2.cpp, src/providers/irc/IrcChannel2.hpp, src/providers/irc/IrcServer.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchChannel.cpp, src/singletons/ImageUploader.cpp, src/singletons/Logging.cpp, src/singletons/Logging.hpp, src/widgets/dialogs/EmotePopup.cpp, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/SearchPopup.cpp
I have removed the `DoNotLog` flags from `UserInfoPopup` on purpose since all messages added from it are "reposts", i.e. messages that wouldn't be logged anyway
~~Currently it's the logger that checks whether or not to log reposts - this should just be moved to Channel's addMessage function instead~~
Fixes #5470
=> Add extra context to messages that are added to channels, allowing the logging controller to take more responsibility in what messages to log

CHANGELOG.md, src/PrecompiledHeader.hpp, src/common/FlagsEnum.hpp, tests/CMakeLists.txt, tests/src/FlagsEnum.cpp, tests/src/Test.hpp
... and `noexcept` and fix `hasAll` and use concepts and add tests and remove `std::initializer_list`.
All tests test an unscoped (`enum`) and scoped (`enum class`) enum, hence the template. Since this is used in many files, I've added `<concepts>` to the PCH.
Clangd was complaining about `Test.hpp`, so I added an export to the gtest headers.
No other code was changed.
=> chore: make `FlagsEnum` constexpr

CHANGELOG.md, src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp
Almost restores the layout of the input before #4350.
"Almost" because it's slightly taller now.
Left: after, right: before
=> fix: restore input layout (almost)

src/common/LinkParser.cpp, tests/src/LinkParser.cpp
- Adds a few more tests
- Switches to `QCompareCaseInsensitive` and `std::set` (no more allocations when searching for domains)
That's the most coverage we can get out of it (codecov doesn't really show which cases were covered in case of partial coverage). 
None of the following checks will trigger, because there will always be three dots and never duplicated dots (guaranteed from the caller, `parse`):
https://github.com/Chatterino/chatterino2/blob/a0b70b8c5e1ee60f2d746ca5234dffd1e2b8a4c2/src/common/LinkParser.cpp#L64
I could remove them, but that makes it a bit more fragile.
Similar things go for https://github.com/Chatterino/chatterino2/blob/a0b70b8c5e1ee60f2d746ca5234dffd1e2b8a4c2/src/common/LinkParser.cpp#L89
With the only difference that we're not guaranteed that `host` doesn't end …
=> chore: improve link parser and its tests a bit

CHANGELOG.md, src/widgets/helper/ChannelView.cpp, src/widgets/helper/ChannelView.hpp
This adds support for the panning gesture on `ChannelView`. This lets users who have touchscreens perform a two-finger pan of the chat (effectively a scroll).
Mouse move events aren't handled while panning is occurring so that erroneous text selection when going into and out panning is avoided.
=> Handle panning touch gestures

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutContainer.hpp, tests/src/MessageLayoutContainer.cpp
Since selection depends on elements being in order, this PR sorts the elements after reordering. This can be expensive, but allows selection of the text. As mentioned in the changelog entry, selection is still wrong, but now it's consistently wrong, which is an improvement.
It might not be too hard to get a more correct selection for RTL messages now (i.e. one that is "aligned" to the right instead of the left), but it's not too important for me.
=> fix: sort elements after RTL reordering

CHANGELOG.md, src/controllers/filters/lang/Types.hpp, src/controllers/filters/lang/expressions/BinaryOperation.cpp, src/providers/emoji/Emojis.cpp, src/providers/twitch/TwitchAccount.cpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/providers/twitch/api/Helix.hpp, src/util/IrcHelpers.hpp, src/widgets/helper/color/ColorItemDelegate.cpp
The underlying deprecations aren't new, but they haven't shown up as a warning in 6.7 and below. 
Notably, the variant conversion/checking in `controllers/filters/lang/Types.hpp` was quite vocal (seems to be included in most files; transitively). `QVariant::type` is deprecated (`typeId` is preferred) in Qt 6, but there's no alternative in Qt 5. Furthermore, `QMetaType::Type` contains predefined type-ids, while a type-id is of type `int` (in both Qt 5 and 6). This isn't really relevant for us, since we don't use user-types.
Some other changes:
- `QVariant::canConvert<T>` is preferred over `QVariant::canConvert(type-id)`
- `QString::fromUcs4` prefers the `char32_t` overload (available in Qt 5)
- Prefer `std::as_const` over `qAsConst` (but we don't need either)
- `QRegularExpression` got a …
=> chore: silence some deprecation warnings in Qt 6.8

CHANGELOG.md, mocks/include/mocks/BaseApplication.hpp, mocks/include/mocks/EmptyApplication.hpp, mocks/include/mocks/TwitchIrcServer.hpp, src/Application.cpp, src/Application.hpp, src/RunGui.cpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp, src/singletons/StreamerMode.cpp, tests/src/Commands.cpp
- **Gracefully quit streamer mode**
- **Set Application::instance to nullptr in dtor, allow us to better catch usages of getApp() after Application is destroyed**
- **move SeventvEventAPI from TwitchIrcServer to Application**
- **move BttvLiveUpdates to Application**
=> refactor: move seventv/bttv event apis to application

CHANGELOG.md, src/RunGui.cpp, src/singletons/Updates.cpp, src/singletons/Updates.hpp
This PR moves the "delete old update files" logic from RunGui to Updates, and uses `QtConcurrent::run` instead of an `std::thread`
I have purposefully not added a platform-check to this yet
=> refactor: move "delete old update files" logic to Updates

CHANGELOG.md, mocks/include/mocks/DisabledStreamerMode.hpp, src/Application.cpp, src/Application.hpp, src/CMakeLists.txt, src/RunGui.cpp, src/common/Channel.cpp, src/common/Channel.hpp, src/providers/bttv/BttvLiveUpdates.cpp, src/providers/liveupdates/BasicPubSubClient.hpp, src/providers/liveupdates/BasicPubSubManager.hpp, src/providers/seventv/SeventvEventAPI.cpp, src/providers/seventv/eventapi/Client.cpp, src/providers/seventv/eventapi/Client.hpp, src/singletons/NativeMessaging.cpp, src/singletons/NativeMessaging.hpp, src/singletons/StreamerMode.cpp, src/singletons/StreamerMode.hpp, src/util/IpcQueue.cpp, src/util/IpcQueue.hpp, src/util/RenameThread.hpp, src/widgets/splits/SplitInput.cpp, tests/src/BasicPubSub.cpp
- **Use Qt's lifetime system for the tab completion model**
- **Exit cleanly, but leak 7tv eventapi**
- **add renameThread function**
- **rename basicpubsubmanager thread**
- **implement stopImpl interface for basicpubsubclient**
- **implement pubsub stop thing for 7tv's pubsub client**
- **Add changelog entry**
This is the final step of our exit-refactor, and uses work from @Mm2PL 's https://github.com/Chatterino/chatterino2/pull/4993
=> fix: cleanly exit on shutdown

CHANGELOG.md, src/BrowserExtension.cpp, src/CMakeLists.txt, src/common/network/NetworkManager.cpp, src/providers/twitch/PubSubManager.cpp, src/singletons/NativeMessaging.cpp, src/util/RenameThread.cpp, src/util/RenameThread.hpp
Additionally, this adds a few names for threads not yet renamed. Names on Windows don't have tight restrictions on the length. On macOS, this would need to be done from inside the thread, as it doesn't have the first argument to `pthread_setname_np`.
=> chore: rename threads on Windows too

CHANGELOG.md, src/util/RenameThread.cpp
=> fix: only attempt to rename threads on Qt6 versions

CHANGELOG.md, src/widgets/BaseWindow.cpp
This needs testing on all platforms
Fixes #5432
Fixes #5521
=> fix: parenting logic, fixing some windows & tooltips misbehaving

.CI/format-recent-changes.py, .github/workflows/build.yml, CHANGELOG.md
With this PR, the nightly release will show the changelog ordered by date. The first five lines will be shown in a list and all other lines in a \<details> to save space. All lines include the date at which the change was done to help users figure out what changed between dates without opening the commit history. See [docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-of-a-multiline-string) for multiline strings and outputs.
<details><summary>Preview</summary>
_GitHub shows the title of PRs here. It doesn't do that in the release description._
- [2024-08-18] Minor: Removed experimental IRC support. (#5547)
- [2024-08-18] Dev: Refactored `MessageFlag` into its own file. (#5549)
- [2024-08-18] Dev: Added …
=> ci: show recent changes in nightly release

.github/workflows/build.yml, CHANGELOG.md
Seems like the default Python version on GitHub actions is too low.
The script worked in the initial run, where I added a test: https://github.com/Chatterino/chatterino2/actions/runs/10475646096/job/29012763358?pr=5554
=> ci: use Python 3.12 for parsing dates

CHANGELOG.md, src/common/SignalVector.hpp
Discovered through a compile error (GCC-15).
```
/var/tmp/portage/net-im/chatterino-2.5.1/work/chatterino2-2.5.1/src/common/SignalVector.hpp:158:22: error: ‘class chatterino::SignalVector<T>’ has no member named ‘items’; did you mean ‘items_’? [-Wtemplate-body]
158 |         return this->items[index];
```
=> fix: typo in `SignalVector::operator[]` member access

CHANGELOG.md, benchmarks/src/Highlights.cpp, benchmarks/src/main.cpp, mocks/include/mocks/BaseApplication.hpp, src/RunGui.cpp, src/main.cpp, src/singletons/Settings.cpp, src/singletons/Settings.hpp, src/widgets/AccountSwitchWidget.cpp, src/widgets/dialogs/SettingsDialog.cpp, tests/src/Filters.cpp, tests/src/HighlightController.cpp, tests/src/InputCompletion.cpp, tests/src/MessageBuilder.cpp, tests/src/ModerationAction.cpp, tests/src/NotebookTab.cpp, tests/src/main.cpp
Previously, if a user changed their user through the account switch dialog but didn't change any settings, we never saved this until the end of the application. If the application shut down uncleanly, that means the user would have to change account again on next startup.
With this PR, we now request a save of settings when the user changes their account.
=> fix: Fixed account switch not being saved if no other settings were changed

CHANGELOG.md, mocks/include/mocks/BaseApplication.hpp, src/Application.cpp, src/CMakeLists.txt, src/common/ChatterinoSetting.hpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/TwitchIrcServer.hpp, src/singletons/WindowManager.cpp, src/singletons/WindowManager.hpp, src/util/SignalListener.hpp, tests/src/MessageLayout.cpp, tests/src/Scrollbar.cpp, tests/src/SeventvEventAPI.cpp, tests/src/SplitInput.cpp
specifically this tries to move some responsibility of signal/conenction stuff from Application to WindowManager
=> refactor: some more Application refactors

CHANGELOG.md, mocks/include/mocks/EmptyApplication.hpp, src/Application.cpp, src/Application.hpp, src/controllers/commands/builtin/Misc.cpp, src/controllers/commands/builtin/twitch/SendWhisper.cpp, src/controllers/notifications/NotificationController.cpp, src/controllers/plugins/api/ChannelRef.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchChannel.cpp, src/singletons/NativeMessaging.cpp, src/singletons/StreamerMode.cpp, src/singletons/WindowManager.cpp, src/widgets/FramelessEmbedWindow.cpp, src/widgets/Window.cpp, src/widgets/dialogs/SelectChannelDialog.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/switcher/NewPopupItem.cpp, src/widgets/dialogs/switcher/NewTabItem.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/splits/Split.cpp
- **fix: remove deprecated `getTwitchAbstract`**
=> fix: remove deprecated `Application::getTwitchAbstract`

.github/workflows/build.yml
Related to https://github.com/Chatterino/docker/pull/12. Afaik this PR just updates the filenames for the artifacts and the Qt version for the builds themselves are configured in the docker container, so in the linked PR.
=> Update filenames for Ubuntu to Qt 6.7.2

CHANGELOG.md, src/singletons/StreamerMode.cpp
The timer was destroyed on the main thread, but its thread is the streamer-mode thread.
=> fix(streamer-mode): destroy timer on correct thread

CHANGELOG.md, src/widgets/BaseWindow.cpp
Fixes https://github.com/Chatterino/chatterino2/issues/5574. On non Linux OSs, `popupFlagsCloseAutomatically` doesn't include `Dialog` but includes `FramelessDraggable`. So that's added to the flags of windows we're considering to orphan.
In https://github.com/Chatterino/chatterino2/issues/5432#issuecomment-2320902867 I mentioned that I can't replicate the underlying issue on 6.8.0. This is either a bug or a feature (not sure).
=> fix: orphan `FramelessDraggable`s too

CHANGELOG.md, src/controllers/commands/builtin/twitch/Raid.cpp, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/providers/twitch/PubSubActions.hpp, src/providers/twitch/PubSubManager.cpp, src/providers/twitch/PubSubManager.hpp, src/providers/twitch/TwitchIrcServer.cpp
useful for mods/broadcaster; unfortunately non-mods would need an unofficial topic to know when raid has started
=> feat: indicate which mods start and cancel raids

CHANGELOG.md, src/RunGui.cpp
our "budget fusion palette" had the same color for the tooltip
background as the tooltip text
=> fix: some tooltips not being readable

CHANGELOG.md, src/widgets/dialogs/EmotePopup.cpp
Emote-sets were always added after they were filtered, even if they didn't contain any emotes.
Also, some mini fixes to avoid copies where possible and the correct display of follower emotes.
Fixes #5581.
=> fix: don't add sets without emotes when searching

CHANGELOG.md, src/widgets/splits/SplitInput.cpp
In https://github.com/Chatterino/chatterino2/pull/4350/files#diff-28a2425a552a515ae2556b51b50f4e3102c012c67dfa291cd13b52e1406e2417L1151-L1154, a method to clear the reply target was added where it was cleared "inline" before. However, there was a check whether inline replying was enabled (i.e. the mode where messages show above the input). This check was removed and this PR re-adds it.
Fixes #5584.
=> fix: only clear reply target when inline replying

CHANGELOG.md, src/util/QMagicEnum.hpp, tests/src/QMagicEnum.cpp
- Removes `enable_if`s over concepts (return types are a bit more readable this way)
- Ports `magic_enum`'s [`is_nothrow_invocable`](https://github.com/Neargye/magic_enum/blob/dae6bbf16c363e9ead4e628a47fdb02956a634f3/include/magic_enum/magic_enum.hpp#L334-L344) to predicates over `QChar`
- Adds some comments to the storage
- Moves static string construction to `detail`
- Removes usage of `magic_enum::detail::enum_subtype` - this is resolved by `magic_enum` (except for `enumFlagsName`, where we verify the type)
- Removes `inline` for `constexpr` functions
- Adds two more members to the flags test that live outside the regular enum range (-128…128)
=> chore: cleanup some parts of qmagicenum

.CI/format-recent-changes.py, CHANGELOG.md
Not really useful here, but I intend to re-use this functionality in 7TV's Chatterino7 fork. To reduce merge conflicts, I'm making some changes to the generator here (only wrapping the parsing in a function).
=> chore: allow unreleased-lines to be reused on other files

.github/workflows/test.yml
This PR aims to increase (depending on hardware) the amount of parallel build jobs used when building chatterino inside of the ubuntu test suite. Currently it's running a single build job, which partially explains the long run times.
=> ci: set test cmake build job count to logical processor count

CHANGELOG.md, src/widgets/settingspages/HighlightingPage.cpp
=> fix: typo in user highlights page

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/api/Helix.cpp
I've been using Helix as the send protocol ever since it got added, and didn't notice more bugs. The main advantage over IRC is that users get better feedback on dropped messages (although it often returns some generic reason).
Sometimes, Twitch returns 500 with an empty message. Now, every time Twitch returns an empty message, we assume an internal server error.
In the future, we could disable the write-connection if the settings allow it.
=> feat: send messages over Helix by default

CHANGELOG.md, benchmarks/src/RecentMessages.cpp, mocks/include/mocks/Emotes.hpp, tests/src/Commands.cpp, tests/src/Filters.cpp, tests/src/InputCompletion.cpp, tests/src/MessageBuilder.cpp, tests/src/ModerationAction.cpp, tests/src/SplitInput.cpp
From #5603:
> While testing, I noticed that `Emotes` initializes the `GIFTimer` which could cause it to invoke the repaint event which tries to access the window manager.
Not sure what the exact conditions are, but now it can't happen anymore (my pc might be a bit slow).
=> fix: don't initialize GIFTimer in tests

.github/workflows/test.yml, CHANGELOG.md, benchmarks/src/RecentMessages.cpp
we only run each iteration once (essentially a benchmark dry run). this is just here to ensure we don't break benchmarks with some change we make
=> feat: run bench in ci

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
From pajlada:
- Double click emote/emoji to select it
- Double click outside a message (in the void) and drag
- *Expected*: The selection starts at the nearest element - *Previous*: The selection starts at that selected emote/emoji
Technically, this fix does some duplicate work, since we did the work of looking at all elements, but shouldn't be that bad.
=> fix: use correct selection index when double-clicking into the void

CHANGELOG.md, src/messages/MessageBuilder.cpp
`getChannelOrEmptyByID` returns an empty channel, not an empty shared_ptr if it doesn't find any (it's still good to check if the pointer is null though).
=> fix(shared-chat): check if source-channel is empty

CHANGELOG.md, src/common/Args.cpp, src/common/Args.hpp, src/providers/twitch/TwitchAccountManager.cpp
Add a new optional launch arg , `--login <username>`, that allows a user to specify which account they want to start Chatterino logged in as. If an account with the supplied username does not exist, then it starts anonymous. This arg is essentially equivalent to modifying `current` in `settings.json` before launch.
I tried to implement similar to how channel args are applied in `WindowManager` by applying the username in `TwitchAccountManager`, but I don't know if it would be preferred to elevate it to `AccountController` instead. I did not implement the platform specificity that the `channel` and `activate` options have. 
I don't know if this is worth noting, but a side effect is that if the user never switches accounts, the `current` saved in `setting.json` will be set to whatever …
=> feat: launch arg to start logged in as a supplied user

.github/workflows/clang-tidy.yml
Allows to skip clang-tidy workflow.
=> Add skip-clang-tidy feature

CHANGELOG.md, src/controllers/commands/builtin/chatterino/Debugging.cpp
- Fixes #5640 
- The proxy url gets printed as: "proxyUrl: N/A" if it is empty
=> feat: Print proxy URL information in `/debug-env` command

BUILDING_ON_WINDOWS.md
Enabling the extension in Qt Creator was required for me after the first installation.
=> Add hint to enable beautifier extension in Qt Creator

.github/workflows/test-macos.yml, .github/workflows/test-windows.yml, tests/README.md
still need to change windows test runner, but i want to test the macos one first
=> test: use httpbox fork release

CHANGELOG.md, src/singletons/helper/GifTimer.cpp, src/singletons/helper/GifTimer.hpp, src/widgets/OverlayWindow.cpp
This will animate emotes if an overlay window is open even if the "animate only when Chatterino is focused" setting is on. This will also animate emotes in the other open windows, but that's due to the design of animated emotes in Chatterino (i.e. we can't control if emotes are animated for a specific view/window).
=> fix: animate emotes when overlay is open

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp
The big goal is to unify parsing/building of historic messages and to refactor the message builder so it's not directly tied to IRC.
The message builder will no longer be stateful but will build an IRC message in one go (like any other message), thus reply info must be available before starting to build (decided to do that separately).
This introduces a `ReplyContext` which holds the thread, the parent message, and whether the message should be highlighted.
The reply "building" is still done in the builder.
=> refactor: decouple reply parsing from MessageBuilder

CHANGELOG.md, src/widgets/BaseWindow.cpp
Our `ChannelView`s don't notice when the DPI changes, so we have to reset their buffers when the DPI changes. However, we have to wait for Qt to process the event. This might do a bit too much (if multiple windows are open), but shouldn't be too heavy, since it only does that once.
=> fix: invalidate buffers on `WM_DPICHANGED`

CHANGELOG.md, src/messages/MessageBuilder.cpp
Got another branch going which updates unit tests to properly catch this
cc @Nerixyz if you want to take a peek - I imagine this was roughly the intent you had
=> fix: subscribed threads not being marked as subscribed

CHANGELOG.md, tests/snapshots/IrcMessageHandler/clearchat.json, tests/snapshots/IrcMessageHandler/emoteonly-on.json, tests/snapshots/IrcMessageHandler/raid.json, tests/snapshots/IrcMessageHandler/shared-chat-raid.json, tests/snapshots/IrcMessageHandler/timeout.json
These are the last tests for messages from recent-messages (hopefully). This adds the following tests:
- CLEARCHAT (`/clear`)
- NOTICE emote-only - in our code, we have paths for [NOTICEs for the current user](https://github.com/Chatterino/chatterino2/blob/18c4815ad74bc794b952a3a787d59477952b91a7/src/providers/twitch/IrcMessageHandler.cpp#L379-L425). To my knowledge, these paths will never run - and if they'd ever run, it would (most likely) be a bug.
- USERNOTICE raid
- USERNOTICE sharedchatnotice (raid)
- CLEARCHAT timeout
=> test: add snapshots for raids, timeouts, and notices

CHANGELOG.md, src/providers/seventv/SeventvBadges.cpp, src/providers/seventv/SeventvEmotes.cpp, src/providers/seventv/SeventvEmotes.hpp
webp versions of badges are now animated, which was not the intent when they were originally included
we now use the `static_name` field in the badge response to use the static version of the badge
Fixes #5673
=> fix: use static version of 7tv badges

CHANGELOG.md, src/providers/seventv/SeventvEmotes.cpp
7TV emotes allow `<` and `>` now, so we need to escape the names.
=> fix: escape 7TV emote names

CMakeLists.txt
probably only active for arch linux & other newer distros
=> fix(cmake): use boost's own cmake config file

CHANGELOG.md, src/providers/seventv/SeventvEventAPI.cpp, src/providers/seventv/eventapi/Subscription.hpp
We currently log something like "Unknown subscription type: INVALID". This just adds the event type to the known ones and silently ignores the event. `entitlement.reset` is pushed every time a user without 7TV cosmetics updates their presence. As most users don't have cosmetics, it's really spammy. I don't see a big reason to handle it. In my opinion, we should handle it once there's a bug that would be fixed by handling the event (keep in mind: we didn't need this in the past).
=> fix(7TV): ignore `entitlement.reset`

CHANGELOG.md, src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp
=> fix: ensure timer doesn't run if the QuickSwitcherPopup is dead

CHANGELOG.md, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/providers/twitch/IrcMessageHandler.cpp, tests/snapshots/IrcMessageHandler/bitsbadge.json, tests/snapshots/IrcMessageHandler/sub-first-gift.json, tests/snapshots/IrcMessageHandler/sub-first-time.json, tests/snapshots/IrcMessageHandler/sub-gift.json, tests/snapshots/IrcMessageHandler/sub-message.json, tests/snapshots/IrcMessageHandler/sub-multi-month-anon-gift.json, tests/snapshots/IrcMessageHandler/sub-multi-month-gift-count.json, tests/snapshots/IrcMessageHandler/sub-multi-month-gift.json, tests/snapshots/IrcMessageHandler/sub-multi-month-resub.json, tests/snapshots/IrcMessageHandler/sub-multi-month.json, tests/snapshots/IrcMessageHandler/sub-no-message.json
Does what the title says. For subgifts, there's a special case, since their messages include two usernames.
Fixes #2673
=> feat: make usernames in USERNOTICEs clickable

CHANGELOG.md, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutContainer.hpp
In `paintSelectionStart`: When the selection ends in the current message, we need to call `paintSelectionEnd` (i.e. we need to return a line-index). When the selection doesn't end in the current message, we need to paint the start _and_ all lines below.
Neither was done when the selection started at a trailing space.
Fixes #5689.
=> fix: handle multiline selection starting at trailing space

.gitmodules, CHANGELOG.md
Related to #5693
Updating the qtkeychain submodule causes
```
src\common\Credentials.cpp(27): fatal error C1083: Cannot open include file: 'keychain.h': No such file or directory
``` 
Specifically `CMAKE_BUILD` gets incorrectly set.
https://github.com/Chatterino/chatterino2/blob/03cdd98c2edec699e13f7bc0a975519de82d5d4f/src/common/Credentials.cpp#L20
=> chore: Specify qtkeychain branch to `chatterino-cmake`

CHANGELOG.md, src/widgets/settingspages/GeneralPage.cpp
started because half the FFZ settings were `ffz` and the other half were `frankerfacez` so if you're used to searching ffz sometimes you don't get the setting you want, but if we update ffz we should update bttv also
now i know what you're thinking, doesn't this make it worse for everyone, and yeah it does lol got u, but standardization
anyway we're respecting branding now and it pushes pajlada towards implementing search tags to restore `bttv` and `ffz` search
=> chore: standardize references to FrankerFaceZ & BetterTTV in settings

CHANGELOG.md, src/common/ChatterinoSetting.hpp, src/messages/MessageBuilder.cpp, src/messages/MessageFlag.hpp, src/messages/layouts/MessageLayout.cpp, src/providers/twitch/PubSubActions.hpp, src/providers/twitch/PubSubManager.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/pubsubmessages/AutoMod.cpp, src/providers/twitch/pubsubmessages/AutoMod.hpp, src/singletons/Settings.hpp, src/singletons/WindowManager.cpp, src/widgets/settingspages/GeneralPage.cpp
Blocked terms can be added at https://dashboard.twitch.tv/settings/moderation/blocked-terms (replace with your username). Twitch fairly recently made messages blocked by blocked terms show up as automod messages. This PR aims to make this customizable, just like it is in Twitch Web Chat.
This is controlled with the new setting "Show blocked term automod messages"
I left it as an enum with two options because I see a near future where this can have the option "Only in streamer mode" or something like that
Instead of not adding the message to the channel view, it does add it but it's not laid out, thus making it hidden. This is how some other moderation action messages work, and I didn't want this PR to be the PR to solidify this behaviour, or figure out which is correct, so I left a …
=> feat: add setting to hide blocked term automod messages

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
Since we do more granular updates now, this makes sure we re-render when pausing. I don't think we have an issue for this other than https://github.com/Chatterino/chatterino2/issues/5704.
=> fix: update channel-view when pausing

CHANGELOG.md, src/controllers/completion/TabCompletionModel.cpp
This PR makes it so if there are multiple emotes with the same name (for example from different sources) and you are using the "smarter emote completion" option, when tabbing through them it no longer cycles through all the instances of the same name.
Originally I changed this in `SmartEmoteStrategy`, but this ended up removing duplicates from the : dropdown menu as well, which is not something we want I believe. Now it's deduplicated specifically in `TabCompletionModel` regardless of the emote strategy, but I think this should be fine as it's a cheap operation.
=> Deduplicate emotes by name in smart tab emote completion strategy

.CI/full-ubuntu-build.sh, .CI/setup-clang-tidy.sh, .cirrus.yml, .docker/Dockerfile-ubuntu-22.04-qt6-build, .github/workflows/build.yml, .github/workflows/test.yml, BUILDING_ON_FREEBSD.md, BUILDING_ON_LINUX.md, BUILDING_ON_MAC.md, CHANGELOG.md, CMakeLists.txt
=> dev: Default building with Qt6 on all platforms

CHANGELOG.md, src/singletons/Toasts.cpp, src/singletons/Toasts.hpp
this might fix a rare crash on shutdown on Windows
There's still room for other crashes (e.g. if TwitchChannel calls `getApp()->getNotifications()` during shutdown), but this patches a tiny hole at least.
Fixes #5601
=> fix: clear WinToast on exit

CHANGELOG.md, src/singletons/Settings.hpp, src/widgets/OverlayWindow.cpp, src/widgets/Scrollbar.cpp, src/widgets/Scrollbar.hpp, src/widgets/settingspages/GeneralPage.cpp
Hiding the scrollbar thumb will disable all mouse click/drag interaction in the scrollbar
Fixes #3874
I have tested the overlay window to ensure I have not broken anything to do with its scrollbar handle hiding.
=> feat: Add setting to hide scrollbar thumb

CHANGELOG.md, tests/src/OnceFlag.cpp
https://github.com/Chatterino/chatterino2/actions/runs/11999441698/job/33447346229 had 165, 192, 185, and 161ms as the duration for `stop - start` (the previous assert was fine), so let's loosen the requirement to not take longer than the specified timeout.
=> fix(test/once-flag): loosen requirement for tight timing

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp
Essentially reverts https://github.com/Chatterino/chatterino2/pull/5607 (not quite but almost).
Rationale: Twitch doesn't provide good errors for the Helix API. See [uservoice](https://twitch.uservoice.com/forums/310213-developers/suggestions/48972260-improve-error-messages-for-send-chat-message), https://github.com/Chatterino/chatterino2/issues/5675, and https://github.com/twitchdev/issues/issues/1019.
See also: https://github.com/Chatterino/chatterino2/issues/1600#issuecomment-2495453370 (not correct until this PR is merged) and https://github.com/Chatterino/chatterino2/issues/5675#issuecomment-2436363418.
=> revert: use helix as the default chat send protocol

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
Seems like I missed that when converting to `queueLayout`. This is not a huge performance gain, as the channels are usually empty when Chatterino starts up. I noticed this in the emote popup, where the channels already contain messages. You can see attempts to load emojis there, which shouldn't happen, as that tab isn't open by default.
=> perf: don't force-layout in `setChannel`

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/pubsubmessages/AutoMod.cpp, src/providers/twitch/pubsubmessages/AutoMod.hpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
Top two AutoMod messages when streamer mode is enabled & the default-enabled "Hide blocked terms" under Streamer Mode is enabled, bottom two is when that is disabled.
=> feat: improve automod blocked term messaging

CHANGELOG.md, resources/qss/settings.qss, src/CMakeLists.txt, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/settingspages/SettingWidget.cpp, src/widgets/settingspages/SettingWidget.hpp
This will create more widgets per setting, but the goal is to more simply allow us to add various free text to settings that need them.
I don't plan on migrating all settings, but I migrated all the enum dropdowns so I removed that implementation.
It's not really a builder pattern but it tries to be similar to it
=> feat: add "tags" or "keyword" support for settings

CHANGELOG.md, src/singletons/Settings.hpp, src/widgets/settingspages/CommandPage.cpp
Any new functionality we'd want to add here would probably not be what
people who checked this setting actually wanted it do be. It's best to
start fresh if we want to add similar functionality.
Fixes #2308
=> fix: remove cosmetic allowCommandsAtEnd setting

CHANGELOG.md, src/controllers/filters/lang/Filter.cpp, src/controllers/filters/lang/Tokenizer.cpp, src/widgets/settingspages/GeneralPage.cpp
=> Add flags.similar filter variable

CHANGELOG.md, src/singletons/Toasts.cpp
If we clear the toasts when they're uninitialized, a winrt error is "thrown" in another thread, because we didn't configure the app user model ID yet. This PR fixes that.
=> fix(toasts): only clear if initialized

CHANGELOG.md, src/widgets/dialogs/EmotePopup.cpp
On Windows, the `currentBounds` are initially zero. When opening the popup, a `resizeEvent` is triggered - at this point, the `currentBounds` are still zero. This makes sure we never save that initial position. This also reveals that #5415 did **not** fix #5414.
Fixes #5414.
=> fix(emote-popup): ignore null gemometry

CHANGELOG.md, src/widgets/dialogs/EmotePopup.cpp, src/widgets/dialogs/ReplyThreadPopup.cpp, src/widgets/helper/ChannelView.cpp
In https://github.com/Chatterino/chatterino2/pull/5737 I changed `performLayout` to `queueLayout` in `ChannelView::setChannel`. This causes usercards and reply thread popups to have their scrollbar at the top when opened (specifically, [this](https://github.com/Chatterino/chatterino2/blob/06d0160b350950f46d033942b3e58a5fdfcbdfe0/src/widgets/helper/ChannelView.cpp#L675-L677) would resolve to `true` before, because the scrollbar was still hidden).
This PR fixes that. For the various channel views, we need to make sure that they're properly initialized. For emojis, we need to make sure the view starts at the top, so we set the channel first and then add messages. On the other hand, for reply thread popups, we want to scroll to the bottom, hence we set the (virtual) channel after adding all …
=> fix: scroll to bottom when setting a channel

CHANGELOG.md, src/widgets/Scrollbar.hpp
Channel views could sometimes have their scrollbar be at the top instead
of bottom when they were first activated if it had messages in it
Scrollbars now assume their default behaviour is: "I'm scrolled down to the bottom" - this seems reasonable & fixes the issue
=> fix: initial scrollbar behaviour in inactive tab

.CI/chatterino-installer.iss, CHANGELOG.md, CMakeLists.txt, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
=> Release v2.5.2-beta.1

CHANGELOG.md, src/widgets/OverlayWindow.cpp, src/widgets/Scrollbar.cpp, src/widgets/Scrollbar.hpp
See: https://github.com/Chatterino/chatterino2/discussions/5633#discussioncomment-11450313
There's no point in showing the highlights if you can't scroll to them.
=> fix: hide scrollbar highlights in overlay window

.github/workflows/build.yml, .github/workflows/test-macos.yml, CHANGELOG.md
=> fix gh actions macos builder

CHANGELOG.md, src/singletons/Fonts.cpp
Top: Chatterino 2.5.1
Middle: current master with this patch applied
Bottom: current master
=> fix: macos font multiplier

CHANGELOG.md, src/providers/seventv/SeventvEmotes.cpp
7TV users can choose any username now. I love it.
Also used `&lt;` and `&gt;` where we put `<` and `>` into the HTML. We should think about a more "automatic" solution at some point (e.g. tooltip builder).
=> fix: escape more 7tv things

CHANGELOG.md, src/providers/bttv/BttvEmotes.cpp
Weird "bug"... For some messages in BTTV's WebSocket API, the `user` object of the emote is missing even though it should be there (i.e. the author isn't the current channel, and it's not some private emote). I reproduced it the first time, but after removing the emote and adding it back, the JSON included `user`. After that, adding any emote would always include `user`. Might be a BTTV bug.
If there isn't a `user` (the author is empty), we now fall back to the `channel`. This is the login name, not the display name, but that's the best we have.
Fixes #5781.
=> fix(bttv): use `channel` if no user was sent

CHANGELOG.md, src/providers/twitch/TwitchEmotes.cpp
The code I changed (introduced in #861) never ran before #5239 (tested 03b0e4881feb6dc7893c45d986406df198d15611). So yea, this does another layer of unescaping, essentially.
Fixes #5785.
=> fix: unescape Twitch emotes even more

CHANGELOG.md, src/providers/seventv/SeventvEventAPI.cpp
Towards https://github.com/Chatterino/chatterino2/issues/5724.
The crashes in the 7TV event-api when exiting are the most frequent in my experience. So let's make sure they don't happen. As mentioned in the linked issue, this should only be considered a temporary solution. Once we figured out how we structure `Application` and `getApp`, we should be able to make this proper.
=> fix: check application in 7TV event-api

.github/workflows/build.yml, .github/workflows/test-windows.yml, CHANGELOG.md, conanfile.py
`CMakeToolchain` now includes more stuff that we don't need (e.g. it sets `CMAKE_CXX_COMPILER`). We remove these settings.
In a followup PR, I'll use conan for boost on macOS in CI (I did that for chatterino7 already). This brings a 🚀 **25 minute decrease** 🚀 in CI time ⚡ (you don't want to miss this 🔥).
=> build(conan): 👷 update version and dependencies

CHANGELOG.md, src/util/IncognitoBrowser.cpp, src/util/IncognitoBrowser.hpp, tests/CMakeLists.txt, tests/src/IncognitoBrowser.cpp
Mozilla’s firefox-nightly apt package now points to firefox-bin in its desktop file, catch all firefox variants by mozilla with one if statement
not sure what the changelog should be
=> consolidate firefox incognitobrowser logic (and deprecate opera/launcher)

CHANGELOG.md, src/util/IncognitoBrowser.cpp
EOL since 2022-06-15.
https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11
=> Remove iexplore, because it is EOL

CHANGELOG.md, src/widgets/Label.cpp, src/widgets/Label.hpp, src/widgets/dialogs/UpdateDialog.cpp
=> fix: missing word wrap in update popup

CHANGELOG.md, src/common/Channel.cpp, src/common/Channel.hpp, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/messages/MessageFlag.hpp, src/messages/MessageSink.hpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/util/ChannelHelpers.hpp, src/util/VectorMessageSink.cpp, src/util/VectorMessageSink.hpp, tests/snapshots/IrcMessageHandler/clearchat-stack-always.json, tests/snapshots/IrcMessageHandler/clearchat-stack-never.json, tests/snapshots/IrcMessageHandler/clearchat-stack-no-user.json, tests/src/IrcMessageHandler.cpp
We stack timeouts, but not "full" clearchats. There's no use in having a chat full of "Chat has been cleared by a moderator".
This PR adds similar stacking functionality to `/clear` messages (both from PubSub and from IRC). Additionally, the user is now clickable in PubSub messages ("{actor} cleared the chat"). Tests for the different stacking settings have been added as well (it reuses the timeout stacking).
=> feat: stack `/clear` messages

CHANGELOG.md, src/widgets/BaseWidget.cpp
I was trying to reproduce https://github.com/Chatterino/Chatterino2/issues/5411 and found this bug:
1. Set scale to something other than 1x (ideally something with a significant difference, so you see the bug)
2. Close Chatterino
3. Open Chatterino
4. Go into the settings and change the scale back to 1x (Default)
5. **Correct** (now): The tabs should scale correctly
**Incorrect** (before): The tabs kinda stay the same (except for the font)
We didn't save the scale of the window when adding child widgets[^1]. So when the scale changed back to 1x, we'd assume it [was 1.0](https://github.com/Chatterino/chatterino2/blob/f53d92c77a304307256ca56e4e07ceb0471f44d4/src/widgets/BaseWidget.hpp#L57) and [return early](https://github.com/Chatterino/chatterino2/blob/f53d92c77a304307256ca56e4e07ceb0471f4 …
=> fix: set initial size of widgets

CHANGELOG.md, src/controllers/highlights/HighlightPhrase.cpp
We never use the capturing groups, so we can discard them. Would be even better if Qt had something like "isMatch()", but we can only dream.
=> fix: use non-capturing group for highlight boundaries

CHANGELOG.md, src/widgets/BaseWidget.cpp
Bug I introduced in https://github.com/Chatterino/chatterino2/pull/5794, where the window would call `scale()`, which would attempt to load `scale_` from itself, but that's the variable it wanted to initialize, so now it read garbage and initialized that variable to garbage and then subsequent reads from `scale_` would yield that garbage until the window loaded the scale setting.
Not sure if that's the cause of #5831 (I couldn't replicate this[^1]).
[^1]: Not the exact issue that is. On MSVC, the scale was initialized to a negative value, meaning that calls to `setMinimumSize` would print an error in Qt.
=> fix: only use window scale in children

.github/workflows/build.yml, .github/workflows/test-macos.yml
or whatever is currently available in homebrew
=> chore(ci): build & test macos with Boost 1.87

CHANGELOG.md, src/common/Channel.cpp, src/common/Channel.hpp, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/messages/MessageSink.hpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/util/ChannelHelpers.hpp, src/util/VectorMessageSink.cpp, src/util/VectorMessageSink.hpp, tests/snapshots/IrcMessageHandler/clearchat-stack-always.json, tests/snapshots/IrcMessageHandler/clearchat-stack-never.json, tests/snapshots/IrcMessageHandler/clearchat-stack-no-user.json, tests/snapshots/IrcMessageHandler/clearchat.json, tests/snapshots/IrcMessageHandler/timeout-stack-always.json, tests/snapshots/IrcMessageHandler/timeout-stack-never.json, tests/snapshots/IrcMessageHandler/timeout-stack-no-user.json, tests/snapshots/IrcMessageHandler/timeout.json, tests/src/IrcMessageHandler.cpp
[The tests are dying](https://github.com/Chatterino/chatterino2/actions/runs/12758619842/job/35560988846?pr=5823). [Twitch hates us](https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043). The animals are leaving. The aliens aren’t contacting us. We might be alone. It just might be you and me. But that’s okay. Because do you really need anyone else?
Anyways, this replaces the use of `parseTime` with `serverReceivedTime`, because `parseTime` isn't set for regular messages (it's set to the current time, meaning our tests will be correct just once throughout the day).
I marked this as a draft, because I don't have time and this needs tests for the stacking of regular timeout messages. If you want to add some, feel free to push to this branch.
=> fix: use `serverReceivedTime` over `parseTime` for stacking

CHANGELOG.md, src/common/Channel.cpp, src/common/Channel.hpp
The backing channels for channel-views in usercards have a name set. So when we close them, they will attempt to close all logging channels with that name. This PR fixes that by only closing a logging channel if we ever added anything to it (i.e. if we created the channel).
- Fixes #5827
=> fix: only remove logging channels if we added them

tests/src/IrcMessageHandler.cpp
=> chore(tests): print more errors when snapshot tests fail

CHANGELOG.md, src/controllers/plugins/LuaAPI.cpp, src/controllers/plugins/LuaAPI.hpp, src/controllers/plugins/PluginController.cpp
I fucked up by not blocking off `package.loadlib`.
=> Fixed a potential way to escape the Lua Plugin sandbox

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp, src/singletons/WindowManager.cpp, src/singletons/WindowManager.hpp
When we join channels because Chatterino (re-)connected, the join requests for channels that are currently selected are now put first. When starting Chatterino, this makes it seem like it's faster than before (even though it's as fast as before).
One downside of this PR is that `TwitchIrcServer` now knows about `WindowManager`, `Window`, `SplitNotebook`, `SplitContainer`, and `Split`.
An alternative would be to track the selected channels *somewhere* (i.e. add/remove them from methods in `Split` or `SplitNotebook`). I think that approach is more complex with little to no benefit.
- Fixes #3129 (it's the last item)
---
When searching for `joinBucket_` in `TwitchIrcServer`, you might find [another use](https://github.com/Chatterino/chatterino2/blob/da2384d695fa12e17b177b8372448435559070f5/sr …
=> feat: prefer visible/selected channels when joining

CHANGELOG.md, src/common/Channel.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchIrcServer.cpp, src/singletons/WindowManager.cpp, src/util/VectorMessageSink.cpp
not optimized, but it means the message is hidden as soon as the message becomes disabled, instead of sometimes slightly after it becomes disabled
an alternative to the "force relayout always" is to return if any messages were disabled from the timeout/clearchat helpers
=> fix: more force relayout on timeout/clear/delete

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp, tests/snapshots/IrcMessageHandler/announcement.json
This restores the display of announcement messages in the mentions tab.
Closes #5812 
I don't like having annoucements included in `isSub` but changing that would require a larger refactor.
=> fix: Allow announcements to show up in /mentions

CHANGELOG.md, src/messages/MessageBuilder.cpp
`searchText` was not populated for pubsub notif of (un)monitor/(un)restrict
=> fix: make suspicious treatment updates searchable

.gitmodules, CHANGELOG.md
https://github.com/Chatterino/chatterino2/pull/5697#issuecomment-2458023845:
> If possible I like to make those changes together with, or after, a release
We had a release, so now we can finally use the upstream qtkeychain (`0.15.0` tag) which means `clang-cl` won't yell because of `/Wall` anymore.
=> fix: use upstream qtkeychain (for real this time)

CHANGELOG.md, src/widgets/dialogs/EditHotkeyDialog.ui
A label can't be a buddy to itself. This causes an assertion failure when deleting the label (closing the edit-hotkey dialog).
=> fix(hotkeys): remove (self-)buddy from `argumentsDescription`

CHANGELOG.md, src/messages/MessageBuilder.cpp, tests/snapshots/IrcMessageHandler/announcement.json
Closes #5778.
Announcements can't be replied to as well so the button isn't added for those either.
=> fix: don't show reply button on inline whispers or announcements

.github/workflows/test-macos.yml, .github/workflows/test-windows.yml, .github/workflows/test.yml
The new version includes the `server.crt` and `server.key` files in the release itself, so we no longer need to download those files manually
=> chore(ci): bump twitch pubsub server version to v1.0.8

.cirrus.yml, BUILDING_ON_FREEBSD.md, CHANGELOG.md, lib/twitch-eventsub-ws/CMakeLists.txt, lib/twitch-eventsub-ws/cmake/GenerateJson.cmake, lib/twitch-eventsub-ws/src/CMakeLists.txt
This can be done using the `SKIP_JSON_GENERATION` flag (off by default)
=> refactor(eventsub): Allow for skipping generation of json implementations

CHANGELOG.md, lib/twitch-eventsub-ws/ast/lib/member.py, lib/twitch-eventsub-ws/ast/lib/templates/enum-implementation.tmpl, lib/twitch-eventsub-ws/ast/lib/templates/field-optional.tmpl, lib/twitch-eventsub-ws/ast/lib/templates/field-vector.tmpl, lib/twitch-eventsub-ws/ast/lib/templates/initializer-basic.tmpl, lib/twitch-eventsub-ws/ast/lib/templates/initializer-optional.tmpl, lib/twitch-eventsub-ws/ast/lib/templates/initializer-vector.tmpl, lib/twitch-eventsub-ws/ast/lib/templates/struct-implementation.tmpl, lib/twitch-eventsub-ws/src/generated/messages/metadata.cpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-ban-v1.cpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-chat-message-v1.cpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-chat-notification-v1.cpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-update-v1.cpp, lib/twitch-eventsub-ws/src/generated/payloads/session-welcome.cpp, lib/twitch-eventsub-ws/src/generated/payloads/stream-offline-v1.cpp, lib/twitch-eventsub-ws/src/generated/payloads/stream-online-v1.cpp, lib/twitch-eventsub-ws/src/generated/payloads/subscription.cpp
- Adds `/* tag */` to tag argument in `tag_invoke`
- Removes `std::move` for (known) trivially copyable types - we have to emulate `std::is_trivially_copyable` a bit. We have `static_assert`s to make sure that's actually true
- Uses `std::move` for vectors (they were copied before)
- Types without members won't create a `root` variable anymore
Fixes #5913.
=> fix: address clang-tidy warnings

.github/workflows/build.yml, .github/workflows/test-macos.yml, .github/workflows/test-windows.yml, CHANGELOG.md, CMakeLists.txt
The intent of this is not to remove every single ifdef qt version thing we have, but instead to stop building for Qt5 in CI.
New code we write should not have to pass Qt5 CI to be accepted in the codebase.
=> chore: disable Qt5 builds in CI

.github/workflows/build.yml, .github/workflows/test-macos.yml, CHANGELOG.md
From https://github.com/Chatterino/chatterino2/pull/5933#discussion_r1947909689
=> chore(ci): bump macos runners from 13 to 14

CHANGELOG.md, src/messages/MessageBuilder.cpp, src/messages/MessageSink.hpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchChannel.cpp, tests/snapshots/IrcMessageHandler/reward-unknown.json
Regarding #5928. We will show redemptions when they come through IRC regardless of whether we know the reward or we don't. If we don't know the reward, we save the message to be rebuilt later. When the reward comes in through PubSub, we replace the previous message. The queued rewards are currently limited to 16.
=> fix: show rewards early, replace later

CHANGELOG.md, src/widgets/dialogs/EmotePopup.cpp
Does the same as #5580, but for the search channel. We reuse a single channel (and view) for the search.
Fixes #5945.
=> fix: reuse one channel for emote search

.cirrus.yml, CHANGELOG.md
=> chore(ci): bump freebsd image from 14.0 to 14.2

CHANGELOG.md, lib/twitch-eventsub-ws/benchmarks/src/parse.cpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/listener.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/messages/metadata.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-ban-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-chat-message-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-chat-notification-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-update-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/session-welcome.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/stream-offline-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/stream-online-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/subscription.hpp, lib/twitch-eventsub-ws/src/session.cpp, lib/twitch-eventsub-ws/tests/src/parse.cpp, src/providers/twitch/eventsub/Connection.cpp, src/providers/twitch/eventsub/Connection.hpp
- The references account for most of the improvement here. Previously, we had to copy the structs in the functions.
- Removing `const` from members restores the default move constructor. With `const`, the struct can't be moved and needs to be copied.
`twitch-eventsub-ws-benchmark --benchmark_repetitions=10 --benchmark_time_unit=ms`:
<details><summary>Before</summary>
```text
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
BM_ParseAndHandleMessages             0.225 ms        0.220 ms         3200
BM_ParseAndHandleMessages             0.221 ms        0.215 ms         3200
BM_ParseAndHandleMessages …
```
=> refactor(eventsub): more references, less const

CHANGELOG.md, src/common/Channel.cpp, src/common/Channel.hpp, src/controllers/commands/builtin/twitch/DeleteMessages.cpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp, src/providers/twitch/TwitchIrcServer.cpp, src/widgets/helper/ChannelView.cpp
> user: how do you delete messages on chatterino?
Chatterino has many moderator focused features, but you can't delete a message from the context menu without reading through the settings or knowing that `/delete` exists. I don't see a reason why there shouldn't be a button if the user has moderator permissions.
=> feat: delete messages from context menu

CHANGELOG.md, src/providers/bttv/BttvEmotes.cpp
BTTV supports WEBP for all emotes (https://github.com/night/betterttv/discussions/7313#discussioncomment-12211280). As mentioned in https://github.com/Chatterino/chatterino2/discussions/5955, WEBP provides better quality for the emotes (WEBPs are usually smaller too).
"Closes" https://github.com/Chatterino/chatterino2/discussions/5955.
=> fix: use WEBP images for BTTV emotes

CHANGELOG.md, src/providers/IvrApi.cpp, src/widgets/dialogs/UserInfoPopup.cpp
When the channelName is "/live", the API call fails because "/live" is not a valid channelName. To fix this, replace "/live" with the userName, which is the actual channelName.
=> fix: opening a usercard from `/live` no longer makes failing ivr API call

CHANGELOG.md, src/providers/twitch/eventsub/Connection.cpp, src/providers/twitch/eventsub/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.hpp
This should make it easier to build simple system messages in the future. A new message builder is born, `EventSubMessageBuilder`. But we merged all builders some time ago? Yes, we could do this in the `MessageBuilder` as well. However, I do feel like this is a bit specific to EventSub. Especially, having `builder.appendUser(esString, esString, text)` is neat and avoids boilerplate. Note: we will need to have even more handlers if we support `channel.chat.notification`.
For more complex messages, a second function name like `onModerateMessage(chan, time, event, action)` can be used.
=> chore(eventsub): simplify building for system messages

CHANGELOG.md, src/widgets/helper/color/ColorInput.cpp
Changed the label for "Blue" back to Blue as it was incorrectly changed to "Red". This bug looks to have been introduced in commit 78a7ebb9f952d4de8fb69b95a786e570e96bdf1c.
To replicate this bug, open any of the color picker windows. One example is the "Highlights" menu. ![image](https://github.com/user-attachments/assets/1a6f8d1f-57cf-44dd-82d9-4e56f4234af6)
This pull request fixes #5979
=> fix: typo in color input selector. changed from red to blue

CHANGELOG.md, src/Application.cpp, src/CMakeLists.txt, src/providers/twitch/TwitchIrcServer.cpp, src/providers/twitch/eventsub/Connection.cpp, src/providers/twitch/eventsub/MessageHandlers.cpp, src/providers/twitch/eventsub/MessageHandlers.hpp, tests/snapshots/EventSub/channel-moderate/clear.json
Basically the same as in PubSub. While testing, I noticed that we call `getTwitch` in `onChannelModerate`. That function isn't called on the GUI thread, though. I moved the assertions to the functions of `ITwitchIrcServer` (where needed).
=> feat(eventsub): implement clearchat

CHANGELOG.md, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp, src/providers/twitch/eventsub/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.hpp, tests/snapshots/EventSub/channel-moderate/delete-long.json, tests/snapshots/EventSub/channel-moderate/delete.json, tests/snapshots/EventSub/channel-moderate/shared-delete-long.json, tests/snapshots/EventSub/channel-moderate/shared-delete.json
Towards #5908
Implements:
- Delete  
- Shared chat delete (we didn't handle this in PubSub)
Will add changelog entry after the chat modes PR is merged in
=> feat(eventsub): implement (shared chat) delete

src/singletons/StreamerMode.cpp, tests/src/AccessGuard.cpp
This fixes the warnings inside Chatterino code with GCC 14 on Linux (which progresses #4825 forward)
Note that sol2 may still have a stubborn `-Wmaybe-uninitialized` warning even after this change
=> Chatterino warning fixes

CHANGELOG.md, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp, src/providers/twitch/eventsub/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.hpp, tests/snapshots/EventSub/channel-moderate/add-blocked-term-three.json, tests/snapshots/EventSub/channel-moderate/add-blocked-term.json, tests/snapshots/EventSub/channel-moderate/add-permitted-term-two.json, tests/snapshots/EventSub/channel-moderate/add-permitted-term.json, tests/snapshots/EventSub/channel-moderate/remove-blocked-term-four.json, tests/snapshots/EventSub/channel-moderate/remove-blocked-term.json, tests/snapshots/EventSub/channel-moderate/remove-permitted-term-from-automod.json, tests/snapshots/EventSub/channel-moderate/remove-permitted-term.json
Implements builders for `{add,remove}_{permitted,blocked}_term` actions in `channel.moderate`. I don't use `AutomodTerms.fromAutomod`. 
=> feat(eventsub): implement AutoMod term actions

CHANGELOG.md, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp, lib/twitch-eventsub-ws/src/generated/payloads/channel-moderate-v2.cpp, src/providers/twitch/eventsub/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.hpp, tests/snapshots/EventSub/channel-moderate/raid.json, tests/snapshots/EventSub/channel-moderate/unraid.json
Looks the same as from PubSub (first line is PubSub, second line is EventSub)
Since we have the info, I've added the channel we've cancelled the raid to (first line is PubSub, second line is EventSub)
=> feat(eventsub): Add support for `/(un)raid`

CHANGELOG.md, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/automod-message-hold-v2.hpp, lib/twitch-eventsub-ws/src/generated/payloads/automod-message-hold-v2.cpp, src/providers/twitch/TwitchChannel.cpp, src/providers/twitch/TwitchChannel.hpp, src/providers/twitch/eventsub/Connection.cpp, src/providers/twitch/eventsub/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.hpp, src/util/Helpers.cpp, src/util/Helpers.hpp, tests/snapshots/EventSub/automod-message-hold/automod-category.json, tests/snapshots/EventSub/automod-message-hold/blocked-term-enclosed.json, tests/snapshots/EventSub/automod-message-hold/blocked-term.json, tests/snapshots/EventSub/automod-message-hold/blocked-terms-4.json, tests/snapshots/EventSub/automod-message-hold/localized-name.json, tests/src/EventSubMessages.cpp, tests/src/Helpers.cpp
Towards https://github.com/Chatterino/chatterino2/issues/5908. I mostly copied the code from the PubSub implementation, but split it in two. The message is "just" added. The fragments (=emotes) are ignored like in PubSub.
(top message is PubSub, because EventSub is slow)
=> feat(eventsub): implement automod message hold

CHANGELOG.md, src/Application.cpp, src/controllers/commands/CommandController.cpp
also update Settings to v0.3.0, giving us the ability to more sparingly save the commands.
We can now call `CommandController::save()` as much as we want, but it'll only save if something has actually saved, thanks to the combined use of `OnlySaveOnChange` and `SettingOption::CompareBeforeSet`
Fixes #6009
=> fix: don't save commands on exit

CHANGELOG.md, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/providers/twitch/eventsub/MessageHandlers.cpp, src/util/ChannelHelpers.hpp, tests/snapshots/EventSub/channel-moderate/shared-timeout-stacking-diff-sources.json, tests/snapshots/EventSub/channel-moderate/shared-timeout-stacking-diff-sources2.json, tests/snapshots/EventSub/channel-moderate/shared-timeout-stacking.json, tests/snapshots/EventSub/channel-moderate/shared-timeout.json, tests/snapshots/EventSub/channel-moderate/timeout-stacking-reason.json, tests/snapshots/EventSub/channel-moderate/timeout-stacking.json, tests/snapshots/EventSub/channel-moderate/timeout.json, tests/src/EventSubMessages.cpp
I can't live without timeout stacking, so I had to implement it. Yes, it's not pretty, but maybe we can fix this soon-ish (with a bigger extra data).
The logic for stacking is as follows:
- Find a past timeout message that looks like the to-be-added message:
- Either both of them are from shared chat and from the same channel _or_ neither is from shared chat
- Both must time out the same user.
- If one message is from PubSub (or EventSub), use that one and drop the other one
- Otherwise, generate a new message with (count + 1) and the same parameters
For this to work, all names must be the login names.
=> feat(eventsub): implement timeout stacking

CHANGELOG.md, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/suspicious-users.hpp, src/providers/twitch/PubSubManager.cpp
Since we handle all events in EventSub that PubSub had handled except channel point rewards, we can stop listening to PubSub topics if EventSub is enabled.
I did the check in the PubSub manager. It could also be done in `TwitchChannel` (where the subscriptions are initiated).
=> feat(eventsub): don't listen to PubSub if EventSub is on

CHANGELOG.md, src/singletons/Settings.cpp, src/singletons/Settings.hpp, src/widgets/BaseWidget.hpp, src/widgets/BaseWindow.cpp, src/widgets/BaseWindow.hpp, src/widgets/OverlayWindow.cpp, src/widgets/OverlayWindow.hpp, src/widgets/settingspages/GeneralPage.cpp
This PR allows overlay windows to zoom in and out independently of the global scale. They also inherit their base scale from the global scale. The scale of an overlay window is computed by multiplying the global scale with the scale factor for overlay windows.
To do this, I turned `OverlayWindow` into a `BaseWindow`. This worked fine, except that on Windows, it would disable resizing (for some reason). This was because the `FramelessWindowHint` was set after the `QWidget` had been constructed in `BaseWindow`. I moved the hint into the constructor (and extracted the ternaries into a function).
See https://github.com/Chatterino/chatterino2/discussions/5633#discussioncomment-10872036.
=> feat(overlay): inherit zoom and add zoom factor

CHANGELOG.md, src/common/Channel.cpp, src/common/Channel.hpp, src/controllers/commands/builtin/twitch/DeleteMessages.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/splits/SplitInput.cpp
- Removed `Channel::findMessage` (deprecated) and migrated uses to `findMessageByID`
- Removed (effectively[^1]) dead code in `SplitInput::handleSendMessage`
- Renamed loop variable to avoid shadowing function parameter
[^1]: Reason for why it's dead: we check the same pointer twice and return if it's null. The only way this code could potentially run is if the pointer was modified in-between from another thread. I don't think that was the intention.
=> chore: remove dead code and get rid of MSVC warnings

CHANGELOG.md, src/singletons/Settings.hpp, src/util/StreamLink.cpp, src/widgets/settingspages/ExternalToolsPage.cpp, src/widgets/settingspages/ExternalToolsPage.hpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/settingspages/SettingWidget.cpp, src/widgets/settingspages/SettingWidget.hpp
Updated the SettingWidget class to support creating a Color Button, Custom Checkbox (checkbox that isn't backed by a setting), and Int Input
Migrated the following settings to use SettingWidget instead of the GeneralPageView creator:
- Hide scrollbar thumb
- Hide scrollbar highlights
- Separate with lines
- Alternate background color
- Hide deleted messages
- Line color
- Shadow color" from Overlay**
- Show moderation messages
- Show user button
- Show preferences button
- Show deletions of single messages
- Show message reply button
- Restart on crash (custom checkbox example)
- Background opacity (0-255) (int input example)
Changed the style of the External tools page to conform to the General page style
Got some feedback from chat, generally nothing big in its styling, but this will …
=> refactor: use some more SettingWidget & restyle external tools page

CHANGELOG.md
Updates the crash handler to https://github.com/Chatterino/crash-handler/commit/7d9811b107d65a6afa3e11ff0370ca38b8060746 (all changes: https://github.com/Chatterino/crash-handler/compare/9753fe802710b2df00f2287ec2e1ca78c251d085...7d9811b107d65a6afa3e11ff0370ca38b8060746).
This means Windows users can now build Chatterino with `clang-cl`.
=> deps: update crash handler

CHANGELOG.md, lib/twitch-eventsub-ws/ast/lib/member.py, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/messages/metadata.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-ban-v1.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/channel-moderate-v2.hpp
When we read a type, we try to infer its tag. Comment commands can still overwrite it. Nothing in the templates needs to change.
Fixes #5912.
=> fix(eventsub): infer `AsISO8601` for chrono time point

CHANGELOG.md, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/listener.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/session-welcome.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/session.hpp, lib/twitch-eventsub-ws/src/generated/payloads/session-welcome.cpp, lib/twitch-eventsub-ws/src/session.cpp, src/Application.cpp, src/common/Args.cpp, src/common/Args.hpp, src/common/network/NetworkPrivate.hpp, src/common/network/NetworkRequest.cpp, src/common/network/NetworkRequest.hpp, src/common/network/NetworkTask.cpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/eventsub/Connection.cpp, src/providers/twitch/eventsub/Connection.hpp, src/providers/twitch/eventsub/Controller.cpp, src/providers/twitch/eventsub/Controller.hpp
When we disconnect, or we're asked to reconnect, we should reconnect. A `Session` can now be orphaned, because we want to transplant the listener. That's mostly it. If we don't have a reconnect URL and are disconnected, we reset all the subscriptions a connection was subscribed to and try to subscribe again.
You can try this with the Twitch CLI. I opened https://redirect.github.com/twitchdev/twitch-cli/pull/347 to have at least one event that we use in there. Otherwise, you can also edit some event in `TwitchChannel` to use `channel.ban`.
```shell
twitch event websocket start-server --ssl --port 3012 # start local server
chatterino --use-local-eventsub # start chatterino
twitch event websocket close --reason=4000 …
```
=> feat(eventsub): reconnect

CHANGELOG.md, src/providers/twitch/eventsub/Controller.cpp, src/providers/twitch/eventsub/Controller.hpp
From https://github.com/Chatterino/chatterino2/pull/6035: if there's no connection, we should retry indefinitely.
Thinking a bit more about this, I came to the conclusion that we don't need the retry count at all but a backoff for each subscription. This makes the code a bit simpler.
Three semi-related changes:
- If Helix returns _403 Forbidden_, we can mark the request as failed (no need to retry). We might need to retry if we get a _429 Too Many Requests_. Unfortunately, that status is also used if a subscription already exists ([docs](https://dev.twitch.tv/docs/api/reference/#create-eventsub-subscription)).
- If someone unsubscribed and immediately subscribed again, we could've discarded the subscription request if it came in while we were `Unsubscribing`. To detect this, we check when …
=> refactor(eventsub): use backoff over retry count

CHANGELOG.md, src/singletons/Fonts.cpp, src/singletons/Fonts.hpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
Since I always used GDI as the font engine, I never noticed that it parses some weights (styles) of fonts as different families (e.g. there's "Segoe UI", "Segoe UI Bold", "Segoe UI Light"). DirectWrite doesn't do that, and properly combines them into one font family ("Segoe UI" with "Normal", "Bold", and "Light" styles). My selected chat font has a different weight than 400 (normal) and I'd like to keep that.
This PR adds a setting to customize the weight of the chat font. Some font engines support variable fonts, and we should allow for customization of this. The setting takes an OpenType font weight that is directly passed to Qt.
Since this touches `Fonts.cpp`, I refactored that a bit to have "getter" functions that each resolve a font property (family, size, weight, italic).
Future …
=> feat: allow custom chat font weight

CHANGELOG.md, mocks/include/mocks/DisabledStreamerMode.hpp, src/messages/layouts/MessageLayout.cpp, src/singletons/Settings.hpp, src/singletons/StreamerMode.cpp, src/singletons/StreamerMode.hpp, src/singletons/WindowManager.cpp, src/widgets/settingspages/GeneralPage.cpp
it's probably best to leave this setting solo'd out as restricted users
so monitored users can get their own behaviour in their own setting later
=> fix: only hide messages from restricted users, not all suspicious users

CHANGELOG.md, src/widgets/dialogs/EmotePopup.cpp, src/widgets/dialogs/EmotePopup.hpp, src/widgets/dialogs/SelectChannelDialog.cpp, src/widgets/helper/SearchPopup.cpp, src/widgets/helper/SearchPopup.hpp
=> fix: make QLineEdit's less ugly in light themes

CHANGELOG.md, lib/twitch-eventsub-ws/benchmarks/src/parse.cpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/session-welcome.hpp, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/session.hpp, lib/twitch-eventsub-ws/src/generated/payloads/session-welcome.cpp, lib/twitch-eventsub-ws/src/session.cpp, lib/twitch-eventsub-ws/tests/src/parse.cpp, tests/src/EventSubMessages.cpp
When suspending the PC or disconnecting for some time, we need to reconnect. We didn't detect this before, because we never did anything with the socket (e.g. writing). Now, we're checking every `keepalive_timeout_seconds * 2` that we received any message.
=> fix(eventsub): check keepalive

CHANGELOG.md, src/CMakeLists.txt, src/RunGui.cpp, src/util/SelfCheck.cpp, src/util/SelfCheck.hpp
All third party emote providers require WEBP. Some users forget to install qtimageformats. This results in missing images. This PR makes sure we are able to load WEBP images and shows a warning if we aren't.
In the future, we could move PNGs to lossless WEBPs. They're almost always smaller.
=> chore: check if WEBP is supported

CHANGELOG.md, lib/twitch-eventsub-ws/ast/lib/comment_commands.py, lib/twitch-eventsub-ws/ast/lib/enum_constant.py, lib/twitch-eventsub-ws/ast/lib/templates/enum-implementation.tmpl, lib/twitch-eventsub-ws/include/twitch-eventsub-ws/payloads/suspicious-users.hpp, lib/twitch-eventsub-ws/src/generated/payloads/suspicious-users.cpp
enum constants can have `/// extra_enum_constant_names` applied to allow for different strings to match to the same types
this is useful if the documentation is wrong and we're unsure for which is actually correct :-)
=> feat(eventsub): handle multi enum constant keys

CHANGELOG.md, src/common/Channel.cpp, src/common/Channel.hpp, src/widgets/dialogs/SelectChannelDialog.cpp, src/widgets/dialogs/SelectChannelDialog.hpp, src/widgets/splits/Split.cpp
We no longer use a Notebook for this, this means the layout we have will autosize appropriately.
To make it autosize on slightly larger font sizes I've done manual word wrapping on the labels instead of letting them word wrap themselves.
If the user resizes the dialog after opening it, things might look a little bit more goofy than before, but the default size it opens as should be better.
Something with how I add labels now (not using the layout creator) I messed up the focus chain.
I've fixed this by checking 2 steps ahead in the nextInFocuschain and previousInFocusChain.
the way we want this to work, we cannot use Qt's own focus chain logic since the QTextEdit that belongs with the "Channel" radiobox will always be ignored since it's not visible
=> fix: correctly scale SelectChannelDialog

CHANGELOG.md, src/messages/MessageBuilder.cpp
I might've strung too many strings in this diff here but it works
=> fix: qt 6.4.3 stringbuilding shenanigans with scope check message

CHANGELOG.md, src/util/WindowsHelper.cpp
If you have added Chatterino to autostart and run tests, then those tests would overwrite the original entry. When starting, the tests would run instead of Chatterino.
=> fix: don't add tests to autostart

CHANGELOG.md, src/widgets/helper/Button.cpp, src/widgets/helper/Button.hpp, src/widgets/splits/SplitInput.cpp
top new, bottom "old"
should look closer (but better) than the non-svg pixmap emote button
=> fix: apply same margin to svg buttons as to pixmap buttons

CHANGELOG.md, src/providers/twitch/eventsub/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.hpp, src/providers/twitch/eventsub/MessageHandlers.cpp, src/providers/twitch/eventsub/MessageHandlers.hpp, tests/snapshots/EventSub/channel-moderate/ban-reason.json, tests/snapshots/EventSub/channel-moderate/ban-stacking-reason.json, tests/snapshots/EventSub/channel-moderate/ban-stacking.json, tests/snapshots/EventSub/channel-moderate/ban.json, tests/snapshots/EventSub/channel-moderate/shared-ban-reason.json, tests/snapshots/EventSub/channel-moderate/shared-ban-stacking-diff-sources.json, tests/snapshots/EventSub/channel-moderate/shared-ban-stacking.json, tests/snapshots/EventSub/channel-moderate/shared-ban.json
In PubSub and IRC, we stack bans. We should do the same with EventSub (In https://github.com/Chatterino/chatterino2/pull/5985 I didn't want to do this, but now I realized that I was wrong). For the message itself, all it takes is to set the `PubSub` flag.
We now set the shared message info correctly on these messages.
Towards #5908.
=> fix(eventsub): stack bans

CHANGELOG.md, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/providers/twitch/eventsub/Controller.cpp
When debugging and breaking at the right time (e.g. because of an exception), the WS session might time out. This will cause Twitch to return a 400. I have a feeling that this will happen more often. When retrying, we retry with the new session ID (if it exists).
Towards #5908.
=> fix(eventsub): retry if the WS session expired

.CI/chatterino-installer.iss, CHANGELOG.md, CMakeLists.txt, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
`komac update ChatterinoTeam.Chatterino --version 2.5.2 --urls https://github.com/Chatterino/chatterino2/releases/download/v2.5.2/Chatterino.Installer.exe`
=> Release v2.5.3-beta.1

CHANGELOG.md, src/widgets/dialogs/SelectChannelDialog.cpp
When opening the dialog for a regular Twitch channel, the input wasn't focused. With this change, the input is first shown and focused afterwards.
=> fix: focus input after updating visibility

CHANGELOG.md, src/widgets/dialogs/UserInfoPopup.cpp
=> fix: don't show moderation buttons on your own usercard

CHANGELOG.md, docs/make-release.md, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
`komac update ChatterinoTeam.Chatterino --version 2.5.2 --urls https://github.com/Chatterino/chatterino2/releases/download/v2.5.2/Chatterino.Installer.exe`
=> Release v2.5.3

CHANGELOG.md, conanfile.py
I was building with VisualStudio recently and used CMakePresets, but it conflicted with conan, because conan would create `CMakeUserPresets.json` which confused VS. The file that conan generates isn't useful.
I should revise the documentation for builds on Windows and add at least a small section about VS and CMakePresets, because with [cmake-conan](https://github.com/conan-io/cmake-conan), they're nice to use and will result in a vcpkg-like experience in VS.
=> chore(conan): don't create `CMakeUserPresets.json`

CHANGELOG.md, src/singletons/NativeMessaging.cpp, src/singletons/NativeMessaging.hpp, tests/CMakeLists.txt, tests/src/NativeMessaging.cpp
Fixes #6115
I did not find a clean way of checking this without creating a new `QDir`(or similar) object since `dir.cdUp()` changes the dir if it succeeds and `dir.exists("..")` returns false if `dir` does not exist.
=> Fix: Don't create native messaging manifest file if browser directory doesn't exist

CHANGELOG.md, src/CMakeLists.txt
`windeployqt` tries to find `libcrypto*` and `libssl*` when deploying and omits `qopensslbackend.dll` in Qt 6.8.0+ if they're not found. However, it will always look in `/bin` (relative to the output), even when specifying `--openssl-root`. Since we deploy OpenSSL to `/`, we need to pass `--force-openssl`. Since we don't have any CI builds with 6.8/6.9, this is only a CMake modification.
=> fix(cmake): use `--force-openssl` on Qt 6.8+

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
fixes #2688
the paused chat indicator in its current form is a little bit difficult to see. I am suggesting:
- adding an outline so that the indicator stands out from other widget elements such as chat timestamps
- moving the indicator to the bottom of the widget since users' eyes are more likely to be focused on the bottom half of the widget than the top half of the widget
- adding "Chat Paused" text next to the symbol to make the indicator bigger and easier to notice
<details>
<summary>before</summary>
<IMG src="https://github.com/user-attachments/assets/428db078-e2ee-481a-9961-428cafb3338e"/>
</details>
<details>
<summary>after (dark theme)</summary>
<IMG src="https://github.com/user-attachments/assets/67aa6d89-8a07-402e-831b-3b64555b503b"/>
</details>
<details>
<summary>after (black …
=> make paused chat indicator more apparent

CHANGELOG.md, src/providers/bttv/BttvLiveUpdates.cpp, src/providers/bttv/BttvLiveUpdates.hpp, src/providers/bttv/liveupdates/BttvLiveUpdateSubscription.cpp, src/providers/bttv/liveupdates/BttvLiveUpdateSubscription.hpp, src/providers/liveupdates/BasicPubSubManager.hpp, src/providers/twitch/TwitchChannel.cpp
bttv socket server changed at some point to _only_ support TLS 1.3 but we previously maxed at TLS 1.2 so the bttv ws stopped connecting due to a tls handshake error
I've tested that 7tv ws (supports tls 1.0-1.3) still works with this change (out of paranoia I disabled tls 1.0 & 1.1, which are both deprecated)
also updates outdated `broadcast_me` payload: https://betterttv.com/developers/websocket#user-broadcast
=> fix: receive bttv live updates again

CHANGELOG.md, src/widgets/helper/ResizingTextEdit.cpp
fixes #4755 
it seems that [QTextEdit](https://doc.qt.io/qt-6/qtextedit.html#editing-key-bindings) does not handle this behavior on its own like [QLineEdit](https://doc.qt.io/qt-6/qlineedit.html#default-key-bindings) does. handling the behavior explicitly fixes the issue.
=> fix cmd+backspace behavior in main chat dialog input

CHANGELOG.md, src/widgets/settingspages/GeneralPageView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/settingspages/SettingWidget.cpp
- When scrolling on combo boxes, using the scroll wheel wouldn't do anything. Now it scrolls the parent container.
- When scrolling on spin boxes, the value would change. Now it scrolls the parent container.
=> fix: allow scrolling by inputs in settings

CHANGELOG.md, lib/twitch-eventsub-ws/cmake/GenerateJson.cmake
Compiling after a `ninja clean` caused the JSON generator to fail. This isn't a complete fix, the root of the problem is a bit deeper, because we'd actually need to split the task into two - one for generating the `.inc` file and one for generating the implementation, because clang will freak out if the `.inc` file doesn't exist and will refuse to resolve types like `std::chrono::system_clock`[^1].
Because we don't add new eventsub topics every day, it's fine having to recompile twice. Not being able to do clean the output is a bit worse, I think.
[^1]: Ok, actually, it's a bit more complicated. The two-step process would work because we generally don't need the type information to generate a forward declaration, but in theory, it still reads an incomplete header so if type information …
=> fix: don't include `.inc` in outputs

CHANGELOG.md, src/RunGui.cpp, src/singletons/Settings.cpp, src/singletons/Settings.hpp
In an attempt to solve https://github.com/Chatterino/chatterino2/issues/6157, I added a handler for [`aboutToQuit`](https://doc.qt.io/qt-6/qcoreapplication.html#aboutToQuit) - specifically because this is called when the application is shut down by Windows ([source](https://github.com/qt/qtbase/blob/53ff8897c5c8bc6175cf94ed24e2d2c5fa17365b/src/plugins/platforms/windows/qwindowscontext.cpp#L1312-L1315)).
If we do this, we shouldn't save afterward - `aboutToQuit` will be called (immediately) before `Application::run` returns. I added `disableSave` to try to avoid saving after we exit.
=> fix: handle `aboutToQuit()`

CHANGELOG.md, src/singletons/Settings.hpp, src/widgets/helper/NotebookTab.cpp, src/widgets/settingspages/GeneralPage.cpp
This PR aims to implement disabling of the "double-click to rename tab" feature through yet another setting, as discussed in #6156. I've stuffed the setting at the bottom of the advanced section, but I'm sure it would be better suited somewhere else. Do we still care given how much of a mess settings are?
Demo:
https://github.com/user-attachments/assets/6f6a3d56-9a4a-45a1-a9f3-52a5caf3597f
=> feat(6156): disable tab renaming on double-click via setting

CHANGELOG.md
https://github.com/google/googletest/releases/tag/v1.17.0
C++17 required - no issues for us
=> dep: update googletest to v1.17.0

CHANGELOG.md, src/common/ChannelChatters.cpp, src/common/ChannelChatters.hpp, src/controllers/commands/builtin/twitch/Block.cpp, src/controllers/ignores/IgnoreController.cpp, src/controllers/ignores/IgnoreController.hpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchAccount.cpp, src/providers/twitch/TwitchAccount.hpp, src/providers/twitch/TwitchUser.hpp, src/widgets/dialogs/UserInfoPopup.cpp, tests/src/IrcMessageHandler.cpp
Users who are blocked no longer show up in the "Users joined:" or "Users parted:" messages
Fixes #2505
The biggest chunk of code of this fix comes from adding user logins to the list of blocks. There are some container types that allow for use of multiple keys (basically keeping the same type of logic we use with multiple sets but internally instead), but that seemed a bit out of scope of this change.
=> fix: don't include blocked users in join/part messages

CHANGELOG.md, src/widgets/settingspages/GeneralPage.cpp
This PR aims to add a tooltip to the setting introduced in #6163. I wasn't aware there were tooltips until I was testing something else :) 
(this screenshot was taken before aligning the wording of "double-click")
=> feat: add tooltip for rename on double-click setting

CHANGELOG.md, src/controllers/plugins/PluginController.cpp, src/controllers/plugins/api/WebSocket.cpp, tests/src/Plugins.cpp
To try use this code:
```lua
c2.WebSocket.new('ws://localhost', {on_close=function()end})
```
=> Do not hide WebSocket API when missing permission

CHANGELOG.md, docs/chatterino.d.ts
Currently, the use of `c2.HTTPRequest.create(...)` in typescript results in code that produces the following error after being compiled with TSTL:
```
Failed to evaluate command from plugin HTTP Error: stack index 1, expected number, received table: (bad argument into 'std::shared_ptr<chatterino::lua::api::HTTPRequest>(sol::this_state, enum chatterino::NetworkRequestType, QString)')
```
This is because the generated lua code for this function call is:
```lua
c2.HTTPRequest:create(...)
```
This PR updates the types file so that the generated lua code is:
```lua
c2.HTTPRequest.create(...)
```
=> fix(plugins): TSTL `HTTPRequest.create` generation

CHANGELOG.md, src/common/network/NetworkResult.cpp, src/common/network/NetworkResult.hpp, src/singletons/ImageUploader.cpp, src/singletons/ImageUploader.hpp, tests/CMakeLists.txt, tests/src/ImageUploader.cpp
This PR notably adds syntax for querying arrays: `https://example.com/{components.1}.png`. It doesn't use `.[0]` because that's harder to parse. It also adds some tests for the parsing.
One difference to before is that now, once the selector reaches a scalar (string/number/boolean/null/undefined), it stops there. Before, it would've continued and evaluated to `QJsonValue::Undefined`. I don't see a reason to keep this.
When Chatterino is compiled with Qt 6.9+, one can also query a scalar/top-level string like `"foo"`: `{.}` (makes use of the change above).
Closes https://github.com/Chatterino/chatterino2/issues/6191.
=> feat(uploader): extend JSON selectors

CHANGELOG.md, src/widgets/AccountSwitchPopup.cpp, src/widgets/BaseWidget.cpp, src/widgets/BaseWidget.hpp, src/widgets/BaseWindow.cpp, src/widgets/DraggablePopup.cpp, src/widgets/dialogs/EditUserNotesDialog.cpp, src/widgets/dialogs/UpdateDialog.cpp, src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/helper/Line.hpp, src/widgets/helper/OverlayInteraction.cpp, src/widgets/helper/TitlebarButtons.cpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/splits/SplitHeader.cpp
- **addSeperator -> addSeparator**
- **seperating -> separating**
- **mesage -> message**
- **noticable -> noticeable**
- **BaseWidget::setScaleIndependantSize -> BaseWidget::scaleIndependentSize**
- **scaleIndependantSize -> scaleIndependentSize**
- **setScaleIndependantSize -> setScaleIndependentSize**
- **setScaleIndependantWidth -> setScaleIndependentWidth**
- **setScaleIndependantHeight -> setScaleIndependentHeight**
- **scaleIndependantSize_ -> scaleIndependentSize_**
=> refactor: fix some spelling mistakes

CHANGELOG.md, src/widgets/Notebook.cpp, src/widgets/Notebook.hpp
Towards https://github.com/Chatterino/chatterino2/discussions/6153.
Should make it easier to implement refactorings to notebook layout (and potentially fix the issues linked in https://github.com/Chatterino/chatterino2/discussions/6153#discussioncomment-12846958).
Top/bottom and left/right layouts are almost the same, except for the direction. Unfortunately, they're not that similar, but we can still put them together and get the same result. The functions are named horizontal for left-to-right/right-to-left layout and vertical for top-to-bottom layout.
The easiest way to test this is to make screenshots and use the "difference" blend-mode in your favorite photo editor (tbf, all I did was diff the branches and insert an `if` where they differed). One small difference is that the custom …
=> refactor(notebook): merge top/bottom and left/right layout

src/RunGui.cpp
i don't want to include stdlib.h
=> refactor: use std::_Exit in rungui instead of _exit

src/Application.cpp, src/Application.hpp, src/controllers/completion/sources/CommandSource.cpp, src/controllers/completion/sources/EmoteSource.cpp, src/controllers/completion/sources/Source.hpp, src/controllers/completion/sources/UnifiedSource.cpp, src/controllers/completion/sources/UserSource.cpp
All time figures mentioned are CPU time from clean in debug on my system as claimed by [ClangBuildAnalyzer](https://github.com/aras-p/ClangBuildAnalyzer)
Things done so far:
- `TimeoutStackStyle` moved to separate file to avoid expensive `Channel.hpp` include in `Settings.hpp` to save about a minute in includes
- Notebook related enums moved to separate file to avoid expensive `Notebook.hpp` include in `Settings.hpp` to save about a minute in includes
- `Application.hpp` include removed in `Plugin.hpp`. I don't think this saves all that much.
- Forward declare `NativeMessagingServer` in `Settings.hpp` and use a `unique_ptr` to save around two minutes in includes
- Forward declare `GenericListModel` in `controllers/completion/sources/Source.hpp` to save around two minutes in includes …
=> Forward declare some things to speed up compile

docs/wip-plugins.md
Using "Post" here causes type mismatch error
```
Failed to evaluate command from plugin Chatterino API: stack index 1,
expected number, received string: (bad argument into
'std::shared_ptr<chatterino::lua::api::HTTPRequest>(sol::this_state, enum
chatterino::NetworkRequestType, QString)')
```
=> Fix plugin docs: HTTPRequest enum

CHANGELOG.md, src/util/Helpers.cpp
QStringBuilder is a bit more finicky on older versions of Qt. This "builds" the builders fully into a QString before we attempt to use them.
This crash was not part of the latest stable release, as it was introduced in #6125 
Fixes #6228
=> fix: crash on older versions of Qt

CHANGELOG.md, src/util/OnceFlag.cpp, src/util/OnceFlag.hpp
We don't need a strict memory ordering here, because there's no associated memory that we care about.
As we only ever saw flaky tests on macOS runners which use ARM, the issue is probably that we aren't atomic enough. There's no real proof that this was the issue (only that it wasn't).
=> fix(once-flag): make `flag` atomic

CHANGELOG.md, src/singletons/StreamerMode.cpp
Previously, the automatic streamer mode check did not work in flatpak builds, as `pgrep` was executed inside of the sandbox, which only has chatterino's processes and not anything else running on the system.
Now the command will be executed outside of the sandbox through `flatpak-spawn`, the same way as it's done for spawning streamlink. I've tested locally that this works and detects obs running correctly.
=> feat: add support for automatic streamer mode check from flatpak

CHANGELOG.md, src/messages/layouts/MessageLayout.cpp, src/messages/layouts/MessageLayout.hpp, src/messages/layouts/MessageLayoutContext.hpp, src/widgets/helper/ChannelView.cpp
Amends https://github.com/Chatterino/chatterino2/pull/6231.
We can't use floating points for the bounds of a message layout, because the backing pixmap will always use whole integers. `MessageLayout::get{Width,Height}` will now return an integer again to reflect this (the pixmap bounds were already rounded down). The layout inside the message still uses floating points to place elements.
Fixes #6253.
=> fix: use integers for message layout bounds

CHANGELOG.md, src/singletons/Settings.hpp, src/util/QMagicEnumTagged.hpp, src/widgets/settingspages/SettingWidget.hpp, tests/src/QMagicEnum.cpp
Currently not implemented anywhere, but I've tested implementing it for a setting and it works as expected.
Example implementation (put in same file/namespace as the enum itself)
```c++
constexpr chatterino::qmagicenum::customize_t qmagicenumDisplayName(
TabStyle value) noexcept
{
switch (value)
{
case TabStyle::Normal:
return "Normal (default)";
default:
return {};
}
}
```
=> feat: implement display name specializations for enums

scripts/clang-format-all.sh
this can be enabled by setting the FAST environment variable to 1
=> feat: optionally parallelize `clang-format-all.sh`

scripts/check-clang-tidy.sh
default now single thread and not using parallel unless FAST=1 is
specified
=> chore: slight restructuring of `check-clang-tidy.sh`

CHANGELOG.md, src/widgets/settingspages/SettingWidget.cpp
This does not fix every single "text box" setting in the settings dialog, only the ones that use `SettingWidget::lineEdit`
I'm OK with that, since that's where I want our development to move anyway.
=> fix: update lineedit if setting changed externally

CHANGELOG.md, src/widgets/buttons/Button.cpp, src/widgets/buttons/Button.hpp, src/widgets/buttons/NotebookButton.cpp
Fixes #6301 
I deliberately did not add getters for `rightMouseButtonDown` and `middleMouseButtonDown` because they would not be used anywhere right now
=> fix: middle & right click buttons not working on `Button` class

CHANGELOG.md, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/settingspages/SettingWidget.hpp
this PR cleans up some includes, and converts all remaining addCheckbox usages to use SettingWidget.
Additionally, I've added `[[nodiscard]]` to all SettingWidget creators, meaning your IDE will scream at you if you don't use `addTo` at the end of the builder pattern
=> refactor: remove GeneralPageView.addCheckbox

CHANGELOG.md, src/util/OnceFlag.cpp, src/util/OnceFlag.hpp, tests/src/OnceFlag.cpp
This does two things to `OnceFlag`:
- Adds checks to `wait`/`waitFor` to check if the flag is already set. The callback passed to the condition variable is only executed when the variable is (potentially spuriously) notified. We need to take the mutex before to avoid a lost-update (e.g. T1: check; T2: set & notify; T1: wait [missed wakeup]).
- Adds a convenience `isSet` method to check if the flag is set. This is equivalent to `wait(0ms)`.
=> fix(OnceFlag): add `isSet` and check before waiting

CHANGELOG.md, src/controllers/plugins/api/WebSocket.cpp, tests/src/Plugins.cpp
If the callbacks for WebSockets are unset, then they can't be called and Chatterino would segfault (I wonder why sol doesn't check for this). This adds a check that the callbacks are actually set before calling them.
=> fix(plugins): check websocket callbacks before calling

CHANGELOG.md, src/providers/twitch/IrcMessageHandler.cpp, tests/snapshots/IrcMessageHandler/sub-message-user-color-override.json
Makes use of the work in #6322 to correctly color usernames based on overrides
Fixes #6313
=> fix: correctly color usernames in most other notice scenarios

CHANGELOG.md, src/common/StreamerModeSetting.hpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/GeneralPageView.cpp, src/widgets/settingspages/GeneralPageView.hpp, src/widgets/settingspages/SettingWidget.cpp, src/widgets/settingspages/SettingWidget.hpp
- **refactor: add private registerWidget function**
- **refactor: remove unused addDropdown variant**
- **feat: conditionallyEnabledBy string equals**
- **feat: QString dropdown**
- **use QString dropdown in theme dropdown**
- **Remove another addDropdown variant from GeneralPageView**
- **remove enableIf from GeneralPageView**
- **increase minimum size of dropdowns**
- **migrate StreamerModeSetting to SettingWidget**
=> some more small settingwidget refactors

CHANGELOG.md, src/widgets/Notebook.cpp, src/widgets/Notebook.hpp
- **make Notebook::performLayout protected**
- **relayout tabs if preferences/user/streamer mode button change visibility**
=> fix: relayout notebook if any custom buttons change

CHANGELOG.md, tests/CMakeLists.txt, tests/src/ChatterSet.cpp, tests/src/TwitchPubSubClient.cpp
clang-cl was quite vocal when compiling the tests. For Clang in GNU mode and GCC, these warnings are disabled project wide. I think we can eventually enable them (I'm probably one of the few people using clang-cl to compile Chatterino and I can live with that - just not for the tests).
=> fix(clang-cl): reduce warnings in tests

CHANGELOG.md, src/controllers/sound/MiniaudioBackend.cpp, src/controllers/sound/MiniaudioBackend.hpp
Tested on:
- Arch Linux (btw) with Pipewire
- Windows 11 in a VM
Both no longer output "Audio thread did not stop within 1 second" on exit, which could crash things as we detached the thread.
=> fix: Fix a crash that would occur on exit if a ping sound played recently

CHANGELOG.md, src/controllers/commands/CommandController.cpp, src/controllers/commands/builtin/chatterino/Debugging.cpp, src/controllers/commands/builtin/chatterino/Debugging.hpp, src/widgets/helper/ChannelView.cpp
There is a bug where images won't show in some occasions and I don't know why (resizing won't show them - only when some image is loaded (I think) they're shown). To aid debugging, I added some commands to trigger relayouts/buffer invalidations. I couldn't reproduce this yet.
I also noticed that the buffer invalidation is reset outside the `if` in `ChannelView::layoutVisibleMessages` but it's only used inside the `if`. This was moved inside, but I don't expect this to make a significant difference.
=> chore: add some channel view layout commands

CHANGELOG.md, src/controllers/sound/MiniaudioBackend.cpp, src/providers/liveupdates/BasicPubSubManager.hpp, src/providers/twitch/PubSubManager.cpp
Previously, we would detach threads that did not exit in a reasonable
time, meaning they'd continue running and potentially accessing data
that had been freed, causing us to crash.
With this change, we _dont_ detach the thread, and let the thread
destructor do as it pleases (which will be terminating).
Neither solution is clean - old solution would sometimes work, but this
should give us a better indicator of where we're doing things wrong.
CC @Nerixyz
=> fix: don't detach threads

CHANGELOG.md, src/widgets/buttons/SvgButton.cpp, src/widgets/buttons/SvgButton.hpp
The `QSvgRenderer::setAspectRatioMode` function only sets the aspect
ratio setting for the currently loaded SVG document.
https://github.com/qt/qtsvg/blob/29c3b512d9ca25941b18f7ee52ce8b80f003f3b4/src/svg/qsvgrenderer.cpp#L311-L320
When the theme changes, or we otherwise call load, this does not retain
our aspect ratio settings.
https://github.com/qt/qtsvg/blob/29c3b512d9ca25941b18f7ee52ce8b80f003f3b4/src/svg/qsvgrenderer.cpp#L412-L432
This means we need to ensure we re-set the SVG renderer's aspect ratio
after calling load.
=> fix: Re-set SVG renderer aspect ratio after load

CHANGELOG.md, src/widgets/dialogs/EmotePopup.cpp
Fixes the two issues mentioned in #6354:
When opening emote popup in a non-twitch channel (such as mentions)
- Global emotes are not showing up in the emote popup 
- Searching anything will crash Chatterino
=> fix: Fix searching in emote popup if not in a twitch channel

CHANGELOG.md, src/messages/MessageElement.cpp, src/messages/MessageElement.hpp, tests/snapshots/IrcMessageHandler/action.json, tests/snapshots/IrcMessageHandler/bad-emotes.json, tests/snapshots/IrcMessageHandler/bad-emotes2.json, tests/snapshots/IrcMessageHandler/cheer1.json, tests/snapshots/IrcMessageHandler/cheer2.json, tests/snapshots/IrcMessageHandler/cheer3.json, tests/snapshots/IrcMessageHandler/emote-emoji.json, tests/snapshots/IrcMessageHandler/emote.json, tests/snapshots/IrcMessageHandler/emotes.json, tests/snapshots/IrcMessageHandler/emotes2.json, tests/snapshots/IrcMessageHandler/emotes3.json, tests/snapshots/IrcMessageHandler/emotes4.json, tests/snapshots/IrcMessageHandler/emotes5.json, tests/snapshots/IrcMessageHandler/first-msg.json, tests/snapshots/IrcMessageHandler/ignore-replace.json, tests/snapshots/IrcMessageHandler/mod.json, tests/snapshots/IrcMessageHandler/no-tags.json, tests/snapshots/IrcMessageHandler/redeemed-highlight.json, tests/snapshots/IrcMessageHandler/reply-single.json, tests/snapshots/IrcMessageHandler/reward-bits.json, tests/snapshots/IrcMessageHandler/rm-deleted.json, tests/snapshots/IrcMessageHandler/shared-chat-emotes.json, tests/snapshots/IrcMessageHandler/simple.json
Before, if an emote failed to load, we didn't show anything. Copying the message through right-clicking wouldn't have any text. With this PR, emotes with empty (→ failed) images will now add themselves as system/gray text. I chose this color to indicate that Chatterino knows _something_ is wrong.
You can test this by randomly marking images as failed, like this:
```diff
diff --git a/src/messages/Image.cpp b/src/messages/Image.cpp
index ce636b5ab..8e26c1a27 100644
--- a/src/messages/Image.cpp
+++ b/src/messages/Image.cpp
@@ -19,6 +19,7 @@
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
+#include <QRandomGenerator>
#include <QTimer>
#include <atomic>
@@ -530,7 +531,8 @@ void Image::actuallyLoad()
}
const auto size = reader.size();
-            if …
```
=> feat: show text if emote failed to load

CHANGELOG.md, src/widgets/splits/SplitInput.cpp
technically 2 fixes in 1, uh oh.
This makes the Message Length label in the text input use the same font / font features as the timestamps do (so tabular numbers), meaning the width of the message count will only change with the number of digits.
While I was here, I made the Emote Button be right-aligned, so it doesn't move at all when the Message Length label changes in width.
=> fix: tabular number message length

CHANGELOG.md, src/providers/twitch/TwitchIrcServer.cpp
Plugins tend to use channels beginning with `/` as their own empty channels. We shouldn't send invalid JOIN commands for channels that are local. This is a simple hack, the fix for the root of the issue would be to give plugins a way to actually own channels, but that is going to take a lot of time to finalize.
We already do not send `JOIN`s for `/watching` and friends (with the exception of `/watching` for some reason)
=> Stop sending `JOIN`/`PART` commands for channels starting with `/`

src/widgets/settingspages/GeneralPageView.cpp
fixes #2845
this will hide lines that don't belong to a full group match
=> fix: hide lines in search

.github/workflows/test.yml
The codecov upload shouldn't happen on forks, as it will error there.
=> fix: only upload codecov on main repo

CHANGELOG.md, src/widgets/settingspages/GeneralPage.cpp
a part of General Page -> Browser Integration was not properly integrated and had issues on search
fixed to
---
fixed to 
---
fixed to
=> fix note/description not filtering in/out when it should

CHANGELOG.md, src/providers/twitch/TwitchChannel.cpp
The invisible Unicode block that `\u{e0000}`'s a part of, can't be sent to TMI any longer, it just gets dropped. `\u{34f}` shouldn't ever be dropped by TMI, it's future-proof, because emojis rely on this character to join. Chatterino currently only appends these characters when the duplicate message doesn't contain any spaces, so make sure to note when testing.
=> fix: Twitch dropping `MAGIC_MESSAGE_SUFFIX`

CHANGELOG.md, src/widgets/Notebook.cpp
In #6371, the padding of the button was decreased by 1dp. This PR changes the padding back to 7dp (like before).
=> fix: make notebook add button 1dp smaller on all sides

CHANGELOG.md, src/widgets/PluginRepl.cpp
The pin button was too big before. This uses the same padding as with the other SVG button.
=> fix(plugin-repl): add padding to pin button

.github/workflows/homebrew.yml, .github/workflows/test-arch-linux.yml, .github/workflows/winget.yml
I didn't want to open two PRs for such tiny changes:
- `strategy` is only valid if `matrix` is specified (the yaml schema complained).
- Similar to the codecov upload (#6391), the winget and homebrew updates should only run on the main repo.
=> ci: remove invalid `strategy` and guard winget/homebrew to main repo

.github/workflows/build.yml, .github/workflows/test-macos.yml, CHANGELOG.md
This PR fixes some CI issues caused by the GitHub action runner suddenly pinning cmake.
See https://github.com/actions/runner-images/pull/12791 for more information
=> ci(macos): use locally installed version of cmake

CHANGELOG.md, src/controllers/commands/builtin/chatterino/Debugging.cpp, src/widgets/Notebook.cpp, src/widgets/Notebook.hpp, src/widgets/Window.cpp, src/widgets/buttons/InitUpdateButton.cpp, src/widgets/buttons/InitUpdateButton.hpp
CC @Wissididom if you could try this out - this is what i added to ensure the client actually responded yes to if there are updates
You can use `/debug-test update-check` to manually check for updates
```patch
diff --git a/src/common/Version.hpp b/src/common/Version.hpp
index faac0110d..6e77e7cd6 100644
--- a/src/common/Version.hpp
+++ b/src/common/Version.hpp
@@ -29,7 +29,7 @@ namespace chatterino {
*  - 2.4.0-alpha.2
*  - 2.4.0-alpha
**/
-inline const QString CHATTERINO_VERSION = QStringLiteral("2.5.4-beta.1");
+inline const QString CHATTERINO_VERSION = QStringLiteral("2.5.4-beta.0");
class Version
{
```
=> fix: relayout tabs when update button visibility changes

CHANGELOG.md, src/widgets/TooltipWidget.cpp
On wayland, the tooltip sometimes gets positioned in a way where the mouse is over both the tooltip and the emote/link. This causes some buggy behaviour where the tooltip is only displayed momentarily.
Adding the `Qt::WA_TransparentForMouseEvents` attribute to the tooltip widget seems to fix this.
Before: 
https://github.com/user-attachments/assets/9eee03e5-abe9-4ec5-8d88-42183d638513
After:
https://github.com/user-attachments/assets/1508a937-010a-442d-88b7-08b098f2fd37
=> fix: mouse over tooltips

CHANGELOG.md, src/widgets/Notebook.cpp, src/widgets/Notebook.hpp
The big change here is that we use `isHidden` instead of `!isVisible` for the custom button visibility test.
The former returns true if it _will_ be shown when the Notebook is shown, where the latter returns true only if the Notebook is currently shown.
Using `isHidden` means we can always perform the layout safely, regardless of the state of the Notebook.
As a bonus, I've removed the layout that happens whenever a custom button is added, and instead now perform a single un-animated layout when _all_ custom buttons have been added.
With these changes, I can no longer reproduce any of the custom buttons being hidden behind tabs. I have tested all tab layouts.
=> fix: notebook custom button resizing/layout

.CI/CreateDMG.sh, CHANGELOG.md
https://developer.apple.com/documentation/security/resolving-common-notarization-issues#Enable-the-hardened-runtime
=> ci(macos): codesign with a hardened runtime

CHANGELOG.md, src/widgets/splits/SplitInput.cpp
I saw [the TODO on message length counter font not updating](https://github.com/Chatterino/chatterino2/blob/c7dea40b6baa9f401cc5559723b103edfb75741e/src/widgets/splits/SplitInput.cpp#L278C1-L278C77) on font change and thought this would be a simple fix. Now the `fontChanged` signal is connected to update the `textEditLength` widget's font. I've also removed the TODO comments.
=> fix: update input fonts on fontChanged signal

CHANGELOG.md, resources/com.chatterino.chatterino.appdata.xml, src/common/Version.hpp
I will be using `2.3.4` as the example release in this document.
```diff
- inline const QString CHATTERINO_VERSION = QStringLiteral("2.3.4-beta.1");
+ inline const QString CHATTERINO_VERSION = QStringLiteral("2.3.4");
```
If you made a beta release, this step will not be necessary.
```diff
project(chatterino
-     VERSION 2.3.3
+     VERSION 2.3.4
DESCRIPTION "Chat client for twitch.tv"
HOMEPAGE_URL "https://chatterino.com/"
)
```
The format for beta releases here differs, you have to use a tilde instead, and omit the period before the beta number.
```diff
<releases>
+   <release version="2.3.4" date="2020-02-03">
+       <url>https://github.com/Chatterino/chatterino2/releases/tag/v2.3.4</url>
+   </release>
<release version="2.3.4~beta1" date="2020-02-02"> …
```
=> Release v2.5.4

CHANGELOG.md, src/controllers/plugins/LuaAPI.cpp, src/util/XDGHelper.cpp
this is unused, and technically unavailable since we don't include the
Core5Compat Qt Component
=> fix: remove QTextCodec include

CHANGELOG.md, src/messages/MessageBuilder.cpp, src/providers/twitch/eventsub/MessageBuilder.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
fixes #6433
replaces hard-coded 50-character limit on system messages' reiteration of deleted messages
=> feat: add setting for character limit of truncated deleted messages

CHANGELOG.md, src/widgets/helper/ChannelView.cpp
This exposes the links of badges to the user. Previously these links were set, but you couldn't access them. Now, the links are accessible when right-clicking the badge.
Previously, I removed the links (as they were never exposed).
=> fix: expose home page of badges (if available)

src/widgets/splits/SplitInput.cpp, src/widgets/splits/SplitInput.hpp
Following [this comment](https://github.com/Chatterino/chatterino2/pull/6462#discussion_r2347576216) in #6462, I've created a `updateFonts()` function for code deduplication.
=> Refactor font update logic in SplitInput

.cirrus.yml
it's not necessary for just building
=> ci(freebsd): skip imageformats install

CHANGELOG.md, tests/src/QMagicEnum.cpp
The range of `MyOpen` is `[1, 15]` but we instantiated `16` - this is an error in Clang 21. The point of the test is to see what happens if the name of an unnamed variant is requested. This PR fixes that by using a value inside the allowed range.
=> fix: compilation error with Clang 21
